### ISSUE TITLE
Recommended tsconfig settings

### ISSUE THREAD

**Issue by bterlson** [kubernetes-client/javascript#100]
There are a few tsconfig settings you might consider adopting in this project.

* esModuleInterop: make TypeScript's ES6 module import/export semantics more in line with standards, and  enables other tools to understand the static module graph for things like tree-shaking.
* allowSyntheticDefaultImports: allow importing a commonjs module as the default export
* strict: make TypeScript extra pedantic about types. This ensures TypeScript is doing the best job possible enforcing the correctness of your code. It also ensures that generated d.ts files are free of loose definitions, allowing strict consumers to benefit from tighter type definitions.
* forceConsistentCasingInFileNames: ensure we always warn when casing differs because some file systems (*cough* NTFS *cough*) aren't strict about casing by default. This helps ensure Windows contributors don't get failures in CI due to casing issues.
* importHelpers: keep package size down by pulling out common helpers into external dependencies (these can be bundled into the final artifact by a build tool like rollup if you desire).
* declarationMap: if you're ok including the original source in the package (IMO very nice for debugging and go-to-definition for inspecting implementation details), declarationMap is needed to make it work.

**Comment by brendandburns** [comment]
Filed #101 adopting nearly all of these settings.

Thanks!
