### ISSUE TITLE
How to connect to remove server using "loadFromOptions"?

### ISSUE THREAD

**Issue by miliu99** [kubernetes-client/javascript#1042]
I ran into a similar problem...I'm trying to connect to a remote server and here is how I did it:

```
const k8s = require('@kubernetes/client-node')
const kc = new k8s.KubeConfig()

const cluster = {name: 'default', server: 'https://my-server.com'}
const user = {name: 'xxx', password: 'yyy'}
const context = {name: 'default', user: user.name, cluster: cluster.name}
kc.loadFromOptions({ clusters: [cluster], users: [user], contexts: [context], currentContext: context.name })

const k8sApi = kc.makeApiClient(k8s.CoreV1Api)

k8sApi.listPodForAllNamespaces().then(r => {
    console.log(r.body)
})
```
I don't see any error, but this is what I got:

```
V1PodList {
    apiVersion: undefined,
    items: undefined,
    kind: undefined,
    metadata: undefined
}
```
What did I miss? I checked many times and think I got all the parameters right. How do I debug this case?

I can ssh to the server and run kubectl with the same parameters.

**Comment by mstruebing** [comment]
My first guess is that you are missing the certificates? 
At least in your example code I can not see any certificate data and I guess your kubernetes API doesn't allow access without certs.

**Comment by miliu99** [comment]
Thanks for your answer. However, where to enter the certificate and how to get the certificate?

As I mentioned, I was able to ssh to the server using the same user name/password. Once I get in, I can run kubectl without problem - I don't need any certificate. Is the user object here used to log in to the server? 

I played a bit with the user name/password and found out that I got the same response no matter if user name/password is valid or not (no error either). The problem is that I don't know how to debug it.

**Comment by brendandburns** [comment]
It's highly unlikely that your ssh username/password is the same as your Kubernetes API server name and password. More over, very few Kubernetes API servers are configured to use basic authentication these days.

What you need to do is to get the `$HOME/.kube/config` file from the machine that you SSH'd into (which probably has certificates embedded in it) and then copy that file to the `$HOME/.kube/config` on the machine where you want to use this client, this client should be able to load the right configurations from that file.

Hope that helps.
