### ISSUE TITLE
Error while listing deployments

### ISSUE THREAD

**Issue by flyboarder** [kubernetes-client/javascript#105]
```
var kc = new k8s.KubeConfig();
kc.loadFromDefault();

var k8sApi = kc.makeApiClient(k8s.AppsV1beta1Deployment);
//var k8sApi = kc.makeApiClient(k8s.AppsV1beta1DeploymentList);

k8sApi.listNamespacedDeployment.then( (res) => {
    return res.body;
});
```

 i get this error:
```
"TypeError: apiClient.setDefaultAuthentication is not a function"
```

_Originally posted by @scher200 in https://github.com/kubernetes-client/javascript/issues/103#issuecomment-423794533_

**Comment by flyboarder** [comment]
@brendandburns I think this is a typo should it be `apiClientType`?

**Comment by scher200** [comment]
You are right I posted the wrong error, it was:
```
"TypeError: apiClient.setDefaultAuthentication is not a function"
```

**Comment by scher200** [comment]
I tried all sorts of stuff but keep getting this error:
```
"TypeError: apiClient.setDefaultAuthentication is not a function"
```
code:
```
var kc = new k8s.KubeConfig();
kc.loadFromDefault();

var k8sApiDeployment = kc.apiClientType(k8s.AppsV1beta1Deployment);

k8sApiDeployment.listNamespacedDeployment('default').then( (res) => {
    console.log( res.body );
});
```

**Comment by scher200** [comment]
@flyboarder can you please past in an example of how you list deployments?

**Comment by flyboarder** [comment]
@scher200 I use an older version of the library wrapped in ClojureScript.

**Comment by brendandburns** [comment]
oh, I figured this out... You need to pass the client, not the call type so it should be:

```js
var k8sAppApiClient = kc.makeApiClient(k8s.Apps_v1beta1Api);
```
e.g. you pass the client for the API group (apps/v1beta1) not the specific type (apps/v1beta1/Deployment)
