### ISSUE TITLE
loadFromCluster does not exist

### ISSUE THREAD

**Issue by conwaychriscosmo** [kubernetes-client/javascript#107]
https://github.com/kubernetes-client/javascript/commit/71f0ac85fbb4d8617ded56c6efa127cfb0916452

```const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromCluster();

const k8sApi = kc.makeApiClient(k8s.Core_v1Api);

k8sApi.listNamespacedPod('default')
    .then((res) => {
	console.log(res.body);
    })
    .catch((err) => {
        console.log(err);
    });
```
has a call to kc.loadFromCluster() and loadFromCluster is not a method.  What should we be using?

**Comment by conwaychriscosmo** [comment]
is it supposed to be more like the below?
```
const k8s = require('@kubernetes/client-node');
const k8sApi = k8s.Config.fromCluster();
```

**Comment by brendandburns** [comment]
The call is here:

https://github.com/kubernetes-client/javascript/blob/master/node-client/src/config.ts#L152

What version of the library are you using?

Thanks
--brendan

**Comment by brendandburns** [comment]
Closing this as I think it is answered. Please re-open if you have additional questions.
