### ISSUE TITLE
[release-1.x] `getPreferredMediaType` doesn't handle empty arrays resulting in `None of the given media types are supported:`

### ISSUE THREAD

**Issue by per2plex** [kubernetes-client/javascript#1075]
**Describe the bug**

`getPreferredMediaType` only checks if `mediaTypes` is falsy and not if it's an empty array:
https://github.com/kubernetes-client/javascript/blob/release-1.x/src/gen/models/ObjectSerializer.ts#L1745-L1749

The API provides an empty array, e.g:
https://github.com/kubernetes-client/javascript/blob/release-1.x/src/gen/apis/CoreV1Api.ts#L2779

If the TypeScript types can be trusted, `mediaTypes` should never be `undefined` anyway.

I didn't know where to provide a fix, because those files are generated?

Might be related to https://github.com/kubernetes-client/javascript/issues/893

**Client Version**
`1.0.0-rc2`

**Server Version**
 `1.24.10`

**To Reproduce**

- Try creating a namespace via API
- Throws `None of the given media types are supported:`

**Expected behavior**
Not throw `None of the given media types are supported:`

**Example Code**
```
const kc = new k8s.KubeConfig()

kc.loadFromDefault()

const k8sApi = kc.makeApiClient(k8s.CoreV1Api)

await k8sApi.createNamespace({
  body: {
    metadata: {
      name: 'my-namespace',
    },
  },
})
```

**Comment by felix-gohla** [comment]
Maybe this is rather a problem with either a) the OpenAPI specs over at the Kubernetes repo or b) in the OpenAPI generator.
The place to fix for the latter one would be here (I did not find any issue regarding that in the OpenAPI generator repo):

https://github.com/OpenAPITools/openapi-generator/blob/cc620d8ba22feedff4a2a4e4ef7c3a69a98eacff/modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache#L198-L201

Another potential fix was in the `kubernetes-client/gen` repo by preprocessing the swagger documentation replacing all `"consumes": ["*/*"]` with `"consumes": ["application/json"]`. But I think fixing the generator would be better.

**Comment by davidgamero** [comment]
after taking a look, I think you're correct. The current generated code doesn't respect the `*/*` media type as a pattern.
This is most likely best addressed with an upstream PR to add support.

I can take a shot at it this week. I don't know if it makes more sense to check explicitly for an `allow all` pattern or to use the existing default of an empty array (this could end up hiding error depending on the implementation`

**Comment by clintonmedbery** [comment]
Any movement on this @davidgamero? I was going to give it a shot tomorrow.

**Comment by davidgamero** [comment]
I've tried to find a simple solution in the upstream MIME type code, but it got tricky in the Java/outside typescript generator level. It may be worth adding a fix substituting the full list of MIME values in the python we use to pull the swagger to get around this, but Id love your thoughts when you take a look tomorrow!

**Comment by felix-gohla** [comment]
@brendandburns Could you please release another version when you get a chance, so that we can test the changes? 😊
