### ISSUE TITLE
Listing Deployments not working

### ISSUE THREAD

**Issue by scher200** [kubernetes-client/javascript#111]
I tried all sorts of stuff but keep getting this error while listing deployments:
```
"TypeError: apiClient.setDefaultAuthentication is not a function"
```

my code:
```
var kc = new k8s.KubeConfig();
kc.loadFromDefault();

var k8sApiDeployment = kc.apiClientType(k8s.AppsV1beta1Deployment);

k8sApiDeployment.listNamespacedDeployment('default').then( (res) => {
    console.log( res.body );
});
```

**Comment by brendandburns** [comment]
You want to use:

```js
kc.makeApiClient(k8s.AppsV1Beta1Deployment);
```

Not the `apiClientType` call...

**Comment by brendandburns** [comment]
Sorry my first comment was not quite correct, I've edited it to correct it.

That should work...

I'll update the docs to to be more clear.

**Comment by scher200** [comment]
thank you!

**Comment by brendandburns** [comment]
CLosing this as I assume 'thank you' mean s 'it works' :)
