### ISSUE TITLE
Data send through websocket to kubernetes api is trimmed by one byte

### ISSUE THREAD

**Issue by mojojoji** [kubernetes-client/javascript#112]
Kubernetes websocket api needs to attach a byte to the message buffer sent to identify if the type of message is stdin, stdout, stderr (https://blog.openshift.com/executing-commands-in-pods-using-k8s-api/)
```
|Code|Meaning |
|----|--------|
|0   | stdin  |
|1   | stdout |
|2   | stderr |
```
This means the length of the buffer created and send to websocket api should be ` 1 + the length of input data`
But as per the below code in websockethandler, the the new buffer has same length of the original buffer and as a result trims off the last byte.
As a result the exec example doesnt work

https://github.com/kubernetes-client/javascript/blob/5a19070fd47e6ac687558e0cdac160a48326fb59/node-client/src/web-socket-handler.ts#L46-L53

A new buffer should be created with 1+ length and then the code byte and the data should be copied over

**Comment by brendandburns** [comment]
Fixed by #113
