### ISSUE TITLE
how to list user groups

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-client/javascript#1133]
sorry i couldnt find anything in the documentations.
how can i get groups?
its not a custome resources, there is not `listGroup` function, and i couldnt see anything with `getAPIResources`

**Comment by zfrhv** [comment]
sorry for the misunderstanding its my bad
i meant users groups

**Comment by brendandburns** [comment]
As far as I know there's no concept of a user group in Kubernetes. If you are using groups for external identity or RBAC (e.g. AAD + Kubernetes) the groups are part of the identity/RBAC system.

If you have an equivalent `kubectl` command, you can always run `kubectl --v=10` to see the URLs that it is accessing.

**Comment by zfrhv** [comment]
i see
when running `kubectl -v=10 get group` i got:
`https://<cluster dns>/apis/user.openshift.io/v1/groups`

and because i have openshift cluster it comes in as default 🤔

is there any other way of getting the groups?
maybe there is something else instead of `k8s.CoreV1Api`?

**Comment by zfrhv** [comment]
thank you
