### ISSUE TITLE
issue with executing command with "-- /bin/bash -c" prefix

### ISSUE THREAD

**Issue by kavandesai** [kubernetes-client/javascript#115]
Hi 
I am not able to execute command - -- /bin/bash -c 'ls -al' or in general command with prefix 
-- /bin/bash -c. 
Below is the code snippet -

let command = "-- /bin/bash -c 'ls -al'";

exec.exec('default', 'pod_name', 'container_name', command, stdoutStream, stderrStream, null, false /* tty */)
.then(() => {
    console.log(`${stdoutStream.contents}`);
  })
  .catch(e => {
      //handle exception (rejection)
      console.log(e);
      });

out put - 

rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"-- /bin/bash -c 'ls -al'\": stat -- /bin/bash -c 'ls -al': no such file or directory"

**Comment by brendandburns** [comment]
I don't think you want or need the '--' that's command-line syntax for "ignore all flags after this" which isn't necessary in a native library. As it stands your code is trying to execute an executable named '--' which isn't what you want...
