### ISSUE TITLE
listPodForAllNamespaces() got HttpError: HTTP request failed

### ISSUE THREAD

**Issue by chengtangzheng2021** [kubernetes-client/javascript#1155]
**Describe the bug**
listPodForAllNamespaces() got HttpError: HTTP request failed, there is no detail information, don't know what caused this error.

listNamespacedPod('namespaceName') is only working with the same namespace that this code is running in. with other namespace, got
HttpError: HTTP request failed, so that maybe the cause of calling listPodForAllNamespaces().
looks it can not get pods from other namespace diffent from its own namespace

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version [eg. 10]
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by mstruebing** [comment]
Could you try to use a newer client?
0.12.0 was released 3 years ago and based on the version compatibility matrix in the readme 0.13.0 supports kubernetes 1.19: https://github.com/kubernetes-client/javascript#compatibility

**Comment by chengtangzheng2021** [comment]
version of 0.18.1 got used on the image

**Comment by brendandburns** [comment]
If it is only working inside one namespace, my guess is that you are getting a 401 error b/c your pod service account is not authorized to talk to other namespaces.

For more details on pod service accounts and RBAC see this document:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

If you catch the error that is being thrown (`try/catch` around the list namespaces call) you should be able to get more details from that error object.

**Comment by chengtangzheng2021** [comment]
> If it is only working inside one namespace, my guess is that you are getting a 401 error b/c your pod service account is not authorized to talk to other namespaces.
> 
> For more details on pod service accounts and RBAC see this document: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
> 
> If you catch the error that is being thrown (`try/catch` around the list namespaces call) you should be able to get more details from that error object.

Lots thanks for your kind reply.
tested with promise call back error loging, and try catch block, try catch got the same error message.
I will look into the pod account

**Comment by chengtangzheng2021** [comment]
> If it is only working inside one namespace, my guess is that you are getting a 401 error b/c your pod service account is not authorized to talk to other namespaces.
> 
> For more details on pod service accounts and RBAC see this document: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
> 
> If you catch the error that is being thrown (`try/catch` around the list namespaces call) you should be able to get more details from that error object.

thanks for your nice reply,
I deployed the app to default namespace there can access all namespaces, it should be accout issue.
