### ISSUE TITLE
Problem with code linter

### ISSUE THREAD

**Issue by DavidIsa** [kubernetes-client/javascript#1162]
**Describe the bug**
In version 0.18.1 (currently master branch) the linter is failing with the following error.
```
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
```
The code base doesn't use `originalKeywordKind`, which makes is impossible to fix this warning.

**Client Version**
`0.18.1`

**To Reproduce**
Run linter `npm run lilnt`

**Expected behavior**
The linter should not fail due to false alarm

**Comment by DavidIsa** [comment]
Since the TSLint is deprecated maybe we should migrate to eslint?

**Comment by mstruebing** [comment]
I think we should, I can try to create a PR for that.

**Comment by brendandburns** [comment]
fwiw, this is probably worth fixing, but this doesn't make CI/CD fail.

**Comment by mstruebing** [comment]
Yes I know, the issue was a prettier issue but I would like to switch anyway as tslint is deprecated since quite a while and it would be cool to not have so many outdated/old/deprecated dependencies :)
