### ISSUE TITLE
how to create a job and apply a deployment

### ISSUE THREAD

**Issue by inyee786** [kubernetes-client/javascript#117]
do you have function which will create job or apply a deployment just like below example

https://github.com/godaddy/kubernetes-client/blob/master/examples/apply-deploy.js

**Comment by brendandburns** [comment]
There's a simple example of how to create a namespace here:

https://github.com/kubernetes-client/javascript/blob/master/examples/namespace.js

It would be easy to modify that to create a Job or a Deployment instead.

You need to:

```javascript
...
var k8sAppApiClient = kc.makeApiClient(k8s.Apps_v1beta1Api);
...

k8sAppApiClient.createNamespacedDeployment(....);
...
```

**Comment by inyee786** [comment]
@brendanburns  thanks for quick response
