### ISSUE TITLE
v1.0.0-rc2: RequiredError: Required parameter body was null or undefined when calling AuthorizationV1Api.createSelfSubjectAccessReview.

### ISSUE THREAD

**Issue by trevorlinton** [kubernetes-client/javascript#1171]
**Describe the bug**
When using the kubernetes client 1.0.0-rc2 and calling the createSelfSubjectAccessReview the following error is returned:

```
RequiredError: Required parameter body was null or undefined when calling AuthorizationV1Api.createSelfSubjectAccessReview.
```

** Client Version **
`1.0.0-rc2`

** Server Version **
`1.23`

**To Reproduce**

The following code works in `0.18.1` but not `1.0.0-rc2`:

```
const k8s = require('@kubernetes/client-node');
(async function() {
  const kc = new k8s.KubeConfig();
  kc.loadFromFile(`${process.env.HOME}/.kube/config`);

  const accessPods = { spec: { resourceAttributes: { verb: 'watch', resource: 'pods' } } };
  const k8sApi = kc.makeApiClient(k8s.AuthorizationV1Api);
  const result = k8sApi.createSelfSubjectAccessReview(accessPods);
  const canWatchPods = (await result).body.status.allowed;
})().catch((e) => console.error(e));
```

**Expected behavior**
To receive back a response of true or false as to whether the access privileges for watch pods is allowed.

** Example Code**
(see To Reproduce section)

**Environment (please complete the following information):**
 - OS: MacOS
 - NodeJS Version: v18
 - Cloud runtime: none

**Additional context**
None

**Comment by brendandburns** [comment]
There are API breaking changes between the `0.x` version series and the `1.0` version series. In particular it added named parameters. I believe that if you switch to:

```javascript
k8sApi.createSelfSubjectAccessReview(body: accessPods);
```

It will work correctly.

**Comment by trevorlinton** [comment]
Yeah that did work, is there a list (or going to be a list) of the breaking changes available somewhere?
