### ISSUE TITLE
`request` doesn't honor SNI when `pool:false`

### ISSUE THREAD

**Issue by tigrato** [kubernetes-client/javascript#1172]
**Describe the bug**

`request` doesn't forward the SNI (Server Name Indication) when the Kubernetes client disables the `pool`. This is critical for [`watch`](https://github.com/kubernetes-client/javascript/blob/c1311683c6b6b70c62b52f23c9102971ea192a22/src/watch.ts#L102) methods as they require the pool to be disabled due to a leak.

``` 
const requestOptions = {
    method: 'GET',
    qs: queryParams,
    headers: headerParams,
    uri: url,
    useQuerystring: true,
    json: true,
     pool: false,
};

``` 

#820 added support for respecting the SNI defined in kubeconfig but request modules does not honor it when the pool is disabled.

Bellow, we have the request object captured after  [await this.config.applyToRequest(requestOptions);](https://github.com/kubernetes-client/javascript/blob/c1311683c6b6b70c62b52f23c9102971ea192a22/src/watch.ts#L104) which correctly specifies the `servername`.

```
{
  method: 'GET',
  qs: { allowWatchBookmarks: true, watch: true },
  headers: {},
  uri: 'https://tele.local:3080/api/v1/namespaces',
  useQuerystring: true,
  json: true,
  pool: false,
  ca: ...,
  cert: '',
  key: '--',
  agentOptions: { servername: 'kube.tele.local' }
}
```

Commenting the `pool: false` fixes the issues and `request` honors the servername.

Since the request is fully deprecated and doesn't receive any update since 2021 we cannot fix the faulty.

** Client Version **
latest

** Server Version **
1.26

**To Reproduce**
Try to watch a resource on a server requiring an SNI

**Expected behavior**
SNI should be honored

** Example Code**

```javascript
k8s = require('@kubernetes/client-node');
kc = new k8s.KubeConfig();
kc.loadFromDefault();
watch = new k8s.Watch(kc);
watch.watch('/api/v1/pods', {}, (p, o) => console.log(`Phase: ${p}`), (error) => console.log(error));
```

**Environment (please complete the following information):**
 - OS: linux
 - NodeJS Version: 18
 - Cloud runtime: none

**Additional context**

**Comment by brendandburns** [comment]
You might try switching to the new fetch based client which is in testing:

https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc2

**Comment by tigrato** [comment]
@brendandburns 

Thank you.

Unfortunately, the v1.0.0 branch misses PR #888.
Because of that, it doesn't set the SNI for **any** request
