### ISSUE TITLE
[release-1.x] The NPM release doesn't match the branch's latest changes

### ISSUE THREAD

**Issue by WassimBenzarti** [kubernetes-client/javascript#1173]
**Describe the bug**
Several issues were fixed in the recent PRs to release-1.x, Unfortunately the [NPM release](https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc2) doesn't reflect the latest changes as it was updated 3 months ago.

Is there any chance we could setup a workflow for automatic releases to this tag until we reach a stable version?

**Comment by brendandburns** [comment]
Ok, this actually requires some PRs to merge first so it's not going to be tonight, but it has started...

**Comment by brendandburns** [comment]
Well that took _way_ to long (apologies!) but an `rc3` is now published:

https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc3
