### ISSUE TITLE
V1AdmissionRequest, V1AdmissionResponse types are not generated

### ISSUE THREAD

**Issue by floriankoch** [kubernetes-client/javascript#1184]
**Describe the bug**
The Kubernets API Types V1AdmissionRequest, V1AdmissionResponse are not in the generated models

**Expected behavior**
V1AdmissionRequest, V1AdmissionResponse  are in the generated models
´

**Environment (please complete the following information):**
   "@kubernetes/client-node": "^1.0.0-rc2",
´

**Comment by brendandburns** [comment]
Because these APIs are part of an extension resource provider, they're not generated by default. We should consider adding support for this, but in the meantime, there are instructions for generating them here:

https://github.com/kubernetes/kubernetes/issues/84081#issuecomment-701686042

**Comment by floriankoch** [comment]
ok thank you, i can work with this, but would be good its included  here
