### ISSUE TITLE
Terminal is not established correctly for powershell 

### ISSUE THREAD

**Issue by qinl-li** [kubernetes-client/javascript#1197]
**Describe the bug**
My work is to exec a PowerShell command into an aks container and create an interactive PowerShell shell. 
Now, bash works fine for me. But, once after I switched to powershell and type any character, the terminal crashes...  

** Client Version **
"@kubernetes/client-node": "^0.18.1"

** Server Version **
e.g. `1.19.1`

**To Reproduce**
Create a container use the following command:
kubectl run toolbox10 --image=azuresearchlab.azurecr.io/toolbox:0.0.4-qinl -- /bin/pwsh -NoLogo -NoExit -Command Start-Sleep -Seconds 9999

using @kubernetes/client-node to create an interactive session

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
const exec_command2 = [
'/bin/bash',
'-c',
'export TERM=xterm-256color;printenv;pwsh -NoLogo']
const exec = new k8s.Exec(kc);

socket = await exec.exec(namespace, podName, containerName, exec_command2, stdout, stdout, stdin, true,
(status: k8s.V1Status) => {
console.log('Exited with status:');
console.log(JSON.stringify(status, null, 2));
})

**Expected behavior**
It should create an PowerShell interactive session and no crash happens when typing 

** Example Code**
`import * as vscode from 'vscode';
import WebSocket from 'isomorphic-ws';
import * as k8s from '@kubernetes/client-node';
import * as stream from 'stream';
//import { Exec } from '../K8sUtils/exec';

export async function Connect(namespace: string, podName: string, containerName: string, dbg: vscode.OutputChannel) {
	// create the  PseudoTerminal proxy for the websocket
	let socket: WebSocket | undefined = undefined;
	const writeEmitter = new vscode.EventEmitter<string>();

	const stdout = new stream.Writable({
		write: function (chunk, encoding, next) {
			writeEmitter.fire(chunk.toString());
			next();
		}
	});

	const stdin = new stream.Readable();
	stdin.pause(); // using this stream as just an event emitter to send input commands

	const pty = {
		onDidWrite: writeEmitter.event,
		open: () => writeEmitter.fire('Initializing ToolBox...\r\n'),
		close: () => {
			dbg.appendLine("Terminal Closed");
			stdin.emit("end");
		},
		handleInput: (data: string) => {
			console.log(data);
			stdin.emit("data", data);
		}
	};
	const terminal = (<any>vscode.window).createTerminal({ name: 'Toolbox Remote', pty });
	terminal.show();

	// when running in the browser use vscode auth

	writeEmitter.fire('Starting a Toolbox shell...\r\n');

	const kc = new k8s.KubeConfig();
	kc.loadFromDefault();

	const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
	const exec_command2 = [
		'/bin/bash',
		'-c',
		'export TERM=xterm-256color;printenv;pwsh -NoLogo']
	const exec = new k8s.Exec(kc);
	writeEmitter.fire(`Connecting to ${namespace} - ${podName}`)
	
	socket = await exec.exec(namespace, podName, containerName, '/bin/bash', stdout, stdout, stdin, true,
		(status: k8s.V1Status) => {
			console.log('Exited with status:');
			console.log(JSON.stringify(status, null, 2));
		})
	socket.onerror = function (event) {
		dbg.appendLine("Error: " + event.message);
	};

	
}
`
**Environment (please complete the following information):**
 - OS: windows 10
 - NodeJS Version v16.17.0
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**
Here is the full error. I have connected with powershell team (https://github.com/PowerShell/PSReadLine/issues/3774 )
and they mentioned when BufferWidth & BufferHeight is zero it means the console doesn't really exist.... 

I actually can exec with kubectl command without any issue. 
kubectl exec -it toolbox1 -- pwsh -NoLogo -NoExit /root/.components/azuresearchlab/Bootstrap/files/shell.ps1

So I am wondering what did I miss? Any help is appreciated! Thanks!
![image](https://github.com/kubernetes-client/javascript/assets/63257243/144b794f-8160-48dc-a7f3-2a744873dad9)

**Comment by brendandburns** [comment]
I suspect that kubectl sends the terminal size, wheras we are missing some query parameters when we establish the exec stream. Can you run `kubectl --v=10 ...` with your `exec` command? `--v=10` will print verbose debugging including all of the URLs that kubectl sends.

That will help us see if we are missing sending the size of the terminal.

**Comment by qinl-li** [comment]
I figured out the solution. It turned out that the stdout needs to be resizable so the library will define a terminal size for exec. To make it resizable, I had to add columns & rows to stdout. I added the following class to fix the issue. 
<img width="626" alt="image" src="https://github.com/kubernetes-client/javascript/assets/63257243/06e11a0a-4564-405e-8e09-f789a45a51d9">

**Comment by brendandburns** [comment]
I'm going to close this as resolved.
