### ISSUE TITLE
how to stop watch，thanks

### ISSUE THREAD

**Issue by vicky-rain** [kubernetes-client/javascript#1200]
I want to turn off watch monitoring. Now I use watch.abort, watch.removeAllListeners, and both report errors, TypeError: watch.abort is not a function, TypeError: removeAllListeners.abort is not a function

The following code also reports an error, TypeError: request.abort is not a function, so how to stop watch，thanks
````
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();
const watch = new k8s.Watch(kc);

const namespace = 'default';
const deploymentName = 'example-deployment'; 

const request = watch.watch(
  `/apis/apps/v1/namespaces/${namespace}/deployments/${deploymentName}`,
  {},
  (type, apiObj, watchObj) => {
    const labels = watchObj.object.metadata.labels;

    if (labels && labels['app'] === deploymentName) {
      console.log('Deployment is modified.');
      
      request.abort();
    }
  },
  (err) => {
    console.log('Watch stopped with error:', err);
  }
);
````

"@kubernetes/client-node": "^0.18.1",

**Comment by mstruebing** [comment]
I think you need to move the `request.abort()` out of the inner function block, as you define `request` in the outside scope, similar to the example: https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts

**Comment by vicky-rain** [comment]
@mstruebing Thank you very much, this method is very useful
