### ISSUE TITLE
watch monitors the deployment, does not end the monitoring manually, but stops monitoring by itself

### ISSUE THREAD

**Issue by vicky-rain** [kubernetes-client/javascript#1204]
watch monitors deployment, does not end monitoring manually, stops monitoring by itself

The following is the sample code, why after running the callback branch, it will directly enter the done branch, I did not manually close the watch monitoring

The desired effect is that the watch can continuously monitor the status changes of the deployment

````
import * as k8s from '@kubernetes/client-node';
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
const watch = new k8s.Watch(kc);
const main = async () => {
    try {
	const namespace = "default";
	const templateName = "deployment-name";
        const req = await watch.watch(
            `/apis/apps/v1/namespaces/${namespace}/deployments/${templateName}`,
            {},
            (type, apiObj, watchObj) => {
                console.log(watchObj);
            },
            (done) => {
		console.log(done);
	    },
        );
    } catch (err) {
        console.error(err);
    }
};
main();

````

"@kubernetes/client-node": "^0.18.1"

**Comment by vicky-rain** [comment]
Added: the type and apiObj parameters in the callback branch all return undefined, and only watchObj returns data. Is this normal?

**Comment by brendandburns** [comment]
Watch is performed on a collection (e.g. `deployments`) not a single instance.

If you want to watch a single instance, you can use a field selector (or other mechanism) to watch for changes to a specific resource.

There is a discussion here:
https://github.com/kubernetes/kubernetes/issues/43299

Which may be useful.

There is a simple watch example here:
https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts

Which you may want to use as a starting point.

**Comment by Ananya2001-an** [comment]
I am facing the same issue I have tried executing the watch example but after printing out the current namespaces it aborts on its own....there is no monitoring happening
