### ISSUE TITLE
Namespace '"http"' has no exported member 'ClientResponse'. with node 10

### ISSUE THREAD

**Issue by FedeBev** [kubernetes-client/javascript#122]
Hi everyone,
adding this library to my typescript project with node 10.11 (types "@types/node": "^10.11.4") I get the following error:
Namespace '"http"' has no exported member 'ClientResponse'. 

Everything works correctly with node 8 (types "@types/node": "^8.10.36"

Maybe it's a bug of the definition of node types for node 10?

**Comment by brendandburns** [comment]
I see the response says we need to move to `IncomingMessage`

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29674

I'll work on a PR to fix this.
