### ISSUE TITLE
Compatibility with 1.26, 1.27 and 1.28

### ISSUE THREAD

**Issue by RCMainak** [kubernetes-client/javascript#1262]
I am wondering about the compatibility of this library with the Kubernetes version newer than 1.25, such as 1.26, 1.27 and 1.28. There is no mention of the same in the readme file.  I tested some of the function works with 1.26 and 1.27, but I would like to know the official compatibility status of the library.

Thanks.

**Comment by brendandburns** [comment]
Yeah, I need to regenerate the client, it hasn't been updated in a while :(

In terms of compatability, any `v1` API will work perfectly. all of the `beta` APIs should work also. `alpha` APIs are more likely to have compatability issues, but you're probably not using any of them anyway.

I will regenerate sometime soon...

**Comment by brendandburns** [comment]
I just regenerated for 1.27.x and I will cut a new release with those changes.

**Comment by brendandburns** [comment]
Just pushed `0.19.0` to npm with support for k8s 1.26 + 1.27

**Comment by brendandburns** [comment]
Regenerated for 1.28

https://github.com/kubernetes-client/javascript/pull/1278

I will cut an `0.20.0` release once it merges.

**Comment by mstruebing** [comment]
@brendandburns could this (`0.20.0`) be the first release one of the new contributors would do?
I guess we would need to get added to the kuberenetes-client npm organisation first, what is necessary to get added?

**Comment by brendandburns** [comment]
@mstruebing there is a github action for cutting a release which _should_ work without you needing to be added to the organization. Feel free to give it a try.

**Comment by mstruebing** [comment]
Okay the action is working partially, the npm release will get published but the GitHub tag creation did not work.
I've created a tag manually and created a draft release: https://github.com/kubernetes-client/javascript/releases/edit/untagged-93880f1e171f1830ffa7 

I used github to automatically generate the release notes, if we want to have more condensed ones like in the previous releases let me know but I think having this overview generated by GitHub is kind of nice as it contains more information and links to the pull requests/commits as well.

**Comment by brendandburns** [comment]
Thanks, the release looks good, but maybe next time we should filter out the dependabot updates? They're a little spammy and probably not super relevant.
