### ISSUE TITLE
Docs don't seem to be generated anywhere.

### ISSUE THREAD

**Issue by pdougall1** [kubernetes-client/javascript#128]
You've got this huge API but I can't find any docs about it.

While spelunking I found a lot of beautiful documentation (really great work IMO) and it looks like you're using swagger, but I don't see the docs generated anywhere.  

I'm actually fine just grepping through the code but I wanted to bring it to your attention in case someone finds this great library while in a more frustrated state and dismisses it too early to find out how extensive it is.

Also, it is entirely likely the docs are generated somewhere and I just missed them.  In that case please excuse me and help me know where they are.

Thanks again for the great tool!

**Comment by itowlson** [comment]
I think at the moment there are just the JSDoc comments - I don't think they are rendered to HTML or pushed to a site.  I suspect the assumption is that people will refer to the k8s API documentation for what all the objects and operations mean, but I can see how it would be difficult for a new user to locate the appropriate operations or types within the JS library.

@brendandburns is there a k8s site for official client documentation?

**Comment by brendandburns** [comment]
Not that I know of, but I filed an intern proposal recently for someone to create such a thing :)

**Comment by brendandburns** [comment]
The general API reference is here:

**Comment by flyboarder** [comment]
This library is built with swagger, so you can use Swagger UI or any of those tools.

To view API docs: https://petstore.swagger.io
Change JSON file at the top to: https://raw.githubusercontent.com/kubernetes-client/javascript/master/node-client/src/swagger.json

**Comment by alewitt** [comment]
fyi: Change JSON file at the top to: `https://raw.githubusercontent.com/kubernetes-client/javascript/master/src/swagger.json`

**Comment by kevinsimper** [comment]
It would be nice with some published documentation for the function `kc.loadFromDefault();`, but I can just read the sourcecode, but for beginners 😄

**Comment by NathanRSmith** [comment]
It would be wonderful if there was some description of the naming scheme in the README. I understand that it's generated from Swagger, but until the JSDocs are hosted somewhere, even a description of how to roughly translate from the [k8s API Docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/) to the code API would be helpful.

I'm not opposed to spelunking, but attempting to use this lib while still getting up to speed on the k8s API itself was a bit frustrating. The lib is functional, but not quite user-friendly yet imo. Good start though.
