### ISSUE TITLE
Support for loading YAML files

### ISSUE THREAD

**Issue by weibeld** [kubernetes-client/javascript#129]
I couldn't find any facilities in this library to load Kubernetes API objects from YAML files, something like [this](https://github.com/kubernetes-client/java/pull/207) for the Java client.

Currently, I have to do it like this with `js-yaml` and `fs`:

~~~javascript
const yaml = require('js-yaml');
const fs = require('fs');

const deployment = yaml.safeLoad(fs.readFileSync('deployment.yml', 'utf8'));

// ...in order to use it for:
apiClient.createNamespacedDeployment('default', deployment, true);
~~~

Maybe it would be good to have a class for this, like in the Java client, or at least mention it in the README how it can be done with `js-yaml`.

**Comment by brendandburns** [comment]
I'll add this support.
