### ISSUE TITLE
instanceof V1ConfigMap returns false

### ISSUE THREAD

**Issue by mbmx10** [kubernetes-client/javascript#1333]
**Describe the bug**
A javascript object returned from a Watch on "/api/v1/configmaps"  won't pass `instanceof V1ConfigMap`.

** Client Version **
e.g. `0.19.0`

** Server Version **
e.g. `1.26.6`

**To Reproduce**
Watch /api/v1/configmaps and check a  retrieved object with instanceof V1ConfigMap.
The check will return false.

**Expected behavior**
The check returns true

** Example Code**
```typescript

const onConfigMap = (phase: string, configMap: any) => {
  if (!(configMap instanceof V1ConfigMap)) {
    return log.error(`Unexpected apiObj type: ${typeof configMap}`);
  }
  ...
}

const loadAndWatchConfigMapData = (): void => {
  const kubeConfig = new KubeConfig();
  kubeConfig.loadFromCluster();
  new Watch(kubeConfig)
    .watch('/api/v1/configmaps', configMapsQuery, onConfigMap, onWatchDone(loadAndWatchConfigMapData))
    .then(setCountdownUntilWatchDone)
    .catch(log.error);
};
```

**Comment by brendandburns** [comment]
This is a limitation of the interactions between `instanceof` in Typescript and the way this code is written generically.

Specifically instanceof requires the constructor to be the same, and that's not happening here b/c the object is parsed from JSON.

There are more details of how `instanceof` works here:
https://stackoverflow.com/questions/45964008/typescript-instanceof-not-working

I'm not sure there's a great way to fix this, but if you have ideas for how to change the code, please feel free to send a PR.

**Comment by brendandburns** [comment]
Closing since I think this has been answered and no further questions.

Please use the `/reopen` command if you need further assistance.
