### ISSUE TITLE
Help find some functions

### ISSUE THREAD

**Issue by Grigsuv** [kubernetes-client/javascript#134]
Hi,I need this functions `

1) Kill pod by name
2)Change deployments pod's count(Add or delete)
3) Restart all pods in deployment

I tried to find it in examples, in files....but can't find enough information

**Comment by itowlson** [comment]
Duplicate of #133 probably due to GitHub glitch (@Grigsuv please reopen if I missed something in this one)

**Comment by Grigsuv** [comment]
Yes it is,github had some problems
