### ISSUE TITLE
Support Dry Run Client

### ISSUE THREAD

**Issue by henrysachs** [kubernetes-client/javascript#1363]
**Describe the bug**
Currently the Dry Run Flag only supports the value All, but in my use case I dont want to allow the corresponding serviceaccount permissions on my cluster where dry-run=client would be helpful

** Client Version **
`latest`

** Server Version **
`1.26.0`

**To Reproduce**

```
result = await k8sApi.createNamespacedSecret(
          ctx.input.namespace,
          {
            data: { ...ctx.input.secrets },
            metadata: { name: ctx.input.secretName },
          },
          undefined,
          'All',
        );
```

If you use Client instead of All I receive an error

**Expected behavior**
The Parameter Dry Run Accepts Server and Client as Parameters and hands them to the corresponding kube call.

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: MacOs and Linux
 - NodeJS Version 18
 - Cloud runtime EKS

**Additional context**

**Comment by brendandburns** [comment]
As far as I can tell, this parameter is passed straight into the calls to the server. I believe that these flag values are `kubectl` values, not API values.

Given that `createNamespacedSecret` simply makes an HTTP call to the API server I'm not sure what client side dry run would mean in this context anyway.

Note that `kubectl` has lots of relatively complex client side logic that is not present in the client SDKs.

If you think this is an issue in the client, please supply a complete reproduction with code if you need further assistance.

**Comment by henrysachs** [comment]
yeah what i was trying to achieve was like a "cheap" templating of a secret yaml. But if thats kubectl exclusive I will try to give the corresponding Serviceaccount the required RBAC Permissions. Thanks for your explanation it really helped me understand the inner processes of dry run!
