### ISSUE TITLE
Unlicensed dependet packages

### ISSUE THREAD

**Issue by omrisdeor11** [kubernetes-client/javascript#1375]
Hi :)
So there are two dependencies for this package, which are not licensed (which makes difficulties for me using the package).
The deps are:
1. stream-buffers
2. tweetnacl

Do you have any recommendation for workaround for this? Since client-node has an apache license already..
Thanks :)

**Comment by brendandburns** [comment]
Both of those packages are covered by the [unlicense](https://en.wikipedia.org/wiki/Unlicense) which makes them compatible with Apache 2.0

**Comment by brendandburns** [comment]
I think so. I generally try to leave issues open for a few days in case someone wants to respond.

Also, given that they can't reopen the issue directly, it is worth telling them that the `/reopen` command will reopen the issue if necessary.

**Comment by mstruebing** [comment]
I did not know that it's not as easy to reopen an issue.
I'll try to follow the same principle in the future.
