### ISSUE TITLE
Metrics server support

### ISSUE THREAD

**Issue by salaxander** [kubernetes-client/javascript#139]
Hello!

I'm interested in adding support for the metrics server endpoints, i.e.  `/apis/metrics.k8s.io/v1beta1/nodes`.

Happy to submit a PR if people are open to it.

Thanks! :)

**Comment by ypjin** [comment]
@salaxander I'm in the need to use this library to get resource metrics and have no clue how to do that. Would you please advice on it? Thanks in advance!
