### ISSUE TITLE
1.0.0-rc3 Error "None of the given media types are supported"

### ISSUE THREAD

**Issue by tugtugtug** [kubernetes-client/javascript#1398]
**Describe the bug**
When any patch functions are called, such as patchNamespacedStatefulSet, the client throws "None of the given media types are supported"

** Client Version **
e.g. `1.0.0-rc3`

** Server Version **
e.g. `1.25.1`

**To Reproduce**
- make a call to patchNamespacedStatefulSet with any parameters

**Expected behavior**
The patch functions should work. And in addition to be working, I'm also not sure how the API will figure out which mediaType to prefer given the content of the body. The old api allows overriding the headers via the options, now this is no longer available.

** Example Code**
```
let kubeConfig = new k8s.KubeConfig();
kubeConfig.loadFromDefault();
const k8sAppsApi = kubeConfig.makeApiClient(k8s.AppsV1Api);
// how to make sure this is done with header
// 'Content-Type': 'application/merge-patch+json'??
await k8sAppsApi.patchNamespacedStatefulSet({
			name: 'test',
			namespace: 'default',
			body: {
				spec: {
					replicas: replicas,
				},
			}
		})
```
**Environment (please complete the following information):**
OS: [Ubuntu 22.04]
NodeJS Version [18]
Cloud runtime [NA]

**Additional context**
Is there a general status the testing coverage of the 1.0.0 branch?
Given the release candidate tag, I had higher expectation of the quality of the code, but it seems quite hard to move forward with all these bugs.

**Comment by mstruebing** [comment]
I think this is connected to #1341 and a known bug right now.

**Comment by mstruebing** [comment]
I think this is connected to #1341 and should be supported if we merge this and cut another RC.

**Comment by mstruebing** [comment]
@tugtugtug I've published a new release `1.0.0-rc4`: https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc4
Could you confirm that this issue is solved in this release?

**Comment by tugtugtug** [comment]
Verified fixed!

**Comment by tugtugtug** [comment]
Hi @mstruebing,
  I thought things were working as no errors were reported. But apparently the example that changes the content-type does not work.
e.g.
```
    patchNamespacedStatefulSetWithHttpInfo(name, namespace, body, pretty, dryRun, fieldManager, fieldValidation, force, _options) {
        const requestContextPromise = this.requestFactory.patchNamespacedStatefulSet(name, namespace, body, pretty, dryRun, fieldManager, fieldValidation, force, _options);
        // build promise chain
        let middlewarePreObservable = (0, rxjsStub_1.from)(requestContextPromise);
        for (let middleware of this.configuration.middleware) {
            middlewarePreObservable = middlewarePreObservable.pipe((0, rxjsStub_2.mergeMap)((ctx) => middleware.pre(ctx)));
        }
```
the passed `_options` is not used as the middleware to be used in the case, instead the object's `this.configuration.middleware` is used.

**Comment by tugtugtug** [comment]
made a new issue https://github.com/kubernetes-client/javascript/issues/1499
