### ISSUE TITLE
Consider making refactoring API object model

### ISSUE THREAD

**Issue by hausdorff** [kubernetes-client/javascript#14]
I propose the following changes to the API object model:

1. Make non-required fields (and fields that aren't `apiVersion` or `kind`) in all API objects optional _e.g._, `containers: V1Container` -> `containers?: V1Container`.
1. Automatically generate [type guards][guards] to make it easy to condition on the types of API objects you're interacting with in TypeScript.
1. Change all API objects in `api.ts` to be `interface`s rather than `class`es.
1. Add a utility type that represent the set of top-level API objects (_e.g._, `type CoreTypes = AppsV1beta1Deployment | AppsV1beta1DeploymentList | [...]`), so that you can deal with a well-typed collection of objects for some API group.

## Justification for (1)

Suppose I manually construct an object so that I can later `kubectl` it to the server:

```
        const svc = <k8s.V1Service>{
          "kind": "Service",
          "apiVersion": "v1",
          "metadata": {
            name: name,
          },
          "spec": {}
        };
```

This will actually not compile because `k8s.V1Service` requires a `status` field. This field need not exist for our purposes, though. It is possible to work around this by casting to `any` first (_e.g._, `        const svc = <k8s.V1Service><any>{ [...] }`, but this is not a particularly compelling "blessed pattern", because `status` actually _is_ an optional field.

This approach will make apps using `--strictNullCheck` a little more verbose, but really not checking `null` here is just hiding from the real issue, which is that it can very well be `null`.

## Justification for (2)

Using the API objects in `api.ts` is pretty painful in TypeScript.

Let's say you are writing an app in TypeScript, and have some object `const foo: AppsV1beta1Deployment | AppsV1beta2Deployment | ExtensionsV1beta1Deployment;`.

If you want to figure out which of these types `foo` really has at runtime, you would ordinarily do something like:

```
if (foo instanceof AppsV1beta1Deployment) {` 
```

But if you have built up an API object using an object literal (as we did in (1)), then that object literal will not be an `instanceof` any of them, because it will be of type `object`. This means that you have to write your own type guard that checks `kind` and `apiVersion`, but really this should just be exposed by the library itself.

Furthermore, if you _did_ want to use the official constructors in `api.ts`, you'd need to do something like the below:

```
const svc = new k8s.V1Service();
svc.metadata = new k8s.V1ObjectMeta();
svc.metadata.name = name;
svc.spec = new k8s.V1ServiceSpec();
```

Needless to say, this is not ideal.

## Justification for (3)

In addition to points (1) and (2), we're not exposing any methods or custom constructors on the API object `class`es in `api.ts`, so we're not getting any benefit from them being classes, and there are significant drawbacks.

[guards]: https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types

**Comment by brendandburns** [comment]
@hausdorff 

The API models object is generated from swagger codegen:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache

These changes seem reasonable to me, but they'll need to be done in that upstream project.

Thanks!

**Comment by brendandburns** [comment]
Closing this since swagger-codegen is the right place to fix this.
