### ISSUE TITLE
createNamespacedJob returns 204 No Content

### ISSUE THREAD

**Issue by jt274** [kubernetes-client/javascript#1412]
**Describe the bug**
The `createNamespacedJob` command returns a status code of `204 (No Content)` and no message body. The job is not created. This implies some kind of error, but the API is returning a success code, but with no error message and no confirmation message.

The below code example logs: `Created Job (204) No Content: undefined`

** Client Version **
`0.20.0`

** Server Version **
`1.27.3-gke.100`

**To Reproduce**
Run below example in 2nd Gen Cloud Function. Unsure if provided code will return the same result in another environment.

**Expected behavior**
According to docs here: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/#create-create-a-job

API should return a status code of `200 (OK)`, `201 (Created)`, `202 (Accepted)` or `401 (Unauthorized)`.

** Example Code**
```
import { BatchV1Api, KubeConfig, V1Job } from '@kubernetes/client-node';
const kc = new KubeConfig();
kc.loadFromDefault();
const k8sApi = kc.makeApiClient(BatchV1Api);

    const jobManifest: V1Job = {
        apiVersion: 'batch/v1',
        kind: 'Job',
        metadata: {
            name: 'my-name',
        },
        spec: {
            template: {
                spec: {
                    containers: [{
                        name: 'my-container-name',
                        image: 'myimage:latest',
                        env: [
                            {
                                name: 'MY_VAR',
                                value: value,
                            },
                        ],
                        resources: {
                            requests: {
                                cpu: '2',
                                memory: '4Gi',
                            }
                        },
                    }],
                    restartPolicy: 'Never',
                    nodeSelector: {
                        'tag1': 'test',
                    },
                },
            },
            backoffLimit: 2,
        },
    };

    await k8sApi.createNamespacedJob('default', jobManifest)
    .then((res) => {
        console.log(`Created Job (${res.response.statusCode}) ${res.response.statusMessage}: ${JSON.stringify(res.body)}`);
    }).catch((err) => console.error(`Error creating Job: ${JSON.stringify(err)}`));
```

**Environment (please complete the following information):**
 - OS: Google Cloud Functions 2nd Gen
 - NodeJS Version [18]
 - Cloud runtime [Google Cloud Functions 2nd Gen]

**Additional context**
IAM service account for cloud function has been given `Kubernetes Engine Developer` permissions and is connected to server through an internal VPC network.

**Comment by brendandburns** [comment]
We don't manipulate the status codes in the client. If you are getting a 204 that means the server is sending a 204. I suspect that there is some problem on your server side. Try looking at the server logs.

**Comment by brendandburns** [comment]
Please use the /reopen command if you need further assistance.
