### ISSUE TITLE
release-1.x branch unit test memory consumption increase

### ISSUE THREAD

**Issue by davidgamero** [kubernetes-client/javascript#1421]
this issue is to track the growth in memory usage when running `npm test`, which has lead to increasing the node memory as a stop gap

> i was able to make some progress isolating the gc memory issue- maybe we make a separate issue to track it
> 
> by executing nyc mocha with the --node-command inspect to enable debugging i was able to connect a memory profiler and get a GC snapshot and allocation timeline
> 
> the majority of the growing heap usage seems to be coming from SourceMapConsumer in node_modules/source-map/lib/source-map-consumer.js at the bottom of a pretty long call stack that includes @ babel/core
> 
> i found https://github.com/meteor/meteor/issues/9568 potentially relevant link that has encouraging similarities.
> 
> by changing nyc.instrument=false in package.json on line 51, the memory never exceeded 600MB, while re-enabling that line eventually balloons up to 12GB which was the most i was willing to test.
> 
> i will continue investigating upgrading our source-map indirect dependency so we can hopefully get this resolved

**Comment by mstruebing** [comment]
Note: We should be able to remove this line once we have success: https://github.com/kubernetes-client/javascript/blob/release-1.x/.github/workflows/test.yml#L28

**Comment by jgielstra** [comment]
FYI I think nyc is no longer maintained.
Last commit was ~3 years ago and there isn't any recent activity.
We've migrated to c8

**Comment by mstruebing** [comment]
This can be closed an was resolved in https://github.com/kubernetes-client/javascript/pull/1480
