### ISSUE TITLE
Do you have documentation?

### ISSUE THREAD

**Issue by harin** [kubernetes-client/javascript#15]
Where can I find the documentation for this client?

I am trying to scale my deployment, but the client doesn't appear to have the scale nor deployment command.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#deployment-v1-apps

**Comment by brendandburns** [comment]
Yeah, this client was generated from 1.8.x sources, we likely need to regenerate to pick up 1.9...

**Comment by loginakhil** [comment]
@brendanburns  could you please regenerate the client code to support 1.9 ?

**Comment by brendandburns** [comment]
@loginakhil Cool, thanks for the offer.

I just regenerated for 1.9.x and added docs.  The PR is here:

https://github.com/kubernetes-client/javascript/pull/17

You can get the next one.

Thanks!

**Comment by brendandburns** [comment]
Closing this as #17 is merged.
