### ISSUE TITLE
Is fieldSelector working correctly for listSecretForAllNamespaces?

### ISSUE THREAD

**Issue by jmsariron** [kubernetes-client/javascript#1510]
**Describe the bug**
I'm trying to list all secrets on a cluster with an specific name, but either I'm doing something wrong or something is not working fine. I can't find more info on this

** Client Version **
0.20.0

** Server Version **
1.26.8

**To Reproduce**
Run the code of the example in a cluster to try and get references to secrets with an specific name, but instead all secrets with different names are being show

**Expected behavior**
Show all secret references with an specific name

** Example Code**
```js
import { KubeConfig, CoreV1Api } from "@kubernetes/client-node";

const kc = new KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(CoreV1Api);

const main = async () => {
	try {
		const secrets = await k8sApi.listSecretForAllNamespaces({ fieldSelector: "metadata.name=access-token" });
		secrets.body.items.forEach(secret => {
			console.log("Secret with name: " + secret.metadata.name);
		});
	} catch (err) {
		console.error(err);
	}
};


main();
```

**Environment (please complete the following information):**
 - OS: Inside Cluster
 - NodeJS Version: 21.5.0

**Additional context**

**Comment by mstruebing** [comment]
hey @jmsariron I think your call to `listSecretForAllNamespaces` is wrong.
It needs to be something like this:

```js
		const secrets = await k8sApi.listSecretForAllNamespaces(undefined, undefined, "metadata.name=admin-user-token");
```

The signature of this method is (not a single object as an argument but rather a lot of individual optional arguments):
```
    listSecretForAllNamespaces(allowWatchBookmarks?: boolean, _continue?: string, fieldSelector?: string, labelSelector?: string, limit?: number, pretty?: string, resourceVersion?: string, resourceVersionMatch?: string, sendInitialEvents?: boolean, timeoutSeconds?: number, watch?: boolean, options?: {
        headers: {
            [name: string]: string;
        };
    }): Promise<{
        response: http.IncomingMessage;
        body: V1SecretList;
    }>;
```

Can you validate this works for you and if so, close the issue?

**Comment by jmsariron** [comment]
@mstruebing I can confirm you solution is working, sorry, thought named parameters that way was valid

**Comment by mstruebing** [comment]
I actually would like to have named parameters - easier to use especially with a lot of arguments - but I guess this will be a change in `kubernetes-client/gen` and I'm not sure if there's a strict convention for how the methods/functions of the the different clients are defined. But in my opinion definitely something to look into
