### ISSUE TITLE
There is no way to invoke legacy API with customObjects

### ISSUE THREAD

**Issue by spiddy** [kubernetes-client/javascript#152]
More specifically I'm interested in deleting custom objects through `deleteNamespacedCustomObject()` but without a `group` (e.g. for ConfigMaps that are on `v1` legacy version)

According to https://kubernetes.io/docs/reference/using-api/api-overview/#api-groups there are two types:

- The core (also called legacy) group, which is at REST path `/api/v1`
- The named groups are at REST path `/apis/$GROUP_NAME/$VERSION`

The `api.js` now only includes calls to `/apis/` with dynamic `{plural}` variable.

**Comment by spiddy** [comment]
Actually I was hoping to find the `/api/v1` migrated the named groups list from server-side, but I can't find it, so I suppose we're stuck having to support it.

**Comment by brendandburns** [comment]
This is all based off of the released swagger.json, so we can only support the paths in that swagger.

It's possible that it's present in an earlier version of this library.

Closing this issue b/c I don't think there's anything more we can do here.
