### ISSUE TITLE
exec command returns before command is executed

### ISSUE THREAD

**Issue by bodycombathuang** [kubernetes-client/javascript#1520]
async function func1() { 
const command = ['tar', 'zcf', '-'];
    command.push('-C', cwd);
    command.push(srcPath);
    const writerStream = fs.createWriteStream(srcPath+".tar")
    const errStream = new WritableStreamBuffer();

    await exec.exec(
        namespace,
        podName,
        containerName,
        command,
        writerStream,
        errStream,
        null,
        false,
        async ({ status }) => {
            writerStream.close();

            if (status === 'Failure' || errStream.size()) {
                throw new Error(`Error from cpFromPod - details: \n ${errStream.getContentsAsString()}`);
            }
            fs.createReadStream(`${srcPath}.tar`).pipe(tar.extract({cwd:tgtPath}));

        },
    );
}
func1()
fs.rmSync(srcPath+".tar"(

I run the above code, fs.rmSync throws the tar file does not exist error,  I feel the command is not executed immediately after exec finishes

**Comment by brendandburns** [comment]
exec returns a promise to the underlying WebSocket, not to the command execution. If you want to wait for the command execution to complete, you need to wait on that callback that you passed in (the function that calls `fs.createReadStream(...)`

**Comment by bodycombathuang** [comment]
hi @brendandburns  how to wait on that callback? 
https://github.com/kubernetes-client/javascript/blob/master/src/cp.ts, I can see a sample here, but I do not know how to wait on that callback, could you help me

**Comment by brendandburns** [comment]
You need to create a `Promise` before you make the call to `exec` and then resolve that promise within the callback. Then wait for that promise to complete before you move on after the `exec`

Details of promises here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
