### ISSUE TITLE
How to use this client with TokenVolume Projection

### ISSUE THREAD

**Issue by omerlh** [kubernetes-client/javascript#1528]
Hey,
I tried looking at the code but I couldn't figure how to do it. I am trying to use the more secure TokenVolume Projection to load short lived token instead of the long lived one, but I can't figure how to do it.

Can you please help me out with some examples?

**Comment by brendandburns** [comment]
You should use the `tokenFile` auth provider, there is an example here that uses the service account token:

https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L237

https://github.com/kubernetes-client/javascript/blob/088193ab93b9726318b7a5e3cf62dd97aefb19a9/src/file_auth.ts#L13

Hope that helps.

**Comment by omerlh** [comment]
So I guess I can't use the loadFromCluster method and has to copy most of it?

**Comment by brendandburns** [comment]
Are you trying to load from a file? Or from the service account in a Pod?

If you are trying to load from a service account in a Pod, `loadFromCluster` should just work.

Can you provide more details about your scenario?

**Comment by omerlh** [comment]
If I understand the code correctly, the code use the default long lived service account token (but maybe this is where I am wrong). I want to stop using the default token of the service account and use the TokenVolume projection to load a short lived token to a file and use this for authentication as it's more secure. Hope this is clearer.

**Comment by brendandburns** [comment]
ok, for that use case I would write a kubeconfig file that points to the right file location (using the `tokenFile` auth handler) and include that `kubeconfig` file in your Pod. Then you can use the methods that load a config from a file.

**Comment by omerlh** [comment]
What do you think about a PR supporting token volume projection? Given this is the recommended method and the more secure one. I can change `loadFromCluster` to support another env var, like `TOKEN_FILE_LOCATION` or something like that

**Comment by brendandburns** [comment]
Sure, if you want to send a PR for this that works for me.
