### ISSUE TITLE
Shell attached through `exec` is not sending line wraps correctly.

### ISSUE THREAD

**Issue by mateuszlewko** [kubernetes-client/javascript#1541]
Hi,

Thanks for the ts client for k8s api.

I'm starting a new shell instance within a container through exec, with tty. I set terminal width with `stty cols 80`. However after exceeding column width when text is supposed to wrap, the terminal doesn't return \n\r, instead it returns <space>\r. This naturally causes overriding of text in the current line, instead of going to the next line. It's a very unusual behavior. Do you have an idea what may be wrong?

** Client Version **
`0.20.0`

**To Reproduce**
Run the code below, send any characters N number of times. Expect `out` stream to print `\n\r` when text is supposed to wrap.

** Example Code**
```js
const in = new PassThrough();
const out = new PassThrough();

out.on("data", (data: Buffer) => { console.log(data); });

await ctx.k8s.exec.exec(
  "default",
  "ubuntu",
  "ubuntu",
  ['bash'],
  out,
  out,
  in,
  true /*tty*/,
  (status: k8s.V1Status) => {
    console.log('Exited with status:');
    console.log(JSON.stringify(status, null, 2));
  },
);
```

**Environment**
 - OS: macOS
 - NodeJS Version v21.6.1

** Other
Sending new line (e.g. pressing enter key) to the terminal works as expected -> it responds with new line.

**Comment by brendandburns** [comment]
The attempt to do terminal line resizing is here:

https://github.com/kubernetes-client/javascript/blob/master/src/exec.ts#L66

It wouldn't surprise me if it doesn't work perfectly, we'll gladly take PRs to fix it up (and add better tests!)

**Comment by mateuszlewko** [comment]
Thanks for the response!

I reviewed the code. The problem is not that the terminal doesn't know the column width, it's just that `\n` is not printed when wrapping the line.
So after sending many characters, the prompt after line wrapping looks like this:
```
extt@ubuntu:/# texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttex
```

Instead of
```bash
root@ubuntu:/# texttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttex
ttexttexttext
```

I'm still out of ideas where to look for the cause of this problem.

**Comment by brendandburns** [comment]
odd, I'm not sure about the cause either, my only thought is that perhaps it is in how the characters are being read from the stream, perhaps if you are reading line by line it doesn't show?

**Comment by mateuszlewko** [comment]
It turned out the problem was on my side. I'm using xterm.js on the frontend side connected to exec streams. I was not sending resize events from xterm to the exec's websocket handler. Some additional context can be found here: https://github.com/xtermjs/xterm.js/issues/4434#issuecomment-1482766980.
