### ISSUE TITLE
exec doesn't work on Windows,

### ISSUE THREAD

**Issue by Nurulla05** [kubernetes-client/javascript#1546]
I have custom function wrapper for exec function
``` 
  /**
   * Executes shell command inside pod container
   * @param {string} podName name of the pod to exec the command inside
   * @param {string} [containerName] name of the container in the pod to exec the command inside, default to container
   *     specified in kubectl.kubernetes.io/default-container annotation or the first container in the pod
   * @param {(string|string[])} command command or command and arguments to execute
   * @param {stream.Writable} [stdout] stream to write stdout data from the command
   * @param {stream.Writable} [stderr] stream to write stderr data from the command
   * @returns {Promise<WebSocket | {code: 0 | 1, stdout: string, stderr: string}>} promise which resolves with websocket
   * if both `stdout` and `stderr` params was specified, otherwise resolves with code, stdout and stderr command output
   */
async exec(podName, containerName, command, stdout, stderr) {
  if (stdout && stderr) {
    return this._exec(this._namespace, podName, containerName, command, stdout, stderr, null, false);
  } 
  const result = {stdout: '', stderr: ''};
  stdout = new Writable({
    write(chunk, encoding, callback) {
      result.stdout += chunk.toString();
      callback();
    }  
  });
  stderr = new Writable({
    write(chunk, encoding, callback) {
      result.stderr += chunk.toString();
      callback();
    }
  });
  const ws = await this._exec(
    this._namespace,
    podName,
    containerName,
    command,
    stdout,
    stderr,
    null,
    false,
    ({status}) => result.code = 
```

I'm using it on another library to perform operation on rook toolbox pod in rook-ceph-tools container.
`const result = await kubeClient.exec(rookCephToolsPod.metadata.name, 'rook-ceph-tools', command);`
toolbox commands works well, but when im trying to put some commands on my custom exec command it gives me
error: rool-ceph-tools: Error occured while executing sh , stderr: '', stdout: 'OCI runtime exec failed: exec failed:
 unable to start container process: exec: "sh ": executable file not found in $PATH: unknown
Ceph cluster deployed on minikube.

.

**Comment by mstruebing** [comment]
This looks rather like a problem with you container.
Can you execute `sh` in your pod by using kubectl?
I assume if you run `which sh` in your pod it doesn't show a path. Try running a command you know would succeed, i.e. `ls`?

**Comment by Nurulla05** [comment]
> This looks rather like a problem with you container. Can you execute `sh` in your pod by using kubectl? I assume if you run `which sh` in your pod it doesn't show a path. Try running a command you know would succeed, i.e. `ls`?

Hello! Thanks for reply. here is 

`kubectl exec -it deploy/rook-ceph-tools -n rook-ceph -- ls
bin  etc   lib    lost+found  mnt  proc  run   srv  tmp  var
dev  home  lib64  media       opt  root  sbin  sys  usr`


`kubectl exec -it deploy/rook-ceph-tools -n rook-ceph -- which sh
/usr/bin/sh`

Here is response for 'which sh' and 'ls' command on my pod.

**Comment by mstruebing** [comment]
I would try running `/usr/bin/sh` instead of `sh` even though it says that `sh` is not in your path it seems to be in your path.
This is probably a different issue than I've thought, sorry!

**Comment by brendandburns** [comment]
Can you provide a more complete code example? The code above is missing line breaks and it appears that you are passing `rook-ceph` as the container name in the `kubectl` example, but passing `rook-ceph-tools` in the code example, but I'm not certain.

Further code details will help narrow down the issue.

**Comment by Nurulla05** [comment]
> Can you provide a more complete code example? The code above is missing line breaks and it appears that you are passing `rook-ceph` as the container name in the `kubectl` example, but passing `rook-ceph-tools` in the code example, but I'm not certain.
> 
> Further code details will help narrow down the issue.

Hello! Thanks for reply. I provided code with linebreaks, sorry for previous code example. So as a pod name of rook-ceph-tools  i'm providing exactly the same pod name as it shown in ```kubecl get pods -n rook-ceph```. I appreciate your help!

**Comment by Nurulla05** [comment]
I found the issue, problem is not related to the OS. Here is simple solution that  exec function expects array of commands, for example: ['ceph', 'status']. So when u put one line command for example 'ceph status', it tries to go through the path and find the file which contains command to execute.
