### ISSUE TITLE
From 'kubernetes-client' to  '@kubernetes/client-node', HTTP Request failed

### ISSUE THREAD

**Issue by wukzu** [kubernetes-client/javascript#1555]
2.0.0
Server 1.28

I moved from the package 'kubernetes-client' to '@kubernetes/client-node'.
With the old package I was doing : 
```
const podsList = cluster.api.v1.nodes(nodeName).proxy('/pods')
```
With the newest, I do not see any good way to get the the pods list from a specific node.

I tried with the new one (at least what I found in the doc) : 
`const res = await cluster.k8sCoreClient.listPodForAllNamespaces()`
But I get an 'HttpError: HTTP request failed'.

Same error with cluster.k8sCoreClient.listNamespacedPod('namespace').

So I tried with axios : 
`const response = await axios.get(`${apiServerAddress}/api/v1/nodes/${nodeName}/proxy/pods``

But I get 'Request failed with status code 403'.  
Looks like the token is missing, an way to get it ?

Thank you

**Comment by brendandburns** [comment]
There's an example of making a `raw` request here:

https://github.com/kubernetes-client/javascript/blob/master/examples/raw-example.js

**Comment by brendandburns** [comment]
Closing since this is more of a request for help vs. an actual issue.

**Comment by wukzu** [comment]
I still have error 403 with request package
