### ISSUE TITLE
Punycode (core-bundled) deprecation from node 20 LTS

### ISSUE THREAD

**Issue by ed-25519** [kubernetes-client/javascript#1562]
Related to https://github.com/nodemailer/nodemailer/issues/1587

Any import from "punycode" will not import the userland module and instead the node core module is used.
This could be fixed by replacing "punycode" with "punycode/". An additional slash indicates this is not a node core module.

<details>
<summary>Deprecation logs:</summary>
<pre>(node:189270) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (......./node_modules/.pnpm/psl@1.9.0/node_modules/psl/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
</pre>
</details>

**Comment by ed-25519** [comment]
This was due to `psl` dependency and maybe this will be fixed with future version bumps.
https://github.com/lupomontero/psl/commit/3ddec00372501a4657d28fbd87e6fd59db12a897

**Comment by brendandburns** [comment]
In general we wait for dependabot to send updates for these kind of packages. I'm going to close this issue.

**Comment by very-doge-wow** [comment]
This problem still persists using node 22 and the latest version of kubernetes-client (0.22.0) today. Simply updating using dependabot doesn't seem to help here. I think the way the module is imported needs to be fixed?

**Comment by mstruebing** [comment]
We don't import/use punycode nor psl directly so we have no control about the code where it's used.
This can only be fixed by the package authors and we need to update the package.
Either something is really wrong or it will be fixed eventually by an dependabot update.

**Comment by very-doge-wow** [comment]
Got it, thanks

**Comment by nick123pig** [comment]
It's coming through the request library, of which you can read about the transition [here](https://github.com/kubernetes-client/javascript/blob/0ec6cc603aa29e6afcc3dbbce75ace1f58c889a7/FETCH_MIGRATION.md)
```
# npm ls punycode
├─┬ @kubernetes/client-node@0.22.2
│ └─┬ request@2.88.2
│   └─┬ tough-cookie@2.5.0
│     └── punycode@2.3.1
```

**Comment by dominykas** [comment]
It's not from `request` - at least not in v1.

In v1 it comes from here:

```
└─┬ @kubernetes/client-node@1.0.0
  └─┬ node-fetch@2.7.0
    └─┬ whatwg-url@5.0.0
      └── tr46@0.0.3
```

> Either something is really wrong or it will be fixed eventually by an dependabot update.

I wonder why dependabot isn't offering the upgrade to `node-fetch@3`? Is it configured to only offer security upgrades or smth? Upgrading to v3 makes the warning go away.

I think I also saw some people discussing using the built-in `fetch` directly? Is that an option?

**Comment by cjihrig** [comment]
> I wonder why dependabot isn't offering the upgrade to node-fetch@3?

I'm not sure that the [OpenAPI generator supports node-fetch@3](https://github.com/OpenAPITools/openapi-generator/blob/43f59bab8182ca446e00c1aa51b5ac496fd583de/modules/openapi-generator/src/main/resources/typescript/package.mustache#L49). If it does, then we might be able to use that since node-fetch@3 represents a move to ESM.

> I think I also saw some people discussing using the built-in fetch directly? Is that an option?

I think this is the ideal case. The biggest problem with that currently is that built-in fetch is listed as experimental until Node 21 (at the time of writing, Node 18 and 20 are still supported). Maybe that's not a big deal to folks. I'd personally take an experimental warning over a deprecation warning.
