### ISSUE TITLE
release-1.x examples line `kc.getCluster(currentContext) returns null

### ISSUE THREAD

**Issue by pauliusg** [kubernetes-client/javascript#1580]
With 1.0.0-rc4 I am running code similar to one in https://github.com/kubernetes-client/javascript/blob/release-1.x/examples/patch-example.js

And when running:
```
    let currentContext = kc.getCurrentContext();
    let currentCluster = kc.getCluster(currentContext);
```
currentCluster is null.

I guess that example code part is not right. For me working code is:
```
 const currentCluster = kc.getCurrentCluster();
```

I wrote example**s** in the title because similar code is in several examples.

**Comment by brendandburns** [comment]
Thanks for the issue report, I will investigate.

**Comment by maxpain** [comment]
Any updates on this?
