### ISSUE TITLE
create from object feature

### ISSUE THREAD

**Issue by zfrhv** [kubernetes-client/javascript#1595]
hello, i have been looking at the examples and couldn't find any example of creating from object function.  
like in the kubernetes python they have [create from dict](https://github.com/kubernetes-client/python/blob/df43d155d9252ab980bf5454e4b9574c5d5c7348/kubernetes/utils/create_from_yaml.py#L173) im looking for something similar for js.

all examples describe that in order to create an object you have to use function for that object.  
for example for creating namespace you have to run `k8sApi.createNamespace(namespace)`, but i want something like `k8sApi.createObject(namespace)`

**Comment by brendandburns** [comment]
There's not a really great example of this, you need an equivalent of the generic client in Java, but it doesn't exist.

The closest example is this "raw" example:

https://github.com/kubernetes-client/javascript/blob/master/examples/raw-example.js

Which you could use, but you'll need to be able to figure out the right HTTP path from the object before hand.

**Comment by zfrhv** [comment]
i see
thank you

why not to implement the this feature then? it seems pretty easy to do.
just take the object api version and kind, and easily you have the uri needed, like kubectl

i think it will very simplify the usage of this tool

**Comment by brendandburns** [comment]
We'd gladly take a PR implementing this if you want to send it.

**Comment by zfrhv** [comment]
alright, just so happens that i [already did it](https://github.com/zfrhv/hnc-ui/blob/main/image/k8s.js) ; )

i will create a seperate class called something like `k8sApi` instead of `CoreV1Api` sounds good?

it will take me few weeks tho, a little busy these days

**Comment by brendandburns** [comment]
Sounds great! Perhaps `GenericApi` ?

**Comment by zfrhv** [comment]
neat
