### ISSUE TITLE
Update api core to support kubernetes 1.9

### ISSUE THREAD

**Issue by loginakhil** [kubernetes-client/javascript#16]
For eg : `/apis/apps/v1beta1/deployments`  has moved into core now and the new url is `/apis/apps/deployments`

**Cluster version info :**

```

root@kubemaster:/home/test# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

```

Please update the apis

**Comment by hausdorff** [comment]
Note that upgrading to v1.9 will likely involve serious changes to `api.ts`. For example, `V1beta2Deployment` -> `IoK8sKubernetesPkgApisAppsV1beta2Deployment`, and so on.

**Comment by loginakhil** [comment]
Yeah i have seen those changes, either we should the refactor the existing repository to support all versions of kubernetes  apis or we should simply remove old (<1.9) version support

**Comment by brendandburns** [comment]
Changed to version `0.2.0` to indicate the potential changes from the `0.1.x` release set.

See:
https://github.com/kubernetes-client/javascript/pull/17

**Comment by brendandburns** [comment]
Closing since #17 merged.
