### ISSUE TITLE
Understanding when exec command has finished running

### ISSUE THREAD

**Issue by amitgilad3** [kubernetes-client/javascript#162]
i am uploading files to my kubernetes container and when i run the following code - i dont know exactly when the command has finished. 
const file = fs.createReadStream(tmpTarResultFile);//which I have and I can see it is a proper tgz
const uploadCommand = ["tar", "xzf", "-"];
Exec.exec(namespace, podName, containerName, uploadCommand, null, null, file, false);

is there a way to find out when the command is done??

**Comment by brendandburns** [comment]
`Exec` returns a `Promise<WebSocket>`. You can use the `WebSocket` API (reference here: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) to determine when the socket is closed/command is done.
