### ISSUE TITLE
Ability to send custom fetch options via `Watch`

### ISSUE THREAD

**Issue by chiragjn** [kubernetes-client/javascript#1656]
In the current client that depends on request we can pass an extra `requestImpl` in `Watch` which allows us to customize how various requests attributes like keepalive, timeouts, etc

On the new 1.x rc releases we see this option was removed entirely. We were wondering how can we pass on options for `applyToFetchOptions` via `Watch` API

**Example Code**
We are trying to port the the following code on the new node-fetch version

```typescript
import { KubeConfig, ListPromise, Watch, RequestResult } from '@kubernetes/client-node';
export const webRequest = (opts: OptionsWithUri): RequestResult => { 
    ...
    axios.request({
        ...
        httpsAgent: new Agent({
            ...
            keepAlive: true,
            keepAliveMsecs: 5000,
            timeout: 5000,
          }),
         ...
    })

}
...
const watch = new Watch(kubeConfig, { webRequest });
const informer = new Informer<T>(path, watch, listPromiseFn, enableCache);
```

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: 20.x
 - Cloud runtime N/A

**Comment by brendandburns** [comment]
I think we could probably add something similar for fetch. We'd be happy to take a PR to add this.
