### ISSUE TITLE
Add new function `readNamespacedJobLog` in the BatchV1Api

### ISSUE THREAD

**Issue by dalejo96** [kubernetes-client/javascript#1663]
I want to get the logs from a certain job, but I am not sure about the right API to use, since on the terminal I do:
```
kubectl logs job.batch/my-job
```
I was expecting to find the function `readNamespacedJobLog` but it is not present in the `BatchV1Api`

How could I achieve this?

I can work on the PR if you provide some guidance.

Let me know what do you think

**Comment by brendandburns** [comment]
In general this client tries to stay true to the Kubernetes RESTful API, and the logs call is associated with a Pod, not a Job.

The `kubectl` command is a short cut which looks up the Job and then finds the right pod (and then finds the logs)

We do have a hand-written `logs` client here:

https://github.com/kubernetes-client/javascript/blob/master/src/log.ts

If you wanted to add additional functionality there which got logs for Jobs (and other resources if you feel like it) that would be the best place to add it.

Thanks!

**Comment by dalejo96** [comment]
Here is my workaroud using `"@kubernetes/client-node": "^0.18.1"`
```ts
    const labelSelector = `${JOB_NAME}=${name}`;
    const podList = await k8sCoreApi.listNamespacedPod(
      namespace,
      undefined,
      undefined,
      undefined,
      undefined,
      labelSelector
    );

    if (!podList.body.items[0]) {
      throw new CustomError('Error getting pod', 404);
    }
    const podName = podList.body.items[0].metadata.name;
    const podRes = await k8sCoreApi.readNamespacedPodLog(podName, namespace);
```
Where `name` is the jobName
