### ISSUE TITLE
[question] support for Kubernetes 1.29 and 1.30

### ISSUE THREAD

**Issue by bydga** [kubernetes-client/javascript#1670]
Hey guys, this is more of a question - are you going to release the (probably) 0.21.0 - to support Kube 1.29? This version is already in the master branch (package.json), just not npm published yet...  I also can see there are some tags around 1.x.x release - so maybe your plan is to switch to "stable" semver versioning and continue releasing under that?

Thanks 🙏

**Comment by bydga** [comment]
maybe becasue of this 🤔 

https://github.com/kubernetes-client/javascript/actions/runs/8757784308/job/24037180091

**Comment by mstruebing** [comment]
There is something wrong with our publishing. I've restarted the job but it failed again.
I've packed it manually locally and the package seems fine to me so I'm not sure what's wrong.
Maybe an outdated access token cc @brendanburns ?

**Comment by brendandburns** [comment]
Yeah, I'll look into fixing this today, I think it is token expiration.

**Comment by brendandburns** [comment]
Ok, I updated the token and kicked off a release, we'll see if it works :)

**Comment by brendandburns** [comment]
Also, @bydga unless you need newer API features of 1.29 or 1.30, the existing client should work with those newer releases.

**Comment by brendandburns** [comment]
Looks like it worked. `0.21.0` is present on npm and supports kubernetes 1.29.

I will work on generating for 1.30 (and generating for the 1.x series too)

**Comment by brendandburns** [comment]
@mstruebing did we already generate release-1.x for kubernetes 1.29?

**Comment by mstruebing** [comment]
@brendandburns In our settings file in the release-1.x branch we use: `export KUBERNETES_BRANCH="v1.28.4"`: https://github.com/kubernetes-client/javascript/blob/master/settings so I assume we did not ever release anything newer than that yet.

In response to this (and other issues) I created a new release back in december: https://github.com/kubernetes-client/javascript/issues/1397 but it's not possible to see the logs of the action anymore which might give some additional clues: https://github.com/kubernetes-client/javascript/actions/runs/7308941612

Last time the code was regenerated in the release-1.x branch is this commit (1st december 2023) if I did not oversee something: https://github.com/kubernetes-client/javascript/commit/062807ce74e1fa3170f40ba2082016f7f8a0e8ab
But I strongly believe this was with 1.28.4: https://github.com/kubernetes-client/javascript/commit/2554f7ed71ba94670df6025e2f57ef3bafc7cc12

**Comment by brendandburns** [comment]
Actually it looks like we override the kubernetes version here:

**Comment by brendandburns** [comment]
Just pushed `1.0.0-rc5` which contains support for 1.29.x will push `1.0.0-rc6` eventually with support for 1.30

**Comment by brendandburns** [comment]
`1.0.0-rc6` now supporting Kubernetes 1.30 has been pushed to npm.

**Comment by RCMainak** [comment]
Will there be any release on 0.X.X version to support Kubernetes 1.30? @brendandburns

**Comment by brendandburns** [comment]
@RCMainak yeah, we need to cut a `0.22.0` release, I'll try to get that done soon. To be clear, the current client should work with 1.30 clusters for most (nearly all) use cases, except for any features added in the 1.30 release.
