### ISSUE TITLE
Only sinceSeconds may be specified as a queryString for LogOptions interface

### ISSUE THREAD

**Issue by UltraSive** [kubernetes-client/javascript#1673]
**Description:**
The `LogOptions` interface in the `Log` class does not allow the `sinceTime` parameter to be specified. According to the Kubernetes API documentation, either `sinceSeconds` or `sinceTime` may be specified, but the current implementation only supports `sinceSeconds`.

**Expected Behavior:**
Users should be able to specify `sinceTime` in addition to `sinceSecond` in the `LogOptions` interface.

**Current Behavior:**
Only `sinceSeconds` is supported, and attempting to use `sinceTime` results in an error.

**Steps to Reproduce:**
Try to use the `sinceTime` parameter in the `LogOptions` interface.

**Environment:**

Kubernetes Client: `@kubernetes/client-node`
Node.js version: `v18.16.0`
Proposed Solution:
Allow the `sinceTime` parameter to be specified in the `LogOptions` interface, similar to `sinceSeconds`.

**Where to modify:**
https://github.com/kubernetes-client/javascript/blob/b456bfc8585c87cd54e29d2631349377cc0d5a49/src/log.ts#L6-L45

**Comment by brendandburns** [comment]
We'd be happy to take a PR for this.

**Comment by UltraSive** [comment]
@brendandburns If I simply add the option onto the LogOptions interface the request builder looks like it should take care of it, but in my testing after creating the option it is not added as a query string request or exists as an argument to a method like readNamespacedPodLog(). Am I missing something?

https://github.com/UltraSive/k8s-javascript-client/commit/ab16a2417441267a75cf9a04ab541a8998836d0e

**Comment by brendandburns** [comment]
Are you using this call here:

https://github.com/kubernetes-client/javascript/blob/master/src/log.ts#L54

**Comment by brendandburns** [comment]
`readNamespacedPodLog` doesn't really work right since pod logs are a non-standard API

**Comment by VasuDevrani** [comment]
Hey @UltraSive is this whats expected:
1. In the `log` method, before constructing the request options, we check if both sinceSeconds and sinceTime are provided in the options object. If both are present, we throw an error indicating that only one of them may be specified.

2. In the `requestOptions` object, we include both sinceSeconds and sinceTime properties in the qs (query string) object. If sinceTime is provided, we convert it to string.

**Comment by cjihrig** [comment]
I think this can be closed since https://github.com/kubernetes-client/javascript/pull/1899 was merged. I'm a bit surprised that it didn't auto-close.
