### ISSUE TITLE
missing fieldValidation option in. customObjectsApi

### ISSUE THREAD

**Issue by PickleTicklewithnospace** [kubernetes-client/javascript#1678]
Is there a way to enable strict validation in the `customObjectsApi`? Right now, if we dry run a `createNamespacedCustomObject()` call, we can't validate that there are no unknown fields since the default seems to be set to ignore. 

In the [java client, the option exists](https://github.com/kubernetes-client/java/blob/master/kubernetes/docs/CustomObjectsApi.md#createNamespacedCustomObject).

I've tried playing around with `addInterceptor` but can't seem to get the validation to work.

**Comment by brendandburns** [comment]
Can you try the 1.0rc4 version of the library? I think that it is present there.

We locked the older client to an older version of the kubernetes-client/gen repo (https://github.com/kubernetes-client/gen)

If we want this in the older client, we'll need to cherry-pick this PR when we generate:
https://github.com/kubernetes-client/gen/pull/260

But given that the `0.X` client is on the path to deprecation, I'm not positive that we want to do that.

**Comment by PickleTicklewithnospace** [comment]
Doesn't seem like the `ObjectCustomObjectsApi` (e.g. `CustomObjectsApiCreateNamespacedCustomObjectRequest`) has the `fieldValidation` arg in `1.0.0-rc4` 

Would you happen to know of any other solution to get this validation to work? Thanks!

**Comment by brendandburns** [comment]
To get it to work, we need to regenerate the client with the updated openapi definition. That means cherry-picking that commit in when we do the generation here:

https://github.com/kubernetes-client/javascript/blob/master/.github/workflows/generate-javascript.yml#L35

If you want to send a PR to update that, we can try regenerating and see if it fixes things.
