### ISSUE TITLE
No release notes or git tag for 0.21

### ISSUE THREAD

**Issue by meganwalker-ibm** [kubernetes-client/javascript#1679]
**Describe the bug**
0.21.0 was recently released to npm.
<img width="808" alt="Screenshot 2024-05-08 at 15 15 50" src="https://github.com/kubernetes-client/javascript/assets/20321922/5eb7f9e5-154b-413e-9faa-dc60a2e70773">

However this repository contains no git tag nor github release (which the prior 0.20.0 release did have), and the CHANGELOG.md is years out of date

** Client Version **
0.21.0

** Server Version **
n/a

**To Reproduce**
Look at the github releases and tags

**Expected behavior**
The release should correspond to a tag, and there should be documentation on the changes in the release.

** Example Code**
N/A
**Environment (please complete the following information):**
N/A

**Additional context**

**Comment by mstruebing** [comment]
@brendanburns is there something up with our release action or was this on purpose?

I can see this action was run and published the 0.21.0 release on npm: https://github.com/kubernetes-client/javascript/actions/runs/8942108125/job/24563952014

In the logs I can see that the git tag step ran but it only outputs `git tag` without a version and the push tag step outputs that everything is up t o date.

So I would think the git tag step wouldn't even run if you would have checked the `skip_tag` input, but I may misinterpret the logs.

**Comment by brendandburns** [comment]
Ah, this is a bug here:

https://github.com/kubernetes-client/javascript/blob/master/.github/workflows/release.yml#L57

it references `$...version` but the actual parameter is `$...releaseVersion`

I'll send a PR.

**Comment by brendandburns** [comment]
I just manually pushed a tag for the release (it was at commit b456bfc8585c87cd54e29d2631349377cc0d5a49)

**Comment by brendandburns** [comment]
And release notes are added too. Closing this issue.
