### ISSUE TITLE
Some questions about APIs

### ISSUE THREAD

**Issue by masalinas** [kubernetes-client/javascript#171]
Whats the diferente from Core_v1Api, Apps_v1Api, etc. ?

For example inside Core_v1Api not exist the function: listDeploymentForAllNamespaces and under Apps_v1Api yes.

Exist more documentation about this question?

Regards

**Comment by flyboarder** [comment]
This is related to how k8s breaks up the api, I recommended reading their documentation.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/

**Comment by brendandburns** [comment]
Specifically, the first part is the 'apiGroup' it's where the default '' api group is called 'Core'

Closing since I think this is answered.
