### ISSUE TITLE
Can this send raw queries to Kubernetes API?

### ISSUE THREAD

**Issue by ypjin** [kubernetes-client/javascript#175]
Hi! 
I'm trying to use this library with Resource Metrics API. Since it does not have such support I'm wondering if it can send raw queries to Kubernetes API. Similar to this https://github.com/kubernetes-client/python/issues/528#issuecomment-402304007.

Thanks and best regards!

**Comment by brendandburns** [comment]
I believe that if you use the `Config.applyToRequest(...)` method here:

https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L146

It should work correctly.

**Comment by brendandburns** [comment]
I validated this and added an example in #181

Closing this since it is answered.

**Comment by ypjin** [comment]
That's perfect. Thanks a lot @brendandburns !

**Comment by jdmaguire** [comment]
@brendanburns You are my hero.
