### ISSUE TITLE
listNamespacedIngress response format

### ISSUE THREAD

**Issue by cabrinoob** [kubernetes-client/javascript#176]
Hi,
I'am using the method `listNamespacedIngress` of `Extensions_v1beta1Api` class and I have a comment on the object format returned. 

 ```
k8sClient.listNamespacedIngress(currentNamespace).then((data)=>{ ... })
```
In the snippet above, the data object have a `body` property which contains an `items` array which contains all ingress objects in _currentNamespce_. But these `ingress` objects lack the **kind** and **apiVersion** properties.

They just have `metadata`, `specs` and `status` properties. I have to encrich them manually to make those objects "valid". 

Is this behavior normal? Or this is a bug?

Thank you

**Comment by brendandburns** [comment]
What happens when you list other objects? If it is only Ingress then it's definitely a bug.

If it does the same thing for other objects then we'll need to investigate further to see what the "correct" behavior is.

**Comment by brendandburns** [comment]
So I used `kubectl --v=10 get ingress` which dumps the raw body, and the raw body that I saw was:

```json
{
   "apiVersion" : "extensions/v1beta1",
   "metadata" : {
      "selfLink" : "/apis/extensions/v1beta1/namespaces/default/ingresses"
   },
   "items" : [
      {
         "metadata" : {
            "namespace" : "default",
            "name" : "cafe-ingress",
            "selfLink" : "/apis/extensions/v1beta1/namespaces/default/ingresses/cafe-ingress",
         },
         "status" : {
            "loadBalancer" : {}
         },
         "spec" : {
            "tls" : [
               {
                  "hosts" : [
                     "cafe.example.com"
                  ],
                  "secretName" : "cafe-secret"
               }
            ],
            "rules" : [
               {
                  "host" : "cafe.example.com",
                  "http" : {
                     "paths" : [
                        {
                           "path" : "/tea",
                           "backend" : {
                              "servicePort" : 80,
                              "serviceName" : "tea-svc"
                           }
                        },
                        {
                           "backend" : {
                              "serviceName" : "coffee-svc",
                              "servicePort" : 80
                           },
                           "path" : "/coffee"
                        }
                     ]
                  }
               }
            ]
         }
      }
   ],
   "kind" : "IngressList"
}
```

And similarly for Pods.

So it looks like that's the way `*List*` objects come back via JSON. I suspect that in Go what happens is that that JSON is converted to a Golang object and then _back_ to JSON, and somehow in doing that the kind is populated.

So I'm going to close this for now. Feel free to re-open if you think there's something that we should do here, perhaps we could add default values to the OpenAPI spec?
