### ISSUE TITLE
1.0.0-rc6 - Patch content-type override doesn't take effect

### ISSUE THREAD

**Issue by impatient** [kubernetes-client/javascript#1836]
**Describe the bug**
Override of content type via middleware does not take effect.  Had to use work around listed here.

https://github.com/kubernetes-client/javascript/issues/1499

** Client Version **
1.0.0-rc6

** Server Version **
1.28.11

**To Reproduce**
Attempt to set StrategicMergePatch using middleware on the 1.0 client

**Expected behavior**
The middleware to take effect.  

** Example Code**
https://github.com/nullplatform/k8s-lease-lock/commit/6b189fd6fa8f001f96d61a52f835cce691edff3a#diff-d8eee3b9c50488b328e4b9805b642354ccbaefadf361cbd9bd763925ed61ebeaR50 

Wrapped in authMethods as a workaround.  As mentioned in linked ticket. 

**Environment (please complete the following information):**
Node 20.11

**Additional context**
Other ticket closed as not planned.  Would you welcome a PR with documentation on this as a workaround or add it to the examples?  Also, the case of Content-Type on header seemed to need to match exactly.  Assume all issues are due to the generator, but might be worth it to expose a wrapper for middleware that hides this or at least some documentation.  

Likely issue: https://github.com/OpenAPITools/openapi-generator/issues/14549

Not sure how often people will run into this, but wanted visibility that it was still an issue that people were running into.

**Comment by brendandburns** [comment]
I reopened #1499 and I'm going to close this issue in favor of that issue.

We'd definitely welcome a PR to fix this. The generator team is usually very responsive to fixes in the generator.
