### ISSUE TITLE
Missing Content-Type header on patch operation

### ISSUE THREAD

**Issue by VEBERArnaud** [kubernetes-client/javascript#19]
Hi,
Everytime I try to patch a node, I hit a HTTP 415
`the server responded with the status code 415 but did not return more information`.

After some researches, I found that the API wait for `Content-Type: application/strategic-merge-patch+json` header for PATCH operations.
But this header is not set.

Is there any way I can override headers before sending the request ?

**Comment by brendandburns** [comment]
If you override `this.defaultHeaders` on the client object it _should_ work, search for `let headerParams: any = (<any>Object).assign({}, this.defaultHeaders);` in `api.ts`

**Comment by VEBERArnaud** [comment]
thanks,

**Comment by danigian** [comment]
@brendandburns this is still an issue.

If I change the api.js to include the Content-Type: application/strategic-merge-patch+json header it works.

Is there a way to definitely solve the problem?

**Comment by runarberg** [comment]
Shouldn't `PATCH` operations have the `Content-Type` header set to `application/strategic-merge-patch+json` by default. It is kind of annoying to use this client if you have to mutate the client object before every patch operation.

**Comment by markanderstam** [comment]
@runarberg I agree this is what's missing. The swagger [spec](https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/apps_v1.json#L5314) clearly states that this endpoint "consumes":  `["application/json-patch+json", "application/merge-patch+json", "application/strategic-merge-patch+json"]`.

And since this file is generated from the swagger spec I'm guessing something have to be done over at [swagger-codegen](https://github.com/swagger-api/swagger-codegen) or at the [gen](https://github.com/kubernetes-client/gen) part of this project. @brendanburns could you help out to answer this? I started looking at a permanent solution but it was a lot to go through.

**Comment by brendandburns** [comment]
@markanderstam 

There are two places that you might want to edit:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L287

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L379

That second one actually looks most promising...

I think you'll want to update the mustache file with something similar to this here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/apex/api.mustache#L96

Let me know if you want to take a stab at it.

Alternately, I can see if I get around to it.

**Comment by SchwarzM** [comment]
why is this closed ? it is still not the default behaviour of patch operations.

**Comment by brendandburns** [comment]
There's a workaround (see setting 'defaultHeaders' above)

I'm ok to reopen of someone wants to work on a more complete solution.

**Comment by msonnabaum** [comment]
I also just hit this. I have to agree that the client isn't providing much value if we have to apply workarounds for existing methods to work.

**Comment by msonnabaum** [comment]
Actually, I don't quite understand how this is even a workaround. I don't see any method on the client that lets me set the request headers.

If I try to set the property directly, I get:

```
error TS2445: Property 'defaultHeaders' is protected and only accessible within class 'Core_v1Api' and its subclasses.```

**Comment by brendandburns** [comment]
@msonnabaum you can extend from the client and update the `defaultHeaders` field.

subclasses can access that field.

**Comment by msonnabaum** [comment]
Right, that makes sense.

This seemed to work to solve my immediate problem:

```typescript
class PatchedK8sApi extends k8s.Core_v1Api {

  patchNamespacedConfigMap(...args) {
    const oldDefaultHeaders = this.defaultHeaders;
    this.defaultHeaders = {
      "Content-Type": "application/strategic-merge-patch+json",
      ...this.defaultHeaders,
    };
    const returnValue = super.patchNamespacedConfigMap.apply(this, args);
    this.defaultHeaders = oldDefaultHeaders;
    return returnValue;
  }
}
```

I appreciate you reopening the issue though so we can get a client-side fix in.

**Comment by silasbw** [comment]
I can take a pass at trying to change swagger-codegen.

I created an issue on swagger-codegen https://github.com/swagger-api/swagger-codegen/issues/9035 and created a strawperson proposal for a solution https://github.com/swagger-api/swagger-codegen/pull/9036.

**Comment by SchwarzM** [comment]
since @silasbw proposal was accepted, can we now get this into the client ?

**Comment by Obirah** [comment]
For anyone who's stumbling across this issue and needs a workaround similar to the one of @msonnabaum but a bit more generic:

```
const coreApi = kc.makeApiClient(PatchedCoreV1Api);

const patch: any = { spec: { replicas: 0 } };
const patchDeploymentOperation = () => appsApi.patchNamespacedDeployment('your-deployment', 'your-namespace', patch);
console.log(await appsApi.patchApiCall(patchDeploymentOperation));

class PatchedAppsV1Api extends k8s.Apps_v1Api {

    patchApiCall<T>(patchOperation: () => Promise<{ response: http.IncomingMessage; body: T; }>): Promise<{
        response: http.IncomingMessage;
        body: T;
    }> {
        const oldDefaultHeaders = this.defaultHeaders;
        this.defaultHeaders = {
            "Content-Type": "application/strategic-merge-patch+json",
            ...this.defaultHeaders,
        };
        const returnValue = patchOperation();
        this.defaultHeaders = oldDefaultHeaders;
        return returnValue;
    }
}
```

**Comment by silasbw** [comment]
Oops, I never circled back around to this.  The change I mentioned [here](https://github.com/kubernetes-client/javascript/issues/19#issuecomment-451821642) was merged into swagger-codegen (https://github.com/swagger-api/swagger-codegen/pull/9036) and I created a PR for the OpenAPITools/openapi-generator (https://github.com/OpenAPITools/openapi-generator/pull/1868) that was also merged.

I haven't been paying attention to the swagger-codegen, but the feature is included in the [v4.0.0 release](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.0.0) of openapi-generator.  **Rebuilding the client with that version** should add an `options` argument to calls, where users can override headers by setting an `options.headers` object.

E.g.,

```js
const headers = { 'content-type': 'application/strategic-merge-patch+json' }
patchNamespacedDeployment(name, namespace: string, body, null, null, { headers }) 
````

or whatever

**Comment by silasbw** [comment]
I've confirmed that users can specify override headers to each REST call.  Close this issue?  @brendandburns

**Comment by brendanburns** [comment]
Sgtm

/close

**Comment by TheHolyWaffle** [comment]
Ok, we have the workaround nowadays to specify custom http headers with request , as described in https://github.com/kubernetes-client/javascript/issues/19#issuecomment-497534040. But this still is not the real solution to PATCH calls. 

Why is "Content-Type": "application/merge-patch+json" simply not the default for patch operations? :(

**Comment by J12934** [comment]
For anyone still running into this, the solution suggested doesn't work as described anymore as the function signature has changed slightly. 

The function now has more args which need to come before the options array, also passing `null` makes the api client pass empty values for dryRun and co. instead of skipping it. Passing `undefined` instead of `null` works for me.

What works for me (`@kubernetes/client-node@0.11.1`) is:

```js
const headers = { 'content-type': 'application/strategic-merge-patch+json' }
patchNamespacedDeployment(name, namespace, body, undefined, undefined, undefined, undefined, { headers }) 
```
