### ISSUE TITLE
What is the release schedule?

### ISSUE THREAD

**Issue by elvisace** [kubernetes-client/javascript#194]
Hello,

I see that `ttlSecondsAfterFinished` on `V1JobSpec` has been added in master in January. The latest release was on `Oct 19, 2018`.

Any idea when there will be another release (including the ttl changes)?

Thanks!

**Comment by flyboarder** [comment]
There was a recent release to `0.8.0`

**Comment by brendandburns** [comment]
As @flyboarder mentions, there was a release 4 days ago, that should include that change.

Closing this issue, please re-open if you need more info.

Thanks!

**Comment by elvisace** [comment]
Thanks!!
