### ISSUE TITLE
Why is `@types/js-yaml` not listed in `devDependencies`?

### ISSUE THREAD

**Issue by kylejb** [kubernetes-client/javascript#1962]
I am curious to better understand why it was not listed as a dev dependency. I would expect most, if not all `@types/*`, to be.

It has a minor impact upstream:

1. I get erroneous errors that I have to ignore. 
    <img width="1125" alt="Screenshot 2024-10-22 at 13 39 41" src="https://github.com/user-attachments/assets/9db59b6e-4734-4ebf-96cc-784ab05fb215">
2. I think it stems from it's declaration as a prod dependency.
    <img width="423" alt="Screenshot 2024-10-22 at 13 33 39" src="https://github.com/user-attachments/assets/97b4dfec-bf85-4c7e-a7b9-ff0f09415214">

### FYI

- Node version: 20.18.0
- NPM version: 10.9.0

**Comment by brendandburns** [comment]
I think it's probably just a question of whether someone took the time to add it. Happy to take PRs to add any missing @types dependencies to `devDependencies`

**Comment by kylejb** [comment]
> Happy to take PRs to add any missing @types dependencies to `devDependencies`

Thanks for answering! I can take that on. 

I don't think anything is missing from the project. I will just move the @types dependencies to `devDependencies`.
