### ISSUE TITLE
Help resolve request, tough-cookie has CVEs 

### ISSUE THREAD

**Issue by midhun1114** [kubernetes-client/javascript#2017]
Since request is deprecated , it has vulnerabilities and the tough-cookie package also has CVEs

version: 0.22.2

**Comment by brendandburns** [comment]
If you are concerned about these CVEs, please use release 1.0.0-rc7 https://www.npmjs.com/package/@kubernetes/client-node/v/1.0.0-rc7

Duplicate of #414
