### ISSUE TITLE
Thoughts on using prettier for code?

### ISSUE THREAD

**Issue by sheldonkwok** [kubernetes-client/javascript#203]
Prettier is becoming more standard across Typescript repos and enforces an acceptable style. Thoughts on introducing it to the code base? I saw that tslint was added somewhat recently.

**Comment by brendandburns** [comment]
I don't have strong feelings one way or the other.

@drubin @itowlson what do you think about prettier vs tslint?

**Comment by drubin** [comment]
Seems like `tslint` is still required for a bunch of rules not purely related to styling, like unused vars.

https://alexjover.com/blog/use-prettier-with-tslint-and-be-happy/ 

I don't have strong views I think as long as we maintain a consistent style that also does basic checking that we also get with tslint.

**Comment by sheldonkwok** [comment]
I personally use both tslint and prettier. Prettier is definitely heavily opinionated and has few configuration options because it wants you to stick to their style. It's very consistent and I didn't have enough reasons to vehemently object to anything. This doesn't really apply as much to this project but style consistency across repos in an org is nice. Prettier is also popular enough that you can somewhat get style consistency across many popular JS/TS repos.

I just ran prettier with `prettier --tab-width 4 --print-width 120 --trailing-comma all --write *.ts`
Most of the "fixes" are coming from single quote double quote consistency and type declaration consistency for functions and classes. For example 

```
public async exec(namespace: string, podName: string, containerName: string, command: string | string[],
                      stdout: stream.Writable | null, stderr: stream.Writable | null, stdin: stream.Readable | null,
                      tty: boolean,
                      statusCallback?: (status: V1Status) => void): Promise<WebSocket> {
```

became

```
public async exec(
    namespace: string,
    podName: string,
    containerName: string,
    command: string | string[],
    stdout: stream.Writable | null,
    stderr: stream.Writable | null,
    stdin: stream.Readable | null,
    tty: boolean,
    statusCallback?: (status: V1Status) => void,
): Promise<WebSocket> {
```

editorconfig looks reasonable as well. Due to the nature of the fixes I saw, it could probably work as well. I personally prefer prettier because of the consistency reason but I'm open to editorconfig because I think we should definitely have something. The Typescript repo uses it https://github.com/Microsoft/TypeScript/blob/master/.editorconfig 

I can commit the prettier changes on my fork if you want to see them.

**Comment by brendandburns** [comment]
Sure, I'd be happy to see the PR with the changes. I lean towards editorconfig since it's what the mainstream typescript repo uses...

**Comment by sheldonkwok** [comment]
https://github.com/sheldonkwok/javascript/commit/9f7482c9ba0ece0460abfa041882dc2bdb0cab30

**Comment by sheldonkwok** [comment]
- A majority of the changes are `'` vs `"` which is something that editorconfig doesn't support.
- The second class of changes seem to be around how people expand a long line onto multiple lines. There are several styles incorporated into the repo and it would be nice if they were more consistent. 
 
The editorconfig on the ts repo seems to mainly enforce spacing.

**Comment by brendandburns** [comment]
@sheldonkwok these look pretty reasonable to me.  Personally, I prefer `'` to `"`, I think that's a Python influence :)

Any chance you can do a different PR with editorconfig so that we can compare?

Sorry to make you jump through the hoops, but this seems like the kind of decision we should only make once...

**Comment by drubin** [comment]
I use editor config for a bunch of different projects but the scope is incredibly limited see https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties. This is not a replacement for linting/formatting per lang.

I think it actually makes sense to implement both. EditorConfig is more widely supported by IDE's out the box and potentially prettier to deal with the more typescript formatting like the method signature styling (which I find way more readable)

I don't think a side by side comparison will do it justice as they solve a few different issues.

So my take 

1.  We should implement a basic `.editorconfig` regardless.
2. Decide which rules (if any) we want to move from tslint to prettier
3. Make a PR comparing those? (I think we have done that)

**Comment by sheldonkwok** [comment]
Maybe we can use https://www.npmjs.com/package/tslint-config-prettier ?

I actually also prefer `'` :) 
I pushed a new change out to see the diffs with `'` 
https://github.com/sheldonkwok/javascript/commit/dc8ea4b3d5f259e3524b9579d200dfc237b0dc4e

**Comment by brendandburns** [comment]
These changes LGTM!  @sheldonkwok can you craft this into a PR with the relevant config files (and possibly instructions in README.md too?)

Thanks!

**Comment by drubin** [comment]
Is it possible to use https://palantir.github.io/tslint/rules/object-literal-key-quotes/ `"consistent-as-needed"` I always find it pretty odd to have some properties quoted as others not?

From the changeset 

```js
       'client-certificate': certFile,
       'client-key-data': keyData,
       'client-key': keyFile,
       password: password,
       username: username,
```

Not sure what everyone else thoughts are? @brendanburns @itowlson

**Comment by sheldonkwok** [comment]
I like that rule. Shouldn't need extra quotes. Will submit a mr

**Comment by sheldonkwok** [comment]
Unfortunately, prettier does not support that rule

**Comment by drubin** [comment]
@sheldonkwok thanks for trying. It just hurts my eyes a little when things don't line up, but it's currently the way it is.
