### ISSUE TITLE
feat: Possibility to create/update multiple objects from YAML or concatenated YAML

### ISSUE THREAD

**Issue by buehler** [kubernetes-client/javascript#206]
Hey there!

Thank you for this api, it's a very useful tool.
I built a wrapper around `kubectl` to actually ease some deployments and fix some issues with those deployments.

Now what bugs me (I'm currently thinking about using `@kubernetes/client-node` in my CLI tool):
is it possible to actually make something like `kubectl apply -f ./`?

So the use-case would be:

I've got a folder in my repository with kubernetes yaml definitions:

./root
--/
--/ k8s
----/ ingress.yml
----/ service.yml

Now my cli tool did read all those files, replaced some environment variables and write them back into a `deployment` folder. After the files are located in the deployment folder, it executes `kubectl apply -f ./deployment`.

I saw, that the api definition contains methods like `createNamespacedSecret` and / or other methods. Is it possible with the raw or yaml method (from the examples) to actually create multiple items at the same time (while not knowing what they are)?

So it would be like:
1. read the files
2. replace the variables
3. concat into one big string with yaml delimiteres like the following example:

```yaml
kind: Ingress
#...
---
kind: Service
#...
---
kind: Deployment
#...
```

4. Throw the whole big yaml to kubernetes to create the requested resources like
    `kc.createFromYaml(myBigYaml);`

Thanks for the work and your time!
Cheers

**Comment by brendandburns** [comment]
Do you really want the 'apply' functionality, meaning "create if not exists"?

Or do you just need "Create multiple objects from YAML"

The first one is fairly hard to implement and will likely not do it in favor of the forthcoming [server-side apply](https://github.com/kubernetes/enhancements/issues/555)

The second is definitely a reasonable feature request.

Let me know what you think (and if it is the second, can you change the issue title to reflect that subject)

Thanks!

**Comment by buehler** [comment]
Actually kinda "both"? :-) 
I mean, when `apply` is executed, it creates resources and if they already exist (I was assuming this is magic by the kubernetes master) it does patch / update the resources. (Am I wrong on this assumption?)

I'm not a `go` pro, so I looked over into the kubectl apply repository code and saw that they map their yamls to whatever magic in go :-)

But actually I meant that you can create multiple objects from YAML or concatenated YAML(s).

What do you think about this?

**Comment by brendandburns** [comment]
Unfortunately, currently the "create if not exists" part of the code is in the `kubectl` tool, not in the server.

There is ongoing work to move it from client to server. Because of that, I don't think it's worth the time to implement it in this client (though if someone else wanted to do it, I'm open to accepting a PR).

So for the time being "apply" == "create if not exists" won't be possible from this library.

You can load multiple objects using:

`loadAll(...)`:
https://github.com/kubernetes-client/javascript/blob/master/src/yaml.ts#L7

The create part is trickier but possibly do-able, I'll have to see how hard it is.
