### ISSUE TITLE
Improve the release process

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/javascript#208]
For example, we need to add a tag to git, probably should automatically rev package.json and package-lock.json...

**Comment by buehler** [comment]
I'd strongly suggest semantic release.

If you wouldn't mind, I could provide some help with that. Currently I'm working heavy with semantic release and the adjacent systems

**Comment by sheldonkwok** [comment]
A lower cost solution for now could also be to use the `npm version` command to manage package versions and git tags. https://docs.npmjs.com/cli/version.html

**Comment by drubin** [comment]
`npm version` uses a slightly different tagging system it uses `v0.1.1` vs `0.1.1` it also doesn't actually ask for confirmation and push and publish. 

But maybe we should look at https://github.com/sindresorhus/np @brendandburns before we merge the bash?
