### ISSUE TITLE
createNamespacedDeployment not available

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [kubernetes-client/javascript#21]
Hi! I'm using 0.2.1 and i've noticed that createNamespacedDeployment is not available on `Core_v1Api`
It is available only under Apps_v1Api but it is not clear for me how to use it
Can you point me in some direction please?

**Comment by brendandburns** [comment]
Look at the code here:

https://github.com/kubernetes-client/javascript/blob/master/node-client/src/config.ts#L186

You need to do something similar but replace `Core_v1Api` with `Apps_v1Api`

```js
    public static defaultClient(): api.Core_v1Api {
        if (process.env.KUBECONFIG) {
            return Config.fromFile(process.env.KUBECONFIG);
        }

        let config = path.join(process.env.HOME, ".kube", "config");
        if (fs.existsSync(config)) {
            return Config.fromFile(config);
        }

        if (fs.existsSync(Config.SERVICEACCOUNT_TOKEN_PATH)) {
            return Config.fromCluster();
        }

        return new client.Apps_v1Api('http://localhost:8080');
    }
```

Looking at this, it could definitely use some improvement in the core library, I'll work on that.

**Comment by brendandburns** [comment]
Closing in favor of #22

**Comment by rafaelcorreiapoli** [comment]
Thanks. I ended up importing the other classes directly and not using defaultClient()

**Comment by flyboarder** [comment]
@rafaelcorreiapoli do you have an example of how you got this working?

**Comment by kazif** [comment]
Hello. I'm using io.kubernetes.client.apis.CoreV1Api;
<dependency>
			<groupId>io.kubernetes</groupId>
			<artifactId>client-java</artifactId>
			<version>4.0.0</version>
		</dependency>
I have created a pod using createNamespacedPod, now I want to run this POD. 
I do not see createNamespacedDeployment() in the library.
Your help greatly appreciated and thanks

**Comment by richardgragasin** [comment]
> Thanks. I ended up importing the other classes directly and not using defaultClient()

Can you provide the steps on how you address this issue? currently having similar issue.
