### ISSUE TITLE
Instantiating non-core APIs is awkward...

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/javascript#22]
See #21

**Comment by tomlarkworthy** [comment]
my hack, though it has to ignore the protected access modifier of "authentications"
`
function appClient(): k8s.Apps_v1beta1Api {
    // This is a hack to boot the Apiextensions_v1beta1Api from the core client
    const coreClient = k8s.Config.defaultClient();
    const appClient = new k8s.Apps_v1beta1Api(coreClient.basePath);
    appClient.setDefaultAuthentication(coreClient.authentications.default)
    return appClient;
}
`
