### ISSUE TITLE
Improve docs for programmatic configuration.

### ISSUE THREAD

**Issue by dynnamitt** [kubernetes-client/javascript#220]
loadFromOptions ? 

Sample using AWS EKS from a lambda ...

**Comment by brendandburns** [comment]
There's an example in the unit test here:

https://github.com/kubernetes-client/javascript/blob/master/src/config_test.ts#L144

It's probably worth improving the docs too.

**Comment by dynnamitt** [comment]
> There's an example in the unit test here:
> 
> https://github.com/kubernetes-client/javascript/blob/master/src/config_test.ts#L144
> 
> It's probably worth improving the docs too.

thx
