### ISSUE TITLE
Path to ca.pem must be absolute

### ISSUE THREAD

**Issue by tetchel** [kubernetes-client/javascript#224]
```
Error: ENOENT: no such file or directory, open 'mycluster/ca.pem'
Logger.js:133
	at Object.fs.openSync (fs.js:577:3)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:483:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:563:29)
	at bufferFromFileOrString (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:280:19)
	at KubeConfig.applyHTTPSOptions (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:199:38)
	at KubeConfig.applyOptions (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:234:14)
	at KubeConfig.applyToRequest (/Users/tim/programs/microclimate-vscode/dev/node_modules/@kubernetes/client-node/dist/config.js:77:14)
	at Extensions_v1beta1Api.listIngressForAllNamespaces 
[...]
```

My cluster config contains
```
- cluster:
    certificate-authority: mycluster/ca.pem
```

If I replace that path `mycluster/ca.pem` with an absolute path (`/Users/tim/.kube/mycluster/ca.pem`), then it works.
If the path is a relative one, or if the file is not found, perhaps the library could prepend the kube config directory `$HOME/.kube/` to the configured path?

FWIW the relative path config worked out-of-the-box with the godaddy `kubernetes-client`, but I like this library's API and typings much more, so I'd like to switch over!

**Comment by tetchel** [comment]
Well, I guess "must be absolute" is not quite correct, because if the working directory was `$HOME/.kube` then it would work. But you see what my issue is.

**Comment by tetchel** [comment]
Potential fix:

We could extract the logic of `findHomeDir` plus [this](https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L205) into a function like `findKubeDir` to return something like `"/Users/tim/.kube"`

Then [here](https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L258) we can test if each file exists before trying to open it. If it doesn't exist, prepend the dir from `findKubeDir`. If it still doesn't exist, _then_ we throw the ENOENT.

**Comment by tetchel** [comment]
Also, looking at [bufferFromFileOrString](https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L358), if the file doesn't exist but the `cluster.caData` is provided, it will still fail because the code tries to access the file first (same with the user's certFile/Data and keyFile/data). I'm not sure if that is intentional. Maybe it's that function that should/could be refactored.

**Comment by tetchel** [comment]
@brendandburns  ?

**Comment by brendandburns** [comment]
@tetchel will look today.

**Comment by brendandburns** [comment]
@tetchel fix is in #226

**Comment by tetchel** [comment]
Now that's service! :+1:

**Comment by tetchel** [comment]
@brendandburns any idea when this will be available in an npm release? I'd like to pick it up as soon as possible
