### ISSUE TITLE
A way to sort returned values?

### ISSUE THREAD

**Issue by NolanChan** [kubernetes-client/javascript#225]
In `kubectl`, you can sort returned values by using `--sort-by`. An example would be:

```
k get events --sort-by='{.lastTimestamp}'
```

I kept looking through the documentation for the `kubernetes` api and inside this client, but I could find no way to sort returned values. Is there a way to do this?

**Comment by brendandburns** [comment]
Sorting happens client side in `kubectl` so you would need to use:

```javascript
const list = client.listNamespacedPods('default');
list.sort((pod1, pod2) => { pod1.lastTimestamp - pod2.lastTimestamp }
```

Or something like that.
