### ISSUE TITLE
Kubernetes Exec WebSocket not sending data

### ISSUE THREAD

**Issue by NolanChan** [kubernetes-client/javascript#229]
I realize I'm a frequent poster, I really appreciate you guys taking some time to look over this!

My issue is [nearly the same as this SO post](https://stackoverflow.com/questions/47781794/kubernetes-websockets-api-pod-exec-node-js-client-send-method), except that I'm using the Kubernetes Javascript Client (hence this issue). 

Basically, if I create a `WebSocket` using `exec.ts`:

```
const exec = new k8s.Exec(kc);
const ws = await exec.exec(
  'exampleNamespace',
  'shell-demo',
  'nginx', 
  '/bin/sh',
  process.stdout,
  process.stderr,
  process.stdin,
  true /* tty */,
);
```

then
 
```
root@shell-demo:/#
```

is properly printed out in my terminal. 

However, if I execute this command after creating the `ws`:

```
ws.send('ls');
```

I don't see any output generated from my container. I've also just tried writing commands directly into `stdin` and still no luck.

And just for a sanity check,

```
kubectl -n exampleNamespace exec -it shell-demo -- /bin/bash
```
works perfectly, connecting my terminal to the container shell.

I've been looking all over the place, but I've not found any helpful documentation/tutorials about setting up a simple nodejs websocket interaction. Would you have any advice on how to move forward?

**Comment by drubin** [comment]
Hi @NolanChan 

The websocket doesn't behave like a "shell" you can't just send commands to it like a normal websocket API as I think you were expecting.

You need to type `ls` inside the terminal `root@shell-demo:/#`

If however you just want to send multiple commands programmatically your issue might be similar to this https://github.com/kubernetes-client/javascript/issues/213 ? if not let me know and we can try to figure it out. 

The following should work if I understand you correctly?

```
const exec = new k8s.Exec(kc);
const ws = await exec.exec(
  'exampleNamespace',
  'shell-demo',
  'nginx', 
  '/bin/sh -c "ls"',
  process.stdout,
  process.stderr,
  process.stdin,
  true /* tty */,
);
```

**Comment by NolanChan** [comment]
Hi @drubin , 

Unfortunately I was hoping that the websocket behaved similarly to [the stream that `dockerode` creates on `exec`](https://github.com/apocas/dockerode/blob/a41fc414d1f74851c7b7e8f32e7ab3020b8e5fa7/examples/exec_running_container.js), in that you could `write` input into the stream and it would recreate a container's `shell`.

On a high level, I'm trying to recreate a shell experience for an end-user. Is there any way I could make the websocket behave like a shell? I would assume that it's possible since there's a `tty` option (although I could be completely mistaken about the meaning of `tty`).

Thanks!

**Comment by brendandburns** [comment]
@NolanChan if you pass a different stream than `process.stdin` then you can write to that stream and it will be read as if it is coming in via `stdin`.

You also almost certainly want to set `tty` to false in that case or else the shell will send control characters (which you probably don't want, unless you are emulating a terminal.)

**Comment by NolanChan** [comment]
Hi @brendanburns , I just tested your suggestion by 

1. passing in a `writable` stream instead of `process.stdin`, 
2. passing commands into `stdin`, i.e. - `stdin.write('echo hello world')`
3. nothing is being outputted to `stdout` except the original line `root@shell-demo:/#` from the initial command

I am trying to emulate a terminal. I experimented with `tty` true or false, and neither helped. @drubin would you have any suggestions?

**Comment by NolanChan** [comment]
Also @drubin when you mentioned that:

> The websocket doesn't behave like a "shell" you can't just send commands to it like a normal websocket API as I think you were expecting.

it seems that the [handleStandardInput](https://github.com/kubernetes-client/javascript/blob/master/src/web-socket-handler.ts#L51) method, which is connecting the `stdin` stream passed to the `exec` call, is basically feeding whatever data is from `stdin` into `ws.send`. It seems that from my understanding, the expected behavior then is to pass commands inside `ws.send`

**Comment by brendanburns** [comment]
The shell expects a newline after the command...

**Comment by NolanChan** [comment]
I forgot to mention that I tried that, along with sending my data encoded in a `Buffer.from`. Things I've tried includes:
```
writableStream.write('echo hello world')
writableStream.write('echo hello world \n')
writableStream.write('echo hello world \n\r')
writableStream.write(Buffer.from('echo hello world \n'))
```

and also each command that I passed into the `writableStream` I also passed into `ws.send`

**Comment by brendandburns** [comment]
You shouldn't be passing anything to ws.send

You should pass the stream instead of `process.stdin` in the example code above.

e.g.
```javascript
const ws = await exec.exec(
  'exampleNamespace',
  'shell-demo',
  'nginx', 
  '/bin/sh -c "ls"',
  process.stdout,
  process.stderr,
  myWriteableStream,
  true /* tty */,
);
```
