### ISSUE TITLE
Some of the function signatures are a little... ergonomically challenging

### ISSUE THREAD

**Issue by technosophos** [kubernetes-client/javascript#230]
When creating various namespaced objects in TS, I found myself writing function calls like this:

```
createNamespacedPod(ns, pod, false, "true", dryRun ? "All" : undefined );
```

Note that arg 3 is boolean, arg 4 is a string that accepts only `"true"`, and argument 5 is a `string | undefined` that accepts only `"All"` (note uppercase) or `undefined` as a value.

I know the clients are largely autogenerated, but writing code this way is frustrating, error prone, and difficult to read. Is there anything we can do?

**Comment by brendandburns** [comment]
Sure, if you want to improve the code generator it's here:

https://github.com/OpenAPITools/openapi-generator

Specifically:
https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/typescript-node

They're quite good at merging PRs....

**Comment by silasbw** [comment]
I'm the maintainer of an unofficial kubernetes-client for JavaScript (with TypeScript declarations) that tries to address your concern with a more fluent/intuitive interface: https://github.com/godaddy/kubernetes-client

I have plans to power godaddy/kubernetes-client with kubernetes-client/javascript (e.g., https://github.com/godaddy/kubernetes-client/pull/394). At that point godaddy/kubernetes-client would be a wrapper around kubernetes-client/javascript that provides (what is hopefully) a more "ergonomic interface".

**Comment by brendandburns** [comment]
@silasbw I'd be open to having a `github.com/kubernetes-client/javascript-fluent` (or somesuch) official repo if you wanted to...

**Comment by silasbw** [comment]
@brendanburns yes, we'd be up for working through that.  Do you have a suggestion on how to proceed?

**Comment by brendandburns** [comment]
@silasbw can you file an issue here:

https://github.com/kubernetes/org

Requesting that repo, and cc me and also @mbohlool 

Thanks!

**Comment by brendandburns** [comment]
@silasbw 

Actually, as I think about it, I'd also be open to there being a `fluent` directory and library within this client. That might be even easier...
