### ISSUE TITLE
Token fails to refresh in windows

### ISSUE THREAD

**Issue by redborian** [kubernetes-client/javascript#232]
I get the following error when accessing the cluster using `@kubernetes/client-node` package with an expired token:
```
Failed to refresh token: ENOENT: no such file or directory, open 'C:\Users\CNARAY~1\AppData\Local\Temp\shelljs_5765fd92c727d3057e30
```
I get this error when I access the cluster after a few hours of idle time. I get this error consistently with the latest version of the package.
After running any `kubectl` command, it starts working again. I suspect the `kubectl` command refreshes the token behind the scenes.

OS: Windows
Cloud Provider: GKE
Package version: 0.8.2

**Comment by brendandburns** [comment]
looks like you don't have the `shelljs` package installed (or it's broken somehow).

you may need to re-install it using `npm`
