### ISSUE TITLE
system env no_proxy with IP range format not inferred

### ISSUE THREAD

**Issue by RabbidDog** [kubernetes-client/javascript#233]
System: Ubuntu 18.04
kubernetes-client: v0.8.2

added the IP range 10.96.0.0/12 in no_proxy env variable. But the requests to get kubernetes resources tries to go through the company proxy. Explicitly added 10.96.0.1 to no_proxy env variable and then requests to get kubernetes resources succeed.

**Comment by drubin** [comment]
As far as I understand `no_proxy` works with wild cards so in your example you would use 

`no_proxy=10.96.` instead of an actual subnet range.

**Comment by brendandburns** [comment]
Yep, it's filter-matching, not a CIDR:

https://github.com/request/request/pull/1096/files#diff-ccc0734f65dd7a299409ff07d35be095R300

Closing.

**Comment by RabbidDog** [comment]
> As far as I understand `no_proxy` works with wild cards so in your example you would use
> 
> `no_proxy=10.96.` instead of an actual subnet range.

I hoped for the same but tests reveal that it does not work for  `no_proxy=10.96.` . Only specifying the complete IP is working.
Also amazing was that I had to include `localhost` in the list of no_proxy.
[Putting this comment in closed ticket just in case anyone faces the same issue]
