### ISSUE TITLE
Unable to access any methods other than listNamespacedPod

### ISSUE THREAD

**Issue by MaxG2395** [kubernetes-client/javascript#235]
For some reason, my code works just fine when using listNamespacedPod. 
However, if I try to use any method other than that (i.e listNamespacedStatefulSet), I get the following error:

Here's my wrapper code:
```
export const listStatefulSetsFromNamespace = (apiInstance, namespaceName) => new Promise((resolve, reject) => {
  apiInstance.listNamespacedStatefulSet(namespaceName)
    .then((res) => {
      console.log(res.body);
    })
    .catch(err => reject(err));
});
```

Here's my test:
```
  describe('StatefulSet Services', () => {
    it('should be able to list all StatefulSets in the mentioned namespace', () => {
      const statefulSet = listStatefulSetsFromNamespace(apiInstance, 'nl-loadgen');
      return expect(Promise.resolve(statefulSet)).to.eventually.be.fulfilled;
    });
```
The error I'm getting is the following:
```
     AssertionError: expected promise to be fulfilled but it was rejected with 'TypeError: apiInstance.listNamespacedStatefulSet is not a function' 
```

If I change the listNamespacedStatefulSet for listNamespacedPod, it works flawlessly.

**Comment by brendandburns** [comment]
StatefulSets are in a different API group than Namespaces.  StatefulSets are in `apps/v1` while namespaces are in `v1` (aka `CoreV1`).

See the code here:

https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L239

And pass `Apps_v1API` as the ApiType. See the file here:

https://raw.githubusercontent.com/kubernetes-client/javascript/master/src/api.ts

Forr all of the different API classes.
