### ISSUE TITLE
how run kubeclt command

### ISSUE THREAD

**Issue by inyee786** [kubernetes-client/javascript#236]
i want to run some kubectl command

eg `kubectl describe po <pod name>`
     `kubectl get <custom resource> -n namespaces`

**Comment by brendandburns** [comment]
This is the javascript library, it's not for kubectl.

There are lots of kubectl docs on the web, e.g. https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

**Comment by inyee786** [comment]
hi @brendanburns 
i want to describe the the pod, so that i can get current the event,
How can i achieve this using JavaScript client?
