### ISSUE TITLE
Split up files to support tree shaking

### ISSUE THREAD

**Issue by from-nibly** [kubernetes-client/javascript#242]
Could the api.js/api.d.ts file be split up into a set of files? This would help with tree shaking and with the fact that even the d.ts file is over 20,000 lines long. Unless something really fancy was done only splitting on clients would actually do anything. This would result in one file for each of the following ApiClients and the models imported for each:

- Admissionregistration_v1alpha1Api
- Admissionregistration_v1beta1Api
- Apiextensions_v1beta1Api
- Apiregistration_v1Api
- Apiregistration_v1beta1Api
- Apps_v1Api
- Apps_v1beta1Api
- Apps_v1beta2Api
- Auditregistration_v1alpha1Api
- Authentication_v1Api
- Authentication_v1beta1Api
- Authorization_v1Api
- Authorization_v1beta1Api
- Autoscaling_v1Api
- Autoscaling_v2beta1Api
- Autoscaling_v2beta2Api
- Batch_v1Api
- Batch_v1beta1Api
- Batch_v2alpha1Api
- Certificates_v1beta1Api
- Coordination_v1beta1Api
- Core_v1Api
- Custom_objectsApi
- Events_v1beta1Api
- Extensions_v1beta1Api
- Networking_v1Api
- Policy_v1beta1Api
- RbacAuthorization_v1Api
- RbacAuthorization_v1alpha1Api
- RbacAuthorization_v1beta1Api
- Scheduling_v1alpha1Api
- Scheduling_v1beta1Api
- Settings_v1alpha1Api
- Storage_v1Api
- Storage_v1alpha1Api
- Storage_v1beta1Api

This would decrease compile times significantly. I doubt most controllers are reaching 60,000 LOC but the api.js file is. When running with typescript it also needs to load the 20,000 LOC api.d.ts file. Because of this most of my compile time is just spent compiling the kubernetes client.

Beyond this separation it would actually be nice if each model had it's own file, but this would not help with compile time tree-shaking. However, loading huge files can slow down some editors. Putting each model in it's own file would guarantee that each file would be really small but it could increase compile times.

**Comment by brendandburns** [comment]
Unfortunately, that file is generated by a code generator. To do this you'd need to modify the code generator. It's located here:

https://github.com/OpenAPITools/openapi-generator

**Comment by from-nibly** [comment]
Gotcha. This would also be a good point to switch to something other than request since request has been deprecated. https://github.com/request/request/issues/3142
