### ISSUE TITLE
HTTP 403 when authenticating via username/password

### ISSUE THREAD

**Issue by Obirah** [kubernetes-client/javascript#245]
Hi,

I am using the kubernetes-client to perform API calls against OpenShift 3.11 (Kubernetes 1.11 API) clusters and I'm facing a problem when authenticating via username and password.

If I use the following KubeConfig, I get a 403 Forbidden on any API call I try:
```
const cluster = {
    server: 'https://console.my.openshift.cluster.com',
    skipTLSVerify: true
} as Cluster;

const user = {
    username: 'my-user',
    password: 'the-password'
} as User;

const kc = new k8s.KubeConfig();
kc.loadFromClusterAndUser(cluster, user);
```

The response I get from the API indicates that the user is not even passed correctly, as the API recognizes me as "system:anonymous", see:
```
'nodes is forbidden: User "system:anonymous" cannot list nodes at the cluster scope: no RBAC policy matched'
```

If I use the token-based authentication with a ServiceAccount token instead (or the token of a regular account, doesn't matter), all my API calls work. This is the token-based KubeConfig:
```
const cluster = {
    server: 'https://console.my.openshift.cluster.com',
    skipTLSVerify: true
} as Cluster;

const user = {
    token: 'some-fancy-service-account-token'
} as User;

const kc = new k8s.KubeConfig();
kc.loadFromClusterAndUser(cluster, user);
```

Are there known problems with the username/password authentication? In theory, I could also imagine that it might happen because of OpenShift-specifics, but I doubt it because its still the Kubernetes API.

Another difference between the two variants, I can point immediately is that the password in my case contains special characters whereas the token is alphanumeric.

I also tried it with multiple users, so there is no problem with the individual credentials.

**Comment by brendandburns** [comment]
It seems clear to me that the user name and password aren't making it through to the server. I will try to repro this in a unit test and see what is going on...

(though basic auth is deprecated afaik...)

**Comment by brendandburns** [comment]
I added a bunch of authentication tests here:

https://github.com/kubernetes-client/javascript/pull/254

everything seems to be working correctly to me, so I don't know why the auth isn't working for you...

**Comment by drubin** [comment]
@brendanburnsIt appears like this is being executed from a pod which I think might be triggering some logic to try to load the default service account tokens?

@Obirah is one of those special characters perhaps a `:`?

**Comment by brendandburns** [comment]
@drubin in cluster shouldn't matter with the code path he's specifying `loadFromClusterAndUser(...)`

But a `:` in the password would definitely mess things up...

**Comment by Obirah** [comment]
@drubin @brendanburns in my case the password contains no colon. 

Unfortunately, due to enforced password policies, I am not able to create an user without special chars in the password. Otherwise, I would've done that in order to exclude the possibility that the chars in the password are messing with the client.

**Comment by drubin** [comment]
@Obirah the password is base64 encoded but we do string concatenation so the only char that could affect things would be `:`  `opts.auth = `${user.username}:${user.password}`;`

@brendanburns why do we have 2 different ways of adding username password auth? 

https://github.com/kubernetes-client/javascript/blob/5946eee7ccb50eca9239ca753c8d1eda29109c28/src/config.ts#L115 
and 
https://github.com/kubernetes-client/javascript/blob/5946eee7ccb50eca9239ca753c8d1eda29109c28/src/config.ts#L130

**Comment by brendandburns** [comment]
@drubin 

First one is used when we make watch calls which use the raw `https` package in node. This package uses a [different convention](https://nodejs.org/api/http.html#http_http_request_options_callback) for specifying auth.

The other one is for all other API requests which use the `request` package which has a [different convention for auth](https://github.com/request/request#http-authentication)

In the sample code above, the call is going through the later version. If the issues were with a watch call, then it would be using the first version.

I have to admit that I don't think I've ever directly tested this code against a live server, since basic auth was deprecated a long time ago in Kubernetes. But the new unit test is pretty comprehensive and seems to indicate that the Authorization header is getting set and sent correctly.
