### ISSUE TITLE
dependency deprecation warning

### ISSUE THREAD

**Issue by 1N50MN14** [kubernetes-client/javascript#247]
`jsonpath` has `jison` as a dependency which in turn has `nomnom` as a deprecated (since 2015) dependency.`jison` doesn't seem to be maintained. `npm` throws two warnings related to that during installation.

Would it be possible to move away from `jsonpath` to an alternative implementation as far as I can see it's only used in `cloud_auth.ts`?

Thanks

**Comment by drubin** [comment]
Wonder if it would be it would be easy to switch it out for https://github.com/s3u/Jsonpath seems like it might be Api compatible and pretty active.

**Comment by brendandburns** [comment]
SGTM, thanks @drubin !
