### ISSUE TITLE
JSON parse uncaught exception in watch implementation

### ISSUE THREAD

**Issue by silasbw** [kubernetes-client/javascript#249]
The [watch](https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts) can raise an uncaught exceptions on [JSON parse](https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L62) errors. Invalid JSON might be piped to the stream when, for example, the connection is abruptly terminated (_e.g._, `'{"start of json'`).

**Comment by brendandburns** [comment]
Closing since #250 is merged.
