### ISSUE TITLE
[0.9.0] Missing dependency: "jsonpath".

### ISSUE THREAD

**Issue by darkobits** [kubernetes-client/javascript#258]
Looking through some other Issues here, it appears that this project is switching from the `jsonpath` package to `jsonpath-plus`. This project's `package.json` at `0.9.0` [corroborates this](https://github.com/kubernetes-client/javascript/blob/0.9.0/package.json#L59).

However, the build artifact for [`cloud_auth.ts`](https://github.com/kubernetes-client/javascript/blob/0.9.0/src/cloud_auth.ts) (`dist/cloud_auth.js`) still contains a reference to `jsonpath`:

> `dist/cloud_auth.js`

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
// workaround for issue https://github.com/dchester/jsonpath/issues/96
const jsonpath = require("jsonpath/jsonpath.min");
const shelljs = tslib_1.__importStar(require("shelljs"));
```

This is causing version `0.9.0` to throw an error when trying to instantiate a new API client.

My only hunch here is that perhaps the project was not re-built before publishing this version, resulting in the discrepancy between the source `.ts` file and the transpiled `.js` file.

**Comment by brendandburns** [comment]
ugh, hrm, let me check....

**Comment by brendandburns** [comment]
@darkobits I just pushed `0.9.1` that I think fixes this, can you double check for me?

Thanks!

**Comment by sergelerator** [comment]
It seems 0.9.1 does not contain an `index.js` file.

**Comment by brendandburns** [comment]
Just pushed `0.9.2` which should work...

**Comment by brendandburns** [comment]
Closing this since I validated that 0.9.2 works correctly.
