### ISSUE TITLE
Support multiple files in KUBECONFIG env variable

### ISSUE THREAD

**Issue by drubin** [kubernetes-client/javascript#265]
According to the [official docs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable) we should be able to load multiple config files and join them.

The client currently doesn't support this we should support it.

References comment in https://github.com/kubernetes-client/javascript/pull/226#issuecomment-498898940

**Comment by brendandburns** [comment]
fwiw, the merging rules here are _really_ poorly defined, but we can take a rough stab and see what compatability things people complain about...

**Comment by drubin** [comment]
@starpit this has been merged it would be really nice if you could give it a test see if it works for you? Let us know if you manage to give it a test

You should be able to reference it before its published via the npm GitHub style includes https://docs.npmjs.com/files/package.json#repository
