### ISSUE TITLE
code gen generates ts with compile errors

### ISSUE THREAD

**Issue by silasbw** [kubernetes-client/javascript#266]
There are two high-level classes of errors.  I'm looking for feedback on how to address:

1. A name change for classes and enums.  swagger-codegen _appears_ to drop the `_` (e.g., Core_v1Api -> CoreV1Api).  This seems like it _should_ have been a breaking change with swagger-codegen (i.e., a major version bump).

2. swagger-codegen started implementing required parameters for typescript using optional parameters for non-required parameters. E.g., all properties in `class V1Pod` are optional because the swagger.json `v1.Pod` definition has no required parameters. This causes type incompatibility with KubernetesObject.

#### Possible solutions for 1:
1. Update names to the new ones generated by swagger-codegen. This breaks existing clients :( but this package is pre 1.0.0 and this is probably the least amount of effort.
1. Try to undo the name change in the generated code by re-inserting the _s.
1. Make the name change controllable/optional in swagger-codegen, but this would probably be cumbersome as there's a new major version of the swagger-codegen and it's not clear what the support policy is for older versions.  We'd probably want to adopt the name change eventually.

#### Possible solutions for 2:
1. Update the swagger.json (or the dependents for generating it) in kubernetes/kubernetes.  I'm not sure how to track down all cases where the swagger.json might be missing values from the `required` array.  If we don't, dependents of this client could start having compile errors.

**Comment by brendandburns** [comment]
For #1, I'm fine with a breaking change. We'll rev. the minor version number and add a release note.

For #2, could we make those fields optional in `KubernetesObject`?  That might require a bunch of code changes in the library.

I'm also ok trying to fix all the swagger (that's probably better for the k8s community anyway)

**Comment by silasbw** [comment]
OK, renaming is easy.

For 2, changing all the fields in `KubernetesObject` does require a bunch of code changes (_e.g._, adding null assertion operators to many of the statements that reference a property of a `KubernetesObject`.  I made https://github.com/kubernetes-client/javascript/pull/268 to be concrete.

I looked into updating swagger.json and I think I was mostly wrong about the missing required parameters.  In many cases the swagger specification uses the same type definitions for specifying parameters to and responses from different operations.  The different operations have different requirements of the type and the swagger defines the type weak enough to work.

For example, when POSTing a `Pod` you can optionally omit `.name` and specify `.generateName`, when getting a `Pod` it's guaranteed to have `.name`.  The swagger.json uses the same type definition for the response to POST and the parameter to GET, which means `.name` is optional in the `V1ObjectMeta` class.  Since `V1ObjectMeta` is used across many object types, there are a bunch of related issues (_e.g._, `.namespace` is optional because you don't need to specify a namespace when messing objects that don't have namespaces).

It seems making stronger types would be a pretty big chunk of work.  Do you have any other suggestions on a path forward?

**Comment by brendandburns** [comment]
Seems like you decided to optionalize things and got them compiling, so I'm going to close this issue. Please re-open if there is more to do.
