### ISSUE TITLE
Error while compiling Typescript project 

### ISSUE THREAD

**Issue by AleF83** [kubernetes-client/javascript#274]
I'll added `@kubernetes/client-node` package to my project. (npm module version is 0.10.0)
I get the following error while running `tsc` command:

```
node_modules/@kubernetes/client-node/dist/log.d.ts(2,10): error TS2305: Module '"../../../@types/request"' has no exported member 'default'
```

I saw in `logs.d.ts` and see that:
```typescript
...
import { default as request } from 'request';
...
```

In `@types/request` package I see the following:
```typescript
...
export = request;

...
```

Am I missing anything?

**Comment by silasbw** [comment]
It looks like `request` is using the CommonJS-style export -- should `logs.ts` use the CommonJS-style import?  _I.e._, https://github.com/kubernetes-client/javascript/pull/275

**Comment by brendandburns** [comment]
Pushed `0.10.1` out to NPM with the fix.

**Comment by AleF83** [comment]
Thanks for quick response!
