### ISSUE TITLE
deleteNamespacedDeployment not deleting cascading resources

### ISSUE THREAD

**Issue by elizabeth-cloudcover** [kubernetes-client/javascript#281]
When I call deleteNamespacedDeployment method, I find that the corresponding replicaSet and Pods are not removed. I also added a call to deleteNamespacedReplicaSet but still I can see one orphan pod running. I have also tried setting the Propagation policy to Foreground and Background but still of no help. Is there is a way to do the cascading deletion. If yes, where and how to use it? If not, do you have plan to make it?
I am using Kubernetes version: 1.11.8-gke.6 and Kubernetes/client-node version: 0.8.2

**Comment by brendandburns** [comment]
The APIs are the same as what kubectl uses so in general the answer is "yes cascading delete should work"

What does your code look like?

**Comment by niklasbuechner** [comment]
I am currently having the same issue. This is the code:

```
async deploymentName => apiClient.deleteNamespacedDeployment(deploymentName, namespace),
```

When you call this code with `const namespace = 'default';` and your deployment name, it deletes the deployment but not the replica set. If you go further and delete the replica set using the api, it will not delete the pods of the replica set.

If you do the same thing using `kubectl delete` everything works as expected.

minikube version: v1.1.0
Kubernetes version: v1.14.2
kubernetes/client-node: v0.10.2

**Comment by niklasbuechner** [comment]
And the fix for the problem is either

```
async deploymentName => apiClient.deleteNamespacedDeployment(
    deploymentName,
    namespace,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    'Background'
),
```
or 
```
async deploymentName => apiClient.deleteNamespacedDeployment(
    deploymentName,
    namespace,
    undefined,
    { propagationPolicy: 'Background' }
),
```

(If you do not want to use the optional values.)

@brendanburns How exactly is the library supposed to behave? The same as `kubectl` which has the `propagationPolicy: Background` as standard or just as an abstraction layer above the api?

As an additional question: if I want to propose a change to the library's function ergonomics, where exactly would I need to do that? A Kubernetes RFC?
