### ISSUE TITLE
patchNode doesn't use the correct headers by default

### ISSUE THREAD

**Issue by aackerman** [kubernetes-client/javascript#287]
By default patchNode should supply the `application/merge-patch+json` header.

I had to call the API as follows to get a patch node call to work

```js
let patchBody = {
  apiVersion: 'v1',
  kind: 'Node',
  metadata: { name: nodeName },
  spec: { unschedulable: true }
}
return api.patchNode(nodeName, patchBody, undefined, undefined, {
  headers: {
    'Content-Type': 'application/merge-patch+json'
  }
})
```

**Comment by brendandburns** [comment]
It appears that the generated typescript code never tries to set a custom content type, so as far as the generated code is concerned this is the right way to do this.

One could argue that it should do something different (though which header is it supposed to chose, since there are three potential content types for patches?)

But either way, this is a bug in the code generator (if it is a bug at all) not this library, so closing.

**Comment by OJezu** [comment]
If this is a bug in code generator not in the library, was this taken to the code generator bug tracker?

There is also hardly any documentation how to use the patch functions.

**Comment by woodcockjosh** [comment]
Thanks @aackerman for posting the workaround. Anyway if its a code generator problem can someone please link me the issue to the bug in the code generator?

**Comment by brendandburns** [comment]
I don't think it's actually a code generator bug. There are three different possible content-type headers to chose from, how is the code generator supposed to know which one to send. Having the user explicitly select the header seems like the right approach.

**Comment by woodcockjosh** [comment]
@brendandburns this defeats the purpose of the sdk. While it may be difficult for the code generator to know with the current architecture. The end user shouldn't have to know this. If I use kubectl I don't have to know the content type of the request.

**Comment by woodcockjosh** [comment]
I could be mistaken but it appears all PATCH requests have the same request header content type in v1.16. Can you not make the generator look at the http method to set the correct content type?
