### ISSUE TITLE
Memory leak when watching nodes

### ISSUE THREAD

**Issue by PepperTeasdale** [kubernetes-client/javascript#288]
kubernetes version 1.12
kubernetes/client-node version 0.10.1
node version: 8.16.0

I have an app that is watching node events in the cluster in a loop, ignoring most events that it receives. Over time this app slowly grows in memory consumption until it reaches the limit and is OOM killed. I made a very minimal reproducible case like the following:
```typescript
class App
    ...
    public async main(): Promise<void> {
        try {
            return new Promise((_resolve, reject) => {
                // this is a k8s.Watch object
                this.watch.watch('/api/v1/watch/nodes',
                    {
                        timeoutSeconds: Number.MAX_SAFE_INTEGER,
                        labelSelector: MY_LABEL,
                    },
                    () => {},
                    () => {
                        reject();
                    });
            })
        } catch(err) {
            this.logger.log(err);
        }
    }

    public async loop(): Promise<void> {
        while (true) {
            await this.main();
        }
    }
}

app.loop();
```

I took some heap snapshots and inspected in dev tools. I think it might be an issue with the [json-stream library that the client uses](https://github.com/mmalecki/json-stream), but I'm not really good with these JS profiling tools so I could be misreading. As a side note, it does seem like that's an older library that's not as widely used as these alternatives: https://github.com/dominictarr/JSONStream https://github.com/uhop/stream-json

**Comment by brendandburns** [comment]
I'm pretty sure the choice of `json-stream` was 100% arbitrary :)

I looked at the code, I actually think it's not needed and we can just use `readline`

Will refactor and send a PR.

**Comment by brendandburns** [comment]
I made a PR here:

https://github.com/kubernetes-client/javascript/pull/289

If you can test it, that would be awesome...

**Comment by PepperTeasdale** [comment]
Thanks for the fast response! The new version works, but I'm still having my memory issue, so that was not the root cause. I'll do some more analysis and update here what I discover.

**Comment by PepperTeasdale** [comment]
Ok, so I've looked into this a little more and ran some experiments. One thing I was doing wrong on my side was not aborting the request when the connection closed or errored out. The library doesn't do this for you, but [returns the request object](https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L67) I think it would be worth making that explicit in the example or somewhere in the documentation.

However, I noticed that even when doing this, memory usage continued to grow while the watch continued. Shortening the timeout (even without aborting the request) and restarting the watch after the server terminated allowed the garbage collector to clear out the buffers. I don't know if there's a way to handle these kinds of long running connections in the request package. For some reason I thought this repo used to have the timeout param set to `Number.MAX_SAFE_INTEGER` in the examples somewhere, maybe this was removed?

If you all want to handle this in code or via documentation somewhere, then I'll keep this issue open, but I can close if you don't think action is necessary for this.

**Comment by brendandburns** [comment]
Ok, so I bet that request is accumulating all of the bytes read from the request stream... It's worth exploring to see if it's feasible to get the request logic to drop the data as it's read instead of retaining it.

Let's leave this issue open and we can explore options here. At the very least we'll need to improve the docs.

**Comment by PepperTeasdale** [comment]
Yeah, it looks like the issue might be coming from [using the callback version of request here](https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L16), which creates an in memory buffer: 

From what I understand from [this issue in the request repo](https://github.com/request/request/issues/225) something along the lines of this might fix:
```typescript
export class DefaultRequest implements RequestInterface {
    public webRequest(opts: request.Options, callback: (err, response, body) => void): any {
        const req = request(opts);
        req.on('data', callback);
        return req;
    }
}
```

**Comment by brendandburns** [comment]
It's trickier than just doing this since we need to stream the lines, not just the raw data. I'll see what I can do here but it may take a bit of time...

**Comment by XiaocongDong** [comment]
Hi, I am having the same issue, any update on this?
