### ISSUE TITLE
No function to list all namespaces

### ISSUE THREAD

**Issue by abedra** [kubernetes-client/javascript#29]
I dug through the api file and could not find anything that hit the https://docs.openshift.org/latest/rest_api/api/v1.Namespace.html#Get-api-v1-namespaces endpoint. Is there a different way this is exposed in this library or is it just missing?

**Comment by itowlson** [comment]
It looks from the source like the following might work:

```
const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.Core_v1Api);

k8sApi.listNamespace().then(...);
```

It's defined on line 44137 of `node-client/src/api.ts` (in the current HEAD at least).

**Comment by brendandburns** [comment]
Closing this since I think it's been addressed.

**Comment by developerdesigner18** [comment]
I am getting this error while calling 

> It looks from the source like the following might work:
> 
> ```
> const kc = new k8s.KubeConfig();
> kc.loadFromDefault();
> 
> const k8sApi = kc.makeApiClient(k8s.Core_v1Api);
> 
> k8sApi.listNamespace().then(...);
> ```
> 
> It's defined on line 44137 of `node-client/src/api.ts` (in the current HEAD at least).

I am gettnig this error "TypeError: k8sApi.listNamespace is not a function". By calling listNamespace(). I have installed 0.16.0 version of "@kubernetes/client-node"
