### ISSUE TITLE
Help: get kubernetes version

### ISSUE THREAD

**Issue by whites11** [kubernetes-client/javascript#293]
I'm trying to get the kubernetes cluster version (the same info you can get from the `kubectl version` command).

Is there a way to get this info with kubernetes-client?

Thanks

**Comment by whites11** [comment]
ok found the answer myself:

client.version.get().then(console.log)

**Comment by hyunil-shin** [comment]
@whites11 
client.version => what is the client ? 
I could not find class with version.

**Comment by whites11** [comment]
> @whites11
> client.version => what is the client ?
> I could not find class with version.

I'm really sorry but I don't remember about this topic.
Considering the age of the issue might it be it was present in an old release?
