### ISSUE TITLE
loadFromOptions does not appear to work with a parsed kubeconfig

### ISSUE THREAD

**Issue by erulabs** [kubernetes-client/javascript#295]
loadFromOptions seems to be a bit hobbled compared to the previous `fromKubeconfig` from https://github.com/godaddy/kubernetes-client/

For example, previously, with fromKubeconfig, one could provide the current context as `current-context` (as it typically appears in yaml). `loadFromOptions` appears to require `currentContext` (camalcase), and additionally doesn't appear to work with TLS - I get a "unable to verify the first certificate" message which makes me think it is similarly not understanding `config.cluster['certificate-authority-data']`. You can see in fromKubeconfig, some transformation on kubeconfig yaml documents is performed: https://github.com/godaddy/kubernetes-client/blob/22a998ddd40d5f3713ed199905206c25d57d8d84/backends/request/config.js#L198

Is there a recommended way to programmatically provide kube credentials? `fromKubeconfig` worked very well, maintaining a sane, human readable kube config format for both users and this library - with this library I don't see a way to provide TLS data programmatically in a way that actually works! The tests appear to have TLS verification disabled as well.

This guide seems to be inaccurate re: swapping from fromKubeconfig to loadFromOptions https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md

Happy to open an issue over with godaddy/kubernetes-client (in my mind, these two functions are pretty different, and removing one in favor of the other is a fairly large breaking change...) - but in my mind if the kubernetes-client library cant... connect to kubernetes... the issue is on this side :P

**Comment by drubin** [comment]
Hi @erulabs the library does support programmatically passing credentials in and it does support both the `-data` and the file references for cert data. 

The docs/examples are definitely lacking here I went to try to find an example and it wasn't there, (pr's welcome) so sorry about that confusion.

I think the best example might be in the tests although it doesn't work exactly as you expect it (passing raw yaml style) you need to pass an object. You can see the params [Cluster](https://github.com/kubernetes-client/javascript/blob/master/src/config_types.ts#L5-L11) and [User](https://github.com/kubernetes-client/javascript/blob/master/src/config_types.ts#L38-L49)

From the tests https://github.com/kubernetes-client/javascript/blob/master/src/config_test.ts#L115 

```js
const kc = new KubeConfig();
const cluster = {
    caData: 'base 64ed ca data',
    // or 
    caFile: '/tmp/file'
    name: 'foo',
    server: 'http://server.com',
} as Cluster;

const user = {
    caData: 'base 64ed ca data',
    name: 'my-user',
    password: 'some-password',
} as User;

kc.loadFromClusterAndUser(cluster, user);

// This might be wrong though I haven't used the godaddy version
const backend = new Request({ kc })
```

> The tests appear to have TLS verification disabled as well. 
We don't validate or disable validation for any TLS since we don't actually have integration tests that connect. 

We do support disabling TLS on the client API and this was added https://github.com/kubernetes-client/javascript/pull/186/files but it's only if you pass in `skipTLSVerify: true`

Let me know if this clears it up? Or if I can try to clarify anything else.

**Comment by erulabs** [comment]
Heya @drubin - thank you very much for the assist - `loadFromClusterAndUser(cluster, user)` works like a charm.

I feel like it would be pretty useful to have a snippet somewhere on the README like:
```javascript
const { KubeConfig, Client } = require('kubernetes-client')
const kc = new KubeConfig()
const config = YAML.safeLoad(`fs.load my .kube/config file ...`)

const client = new Client({
  backend: kc.loadFromClusterAndUser(config.clusters[0], config.users[0]),
  version: '1.13'
})

console.log(client.api['v1'].namespaces('default'))...
```

For people just trying get going quickly with the library from a .kube/config file (obviously context selection can be more complex but I think that example makes it pretty clear that it's a bit of a hack)

Thanks again!

**Comment by erulabs** [comment]
^ This actually doesn't work - It doesn't appear to be using the certificate-authority-data in the cluster definition? `Error: unable to verify the first certificate`....

**Comment by erulabs** [comment]
Got things working after some transformation from a parsed yaml document into what this library expects:
```javascript
      const clusterConfig = {
        caData: cluster.config.clusters[0].cluster['certificate-authority-data'],
        name: cluster.config.clusters[0].name,
        server: cluster.config.clusters[0].cluster.server
      }
      const userConfig = {
        keyData: cluster.config.users[0].user['client-key-data'],
        certData: cluster.config.users[0].user['client-certificate-data'],
        name: cluster.config.users[0].name
      }
```

pretty ugly tho! :(

**Comment by drubin** [comment]
@erulabs 

I noticed you are actually trying to load a custom kubeconfig file. Not actually dynamically load javascript objects.

```js
const kc = new KubeConfig()
kc.loadFromFile(`/path/to/.kube/config`)
```

there is also `kc.loadFromString(fs.readAsync('/path/to/file'))` 

I think this would work much nicer than what you are currently doing

**Comment by brendandburns** [comment]
Closing this as I don't think there's more to do here. Please re-open if there is additional help needed.

Thanks

**Comment by shimmerjs** [comment]
We ran into this issue because we are pulling valid Kubeconfig JSON objects from Vault and trying to instantiate clients with them.  If `loadFromOptions` can't be made to support a direct JSON Kubeconfig representation, maybe an alternative function?  Could potentially make `loadFromString` also support JSON strings and YAML strings.  I think the underlying issue is all of these functions are written assuming YAML or disk, or both.

**Comment by garyo** [comment]
Hi; I'm trying to do the same, with Google Kubernetes Engine (I want to start jobs from a back-end service). My ~/.kube/config doesn't look quite like the ones shown here though. Cluster seems OK:
```
- cluster:
    certificate-authority-data: [REDACTED]
    server: https://35.111.222.333
```
But, a user is 
```
- name: gke_MYPROJECT_us-central1-a_test-zero-cluster-2
  user:
    auth-provider:
      config:
        access-token: [REDACTED]
        cmd-args: config config-helper --format=json
        cmd-path: /c/Users/garyo/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud
        expiry: "2019-12-06T17:43:13Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
I think maybe that's saying to run `gcloud config config-helper ...` which returns something like this:
```
  "credential": {
    "access_token": "REDACTED",
    "id_token": "REDACTED (LONG)",
    "token_expiry": "2019-12-12T23:50:18Z"
  }
```

I've tried various combos of these tokens and I either get "Error: error:0909006C:PEM routines:get_name:no start line" or "Error: unable to verify the first certificate". Any thoughts?

**Comment by kenanarica** [comment]
> Hi; I'm trying to do the same, with Google Kubernetes Engine (I want to start jobs from a back-end service). My ~/.kube/config doesn't look quite like the ones shown here though. Cluster seems OK:
> 
> ```
> - cluster:
>     certificate-authority-data: [REDACTED]
>     server: https://35.111.222.333
> ```
> 
> But, a user is
> 
> ```
> - name: gke_MYPROJECT_us-central1-a_test-zero-cluster-2
>   user:
>     auth-provider:
>       config:
>         access-token: [REDACTED]
>         cmd-args: config config-helper --format=json
>         cmd-path: /c/Users/garyo/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud
>         expiry: "2019-12-06T17:43:13Z"
>         expiry-key: '{.credential.token_expiry}'
>         token-key: '{.credential.access_token}'
>       name: gcp
> ```
> 
> I think maybe that's saying to run `gcloud config config-helper ...` which returns something like this:
> 
> ```
>   "credential": {
>     "access_token": "REDACTED",
>     "id_token": "REDACTED (LONG)",
>     "token_expiry": "2019-12-12T23:50:18Z"
>   }
> ```
> 
> I've tried various combos of these tokens and I either get "Error: error:0909006C:PEM routines:get_name:no start line" or "Error: unable to verify the first certificate". Any thoughts?

For anybody struggling with this issue- What worked for me was setting the node environment variable `export NODE_TLS_REJECT_UNAUTHORIZED=0`. Remember that changing Node's TLS/SSL settings may have consequences depending on your context, so do it at your own risk!
