### ISSUE TITLE
Delete all by label selectors?

### ISSUE THREAD

**Issue by jeasonstudio** [kubernetes-client/javascript#296]
Is there any way to delete all by label selectors?

**Comment by brendandburns** [comment]
No, as far as I know the Kubernetes API doesn't support that. You'd have to do it client side.

**Comment by laidinidis** [comment]
But how we can do this `kubectl delete pods,services -l name=myLabel` ?
(from https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#delete)
