### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by svenefftinge** [kubernetes-client/javascript#3]
There is no package.json.

**Comment by brendandburns** [comment]
There's a package.json here:

https://github.com/kubernetes-client/javascript/blob/master/node/package.json

I don't think we need a top-level one, do we?

**Comment by svenefftinge** [comment]
ok, it's a little uncommon, though. so you might see more people asking about it.

**Comment by brendandburns** [comment]
The motivation was because I want both a `lib` and an `examples` directory and I didn't want to have my examples inside my lib.  How do other projects handle that kind of thing?

Thanks!

**Comment by svenefftinge** [comment]
It would make sense to me if there were different `package.json` for the code and the examples, but I only see one package.json. You can specify in `package.json` that `examples` should not be published.

But the confusion for me might have been caused by the ts files sitting in the same directory as the `package.json`. They usually sit in some sort of source folder, so you can separate them from `.js` and `.d.ts` files. And the `package.json` in the parent.

**Comment by brendandburns** [comment]
I'm definitely new to packaging a TS library, if you have pointers to canonical examples, I'm happy to re-factor the directory layout.

Thanks!



________________________________________

**Comment by svenefftinge** [comment]
It was easier to just make a proposal, than explaining it :)
https://github.com/kubernetes-client/javascript/pull/4

Feel free to take anything you find useful and please ask if you have questions.
