### ISSUE TITLE
serviceaccount "default" not found 

### ISSUE THREAD

**Issue by leowang15** [kubernetes-client/javascript#300]
When I create spec namespace it will catch error:
```
ERRORMSG pods "b-mini-5ce7c80b3e9652e86a5e3ac9" is forbidden: error looking up service account mini-app/default: serviceaccount "default" not found 
```

**Comment by brendandburns** [comment]
Looks like your pods have a service account that doesn't exist in the cluster.

Does kubectl work in the same environment? (my guess is it doesn't)

I think this is a general authn/authz problem not specific to this library.

**Comment by brendandburns** [comment]
Closing this due to lack of response.
