### ISSUE TITLE
CRD creation does not support additionalPrinterColumns.JSONPath with standard spelling

### ISSUE THREAD

**Issue by niklasbuechner** [kubernetes-client/javascript#305]
**Error**

According to the kubernetes documentation, the printer columns of a custom resource definition can be customised by using `additionalPrinterColumns`: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns

Every printer column requires the value `JSONPath`. This library however requires the key name to be spelled `jSONPath` with a lowercase `j` because it will otherwise remove the JSONPath from the request send to kubernetes. So you can not use a valid CRD declaration which works perfectly well with `kubectl` without adjusting the key.

**Code**

When serialising the crd specification using the `ObjectSerializer`, the column definition contains a `jSONPath` `name` attribute which has a different spelling from the `baseName` of `JSONPath`.

ObjectSerializer: https://raw.githubusercontent.com/kubernetes-client/javascript/master/src/api.ts Line 96 (Can't provide GitHub link, since file is too big)
Specification definition: https://raw.githubusercontent.com/kubernetes-client/javascript/master/src/api.ts Line 20979

This does look like it's an openapi-generator bug or configuration error. I tried to hunt down the root cause but was not successful, since I do not have much experience with the openapi-generator. If you can point me in the correct direction, I am happy to open a pr to fix this bug.

**Code to reproduce the issue**
```JS
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const definition = {
    apiVersion: "apiextensions.k8s.io/v1beta1",
    kind: "CustomResourceDefinition",
    metadata: {
        name: "tests.js.crd",
    },
    spec: {
        group: "js.crd",
        versions: [{
            name: "v1alpha1",
            served: true,
            storage: true,
        }],
        scope: "Namespaced",
        names: {
            plural: "tests",
            singular: "test",
            kind: "Test",
        },
        additionalPrinterColumns: [{
            name: "AdditionalColumn",
            type: "string",
            jSONPath: ".spec.additionalColumn",
        }],
    },
};

const apiextensionsV1beta1Api = kc.makeApiClient(k8s.ApiextensionsV1beta1Api);
(apiextensionsV1beta1Api
    .createCustomResourceDefinition(definition)
).catch(console.log);
```

If you change it to `jSONPath` everything works as expected.

**Comment by brendandburns** [comment]
This code is generated, so it's something in either the swagger/open-api spec or the generator.

It's going to take a while before we have the cycles to look.

Would be happy to have you look into it if you want, the relevant code is here:

https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/typescript-node

And:

https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

**Comment by niklasbuechner** [comment]
I found the misconfiguration of swagger and opened a pr in the corresponding kubernetes-client/gen repository.

Thank you for the help @brendandburns. Shall I assign you to the pr or is the correct reviewer assigned automatically?

**Comment by silasbw** [comment]
FYI, we're in the process of switching from swagger-codegen to openapi-codegen:

* https://github.com/kubernetes-client/gen/pull/125
* https://github.com/kubernetes-client/javascript/pull/307

If we can get ^ landed without too much discussion, it might be easiest to pull @niklasbuechner's change into the openapi switch over.

**Comment by brendandburns** [comment]
@niklasbuechner @silasbw 

What is the best ordering for this? Is that flag still present in the openapi generator?

I'd like to optimize for getting the switch done and then pulling in this fix.

Thanks!

**Comment by silasbw** [comment]
The flag is present (fyi, https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-node.md).

I'd also like to switch to the openapi-generator and then pull this in.

**Comment by niklasbuechner** [comment]
Sounds good to me. 👍
