### ISSUE TITLE
Please fix the security issue introduced by request lib 

### ISSUE THREAD

**Issue by rupeshA** [kubernetes-client/javascript#308]
The request being used by this project is vulnerable to Weak Authentication Algorithm. The function function in oauth.js uses SHA-1 for authentication which is no longer considered cryptographically secure. With enough resources an attacker might be able to crack the authentication mechanism and cause security attacks.

Ref:
https://github.com/request/request/issues/2640  https://security.googleblog.com/2017/02/announcing-first-sha...

**Comment by brendandburns** [comment]
PRs would be welcome to fix this.
