### ISSUE TITLE
Allow REST proxy functions to specify a request body

### ISSUE THREAD

**Issue by cmarkwell** [kubernetes-client/javascript#309]
REST Proxy functions such as connectPostNamespacedServiceProxy and connectPutNamespacedServiceProxy do not provide an option to add a request body. This is harmful for APIs that require information to be sent through said means.

As of #19, users can specify headers through the options argument. Perhaps we can use this options object to specify a body for localVarRequestOptions as well? 

I'm willing to submit a PR for this, if it's something I can do.

Thank you

**Comment by brendandburns** [comment]
Per the openAPI swagger definition of the API:

```json
...
 {
          "description": "name of the ServiceProxyOptions",
          "in": "path",
          "name": "name",
          "required": true,
          "type": "string",
          "uniqueItems": true
        },
...
```

From: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

There is no Body expected for that method. We can't fix this in the client, if the OpenAPI/Swagger is wrong, then it should be fixed there, but I actually don't think it is wrong, I don't think proxy expects a body parameter.

**Comment by cmarkwell** [comment]
True. I'll do some more research, and I'll bring up the question over in that repo. Thanks for pointing me in the right direction.
