### ISSUE TITLE
New release that re-includes the byline dependency

### ISSUE THREAD

**Issue by radu-matei** [kubernetes-client/javascript#310]
#250 removed the dependency on `byline` and added `json-stream`. This change was part of all releases starting [0.9.0](https://github.com/kubernetes-client/javascript/releases/tag/0.9.0), including part of the latest release to date, [0.10.2](https://github.com/kubernetes-client/javascript/releases/tag/0.10.2).

However, https://github.com/kubernetes-client/javascript/commit/57f6c0bb924cebfa5ed9cf72c9cddebc20d7208d switched back from `json-stream` to `byline`, and since there is no release that contains this change, dependents that used `byline` who are updating this package from before 0.9 experience failure due to the missing package.

A new release based off `master`should mitigate this, and a workaround is to directly add `"byline": "^5.0.0"` as a dependency.

**Comment by drubin** [comment]
@radu-matei I am a little confused is your application is dependant on `byline` and upgrading to `0.10.2` broke because we removed `byline` and you were explicitly using it somewhere?

**Comment by radu-matei** [comment]
Precisely - that being said, we should probably have explicitly declared it as a dependency (and did after upgrading the Kubernetes client, so this is not blocking in any way) - that being said, a new release would ensure that this doesn't break future upgrades from older versions that relied on `byline`.

**Comment by brendandburns** [comment]
I'm going to close this. We're going to do a new release eventually, but I don't think that there's anything actionable other than "do a new release" which we will definitely get to eventually....
