### ISSUE TITLE
Broken link in SECURITY_CONTACTS

### ISSUE THREAD

**Issue by AmazingTurtle** [kubernetes-client/javascript#311]
See https://github.com/kubernetes-client/javascript/blob/4d8ad748884ec3e77b10240cb65d516f817a1639/SECURITY_CONTACTS#L7
Link pointing to embargo policy is broken

Why do you guys always point to `master` and not a specific commit?

**Comment by drubin** [comment]
@AmazingTurtle Thanks for reporting this. I have submitted a PR that should fix this.
