### ISSUE TITLE
Ingress extensions/v1beta1 vs networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by entropitor** [kubernetes-client/javascript#313]
Currently this client has no method to create an Ingress with the new api `networking.k8s.io/v1beta1` (https://github.com/kubernetes/kubernetes/pull/74057). It's working fine when using kubectl

E.g. this is working
```bash
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-name
spec:
  rules:
    - http:
        paths:
          - path: /test-path
            backend:
              serviceName: echo
              servicePort: http
EOF
```

But there is only one `createNamespacedIngress` function and that is still using the extensions api

**Comment by brendandburns** [comment]
We need to regenerate the API for the newer version.

**Comment by entropitor** [comment]
@brendanburns Is this hard to do?

**Comment by brendandburns** [comment]
Here's an example PR one of the last times we did this:
https://github.com/kubernetes-client/javascript/pull/262

Instructions here:
https://github.com/kubernetes-client/javascript#re-generating-code

**Comment by ianwalter** [comment]
Was this ever done? It seems like it's still using `extensions/v1beta1`?
