### ISSUE TITLE
client should periodically reload InClusterConfig token

### ISSUE THREAD

**Issue by mikedanese** [kubernetes-client/javascript#317]
See https://github.com/kubernetes/kubernetes/issues/70679

**Comment by brendandburns** [comment]
@mikedanese 

I read through the docs on this new feature. How can a client know when a token is about to expire? (and thus needs to be reloaded)

As far as I can tell, the kubelet rotates the token, but there's no notification or other information the client can use.

If this is the case, the only thing a client can do is _always_ reload which isn't ok from a perf perspective.

**Comment by mikedanese** [comment]
There are three options today:

1. Reload once per minute (which is what client go does). Rational for the frequency const is here: https://github.com/kubernetes/kubernetes/blob/ebf15029da1e413365e8e728f0e873a717cf29e7/staging/src/k8s.io/client-go/transport/token_source.go#L54-L57
2. Reload on 401 (which is what some exec auth plugins do e.g. here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L224-L232).
3. Parse the token. There are standard JWTs as defined in https://tools.ietf.org/html/rfc7519. If you base64 the payload (content between the first and second `.` in the token) you should see something like:

```json
{
  "aud": [
    "https://container.googleapis.com/v1/projects/mikedanese-k8s/locations/us-central1-f/clusters/foo"
  ],
  "exp": 1566456687,
  "iat": 1566453087,
  "iss": "https://container.googleapis.com/v1/projects/mikedanese-k8s/locations/us-central1-f/clusters/foo",
  "kubernetes.io": {
    "namespace": "kube-system",
    "serviceaccount": {
      "name": "ttl-controller",
      "uid": "34ee1910-b7ce-11e9-8560-42010a80003c"
    }
  },
  "nbf": 1566453087,
  "sub": "system:serviceaccount:kube-system:ttl-controller"
}
```

If "exp" claim is not set, it doesn't expire. Semantics of the "exp" claim are defined here https://tools.ietf.org/html/rfc7519 and the value is a NumericDate:

> A JSON numeric value representing the number of seconds from
> 1970-01-01T00:00:00Z UTC until the specified UTC date/time,
> ignoring leap seconds.

Do the second or third method seem preferable to the first? Can you think of anything else that would work better?

cc @liggitt @enj (since I can't cc a sig-auth team from another org)

**Comment by enj** [comment]
File system notifications via something like `inotify` is also an option (though difficult to do cross platform).
