### ISSUE TITLE
Exec not working with authentication

### ISSUE THREAD

**Issue by Vinceveve** [kubernetes-client/javascript#32]
Error : UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'Authorization' of undefined

Raised from here (opts.headers does not exists) https://github.com/kubernetes-client/javascript/blob/master/node-client/src/config.ts#L156

When I patch it :
```typescript
if (token) {
            if(!opts.headers) {
                opts.headers = {};
            }
            opts.headers['Authorization'] = token;
 }
```
I get :  Error: Server responded with a non-101 status: 400 Bad Request at WebSocketClient.failHandshake (audit-id: 8c520bd1-f6b8-4c98-9175-b77e23724fc8)

I'm using GCE with Kubernetes 1.8 with .kube/config's user :

```yaml
name: kubectl-exec
  user:
    token: e...Q
```

my script : 

```typescript
import k8s = require('@kubernetes/client-node');
let command = process.argv[2];

let kc = new k8s.KubeConfig();
kc.loadFromFile(process.env['HOME'] + '/.kube/config');

let exec = new k8s.Exec(kc);
exec.exec('default', 'dep-yolo-6476bc5465-9s6bm', 'yolo', command, process.stdout, process.stderr, process.stdin, true /* tty */);
```

Other commands (list namespaces, get pod ...) are working fine

**Comment by brendandburns** [comment]
(cleaning up old issues)

The top level problem (`headers` is null) has been fixed, `headers` should be an array, not an object, so perhaps that's what was causing your problem?

My `exec` examples work correctly for me, so I'm closing this for now. Please re-open if issues persist.
