### ISSUE TITLE
Error Connection Refused

### ISSUE THREAD

**Issue by maminio** [kubernetes-client/javascript#321]
Just by running the example code for listing the pods I get this in the pod logs: 
```
Error: connect ECONNREFUSED 127.0.0.1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8080
}
```

Not sure what’s causing it.

**Comment by brendandburns** [comment]
There's no Kubernetes server running @ 127.0.0.1:8080

My guess is that you don't have a Kubernetes config file in an expected location ($HOME/.kube/config)

If kubectl works (e.g. `kubectl get pods`) and the example doesn't, please send the location and contents (secrets redacted of course) of your kubeconfig file.

**Comment by brendandburns** [comment]
Closing due to no response.

**Comment by JayeshThamke** [comment]
Small addition, it works even though KUBECONFIG env variable is set with kubeconfig path.
