### ISSUE TITLE
Version lock kubernetes-client/gen so we can verify the code generated is always the same

### ISSUE THREAD

**Issue by drubin** [kubernetes-client/javascript#325]
We should not be randomly using master branch of `kubernetes-client/gen` to generate the code. This makes it almost impossible to accept PR's and automatically verifying that the code is from the correct commit (people might have older master versions or running from another commit).

We could also further optimize this by adding a check in CI if the generated code doesn't match the codified commit it can fail and let us know. 

This comes from a comment in https://github.com/kubernetes-client/javascript/pull/316#discussion_r310800028

**Comment by brendandburns** [comment]
Closing since this is mostly covered by #330
