### ISSUE TITLE
"Error: unable to verify the first certificate" when using loadFromCluster()

### ISSUE THREAD

**Issue by itayvallach** [kubernetes-client/javascript#329]

**Comment by yasharma** [comment]
hi, i've faced the same issue when using remote kubernetes cluster from my local machine, there are couple of ways to fix or you can say a workarounds but only for development purpose so for those who faced the similar issue here two few solution
1. add env `NODE_TLS_REJECT_UNAUTHORIZED='0'`
or
2. this library uses request library behind the scene if you call any kubernetes function ex. list `listNode`, so there should be options exposed to configure the 
`strictSSL: false` for development purpose only

Here is my configuration with `loadFromCluster`
```js
const cluster = {
   name: 'my-server',
   server: 'https://yourserver.com:port',
  };
const context = {
   name: 'my-context',
   cluster: cluster.name,
};
const kc = new k8s.KubeConfig();
kc.loadFromOptions({
  clusters: [cluster],
  contexts: [context],
  currentContext: context.name,
});
kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

const result = await k8sApi.listNode('true', undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined,undefined, {
  headers: {
    authorization: 'Bearer passyourtoken here if required'
  }
});
return result.body;
```
if you've any better options let me know
Thanks
