### ISSUE TITLE
Reject with error instead of object

### ISSUE THREAD

**Issue by aeb-sia** [kubernetes-client/javascript#336]
It would be nice if the promises rejected with an error and not with an object. Currently when I try to retrieve an object that is not present a 404 is thrown as an object which doesn't implement `Error`

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/customObjectsApi.ts#L151

**Comment by brendandburns** [comment]
@aeb-sia thanks for filing the issue.

Why is this important? What use case does it block? That information will help us prioritize the work. (or feel free to send a PR)

Thanks

**Comment by aeb-sia** [comment]
It makes life easier. Errors have stacktraces that you don't get when you throw a simple object.

It doesn't block anything. I am open to sending a PR, but I'd need some guidance as to where this shoudl be added. It looks like the code is generated and I have no idea where I should make changes

**Comment by brendandburns** [comment]
The code is generated by the generator here:

https://github.com/OpenAPITools/openapi-generator

Specifically this directory:
https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/typescript-node

They're generally pretty good at accepting PRs...

Thanks!

**Comment by aeb-sia** [comment]
Not sure how this can be rebuilt so it uses the new open api generator. Do I need to check out the project and run the generation locally?

**Comment by aeb-sia** [comment]
@brendandburns not really sure what I need to have installed to regenerate the code. I guess it's easier if you do that. 
[v4.1.3](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.1.3) was just released, which should throw Errors on rejection

**Comment by the21st** [comment]
/reopen

Promises are still being reject with non-Error types. See any line `reject({ response: response, body: body });` in e.g. https://raw.githubusercontent.com/kubernetes-client/javascript/master/src/gen/api/coreV1Api.ts

**Comment by aeb-sia** [comment]
Looks like the generator wasn't actually run. There is an open MR !418 that ran the generator and actually includes the fixes
