### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT when using list namespaces api

### ISSUE THREAD

**Issue by ameerthehacker** [kubernetes-client/javascript#338]
Describe the bug
Getting error"Unable to connect to the kube cluster: UNABLE_TO_GET_ISSUER_CERT"

My kubeconfig is using a self signed cert to connect to the cluster. The CA and private key exist in the kubeconfig.

**Comment by brendandburns** [comment]
Does `kubectl` work correctly?

If so, can you send you attach your kubeconfig file (secrets redacted, but please retain the CA cert) to this issue.

Thanks

**Comment by brendandburns** [comment]
Closing due to lack of response. Feel free to re-open if you want with the requested information.
