### ISSUE TITLE
Listing/Watching kubernetes Custom Resources

### ISSUE THREAD

**Issue by SachinVarghese** [kubernetes-client/javascript#341]
Is it currently possible to list or watch k8s CRDs in javascript and create client code for the same?

**Comment by brendandburns** [comment]
Please see this example here:

https://github.com/kubernetes-client/javascript/blob/master/examples/cache-example.js#L13

And the informer example here:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts

Closing this issue as the question is answered. Please re-open if you need more info.

**Comment by SachinVarghese** [comment]
@brendandburns Thanks for the links but I was actually looking for an example with a custom resource definition listing and not simply listing/watching for pods which could be very similar. Please let me know how can such a use case be implemented in javascript.

**Comment by zoidbergwill** [comment]
So I just stumbled upon this issue looking for a similar answer to @SachinVarghese 

So this client is generated with [this script](https://github.com/kubernetes-client/javascript/blob/master/generate-client.sh) which uses the [kubernetes-client/gen](https://github.com/kubernetes-client/gen) repo to generate a [typescript](https://github.com/kubernetes-client/gen/blob/master/openapi/typescript.sh) client.

I found a issue that hasn't been updated in 6 months about making that 'kubernetes-client/gen' repo work for CRDs too: https://github.com/kubernetes-client/gen/issues/121

**Comment by zoidbergwill** [comment]
Can we re-open it but consider it blocked by https://github.com/kubernetes-client/gen/issues/121?

**Comment by brandonc** [comment]
@zoidbergwill I was able to generate a cluster-specific client with CRD apis/models with a couple of simple steps using the existing code:

1. Download the cluster's `/openapi/v2` spec and replace src/gen/swagger.json.unprocessed with it
2. Append `export OPENAPI_SKIP_FETCH_SPEC=1` to the file `settings`
3. `npm run generate`

**Comment by mcandre** [comment]
Does this handle updates and deletes, or just creates?

**Comment by pfisterer** [comment]
@brendandburns @SachinVarghese Can you point me to a working example that uses `Informer` to watch custom resources?

I'm getting this error:

```console
[DEBUG] Reconciler - init: Watching group 'mk8.farberg.de', version 'v1', plural 'microkeights'
./node_modules/@kubernetes/client-node/dist/cache.js:77
            const list = result.body;
                                ^

TypeError: Cannot read property 'body' of undefined
    at ListWatch.<anonymous> (./node_modules/@kubernetes/client-node/dist/cache.js:77:33)
    at Generator.next (<anonymous>)
    at fulfilled (./node_modules/tslib/tslib.js:112:62)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

when using this code:

```JavaScript
async init() {
  //Create K8s Client
  this.logger.debug(`init: Creating kubeconfig`)
  this.kubeConfig = new k8s.KubeConfig();
  this.kubeConfig.loadFromDefault();
  this.k8sApi = this.kubeConfig.makeApiClient(k8s.CoreV1Api);
  this.customObjectsApi = this.kubeConfig.makeApiClient(k8s.CustomObjectsApi)
  
  // Register custom resource definition
  // registerCustomResourceDefinition @ https://github.com/dot-i/k8s-operator-node/blob/master/src/operator.ts
  this.logger.debug(`init: Registering CRD from file ${this.options.crdFile}`)
  const { group, versions, plural } = await this.registerCustomResourceDefinition(this.options.crdFile);
  this.crdGroup = group;
  this.crdVersions = versions;
  this.crdPlural = plural;
  
  console.log("XXX", await this.customObjectsApi.listClusterCustomObject(this.crdGroup, versions[0].name, this.crdPlural))
  
  this.logger.debug(`init: Watching group '${this.crdGroup}', version '${this.crdVersions[0].name}', plural '${this.crdPlural}'`)
  
  const informer = k8s.makeInformer(this.kubeConfig, `/apis/${this.crdGroup}/${versions[0].name}/${this.crdPlural}`, () => {
     console.log("Called")
  })
}
```
