### ISSUE TITLE
ECONNREFUSED in async function

### ISSUE THREAD

**Issue by RefRec97** [kubernetes-client/javascript#343]
When using the detector externally everything works fine, but when we want to use it in the kubernetes cluster we get this error message.
I'm quite sure the problem is caused in cache.ts with listFn().

`private async doneHandler(err: any) {
        const promise = this.listFn();
        const result = await promise;
        const list = result.body;
        deleteItems(this.objects, list.items, this.callbackCache[DELETE].slice());
        this.addOrUpdateItems(list.items);
        this.watch.watch(
            this.path,
            { resourceVersion: list.metadata!.resourceVersion },
            this.watchHandler.bind(this),
            this.doneHandler.bind(this),
        );
    }`

`const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();

//kc.loadFromDefault(); //for local use
kc.loadFromCluster(); //for server use

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

const path = '/api/v1/namespaces/namespaceName/services';

const watch = new k8s.Watch(kc);

const listFn = () => k8sApi.listServiceForAllNamespaces();

const cache = new k8s.ListWatch(path, watch, listFn);

exports.services = new HashMap();
console.debug('loopstart, api: '+k8sApi+', watch: '+watch+', listFN: '+k8sApi.listServiceForAllNamespaces()+', cache: '+cache);
const looper = () => {
	console.debug('listcache start: ');
	
	const list = cache.list('namespaceName');`

this error message is thrown at this line of code: const list = cache.list('namespaceName');
> (node:1) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED "ip":443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by brendandburns** [comment]
This looks to me like the service account hostname environment variable isn't set in your environment for some reason.

See:
https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L173

Can you check if that environment variable is present in your cluster? You may not have a 'kubernetes' Service defined. What does `kubectl get services` show?

**Comment by RefRec97** [comment]
Thank you for your reply, the environment variable (`KUBERNETES_SERVICE_HOST`) is present with the correct ip in this pod.
The 'kubernetes' service is running in the 'default' namespace.
This Application runs in the 'namespaceName' namespace.

**Comment by brendandburns** [comment]
When you say `"ip"` in the error message that you printed, is that literally the error message that you saw? Or did you remove the actual IP address (for privacy/security/whatever)

**Comment by RefRec97** [comment]
I did remove it, which was stupid as it is a private one, sorry. Yes when i said ip in the errormessage its a 10.x.x.x ip, the same that is saved in the kubernetes_service_host

**Comment by brendandburns** [comment]
Ok, in that case is your master actually serving on `${IP}:443`? Is the master on a different port perhaps?

Can you `kubectl exec` into the Pod and try using `curl` and see if it works?

Thanks!

**Comment by RefRec97** [comment]
strangely it does, it returns  `Client sent an HTTP request to an HTTPS server.`
But in the Podlog I still see: `connect ECONNREFUSED 10.96.0.1:443`

**Comment by brendandburns** [comment]
At this point, running `tcpdump` in the pod might be necessary to see what is going on. I'm out of good ideas about what could be going wrong.

Are you trying to connect repeatedly? Or just once? It's possible that maybe it's taking a second for networking to get setup correctly? [that's a stretch...]

**Comment by RefRec97** [comment]
We are calling cache.list repeatedly, but this error message just comes once. I will try the tcpdump later.
Maybe it could help if we arrange a skype call, if you would have time for that, so you can see it in action.

**Comment by brendandburns** [comment]
does it happen on the first call? or intermittently? Is your API server crashing? It's possible that either CNI networking or the `kube-proxy` isn't always working correctly. Can you find the literal IP address of your api server (the IP address in `KUBERNETES_SERVICE_HOST` is generally a service load balancer not the actual IP address)

If it works talking directly to the ApiServer but not via the Service, then it's a `kube-proxy` issue...

Are you using `NetworkSecurityPolicy` objects? It's possible that something is messing that up or lagging.

At this point I think that this is beyond the scope of this library as it seems to be more of an underlying networking problem rather than a problem in the library.

I guess another possibility is that you are running out of ports or file descriptors, especially if this error occurs after a long time of running.

**Comment by RefRec97** [comment]
It was the serviceaccount, we didnt use it, so your guess with `NetworkSecurityPolicy` was absolutely correct.
Sadly now we get this: `(node:1) UnhandledPromiseRejectionWarning: #<Object>`.
Not sure how to find out what #<Object> is

**Comment by RefRec97** [comment]
maybe it would help if I show you the output of the console debugs.

**1. From outside the cluster:**
loopstart, api: [object Object], watch: [object Object], listFN: [object Promise], cache: [object Object]
listcache start: 
listcache: undefined
Enterprise Portal app listening on 0.0.0.0:14565
listcache start: 
listcache: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
if list
for listlength: 8
resver
existingElement

**2. inside the cluster:**
loopstart, api: [object Object], watch: [object Object], listFN: [object Promise], cache: [object Object]
listcache start: 
listcache: undefined
Enterprise Portal app listening on 0.0.0.0:80
(node:1) UnhandledPromiseRejectionWarning: #<Object>
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: #<Object>
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
listcache start: 
listcache: undefined
listcache start: 
listcache: undefined
listcache start: 
listcache: undefined
listcache start: 


**full code:**
'use strict';
var events = require('events');
var HashMap = require('hashmap');

exports.eventEmitter = new events.EventEmitter();

const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();

kc.loadFromDefault();
//kc.loadFromCluster();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

const path = '/api/v1/namespaces/namespaceName/services';

const watch = new k8s.Watch(kc);

const listFn = () => k8sApi.listServiceForAllNamespaces();

const cache = new k8s.ListWatch(path, watch, listFn);

exports.services = new HashMap();
console.debug('loopstart, api: '+k8sApi+', watch: '+watch+', listFN: '+k8sApi.listServiceForAllNamespaces()+', cache: '+cache);
const looper = () => {
	console.debug('listcache start: ');
	
	const list = cache.list('namespaceName');
	console.debug('listcache: '+list);
    
    if (list) {
    	console.debug('if list');
        for (let i = 0; i < list.length; i++) {
        	console.debug('for listlength: '+list.length);
        	var resVer = list[i].metadata.resourceVersion;
        	console.debug('resver');
        	var existingElement = exports.services.get(resVer);
        	console.debug('existingElement');
        	exports.services.set(resVer, list[i]);                
        }
        exports.eventEmitter.emit('serviceDetected');
        //console.log(exports.names.join(','));        
    }
    setTimeout(looper, 10000);
}

looper();

**Comment by brendandburns** [comment]
I'll look into the ListWatch, I suspect that there is a permissions error (e.g. `503`) that I'm not catching well.

Can you try `kubectl watch ...` inside the Pod and see if it works (or prints an error message?) I bet that something is going wrong in HTTP

Another alternative would be to look at the API server logs to see if you can find the error there.

I'm glad we're making progress!

**Comment by RefRec97** [comment]
im really glad to, in the apiserver logs i got this:
`E0926 21:23:55.248544       1 status.go:71] apiserver received an error that is not an metav1.Status: &http.badStringError{what:"malformed HTTP response", str:"\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00"}`

with `kubectl watch ...` do you mean something like `kubectl get pods -w -n namespaceName`?

**Comment by brendandburns** [comment]
Yeah, `kubectl get pods -w ...` was what I meant, sorry I typed the wrong thing...

I don't think that error is related, that looks like a call to an aggregated API server that's not working correctly or something like that...

**Comment by brendandburns** [comment]
If it's easier/faster we can use the #kubernetes-client channel in Kubernetes slack tomorrow morning sometime (Pacific time) for more interactive discussion/debugging

**Comment by RefRec97** [comment]
The kube slack idea is great, I would really appreciate that.
I made a `helm delete` on the application, then a `helm install`. After that I called `kubectl get pods -w -n namespaceName` but I could only see the new one now running and the old one being terminated.

**Comment by RefRec97** [comment]
Hey, so have you had time to look into it?
