### ISSUE TITLE
Closing issues doesn't make your repo less buggy

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes-client/javascript#345]
@brendandburns So I have seen that some repo owners and it looks like you in this case think that somehow closing issues that are active bugs somehow makes a repo less buggy. Actually it just make you look like a lazy and/or deceptive f*ck. You can write whatever bullshit excuse you want but if people look at all the closed issues, most of them are closed even though they are active bugs. Are you getting paid based on how many active issues are open? If so that is a dying shame for the repo because it makes the repo users worse off instead of better off.

**Comment by brendandburns** [comment]
This repository is part of the Kubernetes community and as such is covered by the CNCF code of conduct. I would encourage you to read the code of conduct that you can find here:

https://github.com/cncf/foundation/blob/master/code-of-conduct.md#contributor-code-of-conduct

Professional and respectful communication is a key value and hallmark of the Kubernetes community, please ensure that future interactions in the Kubernetes community follow adhere to the code of conduct.

Thanks

**Comment by woodcockjosh** [comment]
You got rekt bro. I hope you think twice about closing valid issues.

**Comment by woodcockjosh** [comment]
Dont worry guys I sent them an email myself. We can all be standing tall explaining ourselves.

**Comment by woodcockjosh** [comment]
For your research purposes, here's a model example on how to properly run a repo and encourage people to contribute rather than attract the kind of response you got from me https://github.com/kubernetes/minikube

**Comment by woodcockjosh** [comment]
I apologize for my comments and can assure you it won't happen again. Please continue to manage your repo however you see fit.
