### ISSUE TITLE
bundle failing on electron dependency

### ISSUE THREAD

**Issue by ssube** [kubernetes-client/javascript#350]
The v0.10.3 release seems to have a breaking change for clients bundled with rollup (and likely webpack) thanks to a transitive dependency requiring electron:

```
Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/build/src/git.apextoaster.com/ssube/isolex/out/vendor.js:1:1304)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module.replacementCompile (/build/src/git.apextoaster.com/ssube/isolex/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.<anonymous> 
```

The `openid-client` package added in [this commit](https://github.com/kubernetes-client/javascript/commit/fb1ee0c9069bf686cdc480d522c3a556fa61ec15) has a requirement on `got`:

```
openid-client@2.5.0:
  version "2.5.0"
  resolved "https://artifacts.apextoaster.com/repository/group-npm/openid-client/-/openid-client-2.5.0.tgz#7d4cf552b30dbad26917d7e2722422eda057ea93"
  integrity sha512-t3hFD7xEoW1U25RyBcRFaL19fGGs6hNVTysq9pgmiltH0IVUPzH/bQV9w24pM5Q7MunnGv2/5XjIru6BQcWdxg==
  dependencies:
    base64url "^3.0.0"
    got "^8.3.2"           
    lodash "^4.17.11"     
    lru-cache "^5.1.1"    
    node-jose "^1.1.0"                                                                                                            
    object-hash "^1.3.1"                                                                                                          
    oidc-token-hash "^3.0.1"                                                                                                      
    p-any "^1.1.0"             
```

The `got` library, in turn, requires electron without any `try`/`catch` handling [here](https://github.com/sindresorhus/got/blob/8-release-line/index.js#L91):

```
if (opts.useElectronNet && process.versions.electron) {
  const electron = require('electron');
  fn = electron.net || electron.remote.net;
}
```

I think it should be possible to work around this with `rollup-replace-plugin` or globals, but this does appear to be a breaking change for any bundled/frontend use of the client.

**Comment by brendandburns** [comment]
Sorry about this! We'll fix that asap!

**Comment by brendandburns** [comment]
Actually, @ssube as I dig into this, do you have a suggestion about how to fix this? I haven't used rollup before and I'm not sure if it's something that we need to place in this library/package.json or something that you need to do on the rollup config side.

Advice/pointers would be useful.

Thanks!

**Comment by ssube** [comment]
I've been looking into it as well, and this one seems a little tricky: my usual fix would be to replace the `require('electron')` module with a fake stub that will either `return undefined` or `throw`, as needed for the library doing the require. In this case, the lack of surrounding error handling in `got` or somewhere was complicating that, but I will take another try and see if I can come up with a config workaround.

**Comment by ssube** [comment]
Ok, this fell off my radar for a little bit, but after some experimentation: 

The most-specific replacement, replacing the `require('electron')` within `got`, resulted in a bunch of circular dependency errors:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:146:11)                     
    at Object.<anonymous> (/home/ssube/code/ssube/isolex/out/vendor.js:63561:473)
```
(rollup code for a superclass and subclass that were placed out of order, thanks to a cyclical dep)

However, moving that up and making `got` a [rollup external](https://rollupjs.org/guide/en/#external) seems to do the trick:

```json
const bundle = {
  external: [
    'got',
  ],
...
};
```

Deceptively simple, but it compiles and tests well. My tests don't use the `openid-client`/`got` code path, but when that code is active, `got` would need to be installed by the library consumer. But since `got` seemingly can't be bundled, I'm not sure that's a problem for bundled/frontend consumers.
