### ISSUE TITLE
Using CA Cert, I can't connect: "Error: unable to verify the first certificate". Works fine with curl.

### ISSUE THREAD

**Issue by dan-barrett** [kubernetes-client/javascript#362]
I am trying to issue API calls without a kubectl proxy. In other words, I am trying to hit the remote API directly not through a local proxy. In order to do this, you need to include the ca certificate for TLS security and the Bearer token to authenticate.

I can do that perfectly successfully with `curl`. The following returns perfectly fine. (note: I took the certData from my kubectl config, then base64 decoded it and put it here:  `/tmp/kube-ca.crt`. As I said, this all works fine.)

```
curl https://<my.kube.ip.address>/api --header "Authorization: Bearer <user-secret-token>" --cacert /tmp/kube-ca.crt
```

But when I try the same thing using this javascript client, it fails during TLS connection. Here is the call stack and error message:

```
(node:126) UnhandledPromiseRejectionWarning: Error: unable to verify the first certificate
     at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)
     at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:66:19
     at Scope._activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:40:14)
     at Scope.activate (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:11:17)
     at TLSSocket.bound (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:65:20)
     at TLSSocket.emit (events.js:209:13)
     at TLSSocket.EventEmitter.emit (domain.js:476:20)
     at TLSSocket._finishInit (_tls_wrap.js:792:8)
     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)
```

Here is my code:
```
    const k8s = require('@kubernetes/client-node');
    const kc = new k8s.KubeConfig();

    const cluster = {
      name: '<my-cluster-name>',
      server: 'https://<my.kube.ip.address>/api',
    };

    const user = {
      name: '<my-cluster-user>',
      certFile: '/tmp/certs/ca.crt',
      token: '<user-secret-token>',
    };

    const context = {
      name: '<my-context>',
      user: user.name,
      cluster: cluster.name,
    };

    kc.loadFromOptions({
      clusters: [cluster],
      users: [user],
      contexts: [context],
      currentContext: context.name,
    });

    const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

    k8sApi.listNamespacedPod('default').then((res: any) => {
      console.log(res.body);
    });
```

Am I configuring the code wrong?

**Comment by brendandburns** [comment]
caFile is associated with the `server` not `user` object.

https://github.com/kubernetes-client/javascript/blob/master/src/config_types.ts#L8

Do you have a kubeconfig file? It's much easier to just load from a kubeConfig file than construct it in code...

**Comment by dan-barrett** [comment]
Thank you for looking at this Brendan. I had seen the certData property on User and assumed it was there. Putting it on the cluster obviously makes more sense; I've done that and things work as expected.

Note: I can't load the options from a kubeconfig file because I'm writing an application that needs the configuration data to be dynamic, so I have to set it on a per-request basis. But thanks for the suggestion.

Marking this as closed.
