### ISSUE TITLE
makeInformer watch stops receiving updates for "/api/v1/configmaps"

### ISSUE THREAD

**Issue by mag415** [kubernetes-client/javascript#364]
```
  const kc = new k8s.KubeConfig();
  kc.loadFromDefault();

  const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
  const listFn = () => k8sApi.listConfigMapForAllNamespaces();
  const informer = k8s.makeInformer(kc, "/api/v1/configmaps", listFn);

  informer.on("add", (obj: any) => {
    console.log(`Added: ${obj.metadata!.name}`);
  });
  informer.on("update", (obj: any) => {
    console.log(`Updated: ${obj.metadata!.name}`);
  });
  informer.on("delete", (obj: any) => {
    console.log(`Deleted: ${obj.metadata!.name}`);
  });

  await informer.start();
```
Code above works as expected for about the first 10-15 mins, but stops receiving updates for config maps after that.

**Comment by drubin** [comment]
@mag415  does the application throw an exception? 

The informer API requires a connection to the k8s API server and I  believe if there is a disconnect/error it will throw an error. (but I might be wrong here)

**Comment by mag415** [comment]
I'm not seeing any exception thrown. Also while working with a debugger I'm not seeing the `doneHandler` get invoked at any point.

**Comment by brendandburns** [comment]
My guess is that the TCP stream disconnected, but either an exception got swallowed somewhere, or the system is waiting for a socket timeout (which can be up to 20 minutes on Linux)

I'll take a look at the code and see if an exception is getting swallowed somewhere.

**Comment by mag415** [comment]
Can this issue be reopened? I pulled down the commit for `Add some missing error handling.` (36c9095) which we hoped would have helped, but I'm still seeing this same behavior.

**Comment by mag415** [comment]
We pulled in version 0.11.1, but still seeing some unexpected behavior. 
We're noticing that CRD queries tend to stop returning results after watch restarts.

**Comment by mag415** [comment]
For reference: https://github.com/walmartlabs/cookie-cutter/pull/54
