### ISSUE TITLE
Using with Typescript

### ISSUE THREAD

**Issue by yebrahim** [kubernetes-client/javascript#37]
I'm trying to use the node client from a Typescript file, but I can get the compiler to be happy when including it. Doing:
```import { Config } from '@kubernetes/client-node/dist/src/config';```
the compiler complains that it can't find the definition file for bluebird. This is because it's in the devDependencies of the client's package.json, so it doesn't get installed when doing `npm install`.

What is the recommended way to use the package from Typescript? An example would be appreciated.

**Comment by sheldonkwok** [comment]
https://github.com/kubernetes-client/javascript/pull/39

**Comment by yebrahim** [comment]
@sheldonkwok, when does this get pushed to npm?

**Comment by sheldonkwok** [comment]
@yebrahim https://github.com/kubernetes-client/javascript/issues/40

**Comment by yebrahim** [comment]
Awesome, thanks!
