### ISSUE TITLE
Object serialize adds garbage to body

### ISSUE THREAD

**Issue by amarcazzo** [kubernetes-client/javascript#374]
Hi there,

I'm trying to create an ingress resource and the object serializer its adding values to the original object  that doesn't supposed to be there in the first place.

Original object:
<img width="721" alt="Screen Shot 2019-12-03 at 17 51 33" src="https://user-images.githubusercontent.com/23349663/70088712-96d60280-15f5-11ea-90f4-9dc90c238e7a.png">

Modified object:
<img width="634" alt="Screen Shot 2019-12-03 at 17 43 19" src="https://user-images.githubusercontent.com/23349663/70088274-b02a7f00-15f4-11ea-9dbe-07c89f647fe8.png">

I was able to fix this by modifying the line and passing the object without using the serialize method.
<img width="784" alt="Screen Shot 2019-12-03 at 17 51 03" src="https://user-images.githubusercontent.com/23349663/70088763-ad7c5980-15f5-11ea-8e0f-e7130ba96162.png">

In addition to this issue, the servicePort  in NetworkingV1beta1Ingress is now typed as object when it's supposed to be number | string as it was mentioned on issue #349 

Thank you in advance.

**Comment by brendandburns** [comment]
Your modification got clipped.

Can you provide the full sample code of what you are trying, and what you changed to fix things?

Thanks!

**Comment by brendandburns** [comment]
Closing due to no feedback. Please use the `/reopen` command to reopen this issue if necessary.
