### ISSUE TITLE
Interest in generic object API class

### ISSUE THREAD

**Issue by ddgenome** [kubernetes-client/javascript#375]
I've created a generic Kubernetes object API class that allows you to pass any valid Kubernetes spec object to the action, e.g., create/delete/list/patch, that you want to perform.

https://github.com/atomist/sdm-pack-k8s/blob/43f41c251527f42fd9859453c582ee878af1bb96/lib/kubernetes/api.ts

This allows you to more easily perform tasks equivalent to `kubectl create|apply|delete` using the SDK.

You can see how it can be used to mimic the functionality of `kubectl apply` here:

https://github.com/atomist/sdm-pack-k8s/blob/43f41c251527f42fd9859453c582ee878af1bb96/lib/kubernetes/apply.ts

Is there any interest in incorporating this functionality into this repo's official Kubernetes JavaScript/Node.js client?

**Comment by brendandburns** [comment]
Sure, this looks very useful. We'd welcome a PR.

Can you include an example of how to use it for the examples directory as well?

Thanks!

**Comment by ddgenome** [comment]
Sounds good. I'll start work on it.

**Comment by travisghansen** [comment]
This. Also generic watches (that reconnect and detect dead peers) by simply passing the endpoint without all the autogenerated garbage.

**Comment by binura-g** [comment]
@ddgenome This is extremely useful, thanks! 💯

**Comment by ddgenome** [comment]
I did not include a generic list or watch for the initial PR. List didn't seem to make sense, since if you have a spec, you'd read not list. As this was already delayed several months due to availability, I did not want to further delay it figuring out how to do a generic watch.
