### ISSUE TITLE
What's the difference between a Watch and an informer?

### ISSUE THREAD

**Issue by jwalton** [kubernetes-client/javascript#377]
What's the difference between:

```
        const watch = new k8s.Watch(kubeConfig);
        watch.watch(
            '/api/v1/namespaces/default/pods',
            {},
            (type, obj) => {
                switch (type) {
                    case 'ADDED':  console.log('added'); break;
                    case 'MODIFIED': console.log('modified'); break;
                    case 'DELETED': console.log('deleted'); break;
                }
            },
            err => {
                console.log('error');
            }
        );
```

and:

```
const listFn = () => k8sApi.listPodForAllNamespaces();

const informer = k8s.makeInformer(kc, '/api/v1/namespaces/default/pods', listFn);

informer.on('add', (obj: k8s.V1Pod) => { console.log(`Added: ${obj.metadata!.name}`); });
informer.on('update', (obj: k8s.V1Pod) => { console.log(`Updated: ${obj.metadata!.name}`); });
informer.on('delete', (obj: k8s.V1Pod) => { console.log(`Deleted: ${obj.metadata!.name}`); });

informer.start();
```

It seems like the informer is doing a lot more stuff.  There's a whole in-memory cache of all the Kubernetes objects being watched?

And why is there a `listFn` and a path in the informer case? In this example (which was taken from [the official example](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts), the list function is getting pods for all namespaces whereas the endpoint is only fetching pods in the default namespace, which seems wrong.

**Comment by brendandburns** [comment]
You are correct that example is wrong, It should be listing pods for the default namespace...

The main difference between a Watch and an Informer is that a Watch can disconnect (network problems, timeout, etc) whereas an Informer tries to re-list and re-watch to hide such failures from the caller.

The cache is also there so you can use list/get semantics instead of event-driven semantics if you prefer.

Also the informer API is a little more Javascript-y.

But the main difference is the re-list, re-watch in the presence of failures.

I'll fix the example (and possibly document it a little more)

**Comment by jwalton** [comment]
> The cache is also there so you can use list/get semantics instead of event-driven semantics if you prefer.

The informer doesn't seem to expose the cache, though: https://github.com/kubernetes-client/javascript/blob/master/src/informer.ts#L19-L23  Although I suppose I can just create the ListWatch directly.  :)

**Comment by brendandburns** [comment]
Yeah, 'informer' is the name of a similar concept in the Go library, so it's sort of a wrapper on top of the cache in this library.

I fixed the bug in the example btw :)

**Comment by travisghansen** [comment]
@brendanburns can you point me to where the re-watch logic is? Does it do some sort of dead peer detection at all or does it only detect clean disconnects? I wrote similar logic for a php client and ultimately had to just put a non-activity timeout on the socket and reconnect (keeping track of the last version received). Interested to see how it's implemented here and additionally if it's possible to add the logic to pure watches in addition to informers.
