### ISSUE TITLE
Update Npm package NPM

### ISSUE THREAD

**Issue by roonie007** [kubernetes-client/javascript#382]
Can you push the changes to NPM registry so we can benefit from the changes of this PR #372 ?

**Comment by aeb-sia** [comment]
I'd also appreciate a release. Mainly to get #366 in.  
I'd also like to note that 0.11.0 has been released, at least there is a tag, but there is no changelog entry...

**Comment by brendandburns** [comment]
I just pushed 0.11.1 from head.

https://www.npmjs.com/package/@kubernetes/client-node
