### ISSUE TITLE
Don't fail on missing kubeconfig version / kind

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-client/javascript#390]
These fields are "legacy", optional, and to be removed from downstream per the source types in client-go, as far as i know they can only ever be "Config" and "v1". Creating a client should not fail without these omitempty fields being present.

https://github.com/kubernetes/client-go/blob/940f07561929308fc33fc58bfa185f0544b84846/tools/clientcmd/api/types.go#L32-L41

originally reported in https://github.com/kubernetes-sigs/kind/issues/1242

**Comment by frankfarzan** [comment]
Check for apiVersion:

https://github.com/kubernetes-client/javascript/blob/58aa67475cc671268a08228c65da6d36a3b94b19/src/config.ts#L160
