### ISSUE TITLE
watch with resourceVersion too old triggers done() callback with null err

### ISSUE THREAD

**Issue by travisghansen** [kubernetes-client/javascript#392]
It appears that when the resourceVersion is no longer available in the cluster we probably are receiving a `410 GONE` response. However I'm observing that the `done()` callback has a `null` value for the error.

Any way we can more sanely handle this scenario?

Thanks!

**Comment by travisghansen** [comment]
https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions

**Comment by brendandburns** [comment]
@travisghansen based on this code here:

https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L75

You should be getting a non-null error on a `410` error. Are you sure you are getting a `410`? Have you validated in the API server logs?

**Comment by travisghansen** [comment]
@brendanburns after digging a bit more what I've discovered is that the callback actually receives the error data from the API but *also* done() is getting invoked. I'm not exactly sure how I would expect this all to work now that I know the normal callback is invoked with the data and done() is invoked as well.

**Comment by travisghansen** [comment]
I should say, done() is getting invoked with `null` to be clear.

**Comment by travisghansen** [comment]
@brendanburns what's the behavior now? Does the normal callback still get invoked as before?

**Comment by chriskinsman** [comment]
I am still seeing this behavior.  I was expecting done to get called with an error so I could retry without a resourceVersion.

How are you supposed to recover from starting watch with a resource version that is too old?

@brendanburns

**Comment by juona** [comment]
It seems that in this case the watch callback will be invoked with an event where phase is set to ERROR. You can find the 410 code in the provided API object.
