### ISSUE TITLE
RESTMapper interface

### ISSUE THREAD

**Issue by travisghansen** [kubernetes-client/javascript#395]
I'm not seeing anything of this nature in the code-base, if not can it be added?

I'm trying to map resource apiVersion/name/namespace/etc to REST endpoints.

https://github.com/kubernetes/kubernetes/issues/87434#issuecomment-577189967

**Comment by brendandburns** [comment]
What is your use-case? The client has all of the paths generated in it already.

I suppose we'd be open to a PR  to add this functionality if you wanted to develop it, but I'm uncertain about the need.

**Comment by travisghansen** [comment]
@brendanburns I'm not using any of the auto-generated stuff (nor can I to support CRDs).

I wrote this: https://github.com/travisghansen/node-red-contrib-kubernetes-client

`Node-RED` is a flow-based programming tool where generic messages flow. I've create a 2 kinds of nodes so far:

- `watch` - basic watches
- `http` - REST API

What I'm trying to facilitate in this *specific* use case is to generate the link to the `involvedObject` of a watch event payload so later nodes can automatically feed that data into the `http` node to do a GET/PATCH/DELETE/whatever with the object. The fundamental approach does not play nicely with the generated stuff at all.

**Comment by travisghansen** [comment]
Of note, apparently there's an initiative to also remove `selfLink` generally as well which will make this all the more important.

**Comment by brendandburns** [comment]
I'd be happy to have a PR that added this if you'd like to send one.

--brendan

**Comment by travisghansen** [comment]
Not very good at ts so I'm extending at the moment :(
