### ISSUE TITLE
k8s pod issue in getting IP after creation

### ISSUE THREAD

**Issue by divyamlamiyan** [kubernetes-client/javascript#398]
When we call the method createNamespacedPod after its creation when I called method readnamedspacedPodStatus in its response  apiResponse.body.status.podIP was coming empty since it takes time to generate it. So is there any good way to know whether IP will generate or not(Not in case of memory low failure) because I will be keep calling it.

**Comment by brendandburns** [comment]
You can use watch, to wait for changes to the Pods:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts

I'm going to close this as I believe the question is answered, feel free to use the `/reopen` command if you need to reopen this.
