### ISSUE TITLE
Kubernetes config not updated when token refreshed

### ISSUE THREAD

**Issue by inikolaev** [kubernetes-client/javascript#399]
I'm using OIDC authentication and running in the the following issue:

```
OpenIdConnectError: invalid_request (Refresh token is invalid or has already been claimed by another client.)
    at Client.requestErrorHandler (/Users/inikolaev/Projects/kube/node_modules/openid-client/lib/helpers/error_handler.js:16:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  error: 'invalid_request',
  error_description: 'Refresh token is invalid or has already been claimed by another client.'
}
``` 

After debugging it looks like token is being refreshed correctly the first time, but Kubernetes configuration is not being automatically updated and next time I start application I load old configuration and try to refresh my token using invalid refresh token.

I'm loading configuration from `~/.kube/config` and I was expecting it to be updated automatically. I'm not sure is this is how it's supposed to work and if so do you have any pointers on how to update that configuration properly?

**Comment by brendandburns** [comment]
Unfortunately, the Javascript client library doesn't currently support automatically rewriting the config when it refreshes a token.

There is a utility here: 
https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L352

to call `exportConfig()` to write the config into a string (which could then be written into a file) so it's possible.

To do it right requires a large-ish refactor of the authenticator interface to include refresh()

**Comment by brendandburns** [comment]
I'll look into crafting a PR (or probably multiple PRs) to handle this.
