### ISSUE TITLE
npm registry package needs updating 

### ISSUE THREAD

**Issue by sheldonkwok** [kubernetes-client/javascript#40]
There have been a handful of updates to the client since the last publish from 6c4fc27e4913b5db3d2063e4243f9faf191b775d. Is it possible to publish a new version? I would be happy to tag and publish as well.

Thanks!

**Comment by redborian** [comment]
Please publish a new version of the package. Thanks!

**Comment by sheldonkwok** [comment]
I can publish it if I'm added to the list of owners on npm. My npm user is `sheldonkwok`. Thanks! @brendandburns

**Comment by sheldonkwok** [comment]
Thanks!
