### ISSUE TITLE
TypeScript - watch-example - not working

### ISSUE THREAD

**Issue by unfor19** [kubernetes-client/javascript#401]
I copy-pasted the example, and exported a module, here goes:
```
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sCoreApi = kc.makeApiClient(k8s.CoreV1Api);

function p_witcher(){
    const watch = new k8s.Watch(kc);
    watch.watch('/api/v1/namespaces',
        // optional query parameters can go here.
        {},
        // callback is called for each received object.
        (type: any, obj: any) => {
            if (type === 'ADDED') {
                // tslint:disable-next-line:no-console
                console.log('new object:');
            } else if (type === 'MODIFIED') {
                // tslint:disable-next-line:no-console
                console.log('changed object:');
            } else if (type === 'DELETED') {
                // tslint:disable-next-line:no-console
                console.log('deleted object:');
            } else {
                // tslint:disable-next-line:no-console
                console.log('unknown type: ' + type);
            }
            // tslint:disable-next-line:no-console
            console.log(obj);
        },
        // done callback is called if the watch terminates normally
        (err: any) => {
            // tslint:disable-next-line:no-console
            console.log(err);
        })
    .then((req: any) => {
        // watch returns a request object which you can use to abort the watch.
        setTimeout(() => { req.abort(); }, 10 * 1000);
    });
}

module.exports = {
    witcher: (event: any) => {
        p_witcher();
    },
}
```

Executed it with:
```
ts-node -e 'require("./witcher").witcher()'
```

Error output:
```
/home/witcher.ts:35
    .then((req: any) => {
     ^
/home/witcher.ts:36
        .then(function (req) {
         ^

TypeError: watch.watch(...).then is not a function
    at p_witcher (/home/witcher.ts:35:6)
    at Object.witcher (/home/witcher.ts:43:9)
    at /home/[eval].ts:1:22
    at Script.runInThisContext (vm.js:120:20)
    at exec (/home/meir/.config/yarn/global/node_modules/ts-node/src/bin.ts:310:17)
    at /home/meir/.config/yarn/global/node_modules/ts-node/src/bin.ts:300:27
    at Array.reduce (<anonymous>)
    at _eval (/home/meir/.config/yarn/global/node_modules/ts-node/src/bin.ts:299:18)
    at evalAndExit (/home/meir/.config/yarn/global/node_modules/ts-node/src/bin.ts:259:14)
    at main (/home/meir/.config/yarn/global/node_modules/ts-node/src/bin.ts:209:5)
```

I Googled for - `TypeError: watch.watch(...).then is not a function` but seems like it's not famous enough ... Any help would be appreciated

Example Reference: [https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts)

p.s - I named it witcher instead of watcher, just for fun :)

**Comment by brendandburns** [comment]
I think this must have something to do with the `Promise` library that you are using, what version of nodejs are you running?

The function is here:

https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L34

And it is async.

It would be more Typescript-ish for this example to use `await`, you could also substituting in `await` and see if that fixes things..

I tested this with node `v12.14.0` (typescript 3.7.5) and it worked correctly.

**Comment by unfor19** [comment]
Hi @brendanburns , thanks for the quick response.
I'm using Node `v13.7.0`, and TypeScript `v3.7.2`. I switched to - Node `v12.12.25`, but still the same error.

My package.json:
```
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",
    "@types/node": "^12.12.25",
    "@typescript-eslint/eslint-plugin": "^2.16.0",
    "@typescript-eslint/parser": "^2.16.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.9.0",
    "eslint-plugin-prettier": "^3.1.2",
    "prettier": "^1.19.1",
    "typescript": "^3.7.4"
  },
  "dependencies": {
    "@kubernetes/client-node": "^0.11.0"
  }
```

I've already seen the syntax of [watch](https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L34), I saw it is supposed to return a promise (`Promise<any>`), so the `then` make sense.

Regarding your comment about `await`, I've added `await` before `watch.watch(..)`, but then it shouted:
```
await watch.watch(
         ^^^^^
SyntaxError: await is only valid in async function
```

I also tried to roll back the version of `@kubernetes/client-node` from `0.11.0` to `0.10.0`, in my `package.json` and then used `yarn install` - still now luck.

**Comment by unfor19** [comment]
Just to be on the safe side, I tried it with Docker

`Dockerfile`
```
FROM node:13.7.0
WORKDIR /code
COPY ./package.json ./yarn.lock ./
RUN yarn

# Application
COPY witcher.js ./

CMD ["node", "-e", "require('./witcher').witcher({'data': { 'hash': 'hash5' }})"]
```

Still getting the same error
```
TypeError: watch.watch(...).then is not a function
```

@brendandburns - may you please share your code and the results when it runs? I'm able to run watch if I ommit the `then` part, but then I can't stop it, unless I use `process.exit()`

**Comment by brendandburns** [comment]
I'm attaching the trans-piled javascript from a `watch.js` that works for me.
[watch-example.js.txt](https://github.com/kubernetes-client/javascript/files/4142137/watch-example.js.txt)

**Comment by patrickschur** [comment]
@unfor19 I had the same issue and figured out that different versions of `@kubernetes/client-node` return different results.

The version `0.11.0` **doesn't** return a promise, but `any`.
https://github.com/kubernetes-client/javascript/blob/0.11.0/src/watch.ts#L38

The version `0.11.1` **does** return a promise.
https://github.com/kubernetes-client/javascript/blob/0.11.1/src/watch.ts#L39

To fix this issue update the version of `@kubernetes/client-node` to `0.11.1`.
```js
"dependencies": {
    "@kubernetes/client-node": "^0.11.1",
}
```

**Comment by unfor19** [comment]
Thank @patrickschur ! I'll give it a go and update if it works

**Comment by brendandburns** [comment]
Ah, apologies for the confusion! Yes the examples at HEAD match the code at HEAD, the example for the `0.11.0` release is here:

https://github.com/kubernetes-client/javascript/blob/0.11.0/examples/typescript/watch/watch-example.ts

**Comment by brendandburns** [comment]
I'm going to close this as I think we've resolved the issue. Please use the `/reopen` command if you need to reopen for any reason.

**Comment by unfor19** [comment]
@brendandburns - One more thing regarding the example, it doesn't work (at least not for me).

Both [0.11.1 example](https://github.com/kubernetes-client/javascript/blob/0.11.1/examples/typescript/watch/watch-example.ts) example and [0.11.0 example](https://github.com/kubernetes-client/javascript/blob/0.11.0/examples/typescript/watch/watch-example.ts)  don't work. In 0.11.0, I still get the error `then is not a function`, and in 0.11.1 I get `abort is not a function` (req is a Promise).

I'm using version 0.11.1, and the below example works (watching a deployment). The main thing in my example is this
```typescript
req.then(res => res.abort()).catch(err => reject(err));
```

I use this in the object-callback function, I check for a condition that I'm satisfied with, and then I abort the request. Works like a charm

`watcher.ts`
```typescript
import * as k8s from '@kubernetes/client-node';

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

function watcher(id: string, action: string) {
    return new Promise((resolve, reject) => {
        const watch = new k8s.Watch(kc);
        const req = watch.watch(
            id, // the path to watch, use Kubernetes API - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#watch-namespace-v1-core
            {}, // optional query parameters can go here.
            (type, obj) => {
                // callback is called for each received object.
                if (type === 'ADDED') {
                    switch (obj.kind) {
                        case 'Namespace':
                            if (action === 'create' && obj.status.phase === 'Active') {
                                req.then(res => res.abort()).catch(err => reject(err));
                                resolve(obj);
                            }
                            break;
                        default:
                            break;
                    }
                } else if (type === 'MODIFIED') {
                    switch (obj.kind) {
                        case 'Namespace':
                            if (action === 'delete' && obj.status.phase === 'Terminating') {
                                console.log('Deleting');
                            }
                            break;
                        default:
                            break;
                    }
                } else if (type === 'DELETED') {
                    switch (obj.kind) {
                        case 'Namespace':
                            if (action === 'delete' && obj.status.phase === 'Terminating') {
                                req.then(res => res.abort()).catch(err => reject(err));
                                resolve(obj);
                            }
                            break;
                        default:
                            break;
                    }
                } else {
                    console.log(`unknown type: ${type}`);
                }
            },
            // done callback is called if the watch terminates normally
            err => {
                console.log(err);
            },
        );
    });
}

module.exports = {
    watcher: (event: any) => {
        watcher(event.data.id, event.data.action)
            .then(res => {
                console.log(res);
            })
            .catch(err => {
                console.log(err);
            });
    },
};
```

## Full example
Testing the code, assuming `watcher.ts` in src folder, and you have [ts-node](https://www.npmjs.com/package/ts-node) installed.

1. Create
    -  Watching the **creation** of namespace ns-test, stop when **created**
       ```bash
       $ ts-node -e 'require("./src/watcher").watcher({"data": { "id": "/api/v1/watch/namespaces/ns-test", "action": "create" } })'
       ```
    - In another terminal, **create** the namespace ts-test, once this is done, the above process will stop
      ```bash
      $ kubectl create namespace ns-test
      ```

2. Delete
    - Watching the **deletion** of namespace ns-test, stop when **deleted**
      ```bash
      $ ts-node -e 'require("./src/watcher").watcher({"data": { "id": "/api/v1/watch/namespaces/ns-test",             "action": "create" } })'
      ```
    - In another terminal, **delete** the namespace ts-test, once done, the above process will stop
      ```bash
      $ kubectl delete namespace ns-test
      ```

## How it works (GIF)
_Note_: Ignore `trdev`, this is an alias for [aws-vault](https://github.com/99designs/aws-vault)
![watch-example](https://user-images.githubusercontent.com/15122452/74083131-57022000-4a69-11ea-955a-ec355616e51f.gif)

**Comment by brendandburns** [comment]
Thank you for the detailed sample code, I will use it to update the example.

**Comment by sorushsaghari** [comment]
> Thank you for the detailed sample code, I will use it to update the example.

could you please add this example to the watch example in the repository? it took me a day to find it here in the issues.
