### ISSUE TITLE
API does not have way to get stateful set.

### ISSUE THREAD

**Issue by cksassy** [kubernetes-client/javascript#406]
The API has a function called listNamespacedPod() to query the list of pods. I don't see anything similar for stateful sets.

**Comment by brendandburns** [comment]
It's right here:

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/appsV1Api.ts#L2314

Closing because the question is answered. If more info is needed please use the `/reopen` command in a comment to reopen the issue.

**Comment by cksassy** [comment]
Thank you for the quick response and pointing out I needed to create the "apps" API client: `makeApiClient(k8s.AppsV1Api)`
