### ISSUE TITLE
getNamespacedPod() returns undefined values

### ISSUE THREAD

**Issue by cahite** [kubernetes-client/javascript#409]
When using the getNamespacedPod() and getNamespacedService() functions using a proper namespace, I get a response where all of the fields' values are undefined.
I use the same code as the example here https://github.com/kubernetes-client/javascript#list-all-pods

This is an example of the output I see : 

``` 
V1Service {
       apiVersion: undefined,
       kind: undefined,
       metadata: [Object],
       spec: [Object],
       status: [Object] },
V1Service {
       apiVersion: undefined,
       kind: undefined,
       metadata: [Object],
       spec: [Object],
       status: [Object] },
V1Service {
       apiVersion: undefined,
       kind: undefined,
       metadata: [Object],
       spec: [Object],
       status: [Object] },

```
When using the kubectl command to list the pods/services I see the correct info.
It looks similar to this issue https://github.com/kubernetes-client/javascript/issues/383, however I didn't change any of the functions. I was unsure if the changes made were the reason for the issue.

**Comment by brendandburns** [comment]
This is the way Kubernetes API Server works.

If you ask for a 'list' it doesn't put the API group/kind metadata in the object.

If you look at the verbose JSON from `kubectl` you can see this:

```
kubectl get pods --v=10
```

I think that in the kubectl printer some where they are substituting this data.

You could probably add a heuristic library function that could do this, but I don't think it's something that the base client library wants to support. We provide the data as the API server does it.

**Comment by cahite** [comment]
Ahh ok. So are the any functions that would be able to give me the information I'm looking for(I'm looking for the labels on all of our services), or is your heuristic libraries suggestion my only workaround?

**Comment by brendandburns** [comment]
The labels should be there. They are in the `metadata` field within the object that is returned.

e.g. `listObj.items[0].metadata.labels` should have all of your labels.

**Comment by cahite** [comment]
I'm seeing `undefined` when I try to get the labels that way using the getNamespacedService() function. 
```
k8sApi.listNamespacedService("content").then((res) => {
    console.log(res.body.items[0].metadata.labels);

}, function(err){
  log.error("ERRROR");
  callback(error);
});
```

I'm assuming that's because the listObj shows metadata as [Object]
```
V1Service {
       apiVersion: undefined,
       kind: undefined,
       metadata: [Object],
       spec: [Object],
       status: [Object] },
```
Am I missing something here? Or did i misunderstand your second comment and I won't be able to get that info from the getNamespacedService() function?

**Comment by cahite** [comment]
I see where I went wrong... The first item in my list of services doesn't have any labels, therefore giving me undefined. When doing that operation on a service with labels, I can read them. Thanks for your help!
