### ISSUE TITLE
Error-This error originated either by throwing inside of an async function without a catch block,  or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

### ISSUE THREAD

**Issue by PriyankaTwinkel003** [kubernetes-client/javascript#416]

**Comment by PriyankaTwinkel003** [comment]
hi Team,
I have created a nodejs application and exposed it as a https api.I have used @kubernetes/client-node module of javascript.
My node.js application works fine in local.From my local it gets the GCP context and displays the pod lists. However when i run the same application in K8s cluster on GCP it gives below error. Kindly help me.
UnhandledPromiseRejectionWarning:listening at port 4000..
(node:1) UnhandledPromiseRejectionWarning: #
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by brendandburns** [comment]
How are you creating the client? You should be using the default constructor so that it finds the service account. Also, it's hard to know what went wrong with your code. There's a promise somewhere that is failing and either the client code or your code isn't handling it.

Can you attach your sample code so that we can determine what is going on?

**Comment by brendandburns** [comment]
Closing this due to lack of response. If you want to reopen please use the `/reopen` command in a new comment.
