### ISSUE TITLE
how to return all records

### ISSUE THREAD

**Issue by reachlin** [kubernetes-client/javascript#419]
when i call `listNamespacedPod`, it doesn't return all records. 
is there any example for returning a large number of records?

**Comment by brendandburns** [comment]
are you looking for pagination? 

There are two ways to do this. The `listNamespacedPod` function has a `limit` parameter. You can make this very large. Alternately, if there are more records than the `limit` value the API server will return a `continue` value, if you pass that value in a subsequent call to `listNamespacedPod` then you will get the next page of results.

There's no example of how to do this (yet) but if you come up with an example, we'd gladly accept the PR.

**Comment by reachlin** [comment]
thanks
