### ISSUE TITLE
[Feature Request] Functionality similar to `kubectl describe`

### ISSUE THREAD

**Issue by Bobgy** [kubernetes-client/javascript#420]
I understand kubectl has quite some adhoc logic to support this.
It is very useful for debugging pods.

I'm thinking about exposing similar information for a management UI using kubernetes javascript client.
This can definitely get implemented by client code, but it would be cool as a builtin feature.

Similar ask before in https://github.com/kubernetes-client/javascript/issues/236

**Comment by Bobgy** [comment]
I took a look, it's not hard to list all events related to a pod:
```javascript
k8sV1Client.listNamespacedEvent(
    podNamespace,
    undefined,
    undefined,
    undefined,
   `involvedObject.namespace=${podNamespace},involvedObject.name=${podName}`,
)
```
Events are the only extra information in `kubectl describe`, but not in `kubectl get pod`

**Comment by brendandburns** [comment]
If you want to implement it as an addition to this library, we'd be happy for the PR.

**Comment by Bobgy** [comment]
Thanks for the suggestion!
`listNamespacedEvent` is enough for my use case.

I think the next person which needs exactly `kubectl describe` can think about it.
