### ISSUE TITLE
Trying to run generate behind corporate proxy

### ISSUE THREAD

**Issue by davesargrad** [kubernetes-client/javascript#421]
I'm pretty sure the following failure is due to the fact that I am behind a corporate proxy.

![image](https://user-images.githubusercontent.com/48793689/77082758-ebe62a80-69d2-11ea-9927-49462293ade5.png)

The attempt to apt-get update and apt-get install is failing

I am not sure where I need to make a configuration update to get past my proxy. I have lots of experience dealing with proxies. It looks like the generator is building a docker file. What I've done in the past is to put an ENV http_proxy line into my docker file 

```
FROM ubuntu:latest
ENV http_proxy 'http://proxy_url:proxy_port'
ENV https_proxy 'http://proxy_url:proxy_port'
```

Please guide me relative to how I might 
`npm run generate`
and get past my proxy

**Comment by brendandburns** [comment]
The generate script is downloading this repo:

https://github.com/kubernetes-client/gen

And running this script:
https://github.com/kubernetes-client/gen/blob/master/openapi/typescript.sh

Which uses this Dockerfile:
https://github.com/kubernetes-client/gen/blob/master/openapi/openapi-generator/Dockerfile

So I think what you need to do is clone this repo
https://github.com/kubernetes-client/gen

Then set the `${GEN_ROOT}` environment variable to point to the `gen` repo that you cloned.
Modify the `Dockerfile` in that repo
and the re-run `npm run generate` (or just run the `./generate.sh` script in this repo directly.

Hope that helps, let me know if you run into any problems.

**Comment by davesargrad** [comment]
@brendanburns That does help. Thank you sir! I'll give it a try

**Comment by davesargrad** [comment]
@brendandburns I've looked at the referenced scripts. Neither 
`typescript.sh`
or
`Dockerfile`
referenced GEN_ROOT

Which script or application uses this environment? Also when you say 

> Then set the ${GEN_ROOT} environment variable to point to the gen repo that you cloned.

How exactly do you mean?

**Comment by brendandburns** [comment]
`GEN_ROOT` is used in the `generate-client.sh` script in this repo:

https://github.com/kubernetes-client/javascript/blob/master/generate-client.sh#L9

Sorry I wasn't clear.

**Comment by brendandburns** [comment]
For clarity:

`npm run generate` calls `generate-client.sh` in this repo.
that script clones https://github.com/kubernetes-client/gen or uses a local version of that repo if `${GEN_ROOT}` is set.
then `${GEN_ROOT}/openapi/typescript.sh` is invoked
this in turn builds the docker image described by `${GEN_ROOT}/openapi/openapi-generator/Dockerfile`

**Comment by davesargrad** [comment]
@brendanburns Ty Sir.. Makes Sense

**Comment by brendandburns** [comment]
@davesargrad did you get this to work?

**Comment by brendandburns** [comment]
Closing this because I think it's sorted and non-response.

If you need more assistance, please use the `/reopen` command to reopen the issue.
