### ISSUE TITLE
Watch parameter of listNamespacedCustomObject method

### ISSUE THREAD

**Issue by faxioman** [kubernetes-client/javascript#422]
Hi.
Is the watch parameter available in listNamespacedCustomObject method usable in someway?
I can't find any example and the promise returned by listNamespacedCustomObject method is never resolved when setting watch to true, even if I create/delete the custom resource item.

Thanks

**Comment by brendandburns** [comment]
Sorry for the delay in responding here. Are you looking to do a watch? That code is different than the main client, see the code here:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts
