### ISSUE TITLE
API client type (ApiType) could use more definition

### ISSUE THREAD

**Issue by brandonc** [kubernetes-client/javascript#423]
I'd like to set defaultHeaders on a generic client factory like this:

```typescript
import * as k8s from "@kubernetes-client/javascript";

type ApiConstructor<T extends k8s.ApiType> = new (server: string) => T;

function createClient<T extends k8s.ApiType>(api: k8s.ApiConstructor<T>): T {
  const config = getClusterCofiguration();
  const client = config.makeApiClient<T>(apiConstructor);

  client.defaultHeaders["Impersonate-User"] = getCurrentUser();
  // Property 'defaultHeaders' does not exist on type 'T'.
  return client;
}
```

...but unfortunately k8s.ApiType is defined without defaultHeaders so this code contains a type error.

```typescript
export interface ApiType {
    setDefaultAuthentication(config: api.Authentication);
}
```

I believe it's true that all generated Api classes contain a getter for defaultHeaders and this field in particular is useful when configuring clients centrally. 

(I'll be submitting a PR to accompany this issue)

**Comment by brendandburns** [comment]
Closing since #424 merged
