### ISSUE TITLE
How to replicate "kubectl cp" in kubernetes client

### ISSUE THREAD

**Issue by ShreyGargLTI** [kubernetes-client/javascript#427]
I am trying to copy some files from a pod to local machine.
I am able to do so by " kubectl cp" command but unable to identify how to achieve the same via kubernetes client.

**Comment by brendandburns** [comment]
`kubectl cp` isn't an API call. It is a `exec` of `tar -xvzf <foo>`

So if you use the exec per the example here:
https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/exec/exec-example.ts

You can implement the copy behavior.

If you get a good solution, we'd happily take a PR so others can re-use that code.

**Comment by drubin** [comment]
Also, this is a duplicate of https://github.com/kubernetes-client/javascript/issues/124 

Maybe we can reopen that and add a frozen lifecycle to it?

**Comment by brendandburns** [comment]
Closing this in favor of #124
