### ISSUE TITLE
Add Github Actions

### ISSUE THREAD

**Issue by brendandburns** [kubernetes-client/javascript#428]
Travis is disabled, we need CI/CD...

**Comment by drubin** [comment]
I can look into this but I think i will need some sort of editor access to enable/test it?

But will start with a fork and see what I can do

**Comment by brendandburns** [comment]
I think you can add it to your fork and test it there.

--brendan

________________________________

**Comment by brendandburns** [comment]
@drubin did you make progress on this? If not I think I'm going to take this on, since I want to re-activate the CI/CD.

**Comment by drubin** [comment]
@brendandburns Sorry no I haven't yet.  I was looking for some spare time but its been hard.

Please go ahead and I can review/help it if needed.

**Comment by brendandburns** [comment]
Closing since #433 and #434 have merged.
