### ISSUE TITLE
How to use watch with token and crt

### ISSUE THREAD

**Issue by flyboarder** [kubernetes-client/javascript#43]
It seems the watch class only accepts a KubeConfig object, the example shows loading from a file.

However within a pod we should be using token and crt. How do we apply these to the Watch object?

**Comment by flyboarder** [comment]
@brendandburns you seem to be the maintainer of this package, do you have a suggestion?

**Comment by brendandburns** [comment]
@flyboarder Sorry for the delay in responding here (cleaning up old issues)

There is now a `loadFromCluster` command in the `KubeConfig` class:

https://github.com/kubernetes-client/javascript/blob/master/node-client/src/config.ts#L134

You can use this as follows:

```js
var kc = new KubeConfg();
kc.loadFromCluster();
....
```

There's a complete example here: 

https://github.com/kubernetes-client/javascript/blob/master/examples/in-cluster.js

Closing this (and apologies for leaving this hanging....)
