### ISSUE TITLE
Support for apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by MartinRoss-IBM** [kubernetes-client/javascript#438]
In Kubernetes v1.16 the apiextensions.k8s.io/v1beta1 is being marked as deprecated and due to be removed in Kubernetes v1.19:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals
> The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition is deprecated and will no longer be served in v1.19. Use apiextensions.k8s.io/v1 instead. (#79604, @liggitt)

Also, in Kubernetes v1.16 the The CustomResourceDefinition API type was promoted to apiextensions.k8s.io/v1:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#kubernetes-v1160-release-notes

Currently this Node.js client appears to be built from Kubernetes v1.15.10:
https://github.com/kubernetes-client/javascript/blob/master/settings

Please could this client be updated to be built from at least Kubernetes v1.16 OpenAPI spec so that apiextensions.k8s.io/v1 is available?

**Comment by brendandburns** [comment]
Yeah, we need to regenerate. Last time I regenerated there were some issues, but I'll try again.

**Comment by brendandburns** [comment]
#445 just merged, I will cut a new release to npm soon.

**Comment by brendandburns** [comment]
I just pushed release `0.12.0` which includes code for `1.18.x` so I'm closing this issue.

**Comment by MartinRoss-IBM** [comment]
Thank you @brendandburns
