### ISSUE TITLE
Recieving Status Code 415: Unsupported Media Type when calling patchNamespacedIngress

### ISSUE THREAD

**Issue by SeanM96** [kubernetes-client/javascript#440]
I am trying to update an existing ingress with new parameters using the above mentioned method. Everytime I call it though, I hit line 758 in networkingV1beta1Api.js. I am calling the method with the ingress name, namespace,  config and pretty print.

`k8sIngressApi.patchNamespacedIngress('myingressname', 'myingressnamespace, config, true).then(result => {
        return console.log(JSON.stringify(result, null, 2));
      });`

I am able to create ingresses fine, it's just updating them that is causing issues.

**Comment by brendandburns** [comment]
The content type is likely not correct. you need it to be something like `application/merge-patch+json`

**Comment by SeanM96** [comment]
Applied custom headers to the options parameter of { 'content-type': 'application/strategic-merge-patch+json' };

**Comment by Morriz** [comment]
Why is this not inferred?
