### ISSUE TITLE
createNamespacedDeployment

### ISSUE THREAD

**Issue by SaschaHeyer** [kubernetes-client/javascript#442]
Hi Folks,

is there support to do such simple things like create deployments?
Similar like in the Python library https://github.com/kubernetes-client/python/blob/master/examples/deployment_create.py

Best regards
Sascha

**Comment by SaschaHeyer** [comment]
solved

**Comment by aaomidi** [comment]
@SaschaHeyer What was the code path for this with this library? I'm stuck on the same issue.

**Comment by polaroi8d** [comment]
@SaschaHeyer do you have the example code on how u solved the Create Deployment issue?

**Comment by SaschaHeyer** [comment]
Hi @aaomidi 
Hi @polaroi8d 

hope this helps. 
To create a namespaced deployment you have to use the `k8s.ExtensionsV1beta1Api`

```
const k8sExtensionApi = new k8s.ExtensionsV1beta1Api(
        "https://" + cluster.endpoint
);
deployment = await k8sExtensionApi.createNamespacedDeployment("default", {<your standard deployment json>}
```

**Comment by polaroi8d** [comment]
Thanks @SaschaHeyer, yess I found that the API  that I am using is not implemented the `createNamesapcedDeployment`. 

Thanks for the reply.

**Comment by SaschaHeyer** [comment]
You're welcome

**Comment by weijie0** [comment]
k8s.AppsV1Api createNamespacedDeployment
