### ISSUE TITLE
UnsupportedMediaType when patching ingress

### ISSUE THREAD

**Issue by SaschaHeyer** [kubernetes-client/javascript#443]
Hi

when patching a ingress we get the following error message

```
{
      kind: 'Status',
      apiVersion: 'v1',
      metadata: {},
      status: 'Failure',
      message: '415: Unsupported Media Type',
      reason: 'UnsupportedMediaType',
      details: {},
      code: 415
    }
```

Kubernetes Version: 1.14.10-gke.27

**Comment by brendandburns** [comment]
This is almost certainly because the `Content-type` header is set to `application/json` instead of `application/strategic-merge-patch+json` or something similar.

See #440 which discussed the same issue.

**Comment by brendandburns** [comment]
Closing this issue since I believe the question is answered. If you still have problems, please place them in #440

**Comment by saxicek** [comment]
It would be good to include full patch example in `examples` directory. I also got the same issue. My fixed code looks like:
```javascript
  const k8sNetworkingApi = kc.makeApiClient(k8s.NetworkingV1beta1Api);
  const patchedIngress = {
    metadata: {
      annotations: {
        'nginx.ingress.kubernetes.io/cors-allow-origin': '*'
      }
    }
  }
  k8sNetworkingApi.patchNamespacedIngress(ingressName, namespace, patchedIngress, undefined, undefined, undefined, undefined,
    { headers: { 'content-type': 'application/merge-patch+json' } })
```

**Comment by brendandburns** [comment]
We would happily take a PR adding a complete patch example to the examples directory.

I filed: https://github.com/kubernetes-client/javascript/issues/450

To track this, @saxicek if you have the time to create a PR that would be awesome!
