### ISSUE TITLE
Unhandled promise exception with list error after a watch restart can break the informer watch

### ISSUE THREAD

**Issue by entropitor** [kubernetes-client/javascript#447]
If kubernetes API is down, e.g. for an upgrade to a newer version, the watch will break and the list command will fail.

1. List command runs and returns success
2. Watch command runs and is listening
3. After a while, the watch fails and restarts calling [doneHandler](https://github.com/kubernetes-client/javascript/blob/master/src/cache.ts#L71)
4. In the doneHandler the list fails, this error is not catched anymore. 

I think if the listFn throws an error, this should be reported using `informer.on('error', ...)` as well. This way, the user of the library can restart the informer if needed.

(It's possible to catch this error yourself as an user of the library and that is what I'll be doing for now but I think other people might encounter the same issue)

**Comment by brendandburns** [comment]
Acknowledging the issue. Will work on a repro/test and a fix. Thanks for the report.
