### ISSUE TITLE
typescript examples are actually javascript examples

### ISSUE THREAD

**Issue by Morriz** [kubernetes-client/javascript#449]
Hi, thanks for this library first of all. I have one suggestion though:

Please add typescrip features to your examples, as they are now plain ecmascript mostly.

Most important feature that I am after: return type for `makeApiClient`, so that we get autocompletion in our editors.

**Comment by brendandburns** [comment]
Happy to have PRs to improve the examples if you'd like to contribute.

**Comment by Morriz** [comment]
Hi @brendanburns, I am not sure how to add typing to makeApiClient. I would expect it to be generated somewhere by your tooling.  I would be very useful to have for autocompletion.

**Comment by rafagsiqueira** [comment]
@Morriz, would something like this work?
```
import { CoreV1Api, KubeConfig } from '@kubernetes/client-node';
export class ClusterAPI {
    kc: KubeConfig;
    api: CoreV1Api;
    constructor() {
        super();
        this.kc = new KubeConfig();
        this.kc.loadFromCluster();
        this.api = this.kc.makeApiClient(CoreV1Api) as CoreV1Api;
    }
}
```

**Comment by Morriz** [comment]
Yeah, tnx for the example.

Back then I already managed to find how to work with it by inspecting the code :)

**Comment by brendandburns** [comment]
I figured out the issue, we were missing a bunch of return types. I created a PR to fix this.
