### ISSUE TITLE
Unexpected escaped HTML entities in documentation generated via typedoc

### ISSUE THREAD

**Issue by cdever** [kubernetes-client/javascript#457]
In the documentation generated via typedoc, the HTML entities (e.g. single quote `&#39;` and double quotes `&quot;`) are not decoded.

For instance,
<img width="795" alt="typedoc-cliend-node_escaped" src="https://user-images.githubusercontent.com/21110012/83035482-1a841f80-a06c-11ea-8294-362748275436.png">

was generated from this typedoc block:
(https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/coreV1Api.ts)
```typescript
    * @param pretty If \&#39;true\&#39;, then the output is pretty printed.
    * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type \&quot;BOOKMARK\&quot;. Servers ...
```

**Steps to reproduce:**
1. git clone https://github.com/kubernetes-client/javascript.git
2. npm install
3. npm run docs

**Comment by brendandburns** [comment]
This is probably a bug in the openapi code generator: https://github.com/OpenAPITools/openapi-generator

If there is to be a fix, it should be fixed there, but I'm not sure it's worth fixing.

**Comment by cdever** [comment]
I had an experiment. I tried to remove the backslashes at those HTML entities, like below
```typescript
    * @param pretty If &#39;true&#39;, then the output is pretty printed.
    * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type &quot;BOOKMARK&quot;. Servers ...
```
The generated doc is then able to show the actual quotes characters.

Wonder what was the intension to have those backslashes added in the typedoc. Should we consider removing them?

**Comment by brendandburns** [comment]
I filed a bug on the generator:

https://github.com/OpenAPITools/openapi-generator/issues/6552

And I'm going to close this issue.
