### ISSUE TITLE
Issue similar to Kubernetes Exec WebSocket not sending data 

### ISSUE THREAD

**Issue by boocup** [kubernetes-client/javascript#463]
Hi,

I have an issue very similar to this issue.

#229   **Kubernetes Exec WebSocket not sending data**

I am trying to send a follow-up command to exec after the initial command (which works fine and is sent to stdout).

I tried to follow the suggestions in issue #229, but I am not seeing any output after the write. 

```
       const exec = new k8s.Exec(kc);

        var myws = new stream.Writable({
            write: function(chunk, encoding, next) {
              console.log("enter")
              console.log(chunk.toString());
              console.log("exit")
              next();
            }
          });

        const ws = await exec.exec(
            'test0',
            'test0-65877c78d5-724qw',
            'test0',
            'ls',
            process.stdout,
            process.stderr,
            myws,
            true /* tty */,
        );


        myws.write('ls -ltr \n');
```

In the console, I see....

```
enter
ls -ltr 

exit
UninstallerData  instversion      services
bin              lib              sql
config           log              webapps
```

Should I expect the results of the 'ls -ltr' to be send to stdout?

Thanks and best regards,
Pete

PS- Apologies if it something obvious. I am the only one working on this and don't have anyone to bounce it off of.

**Comment by boocup** [comment]
found a work-around

**Comment by luchillo17** [comment]
@boocup  Would be nice if you included the workaround 🙏

**Comment by boocup** [comment]
@luchillo17 you're right. sorry about that. this was a while ago and the project was canceled, but give me some to look around and remember what I did.

**Comment by boocup** [comment]
@luchillo17  I think this is what I ended up (3+ years ago)....sorry a little fuzzy after all this time...good luck....

    async function zipLogFiles(ns, socketid,pod, container) {
        const exec = new k8s.Exec(global.kc);

        let stream = require('stream');
        let echoStream = new stream.Writable();
        var tailinfo='';

        echoStream._write = function (chunk, encoding, done) {
            //console.log("** "+chunk.toString())
            tailinfo=tailinfo+chunk.toString();
            done();
        };
        echoStream._final = function (callback) {
            //console.log("final")
        }

        var cmd = ['tar','-cvf', 'logs.tar', '/home/nonroot/log', '/home/nonroot/log2'];
        try {
            const cd_cmd = await exec.exec(
                ns,
                pod,
                container,
                cmd,
                echoStream,
                process.stderr,
                process.stdin,
                true /* tty */,
            );
        } catch(e) {
            throw e.message;
        }

    }
