### ISSUE TITLE
Status callback for exec is never called when stdin closes

### ISSUE THREAD

**Issue by mochja** [kubernetes-client/javascript#465]
Is it possible to close stdin for Exec without [closing ws](https://github.com/kubernetes-client/javascript/blob/932c2fbc34db954c6ed397b3cd9ead08b2ff1d10/src/web-socket-handler.ts#L69) connection?

[StatusStream](https://github.com/kubernetes-client/javascript/blob/932c2fbc34db954c6ed397b3cd9ead08b2ff1d10/src/web-socket-handler.ts#L37) is not received if WS connection is closed as well as additional data on stdout, stderr streams is lost.

**Comment by brendandburns** [comment]
You could try sending an explicit `control-D` character across the stream. That should close the stream in the application.

**Comment by mochja** [comment]
@brendandburns neat, that does work indeed, but only when tty is also attached.

With tty I am not able to put binary data into stdin.

```
tar xf - -C /tmp
tar: Refusing to read archive contents from terminal (missing -f option?)
tar: Error is not recoverable: exiting now
{
  metadata: {},
  status: 'Failure',
  message: 'command terminated with non-zero exit code: Error executing in Docker Container: 2',
  reason: 'NonZeroExitCode',
  details: { causes: [ [Object] ] }
}
```

**Comment by brendandburns** [comment]
Makes sense ctrl-d is a terminal character after all.

This error is coming from the tar command itself. I'm not sure why that's happening, but I don't think it's related to this library.

**Comment by mochja** [comment]
@brendandburns you are correct it will be related to tty itself, but the fact with result is as `kubectl exec` is not behaving like that when stdin is closed. I was digging into `kubectl exec` and I figured out it's using SPDY and multiple streams for different io instead of single websocket connection.

I think issue could be solved with #411 or maybe there is way for ws protocol to close streams some other way.

**Comment by brendandburns** [comment]
I'm obviously not certain, but I think `tar` is giving up before stdin is even considered. I'm uncertain about the difference between `tar xf - ...` vs `tar -x -f -` but you may be since that is referenced in the error message.

**Comment by mochja** [comment]
It does not matter what executable I try to run, even cat breaks up in similiar manner as if you try to paste binary data trough regular terminal. I believe I would have to somehow escape the data so the terminal could recognize 0x04 as a byte and as a ctrl-d. I am not sure if thats possible (I was not able to find anything about that), but could also solve the issue.

**Comment by bankyadam** [comment]
Did you find out something @mochja? I'm trying to upload some file with exec to a pod and I experience the same you do.

**Comment by mochja** [comment]
@bankyadam I did not, I think there are only two proper ways to handle this:
- Use SPDY protocol instead of WS
- Implement closing streams into WS protocol itself

I was experimenting by removing following lines
https://github.com/kubernetes-client/javascript/blob/932c2fbc34db954c6ed397b3cd9ead08b2ff1d10/src/web-socket-handler.ts#L68-L70

and if I am remembering correctly it was _somewhat_ working.
