### ISSUE TITLE
Promote Javascript Client to Beta

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-client/javascript#47]
This is an umbrella issue for remaining tasks to promote javascript client to beta.

@brendandburns would you add remaining tasks here and let me know how can I help?

**Comment by flyboarder** [comment]
@mbohlool this library needs to be updated and is 2 versions out of date, only supporting 1.8 and 1.9.

Please see refactor for v1.11 here #57 
The client library also needs to be updated to support #55 and #22

**Comment by brendandburns** [comment]
Quick update here:

1.11 support is merged.

#55 is closed and #22 is in PR.

Once the fix for #22 is merged, I will send a README change moving this to beta/gold.

**Comment by brendandburns** [comment]
#22 is now fixed, I sent a PR to update the status to beta. #93
