### ISSUE TITLE
Specify pods on different worker node

### ISSUE THREAD

**Issue by yiyigit** [kubernetes-client/javascript#471]
Is there a way to list pods that are on a specific worker node by providing a nodename?

**Comment by brendandburns** [comment]
Yes, you should be able to use the `fieldSelector` parameter for `listNamespacedPods(...)` with the value `spec.nodename=some-node-name`

**Comment by yiyigit** [comment]
Hi I am not really understanding how to use the parameter so I tried with 
listNamespacedPod(
        "default",
        undefined,
        undefined,
        undefined,
        `spec.nodename = ${nodeName}`
      )
and get a httpError. Am i implementing this function right?
