### ISSUE TITLE
Exec.exec() timeout after 5mins waiting

### ISSUE THREAD

**Issue by startoday** [kubernetes-client/javascript#478]
Problem description:
I spin up a pod and run this containerExec.exec() function to exec the shell from my standard input and output in the container.
It runs and response normally, but if I stop typing any cmds, after five minutes, the console terminal only have the # but not able to response to any cmd(after typing the cmds, the terminal has no response). No error code /response is returned to indicate this "timeout". 
When I try kubectl exec --stdin --tty thesamecontainerName -- /bin/bash, it is able to keep alive after 5mins waiting (the default for kubectl timeout is 0, no timeout)
The pod is always running while we run this function.

```
    kc.makeApiClient(k8s.AppsV1Api);
    const containerExec = new k8s.Exec(kc);
    containerExec
        .exec(
            namespace,
            podName,
            containerName,
            ["/bin/sh"],
            process.stdout,
            process.stderr,
            process.stdin,
            true /* tty */,
            (status) => {
                console.log("<Exited with status:>");
                console.log(JSON.stringify(status, null, 2));
            }
        )
        .then(() => {
        })
        .catch((err) => {
            console.log(err);
        });
```
Is this a problem relates to exec function itself or websocket? How to address that? thanks!

**Comment by brendandburns** [comment]
Do you have any proxies in between? Many network proxies time out connections after a period of time.

**Comment by startoday** [comment]
> Do you have any proxies in between? Many network proxies time out connections after a period of time.

yes, I am, digging into it now... thanks!

**Comment by oradwell** [comment]
@brendandburns what are your thoughts on implementing an aliveness check here rather than in consumer projects? I've created #2870
