### ISSUE TITLE
Exec.exec("/bin/sh") not able to tab autofill typing in containers

### ISSUE THREAD

**Issue by startoday** [kubernetes-client/javascript#479]
After my pod is running, I run Exec.exec() function to open a shell of the container. It is able to see the files and folders and response to the cmd like "ls, cd, mkdir"
However, when I try to tab to autofill the long name file/folder just as normal terminal, it won't able to do that, instead, it is a normal tab for 2/4 spaces.
run kubectl exec --stdin --tty containerName -- /bin/sh. is able to do the tab autofilling
Is there a way to able the tab autofill functionality in the client library?
Thanks!
My example of exec function.
```
    kc.makeApiClient(k8s.AppsV1Api);
    const containerExec = new k8s.Exec(kc);
    containerExec
        .exec(
            namespace,
            podName,
            containerName,
            ["/bin/sh"],
            process.stdout,
            process.stderr,
            process.stdin,
            true /* tty */,
            (status) => {
                console.log("<Exited with status:>");
                console.log(JSON.stringify(status, null, 2));
            }
        )
        .then(() => {
        })
        .catch((err) => {
            console.log(err);
        });
```

**Comment by brendandburns** [comment]
Tab complete is usually a feature of `bash` not `sh`

Regardless, I don't think there's anything in the client code that could be causing this.

**Comment by startoday** [comment]
nice! it is the problem, since alpine didn't have the sh, I didn't notice it! Thanks a lot! it works!
