### ISSUE TITLE
Any plans for a SharedInformer?

### ISSUE THREAD

**Issue by chriskinsman** [kubernetes-client/javascript#484]
Have a controller I have created that listens to multiple Informers and was wondering if a SharedInformer was possibility for this client.

Thanks!

**Comment by brendandburns** [comment]
What specific functionality are you looking for? You can create an informer for each thing you want to listen to. Are you looking for something where you can register a single event handler for multiple different resource types?

**Comment by chriskinsman** [comment]
I am thinking more about a shared informer factory.  i.e. for a single resource type I might have multiple places listening to it.  Each shouldn't be doing a watch on the API it feels like. 

Instead I would ideally like a way to get an informer that shares an upstream api connection that I can subscribe to it's emitters, let it go out of scope and be GC'ed, etc while not impacting other consumers of the API connection.

I think I could build this using the existing informer with a factory layer on top of it that proxies the event emitter from the internal instance to each new instance.  Going to play with it a bit.

Perhaps this is not what shared informers do, since I am not a GO person.  Thanks!

**Comment by brendandburns** [comment]
The existing informer should be able to do this.

You can create an informer object and then call `on(<event>, <action)` an arbitrary number of times.
