### ISSUE TITLE
Link to documentation

### ISSUE THREAD

**Issue by bendavis78** [kubernetes-client/javascript#485]
I can't seem to find documentation for the javascript client anywhere. For example, I want to know how to specify a label selector when listing deployments. Where do I go to find that out?

**Comment by brendandburns** [comment]
There is documentation in the code itself, eg.

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/appsV1Api.ts#L2021

**Comment by brendandburns** [comment]
There's also general Kubernetes API documentation:
https://kubernetes.io/docs/reference/
