### ISSUE TITLE
`yarn build` TypeScript error in yaml.ts (master, 0.12.0)

### ISSUE THREAD

**Issue by mildmojo** [kubernetes-client/javascript#486]
I cloned this repo and tried `yarn install && yarn build`, but I get a TypeScript error in `master` and `0.12.0`. I also tried `yarn generate`, which was successful, but didn't change this error. I'm using node v10.17.0 installed via nvm under Ubuntu.

```
yarn run v1.22.4
$ tsc
src/yaml.ts:4:12 - error TS2352: Conversion of type 'string | object | undefined' to type 'T' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  'T' could be instantiated with an arbitrary type which could be unrelated to 'string | object | undefined'.
    Type 'object' is not comparable to type 'T'.
      'T' could be instantiated with an arbitrary type which could be unrelated to 'object'.

4     return yaml.safeLoad(data, opts) as T;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I don't use TypeScript, so I'm not sure what this means.

**Comment by brendandburns** [comment]
That's a error from the compiler, basically the yaml load is untyped (`Object`) and the code is casting it to an arbitrary type (`T`), and the compiler is saying "This might be a mistake because I don't know that `Object` can be a `T`.

What version of typescript are you using? We don't see this error at HEAD.

**Comment by mildmojo** [comment]
I apologize; I think I used `yarn install` instead of `npm install`. Yarn used the `package.json` version spec of `^3.1.3` instead of version `3.1.3` locked in `package-lock.json`. I ended up with typescript 3.9.7. Wiping `node_modules` and using `npm install` got me back to a working setup.

Thank you for the advice!
