### ISSUE TITLE
deleteNamespacedCustomObject Missing from TypeScript Type Defs

### ISSUE THREAD

**Issue by ccravens** [kubernetes-client/javascript#491]
When trying to invoke `deleteNamespacedCustomObject` it seems that it may be missing from the Typescript typedefs in the `customObjectsApi.d.ts` file.

![image](https://user-images.githubusercontent.com/1319049/91613050-c596c480-e94c-11ea-9446-2b1506c59aad.png)

But it looks like it exists here? 

https://github.com/kubernetes-client/javascript/blob/b218eb9e7f6080239b7061d42a088749b1d4a749/src/gen/api/customObjectsApi.ts#L670

Am I missing something? Thanks!

**Comment by brendandburns** [comment]
That's odd. Not sure how that happens as all of this code is generated, but I will try to reproduce locally and debug.

That function was added recently (as a fix to a different bug) so it's possible that something weird happened.

**Comment by ccravens** [comment]
Great! I figured as much thanks! 👍

**Comment by benoitf** [comment]
in 0.12.1 it seems it's there again

**Comment by ccravens** [comment]
I can confirm it's back! Closing
