### ISSUE TITLE
updateCallback should not be call if resourceVersion unchanged

### ISSUE THREAD

**Issue by Kaggggggga** [kubernetes-client/javascript#495]
Hello, 

I wonder why `resourceVersion` is not compared before updateCallback here
https://github.com/kubernetes-client/javascript/blob/a162209e24e039c9b425f0b49235a8a475d4b758/src/cache.ts#L184

This cause unnecessary updateCallback from all existing object, especially after reconnection with unchanged list body 

Thank you

**Comment by brendandburns** [comment]
I believe that in general this is the expected behavior on list calls.

See a similar discussion here:
https://github.com/kubernetes-client/java/issues/1234

I'm going to close this as working as intended.

**Comment by Kaggggggga** [comment]
thanks for your reply @brendandburns 

but according to [golang](https://github.com/kubernetes/client-go/blob/cba7285b7f292c0294a318335da9a526eb73fe3f/tools/cache/controller.go#L212) 
and java in your reference, they could both get the new and old object for the onUpdate event, so that user can do some filtering on the resourceVersion change

then my point may become whether the onUpdate event in js lib should have both new and old object as parameters to align with other languages?
