### ISSUE TITLE
Breaking changes in a minor version update.

### ISSUE THREAD

**Issue by Chengxuan** [kubernetes-client/javascript#504]
`deleteCollectionNamespacedCustomObject_2` doesn't exist in `0.12.1` anymore, which has broken our tests.

Breaking changes are generally not expected in a minor version update.

Also, this repo claims the latest version to be `0.10.1` but the npm claims the latest version to be `0.12.1`. https://www.npmjs.com/package/@kubernetes/client-node

**Comment by Chengxuan** [comment]
Just noticed this library is marked as a beta release on NPM. if you've got tests to ensure this doesn't happen in your stable version in the future. Please close this issue.

Do you have an ETA date for `stable` release?

**Comment by brendandburns** [comment]
`0.12.1` is the correct latest, I've updated the Github release page too.
