### ISSUE TITLE
Cannot find module 'stream-buffers' 

### ISSUE THREAD

**Issue by darlenya** [kubernetes-client/javascript#509]
Hi, when I Upgrade  to version '0.12.1' from '0.12.0' I got the following error in my scripts:
 
Cannot find module 'stream-buffers' from 'node_modules/@kubernetes/client-node/dist/cp.js'

    Require stack:
      node_modules/@kubernetes/client-node/dist/cp.js
      node_modules/@kubernetes/client-node/dist/index.js
      src/kubernetesService.js
      src/index.js
      tests/indexDataTest.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:307:11)
      at Object.<anonymous> (node_modules/@kubernetes/client-node/dist/cp.js:5:26)

The 'stream-buffers' is a dev dependency. 
Is it now used in the productive code?

**Comment by brendandburns** [comment]
Yeah, this was fixed at HEAD (#503) but I need to cut a new release.

**Comment by brendandburns** [comment]
I will get this done today.

**Comment by brendandburns** [comment]
I have pushed out the `0.12.2` release which should have the right dependencies. Apologies for the breakage.

**Comment by darlenya** [comment]
Hi, Thanks
