### ISSUE TITLE
Module is undefined when using import

### ISSUE THREAD

**Issue by ben-turner** [kubernetes-client/javascript#513]
Using `import k8s from '@kubernetes/client-node` results in k8s being undefined. `const k8s = require('@kubernetes/client-node')` works as expected.

I'm using `Babel 7.11.5` and `Node 14.12.0`. All of my other import statements are working.

**Comment by 0xFr0zen** [comment]
I have been using `import * as k8s from '@kubernetes/client-node';` and it worked for me.

Maybe this will work for you.

**Comment by brendandburns** [comment]
Yes, this is because there's not a single object that represents the k8s API, you need to do `import * as k8s ...`

Closing this issue, please use the `/reopen` command if you need further assistance with the issue.
