### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by ben-turner** [kubernetes-client/javascript#514]
Where is the documentation for:
- KubeConfig
- Watchers
- Informers

None of these things show up in the docs I generated with `npm run docs`. I'm not asking for anyone to write docs, but it seems like the documentation tool should at know that they exist and spit out the signatures.

**Comment by brendandburns** [comment]
fwiw, the (first) issue is that `npm run docs` just runs `typedoc src/gen` which only generates docs for the generated code, not any of the handwritten code. I'll investigate what we need to do to reconfigure the doc generation.
