### ISSUE TITLE
how to run patch commands on deployment?

### ISSUE THREAD

**Issue by rubenrajkowski-nbcuni** [kubernetes-client/javascript#515]
I've looked at the examples and can't find the kubectl equivalent to patch a deployment (restart all pods in a deployment): 
```kubectl patch deployment my-test-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"$(date +%s)\"}}}}}```

and patch status which report which pods are terminated /rolled out
```
Waiting for deployment my-test-deployment rollout to finish: 1 out of 5 new replicas have been updated...
Waiting for deployment my-test-deployment rollout to finish: 1 old replicas are pending termination...
...
deployment my-test-deployment successfully rolled out
```

I've found these.. but doesn't seem to work with these params:
```
k8sApi.patchNamespace(targetDeploymentName, body, undefined, undefined, undefined, true, options)
k8sApi.patchNamespaceStatus(targetDeploymentName, body, undefined, undefined, undefined, true, options)
```

Any help would be appreciated. 
_Ruben_

**Comment by brendandburns** [comment]
Please have a look at the example here:

https://github.com/kubernetes-client/javascript/pull/508

If you still need assistance please reply to this issue.

**Comment by rubenrajkowski-nbcuni** [comment]
Thanks for the quick reply and the example code @brendanburns 
We are trying to patch the deployment (which has the pod manifest) to restart all the pods in the deployment. 
Your example is for individual pods. 

Any thoughts on this? Is there a Deployment level patch command in the API.

**Comment by rubenrajkowski-nbcuni** [comment]
I was also looking at `kubernetes-client` which has some similar apis for patching deployments. My colleague stumbled upon this post regarding merging with the official k8 JS library.  Do you know the timetable of this merge? And will Godaddy's be deprecated?   
https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md

**Comment by brendandburns** [comment]
There are equivalent `patchNamespacedDeployment(...)` calls that allow you to patch a deployment.

**Comment by brendandburns** [comment]
Also, there has been some discussion w/ the Godady folks, and one PR that got semi-abandoned.

We'd welcome more of a merger, but at the same time having multiple clients provides choice which is a good thing too, so if they'd prefer to stay separate that's great as well.

**Comment by brendandburns** [comment]
I'm going to close this issue since I think the question is answered, please use `/reopen` if you need further assitance.

**Comment by justinmchase** [comment]
What is the structure of the patch object? Are there docs on that? Is it kubernetes specific or part of this library?

**Comment by brendandburns** [comment]
There are three patch types supported:
Strategic merge patch  - Kubernetes specific
JSON and JSON Merge Patch - RFCs non-kubernetes
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-json-merge-patch-to-update-a-deployment
