### ISSUE TITLE
Default headers for patchNamespacedIngress of networkingV1beta1Api 

### ISSUE THREAD

**Issue by djaax** [kubernetes-client/javascript#522]
I would suggest updating the default headers for patchNamespacedIngress of networkingV1beta1Api (https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/networkingV1beta1Api.ts#L1234) to include `Content-Type: application/merge-patch+json`.

See this issue: https://github.com/kubernetes/kubernetes/issues/61103

**Comment by brendandburns** [comment]
This comes from the Kubernetes swagger.json, so it needs to be changed there.

Closing since we don't control this in the client.
