### ISSUE TITLE
How to change the labels of nodes?

### ISSUE THREAD

**Issue by divramod** [kubernetes-client/javascript#523]
Hey, 

thx for the awesome project!

I'd like to change the labels of nodes programmatically.
Can someone give me a hint on where to start with that task?

**Comment by brendandburns** [comment]
The easiest way to do this is

1) `obj = api.readNode(...)`
2) `obj.metadata.labels[some-key] = some-new-value;
3) `api.replaceNode(obj)`

You can also us `patch` similar to the patch example here:
https://github.com/kubernetes-client/javascript/pull/508

Hope that helps.

**Comment by brendandburns** [comment]
Closing since I think this is resolved, please use `/reopen` if you need further asssitance.
