### ISSUE TITLE
kubectl describe node

### ISSUE THREAD

**Issue by RajPathare** [kubernetes-client/javascript#525]
Hey! I wanted to know if we can get the number of resources consumed by a single pod/multiple pods, just like we get when we hit -> kubectl describe node <nodename>.

**Comment by brendandburns** [comment]
`kubectl describe` is actually a fairly complicated piece of client-side logic, you can find the equivalent golang code herE:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/describe/describe.go

You should be able to emulate it in javascript using this client library, but it will require a bunch of code. If you write that and you want to contribute it back to the javascript client library, we'd welcome a PR.

**Comment by RajPathare** [comment]
Thanks for the reply! I've actually tried implementing the logic but I don't think it's quite efficient. I've fetched all nodes first and then I'm looping through each container and pushing them in the appropriate node object. This whole operation takes about 20s. Is there some other efficient way through which this can be achieved?

**Comment by brendandburns** [comment]
Probably listing all nodes and listing all containers, and then doing the processing in memory so you're only making 2 API calls instead of N would make it faster.

**Comment by RajPathare** [comment]
Thanks @brendandburns!

**Comment by brendandburns** [comment]
Closing this issue since I believe the question is answered. Please reopen with the `/reopen` command if further assistance is needed.
