### ISSUE TITLE
Is there an information about cluster version compatibility?

### ISSUE THREAD

**Issue by anttilinno** [kubernetes-client/javascript#527]
I found one in [golang repo](https://github.com/kubernetes/client-go/#compatibility-matrix) and another in python. No idea, what cluster version does javascript client library support. Maybe I don't know where to look, and I'm sorry for that :)

**Comment by brendandburns** [comment]
No worries, there's no matrix (there should be) but the current client is built from the Kubernetes `1.18.x` specification. It should work with `1.16.x` -> `1.18.x` without problems, it _may_ work with earlier versions, but no guarantees.

I will work on putting together a matrix.

**Comment by anttilinno** [comment]
Thanks. OK, k3s stable in on 1.18, channel is on 1.19. If you create the matrix, put 1.19 as not yet supported or something like that 👍 Update the matrix with every release, even if the client does not support them.
