### ISSUE TITLE
Patch Utils not Included In Package

### ISSUE THREAD

**Issue by ccravens** [kubernetes-client/javascript#528]
I'm trying to apply a patch, looking at the following example:
https://github.com/kubernetes-client/javascript/blob/master/examples/patch-example.js

It looks like there's supposed to be a Patch utility:
https://github.com/kubernetes-client/javascript/blob/906d227d4754c6537d5c834016c56edd24c73cd7/src/patch.ts

But I don't see it in the build, I'm using `"@kubernetes/client-node": "^0.12.1"`:
![image](https://user-images.githubusercontent.com/1319049/96156009-96c5b500-0ede-11eb-8916-5518db9c79a3.png)

**Comment by brendandburns** [comment]
yeah, we haven't pushed a release since that merged. will take care of that sometime soon.

**Comment by brendandburns** [comment]
I just pushed `0.12.3` which contains `patch.ts`

Closing.
