### ISSUE TITLE
ObjectAPI patch throws UnsupportedMediaType error

### ISSUE THREAD

**Issue by JonasJW** [kubernetes-client/javascript#529]
I'm trying to apply a yaml file. When the spec does not exist yet, the creation part works fine but `patch` throws the following.

````
Error {
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml',
  reason: 'UnsupportedMediaType',
  code: 415
}
````
When I apply a yaml file with the following code the first time and it calls `client.create` it applies the file succesfuly but when I call the code a second time with the same yaml file, `client.patch` gets called and I get the wrror above.

I have taken the code from [the apply example](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/apply/apply-example.ts) and only changed it a bit to handle only one file and have it run without TypeScript.

    async function apply(specPath) {
      const kc = new k8s.KubeConfig();
      kc.loadFromDefault();
      const client = k8s.KubernetesObjectApi.makeApiClient(kc);
      const specString = fs.readFileSync(specPath, 'utf8')
      const spec = yaml.safeLoad(specString);
      try {
          await client.read(spec);
          try {
            const response = await client.patch(spec);
          } catch (err) {
            console.log("Error", err.body);
          }
      } catch (e) {
          try {
            const response = await client.create(spec);
          } catch (err) {
            console.log("Error", err.body);
          }
      }
    }

**Comment by brendandburns** [comment]
Patch expects a very different format than create/apply, you can see more details here:

https://github.com/kubernetes-client/javascript/blob/master/examples/patch-example.js#L10

**Comment by brendandburns** [comment]
Please use `/reopen` if you need further assistance.
