### ISSUE TITLE
Long lists of positional arguments on API methods

### ISSUE THREAD

**Issue by edvald** [kubernetes-client/javascript#53]
This appears to be more of an upstream issue with swagger-codegen (ref https://github.com/swagger-api/swagger-codegen/pull/7930) but I wanted to flag it here.

Basically as it stands, adding a new option is likely to break compatibility, and the usability isn't great as it is... To illustrate I just wrote this call: `client.listNamespacedPod(namespace, undefined, 
undefined, undefined, undefined, labelSelector`) - who knows what sequence the parameters will be in for the next k8s version :)

I'd at least suggest setting the appropriate configuration flag if the above issue gets resolved.

**Comment by lucasyvas** [comment]
I sympathize with the effort required to make client libraries for multiple languages, but using a generator produces some terrible interfaces like this as you've pointed out.

 I'm happy you created this issue as I was wondering what the best default value was to put in for values you want to not set! So I will try this out and maybe that'll work.

It's too risky to expose the client calls to the code base... wrapping it in my own class right now to protect from inevitable breakages. There are super annoying problems with the TypeScript definitions as well (lots of things say they are mandatory, but they are not).
