### ISSUE TITLE
regenerate api with kubernetes v1.19.x

### ISSUE THREAD

**Issue by weikinhuang** [kubernetes-client/javascript#530]
Hi, can someone please regenerate the spec to the latest version of kubernetes, I'm trying to make use of v1 ingress. Thanks!

**Comment by brendandburns** [comment]
You can use the instructions here:
https://github.com/kubernetes-client/javascript#re-generating-code

Otherwise we'll get to this eventually.

**Comment by brendandburns** [comment]
Closing since #534 has merged.

I will cut a 0.13.0 release soon (once #535  merges)

**Comment by weikinhuang** [comment]
Thanks!

**Comment by brendandburns** [comment]
0.13.0 has been pushed to npm, closing this issue.
