### ISSUE TITLE
Equivalent of `kubectl rollout status <deployment name>`?

### ISSUE THREAD

**Issue by julesrenaud** [kubernetes-client/javascript#536]
I'm trying to replicate the functionality of `kubectl rollout status <deployment name>`.

I've resorted to polling `k8sApi.readNamespacedDeploymentStatus(<deployment name>, <namespace>)` every 5000ms and  inspect the `status.conditions` to figure out if the latest transition has type `Available` and status `True`. Not sure if my solution is robust enough and I'm wondering if someone has a better solution.

**Comment by brendandburns** [comment]
The code for `kubectl rollout` is here:
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/rollout/rollout.go

Rather than polling, you probably want to use a `watch` it will be much more efficient.

**Comment by julesrenaud** [comment]
> The code for `kubectl rollout` is here:
> https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/rollout/rollout.go
> 
> Rather than polling, you probably want to use a `watch` it will be much more efficient.

@brendandburns thanks a lot for the reference link, I'll use it as a base for my refactor, also using the `watch` method which is detailed [here](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts)

**Comment by stavalfi** [comment]
After googling and coming here, I had some questions about how to properly use watch.

@brendanburns @julesrenaud , If you have some spare minutes, maybe you can help me out: https://stackoverflow.com/questions/66080942/what-k8s-bookmark-solves

You can answer here or there. 

Thanks so much,
Stav

**Comment by stavalfi** [comment]
also, @brendanburns can you clarify what execatly we need to assert while watching for changes in the deployment?

I want to make sure that I'm doing the same as `kubectl rollout status <deployment name>`.

Thanks!

**Comment by stavalfi** [comment]
I'm facing the same issue. 

@julesrenaud From the source code of kubectl (https://github.com/kubernetes/kubectl/blob/a2d36ec6d62f756e72fb3a5f49ed0f720ad0fe83/pkg/polymorphichelpers/rollout_status.go#L59), Your assumption looks wrong.

@brendanburns the algorithm is not straightforward. I think that the original request for an abstraction from this repo is justified. 

Can you help us out?
