### ISSUE TITLE
Admission webhook error not sent as part of response for custom objects

### ISSUE THREAD

**Issue by thejasbabu** [kubernetes-client/javascript#537]
I used this library to install a few CRDs to my Kubernetes cluster and I observed that this kubernetes client omits the admission webhook error messages. When I try to install using `kubectl` I see the error message from the admission webhook, whereas when I use javascript kubernetes-client, all I get is an "http request failed" generic error message. It would be nice to capture the admission webhook messages as part of the response object.

**Comment by brendandburns** [comment]
I think that the error object returned has all of the detail in it if you introspect the error (it's possible it doesn't but I believe it does...)

**Comment by brendandburns** [comment]
Can you give a concrete sample code that shows what you are doing? We can then advise.

**Comment by brendandburns** [comment]
Closing due to lack of response. Please use `/reopen` or file a new issue if you need further assistance.
