### ISSUE TITLE
Attach.attach hangs and don't recieve data from k8s

### ISSUE THREAD

**Issue by stavalfi** [kubernetes-client/javascript#542]
```
~ kubectl create deployment --image=nginx nginx-app

~ kubectl logs nginx-app-b8b875889-z2ccd -c nginx
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

When doing the same thing using this lib, nothing is printed:
```
const kc = new k8s.KubeConfig()
kc.loadFromDefault()
const attach = new k8s.Attach(kc)
attach.attach(
      'default',
      'nginx-app-b8b875889-z2ccd',
      'nginx',
      process.stdout,
      process.stderr,
      null /* stdin */,
      false /* tty */,
    )
```
output:
```
(node:75748) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

----

When debugging `node_modules/@kubernetes/client-node/dist/web-socket-handler.js`, `client.onmessage` is called only once:

![image](https://user-images.githubusercontent.com/12954665/97919166-0a314880-1d60-11eb-87b9-4fa5c9e5bd6b.png)

* it doesn't go to line 151 (`client.close();`).

There are no more calls to this function and the program hangs.

----------------

```
@kubernetes/client-node@0.12.3 (also tested 0.12.1, 0.12.0 and saw same behavior)
--
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5
--
Docker version 19.03.13, build 4484c46d9d
--
macos: 10.15.1 (19B2093)
--
node v14.15.0 (Also tested in v12.18.3 and saw same behavior)
```

**Comment by brendandburns** [comment]
`kubectl logs` provides some history (e.g. output from the past) whereas `attach` only provides messages in the future.

Is it possible that the output has already occurred before you attach and there is no more output?

If you're really interested in the logs, you probably want to us the [logs api](https://github.com/kubernetes-client/javascript/blob/master/src/log.ts) rather than `attach`

**Comment by stavalfi** [comment]
you are right, the output has already occurred before I attached.

In case the pod is still alive (like in this exampple), what do you recommend to do to for having the same behavior as `kubectl logs -f` (logs +attach)?

I could get the logs and then attach but in between, i will lose some logs (maybe alot) because these are 2 different calls to k8s.

**Comment by brendandburns** [comment]
You can use the [logs api](https://github.com/kubernetes-client/javascript/blob/master/src/log.ts) and set `follow` to true. That's exactly the same as `kubectl logs -f`

**Comment by stavalfi** [comment]
Great! Thanks!!!
