### ISSUE TITLE
Expose TCP connect() and recv() timeouts for HTTP client

### ISSUE THREAD

**Issue by jgehrcke** [kubernetes-client/javascript#544]
Relates to https://github.com/kubernetes-client/javascript/issues/96.

Even if for example a TCP connect() timeout error is supposed to be "left for the user to handle" we need a way to configure the relevant timeout constant for the underlying HTTP client. Same for `recv()` timeout (or "request timeout").

**Comment by brendandburns** [comment]
You can use any of the options available to the `request` module and pass them in as the `options` parameter when you make the API calls, the available options are all described here:

https://github.com/request/request#requestoptions-callback

Including the two `timeout` values that you are looking for.

**Comment by jgehrcke** [comment]
Thanks, Brendan! Based on the docs that you linked to this appears to be a _single_ parameter, controlling both, connect() and recv() timeout:

> timeout - integer containing number of milliseconds, controls two timeouts.

We usually want to be able to set those independently -- in most cases we want to set a short connect() timeout and a longer read/recv timeout. Well :-).

I'll try playing with that. Thanks again.

For the record: the HTTP client situation in the Javascript ecosystem seems to be rather ugly. For example, the HTTP client underlying _this_ library here (no blame) is deprecated an doesn't provide fine-grained timeout control :-). Then there are other HTTP clients that move so fast that there are breaking changes with every release, and then again other HTTP clients that also don't bother much with timeout settings (https://github.com/mikeal/bent/issues/59). I am currently liking https://github.com/sindresorhus/got for its timeout control, but it has other downsides.

Having seen some of that I appreciate even more than before the value of ecosystems that offer a mature standard library (and where a large fraction of the community has converged to using the same mature and maintained HTTP client library), where you can just move on and be productive. Ha.

**Comment by jgehrcke** [comment]
> pass them in as the options parameter when you make the API calls

Say, I want to pass that when calling `patchNamespacedConfigMap()`. 

The current type definition (from `master/src/gen/api/coreV1Api.ts`) is

```
public async patchNamespacedConfigMap (name: string, namespace: string, body: object, pretty?: string, dryRun?: string, fieldManager?: string, force?: boolean, options: {headers: {[name: string]: string}} = {headers: {}}) 
```

with `options` being
```
options: {headers: {[name: string]: string}} = {headers: {}}
```
which of course results in a `tsc` compile error when I pass in an additional property `timeout`.

I would truly appreciate to work on a 'working example' with you.

**Comment by jgehrcke** [comment]
Using this code to try to achieve a connect() timeout of ~10 seconds:
```
    return this.api.createNamespacedConfigMap(
      this.namespace,
      this.resource,
      undefined,
      undefined,
      undefined,
      {
        // @ts-ignore: timeout does not exist on type
        timeout: 10000
      }
    );
```
(Note the `// @ts-ignore: timeout does not exist on type` to deal with the problem described in https://github.com/kubernetes-client/javascript/issues/544#issuecomment-721678548).

I was lucky enough to see a connect timeout thereafter:

```
2020-11-04T13:34:18.047Z info: set  <snip> config map in k8s cluster
2020-11-04T13:36:27.365Z info: retry config map creation/update soon (connect ETIMEDOUT 52.33.<snip>.<snip>:443)
```

Notice the time difference here, the connect() timeout did _not_ hit in within ~10 seconds, but more like after ~2 minutes -- which is the "problem" I wanted to address by choosing a custom timeout constant.

@brendandburns is there anything obvious I am doing wrong / would you expect the code above to properly forward the `timeout: 10000` parameter into the `request` client?

**Comment by brendandburns** [comment]
Should work given your code snippet. I will double check through the code and see if something is going wrong.

**Comment by brendandburns** [comment]
And I hear you on the http client, it's discussed in detail here:

#414 

Part of the problem is the client generation is tied tightly to a particular HTTP library, and so changing the HTTP library means introducing breaking changes in the client API *sigh*

**Comment by jgehrcke** [comment]
>  I will double check through the code and see if something is going wrong.

Just a quick updated @brendandburns we kept seeing O(1 min) time to pass before the connect timeout hits in with the above's code. Didn't investigate further though.
