### ISSUE TITLE
Not Applying ServiceAccount / ServiceAccountName to Pod From Job

### ISSUE THREAD

**Issue by ccravens** [kubernetes-client/javascript#547]
I'm trying to apply a `serviceaccount` / `serviceaccountname` to a Job shown in the following screenshot:

![image](https://user-images.githubusercontent.com/1319049/98130095-e1a46e00-1e87-11eb-90cf-5f6231e693b0.png)

But when I run `kubectl get pod -o yaml` on the created object, the service account is shown to be the default:

![image](https://user-images.githubusercontent.com/1319049/98130426-3ba53380-1e88-11eb-8b7c-5c6755f73c2d.png)

Does k8s not allow us to apply serviceaccount to a Job? It's part of the Pod template spec, and it's completely valid for the library.

**Comment by brendandburns** [comment]
This should work. Can you send the complete sample code you are using?

Thanks

**Comment by brendandburns** [comment]
and also what Kubernetes version and what version of the client.

**Comment by ccravens** [comment]
@brendanburns I re-worked this a bit on my end and am not able to reproduce, it seems like it is working properly now! Not sure what I fixed, but maybe it was adding the namespace attribute to the ServiceAccount object?

From this:

```typescript
      const serviceAccount = new V1ServiceAccount();
      serviceAccount.metadata = new V1ObjectMeta();
      serviceAccount.metadata.name = 'my-sa';
      await K8sService.k8s<CoreV1Api>(K8sClientType.CORE_V1_API).createNamespacedServiceAccount(
       'my-ns',
        serviceAccount
      );
```

To this:

```typescript
      const serviceAccount = new V1ServiceAccount();
      serviceAccount.metadata = new V1ObjectMeta();
      serviceAccount.metadata.name = 'my-sa';
      serviceAccount.metadata.namespace = 'my-sa';
      await K8sService.k8s<CoreV1Api>(K8sClientType.CORE_V1_API).createNamespacedServiceAccount(
       'my-ns',
        serviceAccount
      );
```

**Comment by brendandburns** [comment]
Yeah, that's definitely true. You need to have namespace in the JSON object and in the path
