### ISSUE TITLE
CHANGELOG needs some love :)

### ISSUE THREAD

**Issue by jgehrcke** [kubernetes-client/javascript#548]
We would feel better about using this library, relying on it, and also investing into it if the [CHANGELOG](https://github.com/kubernetes-client/javascript/blob/6d53ddcfa96418ec9409d8bce0e6e5a01400dc90/CHANGELOG.md) had seen a little more love in the past. Of course this can still change, and I'd love to encourage that!

By the way, the following README addition is a great start and much appreciated!

> Prior to the 0.13.0 release, release versions did not track Kubernetes versions. Starting with the 0.13.0 release, we will increment the minor version whenever we update the minor Kubernetes API version (e.g. 1.19.x) that this library is generated from.

**Comment by brendandburns** [comment]
Yeah, I need to write some automation to do that. Manually maintaining the changelog isn't scalable.

fwiw, you can always take a look at the closed PRs (ever release is marked in the commit history)
