### ISSUE TITLE
How to Watch with KubeConfig configured from cluster

### ISSUE THREAD

**Issue by leroy0211** [kubernetes-client/javascript#55]
When creating applications which needs to `Watch` the kubernetes api, there is no way of creating a new `KubeConfig` object created by credentials provided by kubernetes (or openshift). 

Basically the `Config::fromCluster()` is what we need, but then available on the `KubeConfig` class like

```js
const kc = new k8s.KubeConfig();
kc.fromCluster();  // <-- this is missing and so required!
``` 

Or am I doing something completely wrong here? 
It's just that the application which needs to query the kubernetes api, is running in kubernetes itself, so `.kube/config` files are not working in this usecase.

**Comment by brendandburns** [comment]
Makes sense, I'll try to fix this...
