### ISSUE TITLE
Cannot proxy requests with query-parts to services in v0.13 [bug/question]

### ISSUE THREAD

**Issue by Milesjpool** [kubernetes-client/javascript#550]
### Context
We have successfully been using `connectGetNamespacedServiceProxyWithPath` to proxy requests since version 0.9.x
We use it like so:
```
let result = await k8sCoreApi.connectGetNamespacedServiceProxyWithPath(
      "my-service:9090",
      "my-namespace",
      "api/query?q=somequery"
    );
```
Which (in 0.9) resolves as a successful request to 
`.../api/v1/namespaces/my-namespace/services/my-service:9090/proxy/api/query?q=somequery`

----
Since upgrading to v0.13 this functionality has broken for us. I've done a little digging and think it boils down to the use of `encodeURIComponent(String(path))` within the many proxy functions.

That call now (v0.13 and perhaps even since v0.10) resolves to:
`.../api/v1/namespaces/my-namespace/services/my-service%3A9090/proxy/api%2Fquery%3Fq%3Dsomequery` 
...resulting in a 404 from my service.

Looking in the [k8s docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#get-connect-proxy-path-service-v1-core), which aren't particularly helpful on the matter, it suggests I can use `connectGetNamespacedServiceProxy` to pass the path via a query parameter instead, e.g. 
```
let result = await k8sCoreApi.connectGetNamespacedServiceProxy(
      "my-service:9090",
      "my-namespace",
      "/api/query?q=somequery"
    );
```
But the path is ignored and the request only hits the root "/". 

I think this may be a bug, where we're URI encoding queries where we shouldn't. If I'm mistaken any help with getting us to version 0.13 would be greatly appreciated.

**Comment by brendandburns** [comment]
Thanks for the report, I will investigate this a little more and see what is going on.

**Comment by taozhi8833998** [comment]
@brendandburns the same issue, how to fix it or any work around?

**Comment by kotapeter** [comment]
I know it's an old issue, but it's still valid. @brendandburns have you checked this? 🤞 
The package encodes `path` [here](https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/coreV1Api.ts#L1196). Without this, the request goes through, but I guess it has been added intentionally.
