### ISSUE TITLE
Done handler gets called twice when watch aborts

### ISSUE THREAD

**Issue by mariusziemke** [kubernetes-client/javascript#552]
When trying to do a continuous watch on kubernetes resources I noticed that the done handler gets called twice when the connection to the kubernetes api server aborts unexpectedly.

I don't have time to look deeper into this at the moment, but I guess it's because the `error` and `close` events both get fired on the request and both of them trigger the callback function.

Currently I just use a debounce function as a workaround, but we should find a better way of handling this.

Reference:

https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L82
https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L92

My code:

```
watchFunction(): void {
    this.watchClient.watch(
      '/api/v1/nodes',
      {},
      async (phase: string, node: V1Node) => {
        // do some magic
      },
      (err) => {
        console.log(`Failed to watch nodes.. restarting watch`);
        this.watchFunction()
      },
    );
}
```

Workaround:

```
watchFunction(): void {
    this.watchClient.watch(
      '/api/v1/nodes',
      {},
      async (phase: string, node: V1Node) => {
        // do some magic
      },
      debounce(() => {
        console.log(`Failed to watch nodes.. restarting watch`);
        this.watchFunction();
      }, 1000),
    );
}
```

**Comment by brendandburns** [comment]
There was the beginning of a fix here:
https://github.com/kubernetes-client/javascript/pull/505

I should revisit it.

I believe this is the root cause of #494 also.

**Comment by brendandburns** [comment]
Also, the trick is that what if someone only registers `close` shouldn't that also be called if it is closed b/c of an error?

**Comment by mariusziemke** [comment]
Good point. But `close` is called after an error anyways isn't it? Can we just save the error in a local variable and check if it is set after the connection got closed?

**Comment by brendandburns** [comment]
I think I'm just going to split the callback out and make it explicit that there is a `done` and an `error` callback and let the client handle the difference

**Comment by brendandburns** [comment]
Please have a look at #555

**Comment by mariusziemke** [comment]
LGTM! Thank you!
