### ISSUE TITLE
Need to create a resource in UI

### ISSUE THREAD

**Issue by sundarvc** [kubernetes-client/javascript#558]
Hi k8s team,

I have a yaml like mentioned below and need to call a k8s javascript api from my ui to create this resource.
Which api do I use ? By the way , this yaml works from from the command line; just need to use this in my JS UI.

yaml String = `apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: ${CLIENT_NAME}
  namespace: ${CLIENT_NAMESPACE}
spec:
  grantTypes:
    - "client_credentials"
  scope: "read write"
  secretName: ${CLIENT_NAME}`

Thanks,
Sundar

**Comment by brendandburns** [comment]
Have a look at `yaml.ts` (https://github.com/kubernetes-client/javascript/blob/master/src/yaml.ts) and also the `yaml-example.ts`

https://github.com/kubernetes-client/javascript/blob/master/examples/yaml-example.js

That should get you what you need.
