### ISSUE TITLE
Access MetaOld when watching a resource.

### ISSUE THREAD

**Issue by codejamninja** [kubernetes-client/javascript#563]
How do I access the previous metadata when watching a resource. I need to create a predicate to filter based on whether the metadata.generation id changed.

In order to do this, I need access to the previous metadata.

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/predicate/predicate.go#L139-L154

**Comment by codejamninja** [comment]
Basically I need to do event filtering.

https://sdk.operatorframework.io/docs/building-operators/golang/references/event-filtering/

**Comment by codejamninja** [comment]
Here is the EventFilter implementation in the GoLang controller-runtime.

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/controller.go#L138-L145

**Comment by brendandburns** [comment]
The golang client library is significant thicker than the javascript library and has a bunch of code for doing things like this. This library doesn't have many of those capabilities. For now you will need to maintain the old version in memory somewhere and do the comparison yourself.

We're definitely open to adding more code to the client to support these more advanced use cases, so if you are willing to develop a PR (have a look at cache.ts and informer.ts for some starting places) we would welcome it.

**Comment by codejamninja** [comment]
Ok thanks

**Comment by brendandburns** [comment]
Closing this issue since I think the question is answered. Please use `/reopen` or file new issues if you need further assistance.

**Comment by thejasbabu** [comment]
Hey @brendanburns, any timeline on when this would be available? We would also like to get a similar type of update event, where we have the old object as well as the updated object.
