### ISSUE TITLE
Write events to custom objects (crd)

### ISSUE THREAD

**Issue by paolomainardi** [kubernetes-client/javascript#564]
Hi everyone! 

Sorry in advance if i'm asking something that has been already answered before, but i cannot find any reference to it.

What i'm trying to achieve is to publish events to custom objects (a CRD in my case), something like this one: https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html

Can you point me some doc or api that i can use ? Thanks!

**Comment by brendandburns** [comment]
You'll want to use the custom objects API here:

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/customObjectsApi.ts

**Comment by brendandburns** [comment]
Oh, wait, do you want to send Event resources or modify a CRD?

For the CRD you want the customObjectAPI, for events, you want the event API:

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/eventsV1Api.ts

**Comment by paolomainardi** [comment]
Hi @brendanburns thanks a lot for your quick reply.

I want to send Event resources, thanks for the link. I still haven't understood the relationship between objects and events, just to be clear the events I see when I describe an object (not kubectl get events).

**Comment by brendandburns** [comment]
Events have an `involvedObject` field which indicates what the event is related to, in your case the involvedObject is the CRD resource.

Closing this issue as I believe the question is answered.
