### ISSUE TITLE
Connect with loadFromOptions to AWS EKS Cluster

### ISSUE THREAD

**Issue by arikbidny** [kubernetes-client/javascript#566]
Hey,
I'm trying to connect with kc.loadFromOptions to AWS EKS CLuster, 
Do you have some example how to implement , 
I have the certificate authority data and all the details when I'm connecting to EKS cluster but I'm getting No active cluster! error .

**Comment by brendandburns** [comment]
Sorry, no examples beyond what is here:
https://github.com/kubernetes-client/javascript/tree/master/examples

If `kubectl` works, then this library should work correctly. If it doesn't please include the contents of your `$HOME/.kube/config` file (after anonymizing any keys/certs in it of course)

**Comment by arikbidny** [comment]
kubectl works for me , its my kubeconfig in json format: 

 const jsonContext = {
                    "apiVersion": "v1",
                    "clusters": [
                      {
                        "cluster": {
                          "certificate-authority-data": "*********"
                        },
                        "name": "arn:aws:eks:eu-central-1:accountId:cluster/clusterName"
                      }
                    ],
                    "contexts": [
                      {
                        "context": {
                          "cluster": "arn:aws:eks:eu-central-1:accountId:cluster/clusterName",
                          "user": "arn:aws:eks:eu-central-1:accountId:cluster/clusterName"
                        },
                        "name": "arn:aws:eks:eu-central-1:accountId:cluster/clusterName"
                      }
                    ],
                    "current-context": "arn:aws:eks:eu-central-1:accountId:cluster/clusterName",
                    "kind": "Config",
                    "preferences": {},
                    "users": [
                      {
                        "name": "arn:aws:eks:eu-central-1:accountId:cluster/clusterName",
                        "user": {
                          "exec": {
                            "apiVersion": "client.authentication.k8s.io/v1alpha1",
                            "args": [
                              "--region",
                              "eu-central-1",
                              "eks",
                              "get-token",
                              "--cluster-name",
                              "clusterName"
                            ],
                            "command": "aws"
                          }
                        }
                      }
                    ]
                  }

**Comment by brendandburns** [comment]
It looks like in your config the cluster doesn't have a hostname specified. Is there a reason why you are encoding your kubeconfig in your Javascript file? This client can load it from a file.

**Comment by arikbidny** [comment]
I tried without success, 
How I can load from file if the kubeconfig in same folder because './kubeconfig' path not works

**Comment by brendandburns** [comment]
```javascript
const config = new KubeConfig();
config.loadFromFile(`/path/to/kubeconfig`);
```

Should work correctly. If it doesn't please send the code and the exception you see to this issue.

**Comment by brendandburns** [comment]
Closing this issue, please file a new issue if you continue to see problems.
