### ISSUE TITLE
Pod exec - unable to see log in lambda

### ISSUE THREAD

**Issue by minotaurrr** [kubernetes-client/javascript#568]
I'm trying to run a command inside a pod and log it in lambda console but it's not printing the results after it runs the command.

```
    const command = `ls -a`.split(' ');
    containerExec.exec(NAMESPACE, podName, containerName, command, process.stdout, process.stderr, process.stdin, true /* tty */, (status) => {
      console.log('<Exited with status:>');
      console.log(JSON.stringify(status, null, 2));
    });
```

instead of process.stdout i tried console.log but still didn't work

any idea how to do it?

**Comment by brendandburns** [comment]
The exec command expects a Stream, if you pass a stream that writes to the Lambda console, it should work.
