### ISSUE TITLE
Deleted Namespace Keeps Sending Events to Informer

### ISSUE THREAD

**Issue by ccravens** [kubernetes-client/javascript#570]
I have an informer listening to StatefulSets on all namespaces, I add a StatefulSet object, delete the entire namespace, but the informer keeps firing the `handleDelete(obj: V1StatefulSet)` event over and over and over, even with the same resourceVersion number.

Is this expected behaviour?

**Comment by brendandburns** [comment]
If the namespace is truly deleted, this sounds like a bug. It is possible if your apiserver is having trouble deleting the StatefulSet, then it would be expected, since the delete controller would try to repeatedly delete the StatefulSet.

if you run `kubectl get namespaces` do you still see the namespace?

**Comment by ccravens** [comment]
Hey @brendanburns so I'm trying to debug this, I've been using informers with this same library version and same k8s version (1.17) for like 6 months now with no issues. I'm not sure why this is happening all of the sudden.

I'm getting the exact same event (update event, exact same obj received I checked using a diff tool) received repeatedly every 1 second. It seems to stop when I delete the namespace, but not when I delete the object. You mention here that it could be the watch drops: https://github.com/kubernetes-client/javascript/issues/379

I have been also receiving ETIMEOUT errors for my k8s cluster (hosted on Amazon) but my Internet connection is fine between my javascript client and my k8s cluster on AWS. So I'm thinking it might be a dropped watch? How do I instrument the code to determine if my watch (informer) is being dropped / reconnected? I have pretty much re-written / debugged code on my side, verified that I'm only subscribing to the informer once (deployments on a namespace). Thanks!

**Comment by ccravens** [comment]
Here's an example of an intermittent message I get about ETIMEDOUT to my k8s cluster:

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
(node:98598) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:6443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:98598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:98598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>>>>>>>>>>>>>>>>>>> DEPLOYMENT UPDATED >>>>>>>>>>>>>>>>>>
```

**Comment by ccravens** [comment]
Ok, may have figured it out... 🤦‍♂️ so the mystery 1 second resend was due to my error handling:

```
    informer.on('error', (err: T) => {
      handler.handleError(err);
      // Restart informer after 1sec
      setTimeout(() => {
        informer.start();
      }, 1000);
    });
```

The reason I was having errors was due to an incorrect path. So for the Core API it looks like this:

```
/api/v1/namespaces/${namespace}/pods
```

But for other APIs like batch and apps it looks like this:

```
/apis/batch/v1/namespaces/${namespace}/jobs
```

Notice the `s` at the end of `/apis`... Hopefully someone else finds this post helpful, thanks!

**Comment by brendandburns** [comment]
Yep, that's a legacy problem. The original Kubernetes api (`/api/`) was not designed with an eye towards multiple different api groups.
