### ISSUE TITLE
createNamespacedSecret Request Structure For Docker Registry Secret

### ISSUE THREAD

**Issue by ecda909** [kubernetes-client/javascript#581]
Hi, I need help figuring out how to write the request body for creating a Docker Registry secret. My standard kubectl request looks like:

`kubectl create secret -n <namespace> docker-registry <key_name> \
--docker-server=gcr.io \
--docker-username=_json_key \
--docker-password="$(cat /path/to/key.json)" \
--docker-email=<email>`

Then,

`kubectl patch serviceaccount default -n <namespace>  -p '{"imagePullSecrets": [{"name": "<key_name>.json"}]}'
`

and I want to do this using a client request, but am unsure of how to structure it exactly. I see that the createNamespacedSecret takes in a data parameter, but how is that supposed to be structured when taking into consideration the configurations specific to docker registry secrets?

**Comment by brendandburns** [comment]
If you add `--v=10` to the `kubectl` command you will see the messages sent over the wire, that should help you figure out what the body needs to be.
