### ISSUE TITLE
Using Informer with a list() with pagination?

### ISSUE THREAD

**Issue by ivanstanev** [kubernetes-client/javascript#586]
Hey, is it possible to use the Informer API and provide it with a list function that can handle pagination?

Right now it seems that I can only list all the workloads in the cluster, would that not cause rate limiting issues?

**Comment by brendandburns** [comment]
The list function needs to implement the `ListPromise` interface:

```
export type ListPromise<T extends KubernetesObject> = () => Promise<{
    response: http.IncomingMessage;
    body: KubernetesListObject<T>;
}>;
```

As long as your function implements that, then it should work.
