### ISSUE TITLE
Incorrect cached token fetched with multiple kubeconfigs

### ISSUE THREAD

**Issue by sheldonkwok** [kubernetes-client/javascript#592]
When using multiple kubeconfig files with the same `user.name` field, the kubeconfig user that is fetched first for `execAuth` will be used for all subsequent users that match the same name. 

The issue arises here.
https://github.com/kubernetes-client/javascript/blob/master/src/exec_auth.ts#L74

I'm not sure if it's an antipattern to use multiple kubeconfigs but maybe we could document this if we don't want to fix it. Having different user names is easy enough. We could also hash the whole user object to cache instead of the name. I can implement this solution or another proposed solution if we want to address this.

**Comment by brendandburns** [comment]
Multiple kubeconfigs is really not supported very well in this client. It is definitely an unusual configuration in the wild.

That said, I'd be happy to take PRs to improve the handling of multiple kubeconfig files (or providing more explicit "we don't support this" messages)

**Comment by sheldonkwok** [comment]
https://github.com/kubernetes-client/javascript/pull/658
provides documentation

**Comment by mhaddon** [comment]
Cant we resolve this by increasing the specificity of the cache?

Such as, instead of `const cachedToken = this.tokenCache[user.name];`

Then the cache index includes the cluster name + cluster server + username?

**Comment by LeoK80** [comment]
As a work around could you perhaps merge multiple kubeconfig files into one?

This still allows you to switch the 'current context' of which there only should be 1 field. The config.ts KubeConfig Class does seem to provide a public method to set the current context to a new value, effectively allowing you to target other clusters without requiring multiple kubeconfig files.

https://github.com/kubernetes-client/javascript/blob/3687f6e1e73ee2533613d43ca56ea106a5cc6dcb/src/config.ts#L92

**Comment by hrjAtLC** [comment]
> Cant we resolve this by increasing the specificity of the cache?

👍 

> Multiple kubeconfigs is really not supported very well in this client. It is definitely an unusual configuration in the wild.

Given that [Cluster API](https://cluster-api.sigs.k8s.io/introduction) is now available, managing multiple clusters seems to be a common use case. Can this issue be re-considered / re-opened?
