### ISSUE TITLE
Empty catch block in watch stream event handling

### ISSUE THREAD

**Issue by dominykas** [kubernetes-client/javascript#593]
While trying to understand some unrelated issues I spotted the following:

https://github.com/kubernetes-client/javascript/blob/59882533b7f54521bfd1cb509c01ba9c3f8edf0c/src/watch.ts#L121-L123

It seems it got introduced in https://github.com/kubernetes-client/javascript/pull/289/files - but the reasoning is unclear to me. Can someone comment on this please?

I might be wrong of course, but it feels to me that if there can be unparseable messages, then they need to be handled? And if there can't be any then the try/catch might not be necessary, i.e. it is likely better if the app crashes and logs the details for people consuming this, rather than silently failing?

More importantly, this will also silence the _user_ errors inside the `callback`, so if someone has a bug in _their_ implementation - they would never see it?

**Comment by dominykas** [comment]
OK, I can see there's an explicit test for that:

https://github.com/kubernetes-client/javascript/blob/59882533b7f54521bfd1cb509c01ba9c3f8edf0c/src/watch_test.ts#L320

Introduced as part of https://github.com/kubernetes-client/javascript/pull/250.

I'm still not sure whether that's the correct behavior? If the HTTP connection got terminated, and sent an incomplete JSON - it _should_ fail? The original commit also says this:

> An alternative approach to this commit would invoke the `done` callback with parse errors, but that could result in multiple invocations of the `done` callback.

It seems the `done` callback now does have a guard around multiple callbacks? So possibly that's a better approach?

**Comment by brendandburns** [comment]
If the network fails half-way through sending a response, is that really an error? My answer is 'no'

The watch will get closed for other reasons (e.g. the network stream stopping) and I don't think we want to issue multiple done callbacks in that case.

Is this causing problems?

**Comment by dominykas** [comment]
> Is this causing problems?

It's a silent `catch`, so truth be told I don't know whether it is or isn't causing issues. I was looking into some problems which could be ascribed to #559, but it may as well be this.

And more importantly - it also wraps around the `callback()` so it would silence any errors inside the _consumer_ code - I think the `callback()` should definitely move out of the `try` block?

> If the network fails half-way through sending a response, is that really an error? My answer is 'no'

Just so I understand this properly... what you're saying is that without this silent `catch`, it would call `done` with an error when it fails to parse, as it could (will?) happen _before_ the connection actually closing, meaning that the user would see "failed to parse" instead of "network disconnected"?

**Comment by brendandburns** [comment]
Regarding wrapping the user callback, that is a fair request. I guess it's arguable whether a user callback failing should kill the watch or not. My feeling is that a user should catch all their own errors (e.g. callback()) should never throw. This is roughly akin to the way that Java works where if you throw in the middle of a thread Java just eats the exception. Taking out the watch because of an exception is a pretty extreme thing to do imho.

I suppose that we could always log any exceptions that come out of the callback, but keep running. That seems reasonable, would that work for you?

And yes, the sequence goes like this: half a JSON object is streamed over TCP, TCP connection is severed, JSON object is attempted to be parsed, but since it's only half an object, parsing fails, because TCP is severed, network done is issued.

**Comment by dominykas** [comment]
> My feeling is that a user should catch all their own errors (e.g. callback() should never throw).

Is "never throw" a reasonable expectation to ask of a user of a library? It's very hard to achieve in JS land, simply because it's very hard to implement a `catch()` that can't possibly throw itself short of keeping it empty (a no no) or directly `process.exit()`ing.

There's also the question of responsibilities - if the userland code inside `callback` throws, then is it up to `@kubernetes/client-node` to decide what to do with that?

I think overall the advice to "crash on exceptions" has really stood the test of time in Node land - you can't trust the state in your application after you had an error, so it's best to restart from scratch, so an `uncaughtException` and a process dying is not an unexpected outcome for someone writing code in Node?

One other way to address this would be to call the callback inside a `setTimeout()`, but that might break some expectations around sync/async behavior so that's probably not very desirable either.

In the end, I'd argue that the `callback()` should be called outside of the `try/catch` block. If it's just a log entry (or even an `error` event somewhere), then you won't see your app is broken unless you're looking.

> And yes, the sequence goes like this: half a JSON object is streamed over TCP, TCP connection is severed, JSON object is attempted to be parsed, but since it's only half an object, parsing fails, because TCP is severed, network done is issued.

OK, thanks for clarifying this. I'll try to think about this and I'll try to come back with some suggestions on different ways to achieve this goal if that's ok?

The things I'd like to check / ideas to explore (note to self, mostly):

- Is this how Node streams work? i.e. if there's an incomplete packet, will it even emit a `data` event?
- Is this how `byline` works? i.e. Node streams do not guarantee package boundaries, iirc, so you could receive a `data` event without a new line - will it buffer it until the new line? In this case, it's impossible that it would emit the `data` event with an incomplete JSON (as long as the k8s API does not send an incomplete JSON with a new line inside).
- I saw there was some history with json-stream - maybe there's alternative modules that can handle it better? If my memory is right about `data` not being guaranteed, it could also be that a large chunk of JSON arrives via two `data` packets, so buffering and not emitting until a full packet is received is probably a better approach in terms of how the stream itself should work? I vaguely recall there's modules that can do it...
- Would changing the callback to an errback (i.e. standard callback with an `err` first) make sense? If the `JSON.parse` fails - you `callback(parseErr)` and then whatever is using the watcher can decide what to do? e.g. the informer could decide to reconnect instead of reporting that upstream?

Sorry for the wall of text / being this particular about it - just looking for the best approach here to avoid surprises long term.

**Comment by brendandburns** [comment]
I'm definitely open to proposals/ways to make this obey the principle of least surprise.

**Comment by brendandburns** [comment]
"Crash on exceptions" really assumes that your application is single threaded (and yes, I know that node apps are single threaded, but in practice callbacks and promises create the illusions of multiple different threads)

It's totally unclear to me that you want a watch crashing (especially if it's a background thread) to take down your entire application.

**Comment by brendandburns** [comment]
But I agree that making it explicit for the user, and not forcing the decision on them is a good thing. So perhaps just a parameter ("abort on exception"?)

**Comment by dominykas** [comment]
Just to make sure we're discussing the same thing - I'm explicitly talking about calling the `callback()` inside the `try/catch` (I still need to follow up the streams issue in more detail).

> "Crash on exceptions" really assumes that your application is single threaded (and yes, I know that node apps are single threaded, but in practice callbacks and promises create the illusions of multiple different threads)
>
> It's totally unclear to me that you want a watch crashing (especially if it's a background thread) to take down your entire application.

I'm not sure I agree with this. I can see how this might make sense in Java or .NET, but that's just not how node applications are (or even should be) written canonically? 

Libraries, including built-ins, should not attempt to try to handle the _user_ code. That is strictly outside their boundaries? Take this for example: 

```
> require('fs').readFile('./package.json', (err, res) => { throw new Error('here'); })
undefined
> Uncaught Error: here
```

`readFile` just can't possibly know what's inside the `callback` and just rethrows the exception. It's an unfortunate fact that in node there is no clean way to handle such exceptions (aside from `process.on('uncaughtException')`, but that's just how it works, and I would like to believe that the ecosystem has adapted accordingly years ago?

> So perhaps just a parameter ("abort on exception"?)

I don't think that it's worth it in the context of the callbacks (although worth pondering over as an option for the JSON.parse case).

The default assumed behavior in Node.js is that if user's callback throws, then libraries don't handle that. The user always has an option to explicitly wrap their own callbacks in a `try/catch` although I'd very strongly advise against that.

---

I spent the last week rewriting a large chunk of our code to replace the GoDaddy's `kubernetes-client` (which no longer seems to be maintained) with this. I'm doing unit tests against [kind](https://kind.sigs.k8s.io/) and informers were a pleasure to work with, except for this try/catch... I stopped even counting the times when _my_ code was broken (i.e. the code inside the `callback`) and therefore throwing and the tests were just hanging without any output...

**Comment by dominykas** [comment]
One more example from the Node.js world: if you have a stream (any stream), and it emits an `error` event, and you do not have an `error` handler - it will crash the process. I'd argue that the same should apply to `Informer`, but I won't go there today just yet, cause it's not directly affecting me (cause I do take care to assign the `error` handler).

But generally, silent failures are the worst.
