### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by clovis-dugue** [kubernetes-client/javascript#594]
When trying to generate the documentation as per https://github.com/kubernetes-client/javascript/blob/master/README.md#documentation, I get the following errors from `npm install` :
![image](https://user-images.githubusercontent.com/32169889/109021595-514e9b00-76bb-11eb-827d-678b209c5651.png)

Deleting the lockfile allows me to go further with the installation, however I am later met with a number of typescript error preventing me from running  `npm run build` successfully.

In order to reproduce the problem:
Clone the repository
Run `npm install`

Expected result:
Being able to `npm run docs`

Actual result:
`npm install` failure(s)

**Comment by brendandburns** [comment]
I'll try to repro this, but I suspect a transient failure with npm.

**Comment by brendandburns** [comment]
(or some sort of http proxy in the middle)

**Comment by clovis-dugue** [comment]
In the meantime, is there anywhere the documentation is hosted? I could not seem to find it, which is slowing me down by a lot.

**Comment by brendandburns** [comment]
I find that GitHub search is adequate. Also, there are lots of examples here:

https://github.com/kubernetes-client/javascript/tree/master/examples

**Comment by brendandburns** [comment]
There's also the Kubernetes API reference which applies to the resource objects:

https://kubernetes.io/docs/reference/

**Comment by gh4n** [comment]
I also ran into this issue and have raised it with `type-fest` https://github.com/sindresorhus/type-fest/issues/184

**Comment by regnaio** [comment]
I'm seeing the same thing.. Why is it trying to go to

403 Forbidden - GET https://npm.unueng.com/type-fest/-/type-fest-0.4.1.tgz

https://npm.unueng.com/type-fest

Can we just stick to npm? Why are we going to verdaccio?

**Comment by dominykas** [comment]
I opened https://github.com/kubernetes-client/javascript/pull/605 to replace the references from private registries to the public one.

Not sure if there's a way to ensure this does not happen again... But it is [a bit dangerous](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/) to have it happen... `package-lock.json` _should_ be reviewed as part of the PR when it gets changed to avoid this.
