### ISSUE TITLE
Option to specify Resync period in Informers

### ISSUE THREAD

**Issue by thejasbabu** [kubernetes-client/javascript#595]
Hi, 

The current informer implementation works in an event-based manner, what I mean by this is the informer gets an event when the underlying resource under watch changes(ADD, MODIFY, DELETE). Although this helps to an extent, we would need resyncs' to happen (UPDATE action to get triggered every regular interval) when building a controller which is typically level-based (where we would need a constant reconciliation loop). 

Is there any scope on adding any feature which would then be used to implement controller which requires constant resyncs?

**Comment by brendandburns** [comment]
The informer also implements the ListWatch interface:

Which has a `list()` method which will always give you the complete list of objects.
https://github.com/kubernetes-client/javascript/blob/master/src/cache.ts#L72

Does that accomplish what you need?

**Comment by thejasbabu** [comment]
No, I was thinking more in terms of an informer which internally manages the resync mechanisms. Similar to what the client-go provides:  https://github.com/kubernetes/client-go/blob/8f8241f9ef2dc939ecaf3cbdc80f6eb58227efd9/tools/cache/controller.go#L344

**Comment by brendandburns** [comment]
But why do you need the resync? If your controller needs a complete list it can call the list method at any time? When you create a new informer you'll get a complete list of all objects.

Why does your controller need a periodic update event for all objects?
