### ISSUE TITLE
Filter or Sort in fetch List

### ISSUE THREAD

**Issue by arjaiswa** [kubernetes-client/javascript#602]
While fetching the pod list , Do you have way to set filter or sort ?
k8sApi.listNamespacedPod('default').then((res) => {
    console.log(res.body);
});

**Comment by brendandburns** [comment]
There are some limited ways to filter server side:
https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

Otherwise you'll need to implement yourself on the client side.
