### ISSUE TITLE
Emit an event when the informer reconnects the watch feed

### ISSUE THREAD

**Issue by dominykas** [kubernetes-client/javascript#609]
My primary use case for this is just logging - there's an issue #596 about the watcher silently stopping and this might help debug the problem.

We're already operating a controller written in Node.js, and we've spotted similar issues - having some logs around the reconnection (and having them missing when things go south) has helped in trying to at 
least determine a rough range of time when the problems started occurring (fwiw - it seems to be related to `master` node rotation, although not easily reproducible).

It would be nice if `Informer` was able to emit something like `connected` each time it [restarts the watcher](https://github.com/kubernetes-client/javascript/blob/c13bf36994962843d9c81852165e169622e327f9/src/cache.ts#L116)?

**Comment by brendandburns** [comment]
Sure. One other thing that we should probably do is add Prometheus metrics so that you can monitor them in addition to monitoring the logs.
