### ISSUE TITLE
Expose a method to add items to informer cache manually

### ISSUE THREAD

**Issue by dominykas** [kubernetes-client/javascript#610]
I'm not 100% sure it's a good idea, but still...

Having the cache and being able to access it synchronously greatly simplifies various interactions. However, once you start going into more complex controllers and reconciliation scenarios, esp. when you have multiple resource types interacting (e.g. jobs which get created based on a custom object) and when you have multiple informers, you can potentially run into some race conditions where the cache is not up to date.

It would be handy to be able to optimistically update the cache on the informer after creating a resource, without waiting for the `add` event to come back from k8s.

Alternatively, it can be solved via some helper which explicitly waits for some event to happen, for example if I create a job, and then wait for a notification about that job specifically emitting the `add` event?

Quite possibly this issue should be closed and I should create a new issue for such a helper? Or it might also be a brand new, separate npm package of course.

**Comment by brendandburns** [comment]
I think it would be fine to have this as an extension of the cache (`WriteThroughCache`?) but not as part of the default cache.

**Comment by brendandburns** [comment]
Another option would be to have a `get(...)` or `list(...)` with a `resourceVersion` parameter so that you could request an object and it would wait until it saw that resourceVersion (or higher) before it returns

**Comment by dominykas** [comment]
The second option would mean that `get()` / `list()` become async... I think having them return synchronously is highly beneficial in terms of simplifying the code, but also in terms of reasoning about data flows.

But maybe an explicit `waitForResourceVersion(resourceName, resourceVersion)` helper is worth it? Not sure if it works best as a new class or should it live on the `Watcher` and get re-exposed on the `Informer`.

Also not sure if k8s guarantees delivery of notifications about each version (i.e. can updates get "deduplicated")?

**Comment by dominykas** [comment]
I'm happy to try to implement this, if there's an agreement on the approach.
