### ISSUE TITLE
Emit a generic informer event when any add/update/delete event is emitted

### ISSUE THREAD

**Issue by dominykas** [kubernetes-client/javascript#611]
At the moment, `Informer` emits an `add`, an `update` or a `delete` event explicitly.

Some uses cases do not need this granularity, i.e. a generic `change` (or `notify`, or `watch`, or smth) event is enough, because otherwise you just end up subscribing the same method to three events (and then obviously you need to `off()` it three times as well, if you're implementing the full lifecycle).

Sure, it's just a couple of extra lines of code, so a really minor feature, but still worth considering?

**Comment by brendandburns** [comment]
I'm ok with an `on('change', () => { })` being implemented in the informer.
