### ISSUE TITLE
Unable to run the docs

### ISSUE THREAD

**Issue by bhavelyn** [kubernetes-client/javascript#618]
**Describe the bug**
When I try to run `npm run docs` I get the following error:

```
Error: Tried to set an option (mode) that was not declared.
npm ERR! code 1
npm ERR! path /home/xxx/work/kubernetes-js-client
npm ERR! command failed
npm ERR! command sh -c typedoc src/gen/api

npm ERR! A complete log of this run can be found in:

```

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**
1. Clone the repo
2. npm install
3. npm run generate
4. npm run docs

**Expected behavior**
Docs to be generated

** Example Code**
N/A

**Environment (please complete the following information):**
 - OS: Ubuntu
 - NodeJS Version: 15.2.1 (also tried with v12.16.1 and v10.22.0)
 - Cloud runtime: NA

**Additional context**

**Comment by bhavelyn** [comment]
Is there Documentation some place else or hosted ?

**Comment by bhavelyn** [comment]
Locally going back to typedocs@0.19.2 fixed it for me.

looks like this broke it - https://github.com/kubernetes-client/javascript/commit/2b8f1ab7f139d8821d80b93ab20e3d439031a886#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R99


Or may be my node version OR TS version is not compatible.

**Comment by brendandburns** [comment]
fwiw, the docs are generated and not super useful.

There are a bunch of examples here:
https://github.com/kubernetes-client/javascript/tree/master/examples

And the general Kubernetes API docs here:
https://kubernetes.io/docs/reference/

**Comment by amino19** [comment]
@brendandburns  Is this issue configured?

![Screenshot from 2021-06-01 16-48-58](https://user-images.githubusercontent.com/75872316/120315258-c6082580-c2f9-11eb-928c-01ff2a10d85e.png)

I get this...
