### ISSUE TITLE
How to do a deployment `rollout restart`

### ISSUE THREAD

**Issue by younes-io** [kubernetes-client/javascript#621]
I'd like to do a `rollout restart` using this library, but I can't find the relevant API :

`kubectl rollout restart deployment/myApp`

Could you please help? 

P.S : I'd like to avoid the scaling to 0 and then to N.

**Comment by brendandburns** [comment]
Rollback is a fairly complex operation on the client side. You can find the code for it here:

https://github.com/kubernetes/kubectl/blob/master/pkg/polymorphichelpers/rollback.go#L99

If you do happen to implement that in TypeScript, we'd gladly take a PR to add that support to this library.

**Comment by younes-io** [comment]
@brendanburns : I actually need to do a restart, not a rollback

**Comment by brendandburns** [comment]
Ah, sorry, in that case the code is here:

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/rollout/rollout_restart.go#L159

**Comment by brendandburns** [comment]
Closing this since the question is answered. Please open a new issue if you need further assistance.
