### ISSUE TITLE
How to use list operations with watch=true returning streams

### ISSUE THREAD

**Issue by rafagsiqueira** [kubernetes-client/javascript#622]
**Describe the bug**
Since according to kubernetes api, watch operations will be deprecated in favour of using list operations with watch=true, how do we use the api methods with streams?

**Client Version**
`0.14.0`

**Server Version**
`1.19.6`

**To Reproduce**
```
const api = this.kc.makeApiClient(CoreV1Api) as CoreV1Api;
const stream = api.listNamespacedService('application', _pretty, _allowWatchBookmarks, _continue, _fieldSelector, _labelSelector, serviceLimit, _resourceVersion, _resourceVersionMatch, timeoutSeconds, true);
stream.on('data') {}
```
Property 'on' does not exist on type 'Promise<{ response: IncomingMessage; body: V1ServiceList; }>'.

**Expected behavior**
The returned object should be a stream when using watch=true

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: v14.7.0
 - Cloud runtime: Kubernetes

**Comment by brendandburns** [comment]
This code is generated and the swagger codegen doesn't understand the semantics of watch/streams.

The right way to do this is to use the watch class:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts#L7

Under the hood, that already sets the watch query param to `true`:
https://github.com/kubernetes-client/javascript/blob/master/src/watch.ts#L89
