### ISSUE TITLE
Dependencie net-keepalive does not support win32

### ISSUE THREAD

**Issue by eduardocp** [kubernetes-client/javascript#632]
**Describe the bug**
Dependencie `net-keepalive` does not support win32

**Client Version**
0.14.2

**To Reproduce**
In Windows:
yarn add @kubernetes/client-node

**Expected behavior**
Package successfully add

**Current behavior**
Error on fetching packages
![image](https://user-images.githubusercontent.com/1816859/114062596-11f49c00-986e-11eb-98b6-79cb63c62abe.png)

**Comment by bacongobbler** [comment]
Hey thanks for reaching out.

Good catch with this one. I wonder if it is possible to selectively disable the tcp keepalive probe header on non-unix systems, as that's how Go provides this functionality.

From https://golang.org/pkg/net/ (emphasis bold):

> // KeepAlive specifies the interval between keep-alive
    // probes for an active network connection.
    // If zero, keep-alive probes are sent with a default value
    // (currently 15 seconds), **if supported by the protocol and operating
    // system.** Network protocols or operating systems that do
    // not support keep-alives ignore this field.
    // If negative, keep-alive probes are disabled.

**Comment by bacongobbler** [comment]
Alternatively, it does appear the net-keepalive maintainers are welcome to PRs to provide windows support. So another option would be to perform a no-op pointing to Go's pkg/net implementation as reference.

**Comment by dominykas** [comment]
I'm seeing an error on Linux as well:

```
07:21:22 AssertionError [ERR_ASSERTION]: Unable to get socket fd
07:21:22     at _getSocketFD (/mnt/project/node_modules/net-keepalive/lib/index.js:31:3)
07:21:22     at Object.setKeepAliveInterval (/mnt/project/node_modules/net-keepalive/lib/index.js:73:14)
07:21:22     at Request.<anonymous> (/mnt/project/node_modules/@kubernetes/client-node/dist/watch.js:82:27)
```

**Comment by cebald** [comment]
Hello, I am also seeing this issue with net-keepalive not supporting win64. I was just able to install v0.14.0. Is there a later version that I can use in the meantime where net-keepalive should still work? Thanks for your help.

**Comment by eduardocp** [comment]
> Hello, I am also seeing this issue with net-keepalive not supporting win64. I was just able to install v0.14.0. Is there a later version that I can use in the meantime where net-keepalive should still work? Thanks for your help.
> 
> EDIT: v0.14.1 installed fine as well. v0.14.2 seems to be the first problem 

net-Keepalive was introduced in version 0.14.2. Point to version 0.14.1 and you can use it normally

**Comment by brendandburns** [comment]
Thanks for the report. We'll look into fixing this shortly. In the meantime release `0.14.1` should work for you.

**Comment by bacongobbler** [comment]
Can y’all give #635 a shot and let me know if that fixes the issue for you?

**Comment by cebald** [comment]
Everything seems to have installed just fine, and from my preliminary testing, I'm getting good responses from the API. Thanks so much for the quick fix!
