### ISSUE TITLE
How do I topPods?

### ISSUE THREAD

**Issue by namgk** [kubernetes-client/javascript#633]
Hi there, 

     k8s.topNodes(this.k8sCoreApi);

is a nice API, I'm wondering how do I do a "topPods", like the command:

    kubectl top pods

Thanks

**Comment by brendandburns** [comment]
It's not currently implemented in this library.

There is an equivalent Java implementation here:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTop.java#L150

Which could be ported over to Javascript. We'd happily take a PR for that.
