### ISSUE TITLE
When well Deployments be included in the client?

### ISSUE THREAD

**Issue by joshughes** [kubernetes-client/javascript#636]
Is there a way to use the client to list deploymets? 

If there is not, is there a way we can get deployments included in the client?

**Comment by brendandburns** [comment]
Deployments are already supported by this client (as are all Kubernetes objects since it is generated)

Deployments are in the `apps` API: 
https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/appsV1Api.ts#L2421
