### ISSUE TITLE
Dependency net-keepalive unable to install without python     

### ISSUE THREAD

**Issue by noynir** [kubernetes-client/javascript#637]
**Describe the bug**
The ffi-napi package required by net-keepalive is built with node-gyp which requires python. This breaks on alpine docker images which don't include python      

** Client Version **
0.14.2

**To Reproduce**
Create a node Docker image based on an alpine version and RUN npm install.

**Expected behavior**
stay compatible with alpine images.

**Environment (please complete the following information):**
 - OS: Linux (Alpine)
 
**Additional context**

**Comment by brendandburns** [comment]
This is fixed by #635

**Comment by brendandburns** [comment]
#635 has merged. Closing.
