### ISSUE TITLE
serialize not working well when Array prototype is changed

### ISSUE THREAD

**Issue by dudilugasi** [kubernetes-client/javascript#642]
**Describe the bug**
I added a function to the Array prototype in my app. when running the function createNamespacedJob i'm getting an error that says : 
`"Job.batch \"...\" is invalid: [spec.template.spec.containers[0].ports[1].containerPort: Required value, spec.template.spec.containers[1].name: Required value, spec.template.spec.containers[1].image: Required value, spec.template.spec.tolerations[1].operator: Invalid value: \"\": operator must be Exists when `key` is empty, which means \"match all values and all keys\"]",`

after researching your code i found out that in the serialize function in the file [models.ts](https://github.com/kubernetes-client/javascript/blob/0403427cada5cab3ee7e1e01002cebe4738ae9fb/src/gen/model/models.ts) theres a for...in loop that running on array instead of a for...of loop

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]

**Additional context**

**Comment by brendandburns** [comment]
So this is basically about opt-in vs opt-out serialization.

But I don't think we can/want to support random things being added to basic types like Array.

**Comment by brendandburns** [comment]
Closing in favor of #643
