### ISSUE TITLE
ListWatch with labelSelector

### ISSUE THREAD

**Issue by StefanCenusa** [kubernetes-client/javascript#644]
**Describe the bug**
When using **ListWatch** I couldn't find a way to filter items that are added to the list by label selector.
I've started from [this example](https://github.com/kubernetes-client/javascript/blob/master/examples/cache-example.js).

**Client Version**
`0.14.3`

**Server Version**
`1.18.16`

**To Reproduce**
```
        const watch = new k8s.Watch(kubeConfig);

        const listAllServicesFn = () =>
            this.k8sCoreV1Api.listServiceForAllNamespaces(
                undefined,
                undefined,
                undefined,
                SERVICE_LABEL_SELECTOR
            );
        this.servicesCache = new k8s.ListWatch('/api/v1/services', watch, listAllServicesFn);

        ....
       
        await this.servicesCache.start();

        const services = this.servicesCache.list();
```

Initially, `this.servicesCache.list()` returns items that satisfy the `SERVICE_LABEL_SELECTOR` labelSelector query. However, the watch part (when services are added to the list from ADD, DELETE, MODIFIED etc events) does not apply the same labelSelector, thus the list (cached list of services) becomes populated with services that don't satisfy the `labelSelector` constraint.

**Expected behavior**
The watch component of the ListWatch to apply the labelSelector from the list function, or, at least, give the user some sort of possible configuration option to do that.

**Comment by brendandburns** [comment]
Makes sense. We'd be happy to take a PR to add this or we'll get to it eventually.

**Comment by StefanCenusa** [comment]
@brendanburns Ok, I'll make a PR with the changes.

**Comment by StefanCenusa** [comment]
@brendanburns Any ETA for next releasE?

**Comment by brendandburns** [comment]
I'll try to cut a 0.15.0 release before the end of the week. Apologies for the delay

**Comment by brendandburns** [comment]
@StefanCenusa I just pushed 0.15.0 to npm which contains this fix.
