### ISSUE TITLE
Issue faced using javascript client behind proxy

### ISSUE THREAD

**Issue by flacatus** [kubernetes-client/javascript#648]
**Describe the bug**
Hi!

I'm trying to use javascript behind proxy and I got the following error:
```log
(node:74061) UnhandledPromiseRejectionWarning:  Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 80. If you're sure that your Kubernetes cluster is healthy - you can skip this check

    at ClientRequest.onConnect (/home/flacatusu/WORKSPACE/deploy/testing/proxy/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketOnData (_http_client.js:547:11)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

My proxy environments which I use to deploy also minikube:
```
HTTP_PROXY=http://192.168.1.149:80
HTTPS_PROXY=http://192.168.1.149:80
NO_PROXY=localhost,127.0.0.1,192.168.99.0/24,192.168.39.0/24,192.168.49.0/24,10.96.0.0/12,192.168.1.0/32,192.168.49.2,192.168.49.2
```

It  is there a way to specify to k8s javascript client to use PROXY environments?

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**
- Configure Squid
- Install minikube using proxy env
- Create a simple application with javascript client
- Run the nodejs code and will receive the error described
**Expected behavior**

** Example Code**
```javascript
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

k8sApi.listNamespacedPod('default').then((res) => {
    console.log(res.body);
});
```

**Environment (please complete the following information):**
 - OS: [Linux- Fedora 33]
 - NodeJS Version [eg. 14]
 - Squid Proxy
**Additional context**

**Comment by brendandburns** [comment]
this library uses the `request` library, here are the details for configuring a proxy:

https://github.com/request/request/blob/master/README.md#controlling-proxy-behaviour-using-environment-variables

**Comment by brendandburns** [comment]
Closing this issue as I belive it is answered (and no response for > 1 week).

Please use /reopen if you need further assistance.
