### ISSUE TITLE
How to specify a user

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes-client/javascript#649]
when I use 
```
kc.loadFromCluster();
```
to access k8s from a pod inside cluster, how can I specify the user to act as? Up to now I have been using the default role, but now I need to create a role/binding that lets me access nodes from the cluster scope.  I can create the appropriate user, but how do I spec it in this line?

thanks
Brad

**Comment by brendandburns** [comment]
If you are using loadFromCluster (e.g. from inside a pod) then you need to set the serviceAccount on the pod:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
