### ISSUE TITLE
quantityToScalar does not support all of the SI suffixes

### ISSUE THREAD

**Issue by zephyrxvxx7** [kubernetes-client/javascript#653]
**Describe the bug**
In the file `src/utils.ts`, the function `quantityToScalar` does not support all of the Kubernetes canonical quantity.
It just supports "m" and "Ki" SI suffixes. 

**Client Version**
`0.14.3`

**Server Version**
`1.19.3`

**Expected behavior**
Support all of the Kubernetes canonical quantity:
base1024: Ki | Mi | Gi | Ti | Pi | Ei
base1000: n | u | m | "" | k | M | G | T | P | E

**Environment (please complete the following information):**
 - OS: `macOS`
 - NodeJS Version `v16.0.0`

**Additional context**
The official repo [apimachinery](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go) have more detail about it.

**Comment by brendandburns** [comment]
We'd be happy to take a PR to expand that functionality.

**Comment by yash-saini275** [comment]
I was reading [Managing Resources for Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu) and found that Kubernetes doesn't use **n(nano)** and **u(micro)**. So I don't think there is a need to include it in `quantityToScalar` function.

**Comment by yash-saini275** [comment]
Also `const num = parseInt(quantity, 10);
    if (isNaN(num)) {
        throw new Error('Unknown quantity ' + quantity);
    }`

I doubt if this logic is correct or not. Because if we pass a string starting with the alphabetic character to `parseInt` function it returns NaN but if we pass a string starting with the number it returns the number even though the suffix contains random characters.
Example:- 
`parseInt("100asdf") = 100`
`parseInt("asdf1000asdf") = NaN`

**Comment by yash-saini275** [comment]
Hey guys,
I was working on the test cases for this and found that we are using the previous version of typescript which doesn't support ```BigInt```. And the number for ```Ei```, which is ```2^60=1152921504606846976```, But JS Math.pow function returns ```1152921504606847000``` is going beyond the safe limit for JS. 
What should be the approach to solve this?

**Comment by brendandburns** [comment]
This library is using TypeScript 4.1.3 and BigInt was introduced in TS 3.2, so I think we should be able to use BigInt, right?

**Comment by yash-saini275** [comment]
It should not cause the problem but the tsconfig.json targets es6 which is lower than es2020. This is causing the error.

```BigInt literals are not available when targeting lower than ES2020.```

**Comment by brendandburns** [comment]
Ah, thanks for the detail. I think it's fine to move forward to es2020.

--brendan

**Comment by yash-saini275** [comment]
There is a problem with this implementation. BigInt and number cannot be added so if there is a pod specified with these resource requests.
```
pod = {
            spec: {
                containers: [
                    {
                        name: 'foo',
                        resources: {
                            requests: {
                                cpu: '100m',
                                memory: '10Ki',
                            },
                            limits: {
                                cpu: '200m',
                            },
                        },
                    } as V1Container,
                    {
                        name: 'bar',
                        resources: {
                            requests: {
                                cpu: '10Ei',
                            },
                            limits: {
                                memory: '20Ki',
                            },
                        },
                    } as V1Container,
                ] as V1Container[],
            },
        } as V1Pod;
```

Then addition operation cannot be performed on types of BigInt and number because 1 container requests 100m CPU then the function returns a number type and for 10Ei resource request will be a BigInt. So because of the data mismatch addition operation cannot be performed.
