### ISSUE TITLE
ListWatch objects have incorrect field types after update

### ISSUE THREAD

**Issue by milas** [kubernetes-client/javascript#655]
**Describe the bug**
`Watch` does not use the `ObjectSerializer` to parse the body, but instead uses `JSON.parse()`. Per its types, this is fine - the callback is for `apiObj: any`.

On `ListWatch`, this causes problems, however, because it returns `T extends KubernetesObject`. This means that some fields can have the wrong type compared to the corresponding TypeScript model. For example, timestamp fields will be ISO8601 strings instead of `Date`.

N.B. The _initial_ version of all objects is retrieved with the `listFn`, which is expected to come from an API list method, so the initial field types will be correct, and then change for each object once an updated version is seen.

** Client Version **
`0.14.3`

** Server Version **
N/A

**To Reproduce**
1. Create a `ListWatch` for any object type
2. Print out `.metadata.creationTimestamp.constructor.name` for each object from a call to `list()` -> `Date`
3. Change an object
4. In an `on()` handler or subsequent call to `get()`, see that `creationTimestamp` is now a `string`

**Expected behavior**
Objects should be consistently deserialized.

**Environment (please complete the following information):**
 - OS: macOS
 - NodeJS Version: 14.15.4
 - Cloud runtime: N/A

**Additional context**
`JSON.parse` call in `watch.ts`: https://github.com/kubernetes-client/javascript/blob/2aa448fc5dc80ee2ecdda650ccf9c43537c81d0f/src/watch.ts#L121-L128

Perhaps `Watch` should allow passing in an (optional) deserialize method, which could be used by `ListWatch` to use `ObjectSerializer.deserialize` for the correct type.

**Comment by brendandburns** [comment]
Seems like a good idea :) We'd be happy to take a PR for this (or we will get to it eventually)

**Comment by brendandburns** [comment]
I've started working on this. It is trickier than expected because the object serializer expects a Type and we'll need to synthesize that from the api group and kind.
