### ISSUE TITLE
the server could not find the requested resource

### ISSUE THREAD

**Issue by liu-minjie** [kubernetes-client/javascript#659]
**Describe the bug**
```
const network = kc.makeApiClient(k8s.NetworkingV1Api);
network.createNamespacedIngress(namespace, ingress);
// the request data:
ingress.spec.rules[0].http.paths[0].backend = {serviceName: 'xxxx', servicePort: 9000};
```
after  `models_1.ObjectSerializer.serialize(body, "V1Ingress")`
```
localVarRequestOptions.body.spec.rules[0].http.paths[0].backend = {service: undefined, resource: undefined};
```

** Client Version **
0.14.3

** Server Version **
v1.18.8-aliyun.1

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS:  mac 10.14.6
 - NodeJS Version : v12.11.1
 - Cloud runtime aliyun

**Additional context**

**Comment by brendandburns** [comment]
Ingress only became GA (aka V1) in the 1.19 release of Kubernetes. You need to use the V1Beta1 version of the API to talk to a 1.18 cluster.

**Comment by liu-minjie** [comment]
const network = kc.makeApiClient(k8s.ExtensionsV1beta1Api)
