### ISSUE TITLE
Exec with service account token - missing required Host header

### ISSUE THREAD

**Issue by Paxa** [kubernetes-client/javascript#66]
When we use service account (e.g. login in cluster mode) and wanna run exec command, it will override websocket headers with `Authorization: ...`

```js
        this.config.applytoHTTPSOptions(opts);
        const client = new ws.client({ tlsOptions: opts });
```
How it used: 
https://github.com/theturtle32/WebSocket-Node/blob/7a30e3949a2e5b4f7ea701b7959cc8bd030f4c8f/lib/WebSocketClient.js#L236

```js
       for (var key in self.config.tlsOptions) {
           if (self.config.tlsOptions.hasOwnProperty(key)) {
               requestOptions[key] = self.config.tlsOptions[key];
           }
       }
```

As a result, request options will be:
```js
{ agent: false,
  hostname: '11.22.33.44',
  port: '6443',
  method: 'GET',
  path: '/api/v1/namespaces/monitoring/pods/xxx/exec?stdout=true&stderr=true&stdin=true&tty=true&command=sh&command=xxx&container=yyy',
  headers: 
   [ Authorization: 'Bearer aabbccddee...' ],
  ca: <Buffer ... >,
  cert: null,
  key: null }
```
And response will be:
```
Error: Server responded with a non-101 status: 400 Bad Request: missing required Host header
```

### How to reproduce:

Run exec command from in-cluster or use service account in kube config

**Comment by brendandburns** [comment]
@Paxa Yep, I saw this too, and dug through it.

There's a bug in the `websocket` library we depend on.

I sent a PR to fix it here:

https://github.com/theturtle32/WebSocket-Node/pull/323

Please try patching that into your `node_modules` and see if that fixes things?

Thanks!
--brendan

**Comment by cmosgh** [comment]
@brendanburns  I have the same issue. Any directions on how to patch it when I have a multistage dockerfile that builds the container

**Comment by Paxa** [comment]
@cmosgh you can use yarn's [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)

Your package.json should have something like this:
```json
  "resolutions": {
    "@kubernetes/client-node/**/websocket": "https://github.com/brendandburns/WebSocket-Node.git"
  }
```

---

But to get latest version of kubernetes-client is tricky (because it in subfolder and only typescript files)

```json
  "dependencies": {
    "@kubernetes/client-node": "file:./kubernetes-client/node-client",
  },
```

```dockerfile
# docker file
RUN wget https://github.com/kubernetes-client/javascript/archive/master.zip && \
    unzip master.zip && \
    rm -rf kubernetes-client && \
    mv javascript-master kubernetes-client && \
    rm kubernetes-client/node-client/src/swagger.json* && \
    cd kubernetes-client/node-client && \
    yarn install && \
    yarn build && \
    rm -r node_modules && \
    rm -r src && \
    cd /opt/app/
```

**Comment by brendandburns** [comment]
I don't think you need the latest kube-client, the fix was purely in the websockets library I think...

**Comment by Doccrazy** [comment]
Thanks @brendandburns , I was having the same issue and your patch fixed it for me. I simply added
```
ADD https://raw.githubusercontent.com/brendandburns/WebSocket-Node/master/lib/WebSocketClient.js /app/node_modules/websocket/lib/
```
after the `npm install` command to my Dockerfile. Using client version 0.4.0 from npm.

**Comment by cmosgh** [comment]
It does work @Doccrazy 

Lets hope https://github.com/theturtle32/WebSocket-Node/pull/323 will be merged soon so we don't patch this manually. Thank you @brendanburns !

**Comment by brendandburns** [comment]
We moved to isomorphic-ws so I'm going to close this issue. Please re-open if someone hits it again.
