### ISSUE TITLE
ListWatch Connect Event Fires before everything is actually connected 

### ISSUE THREAD

**Issue by joshughes** [kubernetes-client/javascript#664]
Creating a ListWatch I need to know when it is fully ready to go before I start using it. 

https://github.com/kubernetes-client/javascript/blob/ed1e579d189c727937df65897303434e2cd120fc/src/cache.ts#L131

It seems based on the code the CONNECT event is fired before the promise for the listFn and the request for the watch are fully resolved. 

If I am correct then maybe the CONNECT event should fire at the very end of this function?

I realize that this was originally put in to notify on reconnects but it would be useful to know when the ListWatch is 100% ready.

**Comment by brendandburns** [comment]
I guess it is open to interpretation, but I think of "connect" as "starting connection" (which is what this is doing)

What error are you seeing?

**Comment by joshughes** [comment]
I suppose when I create a ListWatch it would be helpful to know when the ListWatch is ready. 

For instance, if I request an object before the cache is fully populated... I will get undefined or null but the same request 100 ms later the cache is populated and I get the correct response. 

So it would be very helpful to know that the ListWatch is `ready` at least in the sense that it has an active watch and the listFn had been executed.

**Comment by brendandburns** [comment]
I could see adding a `ready` event that triggers when the list function has completed. Feel free to send a PR if you would like.

In the meantime, you can just modify your `listFn` to execute your callback after the promise has completed.

e.g.
```typescript
function WrappedListFn(realListFn, myReadyCallback): Promise<T> {
      var result = await realListFn();
      myReadyCallback();
      return result;
}
```

**Comment by joshughes** [comment]
That is a good enough solution for me in the meantime. Thanks for your help.
