### ISSUE TITLE
Patch deployment and wait for rollout status

### ISSUE THREAD

**Issue by franpog859** [kubernetes-client/javascript#669]
Hello! I need an option to patch deployment and wait for the rollout status to be sure that all the new, patched pods are running and the old ones are terminating

I found [an option to patch](https://github.com/kubernetes-client/javascript/pull/508/files#diff-99b4ee24e7c741cb071dac487c0fd336c8abdacafec5028e97119ad79199a68eR1-R23) the deployment using `patchNamespacedDeployment` function. This function does not wait for the rollout status though so there is no option to figure out **if the new pods are already running and the old ones are terminating**. How to check that?

I found quite a similar question [there](https://github.com/kubernetes-client/javascript/issues/515#issuecomment-700429904) but it was closed without an answer that satisfies me 😞

**Comment by brendandburns** [comment]
You have to implement the polling or watch for the rollout to complete yourself.

The wait is a client-side feature of `kubectl` not something in the Kubernetes API.

**Comment by franpog859** [comment]
Thanks! I ended up waiting for the new replica set to be ready and polling for its status until the pods are ready

**Comment by brendandburns** [comment]
Closing since the question is answered.

**Comment by uluzox** [comment]
> Thanks! I ended up waiting for the new replica set to be ready and polling for its status until the pods are ready

@franpog859 would you mind sharing your solution? I have a similar use case.

**Comment by franpog859** [comment]
Sure, @uluzox ! I used it [here](https://github.com/kyma-project/kyma/pull/11152/files#diff-8914614ea3c864baa5176ccd30e4c21a4485fd090ed30f7cb67f3f8112c21942) :D

**Comment by kalahari** [comment]
This is the implementation I cobbled together, it's getting the job done for now:

```TS
    private readonly kubeWatch: () => Watch;

    public async waitForDeployment(
        ns: string,
        deployment: string,
        labels: Record<string, string>,
        timeout = settings.waitForDeploymentTimeout,
    ): Promise<void> {
        const fieldSelector = `metadata.name=${deployment}`;
        const labelSelector = Object.entries(labels)
            .map(([key, value]) => `${key}=${value}`)
            .join(',');

        await new Promise<void>(async (resolve, reject) => {
            const watchRequest = await this.kubeWatch().watch(
                `/apis/apps/v1/namespaces/${encodeURIComponent(ns)}/deployments`,
                {
                    fieldSelector,
                    labelSelector,
                    timeoutSeconds: timeout / 1000,
                },
                (phase: string, apiObj: any, watchObj?: any) => {
                    log.info({ phase, watchObj }, 'watch event');
                    if (['ADDED', 'MODIFIED'].includes(phase) && this.isDeploymentReady(apiObj)) {
                        if (watchRequest) {
                            watchRequest.abort();
                        }
                        resolve();
                    } else if (phase === 'DELETED' || phase === 'ERROR') {
                        if (watchRequest) {
                            watchRequest.abort();
                        }
                        reject(new Error(`deployment ${deployment} ${phase}`));
                    }
                },
                err => {
                    log.info({ err }, 'watch done');
                    if (err) {
                        return reject(err);
                    }
                    resolve();
                },
            );
        });
    }

    private isDeploymentReady(dep: V1Deployment): boolean {
        const status = dep?.status;
        if (status?.availableReplicas == null) {
            throw new Error('missing deployment status availableReplicas');
        }
        if (status?.updatedReplicas == null) {
            throw new Error('missing deployment status updatedReplicas');
        }
        if (dep?.spec?.replicas == null) {
            throw new Error('missing deployment spec replicas');
        }
        if (
            status.availableReplicas >= dep.spec.replicas &&
            status.updatedReplicas >= dep.spec.replicas &&
            (status.unavailableReplicas ?? 0) <= 0
        ) {
            // replica set is healthy
            return true;
        }
        return false;
    }
```

**Comment by WoodyWoodsta** [comment]
Apologies coming from 2023, but this hasn't been the easiest thing to figure out given how low level the JS api is, so hopefully this helps others.

To me it would make more sense to check for changes to the `status.conditions[number].type === 'Progressing'` timestamp to see if the deployment received a status update after the deployment was annotated for the rollout. I haven't tested this yet, but checking updated replica counts can misrepresent the desired rollout if multiple things are interacting with the deployment.
