### ISSUE TITLE
Use async/await in npm distribution to improve stack traces

### ISSUE THREAD

**Issue by Yogu** [kubernetes-client/javascript#671]
Currently, the files in the distributed npm package use `tslib_1.__awaiter` and generator functions instead of `async` / `await`. [Since node version 7.6.0, native async/await is supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#browser_compatibility). Besides readability, native async/await has the advantage that [stack traces contain the asynchronous context](https://v8.dev/docs/stack-trace-api#async-stack-traces). This is very useful when debugging request errors.

The [oldest supported version of node is v12](https://github.com/nodejs/Release#release-schedule), so I'd suggest to use [a `tsconfig.json` that makes use of all the node-v12 features](https://stackoverflow.com/questions/59787574/typescript-tsconfig-settings-for-node-js-12):

```json
{
  "compilerOptions": {
    "lib": ["es2019", "es2020.bigint", "es2020.string", "es2020.symbol.wellknown"],
    "module": "commonjs",
    "target": "es2019"
  }
}
```

Otherwise, targeting ES2017 would be enough to emit native async/await.

(Sorry for removing the issue template; since I'm not reporting a bug and it has nothing to do with kubernetes itself, it didn't seem to fit.)

**Comment by brendandburns** [comment]
#667 updates our typescript settings for a different reason (BigInt support)

Can you check and see if that update will fix this for you too?

Thanks!

**Comment by brendandburns** [comment]
#667 has merged, I believe that this fixes the issue. Please use `/reopen` if you need further assistance.

**Comment by Yogu** [comment]
Didn't see the reply, thanks! 0.15.0 uses native async/await so that's great.
