### ISSUE TITLE
I can't figure out how to get the list* with `watch: true` to work

### ISSUE THREAD

**Issue by justinmchase** [kubernetes-client/javascript#672]
**Describe the bug**
I'm doing this:
```ts
const configmap = await this.core.listNamespacedConfigMap(
  namespaceName,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  1,
  "0",
  undefined,
  undefined,
  true
)
```

But it never returns even as I am updating configmaps on the server. I'm pretty sure I'm doing it wrong but I don't see a clear example of how to utilize this api.

** Client Version **
`0.14.3`

** Server Version **
`1.19.7`

**To Reproduce**
Use the above snippet then just create or delete configmaps in the kube dashboard

**Expected behavior**
I am expecting events of of some kind

** Example Code**
^

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version [eg. 10]
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by brendandburns** [comment]
Watch isn't an API that Swagger/OpenAPI understands, thus that generated call doesn't work the way you expect.

Watch requires some helper code to make it event-driven, etc.

Please see the example here:
https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts
