### ISSUE TITLE
is it possible to Filter deployments pods by labalseselctor 

### ISSUE THREAD

**Issue by johnico** [kubernetes-client/javascript#676]
I am using the following api:  

lustNamespaceDeployments. or pods

and I see that I can send labels a filter but how can I filter deeper like : "apps=pod_name"

now I can use only "apps" as labe selector , i would like to search like call the HTTP request directly

is it possible ?
 thanks

**Comment by brendandburns** [comment]
I'm not sure I understand your request.

Is there a `kubectl` command that is equivalent to the code you are trying to write? If you share that I may be able to point you in the right direction.

**Comment by johnico** [comment]
@brendandburns hi thanks 
yes 
if this is my yaml file:

```
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
```

I can run 
```
kubectl -n="namespace" get deployments -l=stack=pu
```
so it will return only the matched labels

**Comment by brendandburns** [comment]
Use `'app=nginx'` in as the `labelSelector` parameter in the call to `listNamespacedDeployments`

In general, if you want to understand what `kubectl` is doing, just add `--v=10` to the `kubectl` call and it will print all of the HTTP calls that it is making.

**Comment by johnico** [comment]
thanks .works
