### ISSUE TITLE
Generic access to Scale subresource

### ISSUE THREAD

**Issue by tommazzo89** [kubernetes-client/javascript#677]
Hi everyone,

Is there a generic way to access the `autoscaling/v1.Scale` subresource of any kind that that supports it? I found #475, but it explicitly loads a Deployment. However, I'm writing a scaling controller that should support Deployments, StatefulSets, etc., and CRDs that have the Scale subresource.

If this is not supported by `@kubernetes/client-node`, is it maybe possible to issue a REST request that passes through the library to handle authentication, so that I only need to provide the path of the resource?

**Client Version**
`0.14.3`

**Server Version**
`1.20.7`, soon upgrading to `1.21.1`

Best regards,
Thomas

**Comment by brendandburns** [comment]
There's no code in the project that knows how to do this, but there's an example here:

https://github.com/kubernetes-client/javascript/blob/master/src/log.ts#L62

Of how to auth an arbitrary request.

If you do implement access for Scale subresources, we'd be happy to take a PR to add the support.

**Comment by brendandburns** [comment]
Thanks!
