### ISSUE TITLE
Kubernetes Javascript connection to custom API server

### ISSUE THREAD

**Issue by sankarp-kavach** [kubernetes-client/javascript#687]
I have a pod P1 in a kubernetes environment. The kubernetes environment has a second API server. From the Pod P1, I am able to execute the following command:

```
kubectl -s secondAPIServer:8080 get mycrd.example.com -n my-namespace my-name -o json
```

This properly lists a CRD object.

In the Pod P1, I have two containers. A golang container and a typescript container. The golang container has the following code (edited for brevity):

```go
import (
	"k8s.io/client-go/rest"
)

main() {
	conf = &rest.Config{Host: "secondAPIServer:8080"}
        crdClient, err := clientset.NewForConfig(conf) // Does open some connections here to the API server without errors
	if err != nil {
		return nil, nil, fmt.Errorf("can not create kubernetes clientset: %v", err)
	}
}
```

The typescript container has the following code:

```typescript
import * as k8s from '@kubernetes/client-node';

const cluster = {
    name: 'my-server',
    server: 'secondAPIServer:8080',
};

const kc = new k8s.KubeConfig();
kc.loadFromOptions({
    clusters: [cluster],
});

let customObjectsApi: any
try {
    customObjectsApi = kc.makeApiClient(k8s.CustomObjectsApi);
} catch (err) {
    console.error(err);
}
```

Here the `kc.makeAPIClient` causes an exception and prints:
```
Error: No active cluster!
```

What should I do to fix this ? I searched around but could not find anything relevant to this issue myself. I am new to typescript and there may be something that I could be doing wrong. The go code works fine.

**Comment by sankarp-kavach** [comment]
I spent some more time and I was able to get the `makeApiClient` call go through without throwing an exception. But any subsequent operation on the `customObjectsApi` is throwing an error related to certificates, where the network location is read as a file for some strange reason. I am trying to debug the issue. But wanted to make an update here, in case someone can throw some light.

The updated code and the error trace is:
```typescript
        const cluster: k8s.Cluster = {
            name: 'my-server',
            server: 'http://secondAPIServer:8080',
            skipTLSVerify: true,
            caFile: '',
        };

        const kc = new k8s.KubeConfig();
        kc.addCluster(cluster);  // <----- Did the trick
        kc.loadFromCluster('http://secondAPIServer:8080');

        let customObjectsApi: any
        try {
            customObjectsApi = kc.makeApiClient(k8s.CustomObjectsApi);
        } catch (err) {
            console.error(err);
            return;
        }
        

        await customObjectsApi.getNamespacedCustomObject(
            'example.com',
            '',
            'my-namespace',
            'mycrd',
            'my-name',
        ).then((res) => {
            logger.info('customObjectsApi done', res.body);
        }).catch((err) => {
            console.error('err in customObjects', err);      <------ This is getting thrown now
            return;
        });

```

The error that I got now is:

```
err in customObjects Error: ENOENT: no such file or directory, open 'http://secondAPIServer:8080/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
    at Object.openSync (fs.js:451:3)
    at Object.readFileSync (fs.js:353:35)
    at bufferFromFileOrString (/home/mycodebase/node_modules/@kubernetes/client-node/dist/config.js:399:19)
    at KubeConfig.applyHTTPSOptions (/home/mycodebase/node_modules/@kubernetes/client-node/dist/config.js:305:38)
    at KubeConfig.<anonymous> (/home/mycodebase/node_modules/@kubernetes/client-node/dist/config.js:340:18)
    at Generator.next (<anonymous>)
    at /home/mycodebase/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/mycodebase/node_modules/tslib/tslib.js:106:16)
    at KubeConfig.applyOptions (/home/mycodebase/node_modules/@kubernetes/client-node/dist/config.js:339:24)
    at KubeConfig.<anonymous> (/home/mycodebase/node_modules/@kubernetes/client-node/dist/config.js:92:24)
    at Generator.next (<anonymous>)
    at /home/mycodebase/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/mycodebase/node_modules/tslib/tslib.js:106:16)
    at KubeConfig.applyToRequest (/home/mycodebase/node_modules/@kubernetes/client-node/dist/config.js:89:24) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'http://secondAPIServer:8080/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
}
```

**Comment by brendandburns** [comment]
You are passing your server name as a parameter to the `loadFromCluster(pathPrefix: string)` so it is using that string as a prefix.

If you are trying to use this client inside a Pod, you should just call `loadFromCluster()` in most cases, and you should definitely not pass the server URL as a path prefix.

If you are trying to use this client outside a Pod you should use `loadFromOptions(...)` the reason your first `loadFromOptions()` isn't working is because you aren't setting the `currentContext` value.

Look at this example here:
https://github.com/kubernetes-client/javascript/blob/b62230fbd7bdf049a64e8f849ccfe55545db6f49/README.md#create-a-cluster-configuration-programatically

for more details of how to use the `loadFromOptions(...)` function.

**Comment by sankarp-kavach** [comment]
@brendanburns Is it not possible to use the `loadFromOptions` without setting a `currentContext` . The `client-go` and the `kubectl` seem to work fine in my case without setting any extra `auth` information. So I am a bit confused why we need to set a `currentContext` here.   I understand the `pathPrefix` now and I removed it, thanks for the explanation.

**Comment by brendandburns** [comment]
I suppose we could add some defaulting here if things are missing, but I'm not sure I see the utility. Why not just initialize it with a cluster/user/context?

**Comment by sankarp-kavach** [comment]
> Regardless of what the right eventual design is. The current library requires that you specify a server, a user and a context, and then select the current current context. Then it should work correctly.

@brendanburns In my case, the second API server that I am querying does not have any auth at all. In fact if I do just `curl http://secondAPIServer:8080/apis/myCRD` then I am able to get the json correctly. In the `client-go` I am able to get the CRDs without specifying any `auth` information. This `should set up user, context, current-context` is a requirement that is happening only in the typescript client library. This mandate is not existent in the other client libraries. That is why I feel that this should be a bug. We should have some way to skip setting up the auth, user, context etc. and just use the client-node directly.

**Comment by sankarp-kavach** [comment]
I am able to solve the problem by directly using the underlying object, like:
```typescript
customObjectsApi = new k8s.CustomObjectsApi('http://apiserver:8080');
await customObjectsApi.getNamespacedCustomObject(...)
```

The need to mandate the `current-context` is something that we should consider making uniform across all the client imho though :-) Thanks @brendanburns for all the help.

**Comment by brendandburns** [comment]
@sankarp-kavach I agree that the details of how client auth is defined is inconsistent. There's no standard written down for it anywhere. The best we have is here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities

But that doesn't cover this level of detail.

Worth taking a look at someday :)
