### ISSUE TITLE
readNamespacedPodLog just hangs if follow set to true

### ISSUE THREAD

**Issue by hardillb** [kubernetes-client/javascript#689]
**Describe the bug**
Trying to tail logs with `readNamespacedPodLog` never returns it's promise

** Client Version **
v0.15.0

** Server Version **
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.11-34+dbfb3a2003fa8d", GitCommit:"dbfb3a2003fa8dc6661ba29a533e645922978b0f", GitTreeState:"clean", BuildDate:"2021-06-11T05:27:21Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/arm64"}

**To Reproduce**

Set up a client and try and tail the logs from an existing pod using the example code supplied

**Expected behavior**
I expect the 50 lines of previous logs to be received and then be able to read any new logs written.

**Example Code**

```
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig()
kc.loadFromDefault()
const k8sApi = kc.makeApiClient(k8s.CoreV1Api)

k8sApi.readNamespacedPodLog('ben', 'default', 'node-red', true, false, undefined, "true", false, undefined, 50, true)
.then(res => {
	console.log(res)
})
.catch(err => {
	console.log(err)
})
```

**Environment (please complete the following information):**
 - OS: Linux (Rasbian/Debian 10/buster)
 - NodeJS Version v12.22..1

**Additional context**
Trying to migrate from the Godady library and looking for feature parity given it appears to have stopped being worked on since announcing the merge with this project.

#110 looks to have timed out and been closed without a obvious solution.

**Comment by brendandburns** [comment]
Log with follow isn't an API that the OpenAPI generated client understands. The generated client only understands RESTful semantics (which log doesn't follow).

Please use the custom code here instead:
https://github.com/kubernetes-client/javascript/blob/master/src/log.ts#L54

**Comment by hardillb** [comment]
OK,

But this is going to keep coming up while the doc for `readNamespacePodLog` implies it's possible.

I assume that the doc is also auto generated from the OpenAPI spec so at some point there either needs to be a change to the code generator build a client that supports streaming or the doc generator to add a note about this edge case.

**Comment by hardillb** [comment]
Also adding some example code for the new Log class would go a LONG way to working round the problem because I assume the first thing most people will do when it just hangs will be to go look for an example to copy/

**Comment by brendandburns** [comment]
The truth is that this is a disconnect between the OpenAPI spec describing what a parameter like `follow` does and the code generation libraries implementation (which assumes that an API will terminate the TCP stream, not leave it hanging open like the server does when `follow` is true)

It's pretty hard to see what the right answer is here, since the docs are general (in the OpenAPI schema) but the behavior is client-specific.

Adding an example seems to be the right compromise (and possible a FAQ too).

Thanks for sending the PR.

**Comment by brendandburns** [comment]
I'm going to close this, since the example has merged, the question is answered, and I don't think we'll take any more action here.

Please use the `/reopen` command if you need to reopen for any reason.
