### ISSUE TITLE
how can I healthcheck / ping the api ?

### ISSUE THREAD

**Issue by johnico** [kubernetes-client/javascript#693]
is it possible to call health check API to check that API is running? 
like healthz/ or something similar 
did not fine in the api docs

**Comment by brendandburns** [comment]
The endpoints are there:

https://kubernetes.io/docs/reference/using-api/health-checks/#api-endpoints-for-health

But there's no current client support for accessing them, you would need to craft/auth your own request, similar to the code here:
https://github.com/kubernetes-client/javascript/blob/master/src/log.ts#L62

If you do write the code to do that, we'd be happy to take it as a PR (e..g `health.ts`)

**Comment by feloy** [comment]
@brendandburns I would like to reopen this issue as I would like to propose a patch for it.

I have a few questions about the deprecated endpoint healthz) and its replacements /livez and /readyz:

- On which version of Kubernetes API the /livez and /readyz have been introduced?
- Do we want to fallback on the /healthz if we get a 404 on these endpoints? Either internally, or send a specific error (for the developer/user) indicating that the endpoint is not supported for the cluster and the /healthz one should be used instead?
