### ISSUE TITLE
docs: proposal to host autogenerated docs

### ISSUE THREAD

**Issue by mattxwang** [kubernetes-client/javascript#697]
Hi! First of all, really appreciate this library, I'm already finding it very useful - and appreciate the work that goes into this.

I know there's been some discussion already around hosted docs (a quick search gives me #618, #594, #485, #133, #128, #15), and the general response is that they're not that useful/it would make more sense to refer to the [API Reference](https://kubernetes.io/docs/reference/) or [the code examples](https://github.com/kubernetes-client/javascript/tree/master/examples), which are both reasonable requests.

However, I think it still might be useful to have a copy floating around - as a developer using the library, it's a bit easier for me to read the generated docs rather than to just use the GitHub search bar. And, for other users with similar use-cases, they won't have to clone + `npm install & npm run docs` to peek at the documentation.

With that in mind, is it possible to deploy a copy of the docs somewhere online? I know that we likely want as minimal load + to keep them as up to date as possible, so I'm thinking something like:

1. write a GitHub Action that auto-runs `npm run docs` on push to `master`, and deploys it to a static host of our choice (ex GitHub Pages, Netlify, etc.)
2. note somewhere on the generated site and in the README:
     1. the API reference and code examples make good documentation
     2. the current docs are not particularly great, and community contribution is always helpful
     3. the current live version of the docs

I'm more than happy to take up some of this work!

Very open to suggestions of course, and I'm still new to the Kubernetes ecosystem in general, so more perspective is great!

**Comment by brendandburns** [comment]
If you wanted to take on writing a PR that helped us manage this, we'd be happy to take the addition.

Thanks!

**Comment by brendandburns** [comment]
Closing this issue as the docs are now hosted:

https://kubernetes-client.github.io/javascript/

**Comment by mattxwang** [comment]
Hi @brendandburns, I think there's one more step to hosting the docs; bumping what I mentioned in the PR, 

>  I'm not sure if the GitHub pages host is pointing to the right branch - https://kubernetes-client.github.io/javascript/ looks like it's just hosting the README currently, while https://mattxwang.github.io/javascript/ has the rest of the Typedoc UI (i.e. search bar, classes on the right, etc.) - would you be able to check that GitHub Pages is pointed at `gh-pages` when you have a chance?
