### ISSUE TITLE
OOM caused by exec cmd in container

### ISSUE THREAD

**Issue by love477** [kubernetes-client/javascript#699]
**Describe the bug**
I want exec cmd in container, so use exec like example exec-example.ts: 
```
import * as k8s from '@kubernetes/client-node';
import * as stream from 'stream';

const command = process.argv[2];

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const exec = new k8s.Exec(kc);
exec.exec('default', 'nginx-4217019353-9gl4s', 'nginx', command,
    process.stdout as stream.Writable, process.stderr as stream.Writable, process.stdin as stream.Readable,
    true /* tty */,
    (status: k8s.V1Status) => {
        // tslint:disable-next-line:no-console
        console.log('Exited with status:');
        // tslint:disable-next-line:no-console
        console.log(JSON.stringify(status, null, 2));
    });
```
I've analyzed the problem， mainly due to the global variable in process: stdin，so I use custome readable stream instead of process.stdin. I think, there are the same problems if you use process.stdout or process.stderr  as parameter for exec function.

** Client Version **
0.13.2

** Server Version **
1.20.2

**Comment by brendandburns** [comment]
This is just example code, so it is not intended to be production quality, and it works for a quick example.

I'm not sure there is anything to fix here. Closing this issue. Please use the `/reopen` command and provide more details (or file a new issue) if there is anything further that we should do here.

**Comment by Jenniferyingni** [comment]
Hi, I met the same problem. Did you find the solution in your project?
@love477
