### ISSUE TITLE
[feature request] Support GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by mansona** [kubernetes-client/javascript#700]
In https://github.com/kubernetes-client/javascript/issues/623#issuecomment-810653868 you mention that `The current GCP authentication doesn't support that environment variable (GOOGLE_APPLICATION_CREDENTIALS)` and that you wouldn't mind a PR. 

I'm opening this PR to keep track of the feature request and maybe to open up the discussion on how to achieve this. I'm happy to take a crack at it but I really don't have a clue where to start and would love a few pointers 👍

**Comment by brendandburns** [comment]
The current GCP auth is here:

https://github.com/kubernetes-client/javascript/blob/master/src/cloud_auth.ts#L21

The right thing to do is probably to break GCP out into it's own file (that authenticator supports both Azure and GCP currently) and create a `gcp_auth.ts` update the registrations, etc.

Then you will need to figure out the right implementation of the authenticator interface.

**Comment by mansona** [comment]
So I did a minimal amount of work on this yesterday just to check to see if you were happy with the direction. I noticed that there weren't any tests for the cloudauth class so I copied some of the basic tests from `oicd_auth_test.ts` to at least get this process started.

I could do with some guidance on the testing front, even just giving me some pointers on things to test. I am not all that familiar with k8s authentication methods so I don't know if the placeholder tests that I copied from `oicd_auth_test.ts` apply to either GCP or Azure 🤔

**Comment by brendandburns** [comment]
There are a bunch of tests for the cloud provider in `config_test.ts` for historic reasons
e.g. https://github.com/kubernetes-client/javascript/blob/master/src/config_test.ts#L622

If you split out all of the tests with `'azure'` in them into `gcp/azue_test.ts` and take them out of `config_test.ts` that's probably the best bet.

Thanks!
