### ISSUE TITLE
How to wait for the kube.exec executed command to be finished (and not just to be started)?

### ISSUE THREAD

**Issue by san-ouadghiri** [kubernetes-client/javascript#704]
I'm using exec to purge a DB.
I want the DB to be effectively purged before moving on to any other action.

**Describe the bug**
Today I sometimes move on with my code before exec is done (sql command is initiated but not finished).

** Client Version **
e.g. `0.14.3`

** Current code**
```
async clearAll(){
      const sqlCommand = (user:string, pass:string) => {return [hereMyCommandUsingUserAndPass]}
      const sqlAppName = mySqlAppName
      const namespace = myNamespace
      const podName = myPodName

      await exec.exec(
            namespace,
            podName,
            sqlAppName,
            sqlCommand,
            process.stdout as stream.Writable,
            process.stderr as stream.Writable,
            process.stdin as stream.Readable,
            true /* tty */,
             (status: k8s.V1Status) => {
              if (status.status !== 'Success') {
                console.log(JSON.stringify(status, null, 2))
                throw new Error('Call failed')
              }
            }
        )
      return console.log(`DONE`)
    }

```

And somewhere

```
clearAll().then(() => {
    console.log('HEY')
  })

```

This works fine in the sense that it does initiate the sql command.
But I will get:
 (logs before)
 DONE
 HEY
 k8s stdout, so my sql outcome (ex (36 rows affected))

The issue I have is that IRL 'Hey' are actions that should not be performed before the sql call is finished.
Thus I should always get k8s stdout (36 rows affected) and DONE around each other, and then 'Hey' after those guys.

Could you help me? I tried several approaches but none looks successful so far.

**Comment by brendandburns** [comment]
`exec` returns a promise that contains the WebSocket for the connection.

What you are awaiting is not the completing of the connection, but the initiation of the connection.

you will need to wait on the `onclose(...)` of that web socket to wait for the completion of your command.

**Comment by san-ouadghiri** [comment]
Hi @brendanburns 
Thanks for the feedback. I was starting to look at how to check for process.stdout and I was not liking where I was going.
I'm sadly not that familair with Web socket in general. But I'll give it a try. If you have code snippet I'll also look into it.

I'll let you know if I succeed!

**Comment by san-ouadghiri** [comment]
That works :) !

**Comment by san-ouadghiri** [comment]
If someone wonder, it gives something like

```
async clearAll(): Promise<null> {
      const sqlCommand = (user:string, pass:string) => {return [hereMyCommandUsingUserAndPass]}
      const sqlAppName = mySqlAppName
      const namespace = myNamespace
      const podName = myPodName

      await exec.exec(
            namespace,
            podName,
            sqlAppName,
            sqlCommand,
            process.stdout as stream.Writable,
            process.stderr as stream.Writable,
            process.stdin as stream.Readable,
            true /* tty */,
             (status: k8s.V1Status) => {
              if (status.status !== 'Success') {
                console.log(JSON.stringify(status, null, 2))
                throw new Error('Call failed')
              }
            })
        return new Promise<void>((resolve) => {
           websocket.onclose = function () {
           resolve()
        }
     })
    }
```
