### ISSUE TITLE
Could you do a new release to fix vulnerabilities?

### ISSUE THREAD

**Issue by ivanstanev** [kubernetes-client/javascript#707]
Hey there, could you please release a new `npmjs` version? I see that yesterday a dependabot PR was merged that may be resolving some vulnerabilities.

Currently we cannot release some of our services because we have an explicit CI/CD check for new vulns:

```shell
$ snyk test
...
found 2 issues, 2 vulnerable paths.


Issues with no direct upgrade or patch:
  ✗ Arbitrary File Overwrite [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1536528] in tar@6.1.0
    introduced by @kubernetes/client-node@0.15.0 > tar@6.1.0
  This issue was fixed in versions: 3.2.3, 4.4.15, 5.0.7, 6.1.2
  ✗ Arbitrary File Overwrite [High Severity][https://snyk.io/vuln/SNYK-JS-TAR-1536531] in tar@6.1.0
    introduced by @kubernetes/client-node@0.15.0 > tar@6.1.0
  This issue was fixed in versions: 3.2.2, 4.4.14, 5.0.6, 6.1.1
```

Thank you!

**Comment by brendandburns** [comment]
I'll see what I can do in the next week or so. fwiw, this security issue only affects you if you use the `cp.ts` code to copy files to/from a Pod.

**Comment by brendandburns** [comment]
Apologies for the delay, I just pushed `0.15.1` to `npm`
