### ISSUE TITLE
Exec api can leak connections which prevents the calling client process from exiting

### ISSUE THREAD

**Issue by justinmchase** [kubernetes-client/javascript#713]
**Describe the bug**
When using the `exec` api to a container, if the client experiences a timeout then its connection is leaked, which prevents the client process from exiting cleanly.

** Client Version **
`0.14.0`

** Server Version **
`1.20.7`

**To Reproduce**
Its very hard to reproduce as the issue only occurs when using the Exec api and only when it experiences a timeout which is very rare but over a large number of calls it is happening approximately once a day for us. There is no practical reason why it should timeout but occasionally does. We handle the error and try again and the second call succeeds but then the process does not exit.

**Expected behavior**
I expect the process to exit cleanly after the promise is caught.

** Example Code**
```ts
try {
  const command = ["sh", "-c", "kill -s TERM 1"]
  const exec = new Exec(client)
  await exec.exec(
    namespace,
    podName,
    container.name,
    command,
    process.stdout,
    process.stderr,
    process.stdin,
    false
   )
} catch (err) {
  const { name, code, message, stack, ...more } = err
  console.log(`ERR ${JSON.stringify({ name, code, message, stack, ...more })}`)
  if (code === 'ETIMEDOUT') {
    // If this error is caught, the process will not exit
    // it seems like there is a leaked resource which keeps nodes event loop alive forever
  }
}

console.log('done.')
// The process exits cleanly here if there is no timeout...
```

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: 14
 - Cloud runtime: Docker container in internally hosted kubernetes

**Additional context**
As a workaround we will add `process.exit(0)` to ensure the process exits but this isn't always possible to do, we want to make sure there are no leaks in this library still.

**Comment by brendandburns** [comment]
When you say `process` you're referring to the nodejs process correct? Not the process that is running via `exec` in the container?

**Comment by justinmchase** [comment]
Correct, the calling application's event loop doesn't end as expected. I'm actually not aware of what is happening in the container, it could also leak but this ticket is not reporting that issue if it exists.

**Comment by justinmchase** [comment]
I believe its leaking event handles in the event loop.

The workaround is to add an explicit `process.exit(0)` call when the function ends.
