### ISSUE TITLE
How do we get the children job statuses from the parent cron job?

### ISSUE THREAD

**Issue by HirokoMatsumoto-novade** [kubernetes-client/javascript#715]
Hi, I'm making jobs from main orchestrator cron job that is referenced below.
https://github.com/kubernetes-client/javascript/blob/master/examples/in-cluster-create-job-from-cronjob.js

However, how do we get to know those jobs statuses?
If it's possible, I'd like to know the statuses asyncronus method. (looks like 'kubectl wait' https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait)
But I can't find out this kind of Rest API from https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/ and this repo.

Or do we have only solution is that 'readNamespacedJobStatus' to know the job status?
https://github.com/kubernetes-client/javascript/blob/681af0941f306a1f6ac6a4d7622a5901c5ebb0e3/src/gen/api/batchV1Api.ts#L1968

Thank you so much.

**Comment by brendandburns** [comment]
You probably want to use the `watch` API, there is an example of how to do this here:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/watch/watch-example.ts

**Comment by HirokoMatsumoto-novade** [comment]
Thank you, brendandburns! I couldn't notice this function. Let me take a look.
