### ISSUE TITLE
TypeError: Cannot read property 'signals' of undefined

### ISSUE THREAD

**Issue by PKUFlyingPig** [kubernetes-client/javascript#717]
I want to use the API in a React project, but I import the "@kubernetes/client-node" package, my website saw an error below:
![image](https://user-images.githubusercontent.com/60659728/132683664-dd1e28b5-62de-40a7-985d-432c387735f4.png)
My code only contains one line related to kubernetes-client package :
```
import { KubeConfig } from '@kubernetes/client-node';
```
I also tried 
```
const k8s = require('@kubernetes/client-node');
``` 
but encounter the same error.

**Comment by brendandburns** [comment]
Where are you running this? typically React is in the browser, but this library only works in node.js, so unless this is in electron, I don't think that this is a supported use case (right now)

I'm also really not sure that this error is related to this client SDK at all, since normalizeSignal isn't a function in this library afaik.

**Comment by PKUFlyingPig** [comment]
Sorry I am a fresher to frontend application. I created a React project and used npm to install this package into my node_module. There is a button which is a react component in my UI, and click it will trigger a function to create a k8s client to communicate with the cluster (by the way, my UI will be employed as a pod in my cluster). But in my development environment,   when I call  yarn start which will web pack my whole project and launch a local website, then this error occurred. Do you have any clue about where I did wrong ?

**Comment by brendandburns** [comment]
Really not sure, but this client won't run correctly in the browser and it seems like you are running the code in the browser?

**Comment by PKUFlyingPig** [comment]
Thanks, I ran the code in the browser, sorry for my silly mistake ~
