### ISSUE TITLE
Help: get Kubernetes server version

### ISSUE THREAD

**Issue by tomkivlin** [kubernetes-client/javascript#724]
I see the steps found in #293 are no longer relevant (at least, I can't work it out from [the docs](https://kubernetes-client.github.io/javascript/index.html)). 

Is there a way to get the Kubernetes server version, in the same way that you might with `kubectl version`?

I have got the version of each node using the following but not sure if that's the best / a good way of doing it. 

```
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

k8sApi.listNode().then((res) => {
    res.body.items.forEach(element => console.log(element.status.nodeInfo.kubeletVersion));
});
```

**Comment by brendandburns** [comment]
There's no built in client support for this, you'll need to make the call yourself as a 'raw' call.

There's an example of how to do this (with auth and everything else) here:
https://github.com/kubernetes-client/javascript/blob/master/examples/raw-example.js

The path you want is `/version`

**Comment by tomkivlin** [comment]
Ah nice, thanks @brendandburns appreciate the pointer.

**Comment by tomkivlin** [comment]
In digging around trying to work out where to add this feature, I found the VersionAPI is already included, with `getCode` being the method I needed all along:

```js
const k8s = require('@kubernetes/client-node')
const kc = new k8s.KubeConfig()
kc.loadFromDefault()
const k8sVersionAPI = kc.makeApiClient(k8s.VersionApi)

k8sVersionAPI.getCode().then((res) => {
    console.log(res.body)
})
```

This results in what I was after:

```
VersionInfo {
  buildDate: '2021-09-15T21:32:41Z',
  compiler: 'gc',
  gitCommit: '8b5a19147530eaac9476b0ab82980b4088bbc1b2',
  gitTreeState: 'clean',
  gitVersion: 'v1.22.2',
  goVersion: 'go1.16.8',
  major: '1',
  minor: '22',
  platform: 'linux/amd64'
}
```
