### ISSUE TITLE
Creating Informers for Custom Objects

### ISSUE THREAD

**Issue by ccravens** [kubernetes-client/javascript#730]
I need to create informers for custom objects (objects based on a custom resource definition). I deploy a custom object like this:
```typescript
      await K8sApi.k8s<CustomObjectsApi>(K8sClientType.CUSTOM_OBJECTS_API).createNamespacedCustomObject(
        group,
        version,
        namespace,
        plural,
        manifest
      );
```

I'm currently creating informers using a "listForAllNamespaces" method for Deployments, StatefulSets, etc like this:

```typescript
K8sApi.createInformer<V1Deployment, V1DeploymentList>(`/apis/apps/v1/deployments`, informer, () =>
      K8sApi.k8s<AppsV1Api>(K8sClientType.APPS_V1_API).listDeploymentForAllNamespaces(
        true,
        null,
        null,
        'informer-label=true'
      )
    );
```

but it doesn't look like there's a `listCustomObjectForAllNamespaces` implementation. I only see the following list methods for custom objects:
- `listClusterCustomObject` - which means the object is deployed at the cluster level
- `listNamespacedCustomObject` - which requires me to specify a namespace per informer

I think what I need is a `listCustomObjectForAllNamespaces` which doesn't seem to exist? Is this something that needs to be implemented?

Thanks!

**Comment by brendandburns** [comment]
Ah, ok cool because that openapi spec is hand crafted, looks like there may be naming inconsistencies with the rest of the APIs
