### ISSUE TITLE
makeApiClient has deps on external service

### ISSUE THREAD

**Issue by Morriz** [kubernetes-client/javascript#744]
**Describe the bug**

Our tests are not able to mock any of the provided api clients, as there seems to be code running that wants to connect to a cluster:
```
Error: No active cluster!
```

** Client Version **
`0.12.3`

**To Reproduce**

```ts
const kc = new KubeConfig()
kc.loadFromDefault()
const k8sCoreClient = (): CoreV1Api => kc.makeApiClient(CoreV1Api)
```
Observe the error. 

**Expected behavior**

The instantiation of an api client not to have deps on any service. If any method relies on server connectivity, that should be expected to be available. No premature checking should happen.

**Environment (please complete the following information):**
 - OS: MacOS Monterey
 - NodeJS Version: 16

**Additional context**

**Comment by brendandburns** [comment]
@Morriz 
This error isn't caused by trying to reach a cluster. Instead it is caused because the KubeConfig that is being loaded doesn't have an active cluster selected:

https://github.com/kubernetes-client/javascript/blob/1adb9a7eeb6c5c80d5d8b38d7f2b77787b4564dc/src/config.ts#L354

Because there is no cluster selected, there is no way for us to know where the client should talk to, so I think that is a legitimate error to throw.

The solution is just to make sure that `kc.getCurrentCluster()` returns a non-null value.

**Comment by Morriz** [comment]
But why would this dependency on files be needed? IMO the client should just be instantiated and only check deps when operations are performed. And if it can't find it it should still pass as "in-cluster mode" where no kubeconfig file exists and 127.0.0.1 is used to target the api? 

I was able to wrap and stub the client to circumvent this, but like I said something feels not right about this as it is now.

**Comment by brendandburns** [comment]
If you don't have a `$KUBECONFIG` or `$HOME/.kube/config` present in the environment, then the code above should definitely work. (e.g. the default `localhost` config) If it doesn't that's a bug and we should fix it.

Regarding when to throw the exception, that's a philosophical debate I guess. When you call `makeAPI` you're asking the code to make you something. If the code knows it won't work, should it tell you when you try to make it? Or should it tell you when you try to use it?

I'd personally prefer errors earlier (and in setup) versus later. I agree that this in some cases makes mocking harder, but I would rather make the mainline use of the code better at the expense of mocks being somewhat more complicated, vs making mocks easier at the cost of making errors harder/more complicated to catch.

**Comment by Morriz** [comment]
Ok, thanks for the elaborate response. I will close this as we worked around it as well.
