### ISSUE TITLE
Errors from k8s api lost during object deserialization

### ISSUE THREAD

**Issue by Dever4eg** [kubernetes-client/javascript#745]
**Describe the bug**

Errors from k8s api lost during object deserialization in BatchV1Api

**Client Version**
e.g. `0.16.1`

**Server Version**
e.g. `1.19.1`

**To Reproduce**

Make request which will return error from k8s api

**Expected behavior**

Error body is present in `error.response.body`

**Example Code**

In this part of BatchV1Api, deserialization should be inside if statement. Because in case of error from Kubernetes API, error body will be mapped to success result object, and helpful info about error will be lost.

<img width="829" alt="Screenshot 2021-11-23 at 18 24 33" src="https://user-images.githubusercontent.com/16056824/143063424-786f32d2-11b5-4ef0-856d-56e30f1e8b99.png">

**Environment (please complete the following information):**
 - OS: Mac OS
 - NodeJS Version 14
 - Cloud runtime: Azure K8S

**Additional context**

Here is an issue in openapi-generator which is used in kubernetes-client
https://github.com/OpenAPITools/openapi-generator/issues/2924

And here is my PR
https://github.com/OpenAPITools/openapi-generator/pull/10940

**Comment by Dever4eg** [comment]
Here is the workaround

```
const deserialize = ObjectSerializer.deserialize;
ObjectSerializer.deserialize = (data: any, type: string) => {
  if (data?.status === 'Failure') {
    return data;
  }
  return deserialize(data, type);
}
````

**Comment by brendandburns** [comment]
@Dever4eg thanks for digging into this!

Once the generator code merges, I will re-generate the client with this fix.
