### ISSUE TITLE
Function listNamespacedDeployment  is not in released in v0.16.1 

### ISSUE THREAD

**Issue by JaLe29** [kubernetes-client/javascript#746]
According to this issue https://github.com/kubernetes-client/javascript/issues/636 `listNamespacedDeployment` already exist in source code, but it's not in published package.

Client Version: 0.16.1 

 Looks like you must publish new version.
 
 Thank you.
 
![image](https://user-images.githubusercontent.com/22296816/143689482-0c35557e-201f-4911-b561-ea55918f0e0d.png)

**Comment by brendandburns** [comment]
I just installed the 0.16.1 library and that function is in `dist/gen/api/appsV1Api.js` 

Are you having trouble using it?

**Comment by JaLe29** [comment]
You are right. I am sorry.

I see, that I must use AppsV1API.

```
	const k8sApi = kc.makeApiClient(k8s.AppsV1Api); 
	k8sApi.listNamespacedDeployment ....
```
