### ISSUE TITLE
findHomeDir should handle Windows home variations similar to the reference Go client

### ISSUE THREAD

**Issue by ericpromislow** [kubernetes-client/javascript#747]
**Describe the bug**
The `findHomeDir` function should support the same environment variables, and in the same priority, as in the kubernetes Go-client (https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/client-go/util/homedir/homedir.go#L31)

** Client Version **
`0.16.1`

** Server Version **
Doesn't matter

**To Reproduce**

This is all for Windows, which has a concept of three different possible environment variables for `HOME` (which we can call `homeish` environment variables: `$HOME`, the combination of `$HOMEDRIVE/$HOMEPATH`, and `$USERPROFILE`) (Note also that I use forward slashes as path separators so we can leave backslashes to escape formatting characters, as the ASCII gods intended many millennia ago).

1. Run a kubernetes client so a `.../.kube/config` file gets created in one of `$HOME`, `$HOMEDRIVE/$HOMEPATH`, or `$USERPROFILE`
2. Shut down the kubernetes client and move the subtree `.kube` to `$USERPROFILE/`
3. Ensure that `$HOME` and/or `$HOMEDRIVE/$HOMEPATH` exist and are in the environment. Verify that neither of these directories contains `.kube/config`.
4. Rerun the kubernetes client.

According to the code, a new `.kube/config` is placed in the `$HOME` directory, and the existing `<OTHER>/.kube/config` file is ignored.

The client should use the existing `$USERPROFILE/.kube/config`

The go-client first returns a home-ish existing directory that contains a `.kube/config` subtree; then it returns a writable home-ish directory; then it settles for sheer existence, and only then does it give up.

Just for fun, the go-client gives the homedrive/homepath priority over userprofile when looking for an existing `.kube/config`, but reverses that priority otherwise. I don't know why. And `HOME` always wins, even though it's not typically used on Windows.

** Example Code**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - NodeJS Version: N/A
 - Cloud runtime: N/A

**Additional context**
We're treating the kubernetes go-client code as a reference, and trying to meet its specs.

**Comment by brendandburns** [comment]
fwiw, the Java client implementation of this is here:

https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L170

None of this behavior is specified anywhere fwiw :) So I'm not surprised that it is inconsistent.

We'll implement this in the Javascript client, but it really deserves a canonical specification somewhere (I guess that is `client-go`'s source code for now)

**Comment by ericpromislow** [comment]
I can have a PR for you within an hour

**Comment by ericpromislow** [comment]
Unfortunately I can't run tests:
`npm run test` - runs no tests, and if I specify a file, I get a typescript/javascript error message:

```$ npm test src/config_test.ts

> @kubernetes/client-node@0.16.1 test
> nyc mocha "src/config_test.ts"


/Users/ericp/git/ericpromislow/kubernetes-client/javascript/src/config_test.ts:1
import { readFileSync } from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

The win32 tests are almost there though. I might have to submit a PR and fix tests via the CI before bothering y'all.

**Comment by brendandburns** [comment]
Go ahead and send the PR.

What version of node/typescript are you running? This is related to this change:

https://github.com/kubernetes-client/javascript/pull/727/commits/ade7dbcc6250777778b59b25b090269e0144e02b

**Comment by brendandburns** [comment]
Closing this since #1032 merged.

**Comment by ericpromislow** [comment]
Just saw https://github.com/kubernetes-client/javascript/issues/747#issuecomment-982212727

Mostly I use v16.9.0 on macos Monterey, but I installed  v12.22.7 and v14.17.6 to test on all three supported versions to work with the CI. What's the issue with change ade7dbc ?
