### ISSUE TITLE
Config: read from Buffer or create from Constructor

### ISSUE THREAD

**Issue by nagapavan** [kubernetes-client/javascript#75]
We have a use-case of loading config params from another Json Object, loaded from persistence layer - as the target cluster is dynamic in our case.  

It would be helpful to have Config read from Buffer or by invoking parameterised constructor:
```javascript
{
  kubernetesPassword: string;
  kubernetesUrl: string;
  kubernetesUserName: string;
  registrySecret: string;
  caCert: string;
  cert: string;
  key: string;
}
```

**Comment by brendandburns** [comment]
Ack, will work on this.
