### ISSUE TITLE
Build and deploy docs action not working

### ISSUE THREAD

**Issue by sorenmat** [kubernetes-client/javascript#758]
**Describe the bug**
Master build seems to be broken. Seems to be related to the fact that ghpages is a protected branch.

** Client Version **
Not relevant 

** Server Version **
Not relevant 

**To Reproduce**
Run the master branch build

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version [eg. 10]
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

Seems to start happening around this commit https://github.com/kubernetes-client/javascript/commit/6b713dc83f494e03845fca194b84e6bfbd86f31c

**Comment by brendandburns** [comment]
What specific break are you seeing?

When I check out a clean repo and run:
```sh
npm install
npm run build
npm run test
```

It works as expected.

**Comment by brendandburns** [comment]
Ah, I see the GH action to deploy the docs doesn't appear to be working.

That doesn't block anything, but I will see about getting it fixed.

**Comment by sorenmat** [comment]
ahh.. yeah sorry for that, the description could be more clear :|
