### ISSUE TITLE
0.16.1 - Wrong Cpu usage metrics

### ISSUE THREAD

**Issue by Fab-z4qx** [kubernetes-client/javascript#763]
**Describe the bug**
Hi, i got some strange value from metrics of CPU Usage with the version 0.16.1.
kube cluster on V-1.21.5 running on GKE. 

Code to reproduce : 
```
const podsStats = await k8s.topPods(this.k8sApi, metricsClient, namespace);
podsStats.flatMap(async (pod) => {
        pod.Containers.forEach((containerUsage) => {
            if (containerUsage.CPUUsage.CurrentUsage > 0 && containerUsage.MemoryUsage.CurrentUsage > 0) {
                console.log('CPUUSAGE', container.CPUUsage.CurrentUsage);
            }
        });
});

```
```
==>
 CPUUsage: CurrentResourceUsage {
    CurrentUsage: 12.6320289,
    RequestTotal: 1,
    LimitTotal: 2
  }

```
The currentUsage is > limit, it's seem's to be impossible.

**Comment by wejendorp** [comment]
There was an off by 10x error for `nano` units in the current release, so maybe it was returned in nanos, showing 1.2 as 12? Just guessing/hoping, since it was just patched awaiting release.

**Comment by brendandburns** [comment]
I just pushed `0.16.2` which contains the fix, can you give that a try?

**Comment by Fab-z4qx** [comment]
Fixed ! Thanks !
