### ISSUE TITLE
Error in file apply-example.ts

### ISSUE THREAD

**Issue by raakeysh** [kubernetes-client/javascript#778]
This method 'KubernetesObjectApi' is not available.

**Comment by brendandburns** [comment]
The object is there:

https://github.com/kubernetes-client/javascript/blob/b8382b6e9878fdbe99546c56f1fe54062e9d6f41/src/object.ts#L43

How are you running this? What version of typescript are you using to compile? What version of the library are you installing?

**Comment by raakeysh** [comment]
Thanks. It is working fine now.
