### ISSUE TITLE
apply example throws HttpError: HTTP request failed

### ISSUE THREAD

**Issue by muka** [kubernetes-client/javascript#782]
Hi,
I am using the example for `apply` for a simple busybox pod and I see the `create` worked. Running again I `read` fails with a `HttpError: HTTP request failed`

Doing the  same with `kubectl apply -f ...` works

Could you help me in debugging? 

Thank you

**Comment by brendandburns** [comment]
We need more details from the error message, e.g HTTP error code, message etc.

**Comment by brendandburns** [comment]
I'm going to close this issue due to lack of response. Please use the `/reopen` command if you want to reopen with more details.
