### ISSUE TITLE
Fails to start on windows with WSL in some cases

### ISSUE THREAD

**Issue by andreas-ateles** [kubernetes-client/javascript#788]
Docker Desktop on Windows with WSL2 fails to start (just hangs without any information) due to this client running:

```sh
wsl.exe bash -ic "printenv KUBECONFIG"
```

This happens in [`loadFromDefault()` in config][1].

I'm guessing that this client does this on start, thus the client itself fails to start.

The problem with the command is that bash is ran in interactive mode (the `-i` flag), while it's run as a non-interactive command/shell.
And anything needing interaction in ones `.bashrc` will just wait and hang since there is no way for the user to interact with it.

**Solution**
The `-i` flag to bash should be removed. As the shell is non-interactive, and should not be flagged as interactive.

**Background**
In my case I'm using [`keychain` to automatically add SSH keys to WSL2][2]. This asks for the key passphrase when bash starts interactively. So it (Docker Desktop in my case) just gets stuck there and is unable to continue. (As a workaround for this it's possible to add a `timeout` to the interactive command to kill it after some time, but it shouldn't be needed in the first place.)

**Version**
[`master`][1]

**Environment:**
 - OS: Windows 10, WSL2
 - NodeJS Version: Docker desktop 4.6.1

[1]: https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L314 
[2]: https://devblogs.microsoft.com/commandline/sharing-ssh-keys-between-windows-and-wsl-2/

**Comment by brendandburns** [comment]
This seems like a reasonable fix, however I'm curious, does this mean that Docker Desktop is using this client library? Or are you trying to run something in Docker Desktop?

Is there a corresponding Docker Desktop issue?

Happy to take a PR to remove the `-i`

**Comment by andreas-ateles** [comment]
> however I'm curious, does this mean that Docker Desktop is using this client library?

When I googled for this command, this repo was the only thing that came up. So I assumed that this was used in/was a part of Docker Desktop. This might be an incorrect assumption and it might just be a coincidence.

> Or are you trying to run something in Docker Desktop?

Not trying to run anything in Docker Desktop, just trying to start it.

> Is there a corresponding Docker Desktop issue?

Not any that I am aware of. I will create one.

Here's a screenshot of the process tree when Docker Desktop is starting and the issue is happening:

![screenshot](https://user-images.githubusercontent.com/19323772/160083890-73243ea2-b8ec-4086-a1c3-84c8b39b8e49.png)
