### ISSUE TITLE
volume snapshot support?

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes-client/javascript#797]
Does your package have support for volumeSnapshots?

I have looked all over and don't see anything.  Do you know of an alternative?

**Comment by Daxcor69** [comment]
ok, so I see that it is a CR.   I can't figure out which API to use to delete the CR.

**Comment by brendandburns** [comment]
For now you will need to use `raw` access to the API there is an example here:

https://github.com/kubernetes-client/javascript/blob/master/examples/raw-example.js

That should help you get started.
