### ISSUE TITLE
Original example throws error while aborting connection.

### ISSUE THREAD

**Issue by sahilrajput03** [kubernetes-client/javascript#801]
**Describe the bug**:

Can't read .abort property of `undefined` while running https://github.com/kubernetes-client/javascript/blob/master/examples/follow-logs.js locally.

**Client Version:**

`^0.16.3`

**Server Version**

`kubectl version` outptut:
```txt
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"2022-03-17T21:14:47Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**To Reproduce**
Steps to reproduce the behavior: Simply run file locally from `https://github.com/kubernetes-client/javascript/blob/master/examples/follow-logs.js`

**Expected behavior**: No error exception.

**Environment:**
 - OS:
```bash
uname -a
Linux arch-os 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux
```
 - NodeJS Version: `v16.13.1`
 - Cloud runtime [e.g. Azure Functions, Lambda]: Locally.

Some images:

![image](https://user-images.githubusercontent.com/31458531/167303370-22cc82bd-d5b3-420b-a696-b0b99fdf4ce3.png)

![image](https://user-images.githubusercontent.com/31458531/167303381-f324b6de-119d-4a74-bf83-52087528e58b.png)

**Comment by brendandburns** [comment]
The example is looking for the logs for a pod named `pod1` with a container named `container` You will need to update the sample code to reference a pod name and a container name that is in your cluster (in the `default` namespace) if you update that it should work.

I will improve the code so that it makes this error more clear.
