### ISSUE TITLE
Issues when using AWS Cluster API

### ISSUE THREAD

**Issue by mstruebing** [kubernetes-client/javascript#811]
**Describe the bug**

The cluster API for AWS uses enums with the same values which only differ in casing for `internet-facing`:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/760e4e7651f46c29bf309607a0b6307570228988/config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml#L139-L147
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/760e4e7651f46c29bf309607a0b6307570228988/config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml#L127-L135

```yaml
  scheme:
    default: internet-facing
    description: Scheme sets the scheme of the load balancer
      (defaults to internet-facing)
    enum:
    - internet-facing
    - Internet-facing
    - internal
      type: string
```

This results in files being created with duplicated identifiers:

```js
export namespace IoXK8sClusterInfrastructureV1alpha3AWSClusterSpecControlPlaneLoadBalancer {
    export enum SchemeEnum {
        InternetFacing = <any> 'internet-facing',
        InternetFacing = <any> 'Internet-facing',
        Internal = <any> 'internal'
    }
}
```

```js
export namespace IoXK8sClusterInfrastructureV1alpha4AWSClusterSpecControlPlaneLoadBalancer {
    export enum SchemeEnum {
        InternetFacing = <any> 'internet-facing',
        InternetFacing = <any> 'Internet-facing',
        Internal = <any> 'internal'
    }
}
```

I got around it with a hacky script for now:

```sh
sed -i.tmp "s/InternetFacing = <any> 'internet-facing',/internetFacing = <any> 'internet-facing',/" src/gen/model/ioXK8sClusterInfrastructureV1alpha4AWSClusterSpecControlPlaneLoadBalancer.ts
rm src/gen/model/ioXK8sClusterInfrastructureV1alpha4AWSClusterSpecControlPlaneLoadBalancer.ts.tmp
sed -i.tmp "s/InternetFacing = <any> 'internet-facing',/internetFacing = <any> 'internet-facing',/" src/gen/model/ioXK8sClusterInfrastructureV1alpha3AWSClusterSpecControlPlaneLoadBalancer.ts
rm src/gen/model/ioXK8sClusterInfrastructureV1alpha3AWSClusterSpecControlPlaneLoadBalancer.ts.tmp
```

** Client Version **
0.16.3

** Server Version **
1.22.7

**To Reproduce**

Try to generate a client with Cluster API AWS CRDs applied.

**Expected behavior**

There should be no duplicated identifier so it is possible to build with `tsc`.

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: OSx
 - NodeJS: 16.14.2

**Comment by brendandburns** [comment]
This is an issue with the openapi generator not with this client. (honestly, I would argue it's an issue w/ the AWS OpenAPI specification, but I digress...)

You can find  the API generator here:
https://github.com/OpenAPITools/openapi-generator
