### ISSUE TITLE
`pod.status.phase` not matching the status returned by standard kubectl cli

### ISSUE THREAD

**Issue by benbonnet** [kubernetes-client/javascript#816]
Getting my hands on the lib, hope I'm not missing the point

**Describe the bug**
kubectl get pods returns the correct status, PENDING, RUNNING, TERMINATING, ContainerCreating, etc...

k8sApi.listNamespacedPod("default"), pod.status.phase only returns **pending** or **running**. that's about it.
For example, a container in a TERMINATING state (returned accurately by kubectl cli) keeps its status.phase value at running when verified via k8sApi

left is via informer, right is kubectl :
<img width="937" alt="Screenshot 2022-06-02 at 07 54 41" src="https://user-images.githubusercontent.com/7711/171562393-4a74acc3-2a5f-4d7a-a9e8-a1fe6d5374a2.png">

**Client Version**
0.16.3

**Server Version**
v1.21.5

**To Reproduce**
compare `kubectl get pods` status with what is by the below "example code"

**Expected behavior**
accurate pod.status.phase

**Example Code**
```
const k8s = require("@kubernetes/client-node");
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
(async() => {
    const req = k8sApi.listNamespacedPod("default");
    req.body.items.map(it => console.log(`${it.metadata.name} : ${it.status.phase}`));
})()
```

**Environment (please complete the following information):**
osx / docker desktop

**Comment by w3ichen** [comment]
@benbonnet were you able to fix this? I'm facing the same issue

**Comment by benbonnet** [comment]
@w3ichen the only thing i can remember is that there was a reason about it; but its been a while sorry
