### ISSUE TITLE
Add a client for the pod read-log endpoint

### ISSUE THREAD

**Issue by dbolkensteyn** [kubernetes-client/javascript#82]
**Command-line:** `kubectl log <pod-name>`
**Documentation:** https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#read-log-pod-v1-core

From what I read so far on https://github.com/kubernetes/kubernetes/pull/13885, the `/log` endpoints only expects `binary.k8s.io` as protocol. Without it (but still sending the `*.channel.k8s.io` ones), a `403 Forbidden` status code is returned.

I'll try to submit a PR for this in the upcoming days, suggestions are welcome.

Right now I'm trying to fit this into `WebSocketHandler`, but there is already a binary handler that expects the first byte of the message to be the channel number, which is not the case for the `/log` endpoint. See https://github.com/kubernetes-client/javascript/blob/master/node-client/src/web-socket-handler.ts#L89-L94

**Comment by chadbr** [comment]
@dbolkensteyn Hey Dinesh -- Can you point me to an example of how to use the Log.log(..) method? I have not been able to figure out how to get something out the of the _stream: Writable_ parameter.

Thanks, Chad

**Comment by dbolkensteyn** [comment]
It's been a while but try something along these lines:
```
const myStream = new stream.Writable({
    write(chunk, encoding, callback) {
      console.log(chunk.toString().trimRight())
      // or do something else more useful to you
      callback()
    }
  })
```

and then pass `myStream` as the argument.

**Comment by chadbr** [comment]
Thanks @dbolkensteyn -- I'm failing to grasp why we would pass a writable stream instead of getting a readable stream from the log function? I'm assuming the function is there to read log streams?

Sorry for the dumb question...

For example, when I call `spawn` - I get an object back with the process streams:

```typescript
    // return this object when stdio option is undefined or not specified
    interface ChildProcessWithoutNullStreams extends ChildProcess {
        stdin: Writable;
        stdout: Readable;
        stderr: Readable;
```

I would have assumed the log function would return something like `stdout: Readable;'? What am I missing?

**Comment by chadbr** [comment]
As a side note -- I think I might have found a small bug?

This function is async / returns a promise, and it's not awaited / then'd? I'm not sure if it matters...

```
        this.config.applyToRequest(requestOptions);
```

https://github.com/kubernetes-client/javascript/blob/9d5757e4757194e4fe93b513ea0b7703ab1c906a/src/log.ts#L78-L79

Sorry for the noise...

**Comment by dbolkensteyn** [comment]
I don't have a good answer to either of your points as my knowledge of TypeScript is limited. Feel free to further investigate and open new issues (and/or PRs).
