### ISSUE TITLE
Installation failed with error message

### ISSUE THREAD

**Issue by lchrennew** [kubernetes-client/javascript#832]
**Describe the bug**
Installation failed with error message: error openid-client@5.1.7: The engine "node" is incompatible with this module. Expected version "^12.19.0 || ^14.15.0 || ^16.13.0". Got "18.0.0"

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: Windows
 - NodeJS Version 18
 - Cloud runtime -

**Additional context**

**Comment by brendandburns** [comment]
Looks like the openid client doesn't currently support node-18:

https://github.com/panva/node-openid-client/issues/494

We should probably mark openid-client as an optional dependency since it's only required by people who want to use openid based authentication.

**Comment by brendandburns** [comment]
Filed #837 to fix this.
