### ISSUE TITLE
`applyToRequest` and `applytoHTTPSOptions` doesn't passes `opts` to request lib.

### ISSUE THREAD

**Issue by DevT0ny** [kubernetes-client/javascript#833]
**Describe the bug**
I wanted to pass options to `request` library via `kc.applyToRequest` or `kc.applytoHTTPSOptions` but it never passes those options.
 
** Client Version **
e.g. `0.16.3`

**To Reproduce**
see example code.

** Example Code**
```javascript
import k8s from '@kubernetes/client-node'

const kc = new k8s.KubeConfig()
kc.loadFromDefault()

await kc.applyToRequest({ url: 'https://google.com/', family: 4 })
await kc.applytoHTTPSOptions({ port: 69 })

const k8sClient = kc.makeApiClient(k8s.CoreV1Api)

k8sClient.addInterceptor((reqOptions) => {
  console.log('reqOptions', reqOptions)
})

const res = await k8sClient.listNode()
// console.log(res.body)
```
**Expected behavior**
 `reqOptions` should have properties of object passed in `applyToRequest` & `applytoHTTPSOptions` argument.

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: 18.3.0

**Comment by brendandburns** [comment]
That's not how those APIs work. They are called inline whenever a request is processed (e.g. an API call is made) instead you need to add an interceptor that modifies the options appropriately. That interceptor will be called whenever a request is made.

Hope that helps. I will try to add an example documenting how to do this.

**Comment by DevT0ny** [comment]
Got it, its meant to use internally. I think its better to prefix those functions with underscore to indicate that, something like [this](https://jsdoc.app/tags-protected.html). 

Ya I'll stick to `addInterceptor` to modify those options, Thanks.
