### ISSUE TITLE
Should informer watcher supports periodic restart for the closing of stream connection?   

### ISSUE THREAD

**Issue by pillumina** [kubernetes-client/javascript#836]
**Describe the bug**
  The informer employs the watch module and passes in the `doneHandler`  as the callback for the stream close/error event. The `doneCallOnce` callback function would call `doneHandler` with arg `null` if the server-side shut down unexpectedly so as to make another connect attempt. The problem in this case is calling doneHandler wouldn't catch the potential exception threw by the `listFn` in `doneHandler` when the server side is unavaiable or any issue of the network in between.
```
        const doneCallOnce = (err: any) => {
            if (!doneCalled) {
                req.abort();
                doneCalled = true;
                done(err);
            }
        };
```
  I wonder if the code snippet should catch the potential exception from `doneHandler` and periodically call it to make sure the informer watch could recover when the api server is available again.

  The issue get raised as we use this package in our production environment and the apiServer / network de-facto would have some problems in some cases. And we've got to restart our service pod container to make the watch continue.

** Client Version **
0.16.3

** Server Version **
1.21.2

**To Reproduce**
Start the informer, stop the api server and observe the behaviour of informer.

**Expected behavior**
Informer should be in a loop of trying to restart the watch when the apiserver is down, and finally re-establish the watch stream when the server is available. 

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: v14.16.1
 - Cloud runtime: kind v0.10.0

**Comment by brendandburns** [comment]
Yeah, that seems reasonable. I think the right thing to do is to catch the exception in `doneHandler` and then use `setTimeout` to call `doneHandler` again after some exponential back-off or retry period.

We'd be happy to take a PR to cover this.

Thanks!

**Comment by pillumina** [comment]
> 

Thanks for the reply.

I'll be happy to create a PR for it with your suggestions.
