### ISSUE TITLE
Jest testing resources? 

### ISSUE THREAD

**Issue by bmoe24x** [kubernetes-client/javascript#841]
Sorry if this is the wrong place to ask but are there any resources for testing code that utilizes this client? In particular I am using Jest and would like to be able to test code I have built around the k8s client

For example code like this:

```typescript

    public async getDeployment( deploymentName: string ): Promise<k8s.V1Deployment> {
        const res = await this.k8sApi.readNamespacedDeployment( deploymentName, this.namespace );
        return res.body;
    };

    public async getLoaderPollSizeString( deploymentName: string, deploymentObject?: V1Deployment ): Promise<string> {
        const deployment: V1Deployment = deploymentObject != undefined ? deploymentObject : await this.getDeployment( deploymentName );
    
        const pollSizeValueString: string = deployment.spec.template.spec.containers.find( container => container.name === this.loaderContainerName ).env.find( envvar => envvar.name === this.pollSizeEnvVarName ).value;
    
        return pollSizeValueString ;
    };
```

Any help is much appreciated as I am finding this rather difficult to test due to k8s setup, underlying http calls, mocking of k8s objects, etc.

Thank you

**Comment by brendandburns** [comment]
The client code is extensively unit tested, you can look at any of the `_test.ts` files here:

https://github.com/kubernetes-client/javascript/tree/master/src

There's an example of mocking an HTTP call here:

https://github.com/kubernetes-client/javascript/blob/master/src/top_test.ts#L155
