### ISSUE TITLE
AWS/EKS - What happens if credentials are not in their normal location?

### ISSUE THREAD

**Issue by gamename** [kubernetes-client/javascript#843]
HI,

This is a design query I haven't been able to get answered anywhere else. 

I have a situation where I use dynamic credentials for a k8s client.  Put another way, the credentials are *not* in pre-existing environment vars (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY), nor are they in the user's `.aws` directory.  

But it appears the k8s client assumes one of these 2 options are in use.

Is there some way to inject these values into the environment in a way other than I described?

Thank you for your time.

**Comment by brendandburns** [comment]
This client should respect a `$KUBECONFIG` environment variable. So as long as they are embedded in the kubeconfig file, it should work.

As far as I know, AWS uses an `exec` plugin for their credentials, so it's possible that this isn't really a question for this library, but rather for the AWS/EKS `exec` implementation.

Put another way: If you can construct a `kubeconfig` file that works with `kubectl` it should work with this client. If that isn't the case, please let us know.

**Comment by gamename** [comment]
Thanks for the reply @brendandburns. Much appreciated.

Actually, we're talking about 2 different things. There is the kube config file on the one hand, and the AWS credentials on the other.  It sounds like this library doesn't really have any knowledge of the AWS credentials, just the kube config contents. 

Looks like I need to look at the exec plugin.
