### ISSUE TITLE
Patch - Adding single pod metrics into Metrics

### ISSUE THREAD

**Issue by RCCSilva** [kubernetes-client/javascript#844]
**Overview**
Is the possibility to query single pod metrics under development? If not, **I'd like to help you do it**.

With the `metrics-server` enabled, we are able to query not only a list of pods, but specific ones based on their name. You may find it documented [here](https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/).

Here is an example of this functionality that you may try on a running Kubernetes cluster with metrics server enabled.

```shell
kubectl run nginx --image=nginx --restart=Never
kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/nginx" | jq '.'
```

**Proposed Interface**

Based on the API's [response schema](https://github.com/kubernetes-sigs/metrics-server/blob/2efcd9fe23d41e20660d06eaf15619db25b900ed/pkg/api/generated/openapi/zz_generated.openapi.go#L2639) and on the [metadata object schema](https://github.com/kubernetes-sigs/metrics-server/blob/2efcd9fe23d41e20660d06eaf15619db25b900ed/pkg/api/generated/openapi/zz_generated.openapi.go#L1347), I propose the following interface and method to be added at the `metrics.ts` file.

```ts
export interface SinglePodMetrics {
    kind: 'PodMetrics',
    apiVersion: 'metrics.k8s.io/v1beta1',
    metadata: {
        name: string;
        namespace: string;
        creationTimestamp: string;
        labels: { [key: string]: string }
    };
    timestamp: string;
    window: string;
    containers: ContainerMetric[];
}

export class Metrics {
    public async getSinglePodMetrics(namespace: string, pod: string): Promise<SinglePodMetrics>
}
```

**Comment by brendandburns** [comment]
Thanks, I think this would be a great addition.

Instead of adding a new function signature, what do you think about adding:

`getPodMetrics(namespace? string, name? string) { `

That seems more ergonomic.

**Comment by RCCSilva** [comment]
Ok! I'll look into it and come back with a PR.
