### ISSUE TITLE
proxy-url in kube config not used

### ISSUE THREAD

**Issue by jalkjaer** [kubernetes-client/javascript#853]
Cluster config  in kube config allows `proxy-url` setting  (i.e. proxy-url: http://127.0.1.1:8080) but is not used in the js lib

** Client Version **
e.g. `0.13.6`

** Server Version **
doesn't apply

**To Reproduce**
Running the example from the main README.md with the current context pointing to a cluster that is configured with proxy-url, the example with throw "connect EHOSTUNREACH" when the cluster IP is not directly accessible. 

Running the example with the env var `HTTP_PROXY` works as expected

**Expected behavior**
The clientlib should respect the proxy-url setting

** Example Code**
```
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
k8sApi.listNamespacedPod('default').then((res) => {
    console.log(res.body);
}).catch(console.error);
```

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version 12.10.0

**Comment by brendandburns** [comment]
Relevant pointers:
* https://github.com/kubernetes/client-go/issues/351
* https://github.com/kubernetes/kubernetes/pull/81443
* https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/staging/src/k8s.io/client-go/rest/config.go#L137-L139

This really points out the need for a clean spec for the kubeconfig file, since this never went through a KEP or anything else and just merged.

I'm happy to take a PR to add support for this, otherwise, we will get to it eventually.

**Comment by dgolovin** [comment]
Full implementation, obviously, is going to take time. Is that possible to start applying some fixes related to this issue? For example, stop filtering 'proxy-url' property while loading cluster configuration from config [here](https://github.com/kubernetes-client/javascript/blob/eaf1b23537df96a4f6e93bdd43a971d86bf5576a/src/config_types.ts#L60).

**Comment by mstruebing** [comment]
I would like to try to provide a PR for this.

Could someone recommend a way to set up a test environment for this?
Would it be correct to assume that if I have a kubernetes cluster and do a `kubectl proxy --port <number>` and set set the proxy URL to `http://127.0.01:<number>` in my kubeconfig is a valid way to test this?

**Comment by bradyburke** [comment]
Any update on this? I am running into the same issue

**Comment by bradyburke** [comment]
Any update on this issue?

**Comment by himanshusharma27** [comment]
please assign me this issue.

**Comment by SD007CSE** [comment]
I am having an issue for `kube test` and `kube run docs`
<img width="1440" alt="Screenshot 2023-05-10 at 3 31 58 AM" src="https://github.com/kubernetes-client/javascript/assets/88923088/169ab564-6cc2-49fd-9e1f-746ab1ebb503">

**Comment by SD007CSE** [comment]
@brendandburns Help me out

**Comment by j4acks0n** [comment]
> I am having an issue for `kube test` and `kube run docs` <img alt="Screenshot 2023-05-10 at 3 31 58 AM" width="1440" src="https://user-images.githubusercontent.com/88923088/237313314-169ab564-6cc2-49fd-9e1f-746ab1ebb503.png">

Hello  Mybe You Can Try
import {  BsModalModule } from 'ng2-bs3-modal'; 
Mybe  This Will Help

**Comment by j4acks0n** [comment]
> Any update on this issue?
Hello,
Mybe You Can Try This Multiple Solution
Way 1.Export KubeConfig To Path Directory Yaml Or 
Way 2.Paste The Yaml to YourDirectory/.Kube/Config

**Comment by SD007CSE** [comment]
Actually in most of the .ts files which have "/api" it showing the the problem Module `'"./api"' has no exported member 'V1Secret'.ts(2305)``

**Comment by geisbruch** [comment]
Hi Guys ! Until this is solved I did a simple hack to be able to use proxy-url. I've override the KubeConfig makeApiClient method to be able to override the "request" configuration. It's not super safe but runs

Here the code

```javascript
    const kc = new k8s.KubeConfig();
    const originalMakeApiClient = kc.makeApiClient;
    kc.makeApiClient = function(api) {
        const client = originalMakeApiClient.call(kc, api);
        client.interceptors.push(async (config) => {
            config.proxy="http://host:port";
        });
        return client;
    };
```

**Comment by kc1r74p** [comment]
> Hi Guys ! Until this is solved I did a simple hack to be able to use proxy-url. I've override the KubeConfig makeApiClient method to be able to override the "request" configuration. It's not super safe but runs
> 
> Here the code
> 
> ```js
>     const kc = new k8s.KubeConfig();
>     const originalMakeApiClient = kc.makeApiClient;
>     kc.makeApiClient = function(api) {
>         const client = originalMakeApiClient.call(kc, api);
>         client.interceptors.push(async (config) => {
>             config.proxy="http://host:port";
>         });
>         return client;
>     };
> ```

Thanks for your initial workaround.
Still had issues when using `k8s.Log(kc);` as it seems not to apply to all requests.

Solved it for me using:
```js
    const originalApply = kc.applyToRequest;
    kc.applyToRequest = function(options) {
        originalApply.call(kc, options);
        // process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
        options.proxy = 'http://proxy:port';
    };
```

Works for normal api calls and log. 
In case someone also wants to use a socks proxy, currently can only recommend a workaround via:
`hpts -s socksProxy:socksPort -p localHttpProxy` using `http-proxy-to-socks`.

Best would be a migration away from `request` to `got` or some client which has better proxy support.

**Comment by cjihrig** [comment]
This landed on both release lines in https://github.com/kubernetes-client/javascript/pull/2091 and https://github.com/kubernetes-client/javascript/pull/2111.

/close
