### ISSUE TITLE
Errors from watch callback function are caught

### ISSUE THREAD

**Issue by Nicklason** [kubernetes-client/javascript#856]
**Describe the bug**
When using the Watch class and watch function, if there is an error in the callback function, then the error is caught by the watch class, instead of being thrown.

https://github.com/kubernetes-client/javascript/blob/eaf1b23537df96a4f6e93bdd43a971d86bf5576a/src/watch.ts#L123-L130

The function is not only ignoring parsing errors, but also errors made by the callback function. The callback should be called outside the try-catch to solve the problem.

**Client Version**
`0.17.0`

**Server Version**
`n/a`

**To Reproduce**

1. Create instance of Watch class and call watch function using a callback function
2. Throw an error inside the callback function
3. Error is caught by watch function instead of resulting in an uncaught exception

**Expected behavior**
The error should not be caught, an uncaught exception should occur.

**Example Code**

```js
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const watch = new k8s.Watch(kc);
watch.watch('/api/v1/namespaces', {}, () => {
    // Error is thrown but caught by watch function 
    throw new Error('something bad happened');
}, () => {});
```

**Environment (please complete the following information):**
 - OS: Windows 11
 - NodeJS Version: v18.3.0

**Comment by brendandburns** [comment]
Closing since #857 merged.
