### ISSUE TITLE
Authenticate using headless in GKE

### ISSUE THREAD

**Issue by skhaz** [kubernetes-client/javascript#859]
Is it possible to authenticate using headless?

Reference: https://ahmet.im/blog/authenticating-to-gke-without-gcloud/

**Comment by brendandburns** [comment]
Any config file that works with `kubectl` should work with this client. If it does not, please file an issue with the problems that you see and the contents of your config file (secrets redacted).

**Comment by skhaz** [comment]
I just discovered a way better to do this, posted about it 

https://nullonerror.org/2022/08/21/operating-a-google-kubernetes-cluster-using-typeScript/
