### ISSUE TITLE
Unexpected server response: 400

### ISSUE THREAD

**Issue by luyangsc** [kubernetes-client/javascript#865]
I run ts-node exec-example.ts,but response 400. Here are the details of the error:

ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      error: [Function],
      message: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://172.20.0.1:443/api/v1/namespaces/default/pods/fds-clamav-mulit-65c5458fcf-8gcsk/exec?stdout=false&stderr=false&stdin=false&tty=true&command=ls&container=fds-clamav',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /api/v1/namespaces/default/pods/fds-clamav-mulit-65c5458fcf-8gcsk/exec?stdout=false&stderr=false&stdin=false&tty=true&command=ls&container=fds-clamav HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: /kV8jIsaGfrh3BhxVEhqfg==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Authorization: ...\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Sec-WebSocket-Protocol: v4.channel.k8s.io, v3.channel.k8s.io, v2.channel.k8s.io, channel.k8s.io\r\n' +
        'Host: 172.20.0.1\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/namespaces/default/pods/fds-clamav-mulit-65c5458fcf-8gcsk/exec?stdout=false&stderr=false&stdin=false&tty=true&command=ls&container=fds-clamav',
      _ended: false,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '172.20.0.1',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 400',
  error: Error: Unexpected server response: 400
      at ClientRequest.<anonymous> (/opt/javascript-master/node_modules/ws/lib/websocket.js:783:7)
      at ClientRequest.emit (node:events:513:28)
      at ClientRequest.emit (node:domain:489:12)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:674:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at TLSSocket.socketOnData (node:_http_client:521:22)
      at TLSSocket.emit (node:events:513:28)
      at TLSSocket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
}

**Comment by brendandburns** [comment]
@luyangsc HTTP 400 indicates that you sent a bad request. You should print the response body (it's in the `res` field in that error) for more information.

Also, important to note that you posted a bearer token into this github issue which is publically readable. You should:

a) Make certain that you have revoked that token
b) In the future make sure that you redact/remove tokens and other secure credentials before posting to Github.

**Comment by luyangsc** [comment]
> @luyangsc HTTP 400 indicates that you sent a bad request. You should print the response body (it's in the `res` field in that error) for more information.
> 
> Also, important to note that you posted a bearer token into this github issue which is publically readable. You should:
> 
> a) Make certain that you have revoked that token b) In the future make sure that you redact/remove tokens and other secure credentials before posting to Github.

thank you
