### ISSUE TITLE
TS interfaces for kube resources

### ISSUE THREAD

**Issue by whitecolor** [kubernetes-client/javascript#87]
I think this library could include kube resources definitions. I have one for my own, look something like this:

```ts
/**
 * https://kubernetes.io/docs/api-reference/v1.6/#deploymentspec-v1beta1-apps
 */
export interface DeploymentSpec {
  /**
   * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)
   */
  minReadySeconds?: number,
  /**
   * Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.
   */
  replicas?: number,
  /**
   * The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 2.
   */
  revisionHistoryLimit?: number,
  /**
   * The config this deployment is rolling back to. Will be cleared after rollback is done.
   */
  rollbackTo?: RollbackConfig,
  /**
   * Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.
   */
  selector?: LabelSelector,
  /**
   * The deployment strategy to use to replace existing pods with new ones.
   */
  strategy?: DeploymentStrategy
  /**
   * Template describes the pods that will be created.
   */
  template: PodTemplateSpec
}

export interface Deployment extends Resource {
  apiVersion: 'extensions/v1beta1'
  kind: 'Deployment',
  spec: DeploymentSpec
}
```

Though they are manually created, not generated as I assume can be.

I use those interfaces to created helm charts or kube configs (JS results are converted to yalm configs and applied to server). I find using Typescript for making configs much more convenient, flexible and safe than directly writing configs in native YAML format.

**Comment by brendandburns** [comment]
I think that this is a good idea.

The generator template is located here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache

It should be easy enough to add something around here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache#L137

That also defines an Interface.

This library is then generated from that, so that's where the change needs to be.

Thanks!

**Comment by ddgenome** [comment]
Types for all Kubernetes resources are available in the Node package in `dist/api.d.ts`, which is exported from `dist/index.d.ts`. For example, the complete deployment definition is available as `AppsV1beta1Deployment`, `ExtensionsV1beta1Deployment`, `V1Deployment`, and `V1beta2Deployment`, dependending on which version you are using/your cluster supports. There are some issues with the definitions as they do not properly identify optional properties.

Were you looking  for something else?

**Comment by ddgenome** [comment]
I understand the issue with optional/required. What usability issues does them being classes and not interfaces present?  This seems to work:

```typescript
const d: k8s.V1Deployment = {
    …
};
```

Just curious, as I went down a similar road as you before this client existed and the others had resource interfaces, https://github.com/atomist/k8-sdm/blob/98b289bed20387845ff83612d0c8c86084e555fb/src/k8.ts#L231-L556 .

**Comment by whitecolor** [comment]
> I understand the issue with optional/required. What usability issues does them being classes and not interfaces present?

I don't like classes/OOP in general =)

Well, need to try. I'm still using my definitions and they work ok for me.
