### ISSUE TITLE
401 unauthorized error when trying to switch contexts

### ISSUE THREAD

**Issue by scho3034** [kubernetes-client/javascript#871]
I have a kubeconfig file with 3 clusters, 3 users with 1 user for each clusters and 3 contexts. I create the new kubeconfig and use loadFromfile() to load the kubeconfig in an express server. I am using React frontend to control the context switch event. 
I get a 401 unauthorized error when I use setCurrentContext() to switch to the user selected context. 
I know about the anonymous request but is there any solution to this?

**Comment by brendandburns** [comment]
There's not enough information in this report to determine what is going wrong.

We need more details to understand this, in particular, the detailed message from the server (included in the 401 response body) will include which user it is using.

Additionally we need the code for a simple reproduction of the bug.

**Comment by imaspeer** [comment]
I looked at the code and did some tests and I think I found the bug.

The problem is that in KubeConfig::makeApiClient(), the server address is set to the current context's server at the time the client is created, but for the authentication part a reference to the KubeConfig instance is passed. If the context in the KubeConfig is then modified, an inconsistent situation is created where the client will try to access the cluster from a context with the user from another.

The following code reproduces this situation:
```javascript
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromOptions({
  clusters: [
    {name: 'cluster1', server: 'https://...', caFile: '...'},
    {name: 'cluster2', server: 'https://...', caFile: '...'}
  ], users: [
    {name: 'user1', token: '...'},
    {name: 'user2', token: '...'}
  ], contexts: [
    {name: 'user1@cluster1', cluster: 'cluster1', user: 'user1', namespace: 'ns1'},
    {name: 'user2@cluster2', cluster: 'cluster2', user: 'user2', namespace: 'ns2'}
  ], currentContext: 'user1@cluster1'});

const kappsv1 = kc.makeApiClient(k8s.AppsV1Api);

kappsv1.listNamespacedDeployment('ns1').then(console.log, console.error); // works as intended

kc.setCurrentContext('user2@cluster2');

kappsv1.listNamespacedDeployment('ns2').then(console.log, console.error); // makes a request to cluster1 with user2's credentials
```

**Comment by brendandburns** [comment]
Thanks for the details.

That makes sense and I think you are right. I'm not sure if the generated code for this client is smart enough to handle this situation, but I will investigate.

In the meantime, you may have to load different clients for different contexts.

**Comment by scho3034** [comment]
Loading different clients seems to resolve the issue. Thanks!

**Comment by seunggs** [comment]
@scho3034 Do you mind sharing how you resolved this? I'm trying to use multiple kubeconfigs to access multiple clusters, but I'm still getting 401 on all other clusters but one.

```
const k8s = require('@kubernetes/client-node')

const kcApp = new k8s.KubeConfig()
kcApp.loadFromString(process.env.KUBECONFIG_APP)

const kcUserMachines = new k8s.KubeConfig()
kcUserMachines.loadFromString(process.env.KUBECONFIG_USER_MACHINES)

const kcFlyte = new k8s.KubeConfig()
kcFlyte.loadFromString(process.env.KUBECONFIG_FLYTE)

export const loadKubeConfig = (clusterName: string) => {
  const kubeConfigMap = {
    'app-cluster': kcApp,
    'user-machines-cluster': kcUserMachines,
    'flyte-cluster': kcFlyte,
  }
  return kubeConfigMap[clusterName]
}

// Usage
const listNamespaces = async (clusterName) => {
  const kc = loadKubeConfig(clusterName)
  const k8sCoreV1Api = kc.makeApiClient(k8s.CoreV1Api)
  return await k8sCoreV1Api.listNamespace()
}
```

Works for one cluster, but the second cluster throws `401 (unauthorized)` error

**Comment by seunggs** [comment]
I found the issue - my kubeconfigs were using the same context name

**Comment by jobcespedes** [comment]
Same. May I suggest to reopen this issue.

**Comment by jobcespedes** [comment]
The following workaround seems to be working: explicityly setting `basePath` after setting new context. What do you think?
```js
private setContext(contextName: string) {
    const cluster = this.kc.getContextObject(contextName).cluster
    this.kc.setCurrentContext(contextName)
    this.customObjectsApi.basePath = this.kc.getCluster(cluster).server
  }
```
