### ISSUE TITLE
Can not apply crd after upgraded to `0.17.1`

### ISSUE THREAD

**Issue by zzjin** [kubernetes-client/javascript#875]
**Describe the bug**
After upgrade to sdk version to `0.17.1`, cannot apply crd using apply example [apply-example.ts](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/apply/apply-example.ts)

**Client Version**
`0.17.1`

**Server Version**
n/a

**To Reproduce**
Download example file and try to apply come custom crd.

**Expected behavior**
Work like usual.

**Example Code**
Same as apple example file.

**Environment (please complete the following information):**
n/a

**Additional context**
Error output:

```
./apply-example.ts:32:47
Type error: Argument of type 'KubernetesObject' is not assignable to parameter of type 'KubernetesObjectHeader<KubernetesObject>'.
  Type 'KubernetesObject' is not assignable to type '{ metadata: { name: string; namespace: string; }; }'.
    Types of property 'metadata' are incompatible.
      Type 'V1ObjectMeta | undefined' is not assignable to type '{ name: string; namespace: string; }'.
        Type 'undefined' is not assignable to type '{ name: string; namespace: string; }'.
```

**Comment by brendandburns** [comment]
Thanks for reporting, I will take a look at this.

**Comment by ontehfritz** [comment]
came accross this issue when upgrading from x.15 to x.17.1 any resolve on this?

**Comment by ontehfritz** [comment]
it is on the client.read(spec) line I do something very similar and get the exact same message

**Comment by naimetti** [comment]
same problem here!

**Comment by ontehfritz** [comment]
The signature has changed I was able to get it working by not reading the whole spec but by providing the metadata:
