### ISSUE TITLE
Missing type dependencies in 0.17.1

### ISSUE THREAD

**Issue by Rugvip** [kubernetes-client/javascript#883]
**Describe the bug**
Dependencies are missing for type declarations, leading to type errors for users of this package.

** Client Version **
`0.17.1`

** Server Version **
N/A

**To Reproduce**

- `npm init -y`
- `npm install typescript`
- `npm install @kubernetes/client-node`
- `echo 'import "@kubernetes/client-node"' > index.ts`
- `yarn tsc index.ts` <- Lots of errors

**Expected behavior**
I expect `@kubernetes/client-node` to declare direct or peer dependencies for all types that are referenced in the published type declarations.

**Example Code**
Just a simple `import "@kubernetes/client-node"'`

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: 16
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**
Essentially a revert of #847, although not necessarily all of those dependencies.

**Comment by matteosilv** [comment]
The problem is outlined here too https://github.com/kubernetes-client/javascript/issues/864#issuecomment-1243216296

**Comment by Rugvip** [comment]
Fixed by #890 👍
