### ISSUE TITLE
ExecAuth token cache is stale and cannot be reset when ADC auth token is regenerated

### ISSUE THREAD

**Issue by glouischandra** [kubernetes-client/javascript#886]
**Describe the bug**
exec_auth cache the token despite gcloud adc token has been invalidated using gcloud auth revoke. 
Our product Cloud Code integrates with this k8s nodejs application and we use gcloud ADC for permission to GCP services, our tool does allow user to sign out and sign back in and we need a way to clear the exec_auth cache as gke_gcloud_auth_plugin (which is an exec) is a common auth method for GKE clusters.

** Client Version **
0.16.3

** Server Version **
n/a

**To Reproduce**
1. use gcloud auth revoke
2. re-sign in using gcloud auth application-default login 
3. Token inside exec_auth is the old token despite the new token generated by gcloud

**Expected behavior**
A way for application to clear the cache in exec_auth on demand. 

** Example Code**
ExecAuth.clearCache() and access to ExecAuth instance from KubeConfig object or
KubeConfig.clearTokenCache() 

We can also send you a PR if you're ok with the API proposal below. Thanks!

**Environment (please complete the following information):**
 - OS: MacOSX, Linux and Windows 
 - NodeJS Version: 18.7
 - Cloud runtime: GCP 

**Additional context**

**Comment by brendandburns** [comment]
We'd be happy to take a PR to implement this.
