### ISSUE TITLE
json-schema is vulnerable to Prototype Pollution

### ISSUE THREAD

**Issue by angelsk** [kubernetes-client/javascript#894]
**Describe the bug**
I'm using the latest version of the client, but getting this dependabot warning. Hopefully this is easily resolved?

Dependabot cannot update json-schema to a non-vulnerable version
The latest possible version that can be installed is `0.2.3` because of the following conflicting dependency:

`@kubernetes/client-node@0.17.1 requires json-schema@0.2.3 via a transitive dependency on jsprim@1.4.1`

The earliest fixed version is `0.4.0`.

https://github.com/advisories/GHSA-896r-f27r-55mw

** Client Version **
0.17.1

** Server Version **
1.21.14

**To Reproduce**
Steps to reproduce the behavior: Have client lib included into package.json

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version [eg. 10]
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by WillCohenInfotrack** [comment]
bump  - We would also like to see this resolved. I think this all stems from deprecated "request" package - https://www.npmjs.com/package/request?activeTab=dependencies

**Comment by brendandburns** [comment]
@WillCohenInfotrack if this comes from request, please see #754 we'd certainly appreciate help in completing that work.

**Comment by brendandburns** [comment]
Although if you want to send a PR to just update the json-schema dependency in `package-lock.json` that would likely work as well.

fwiw `npm audit` shows green for the library.

**Comment by brendandburns** [comment]
oh, hang on, I checked `package-lock.json` and this is updated to `0.4.0` in the `0.18.0` release, so I believe this is fixed.

Closing. Please use `/reopen` if you need to add anything additional.
