### ISSUE TITLE
Refresh token with GKE and cloud functions

### ISSUE THREAD

**Issue by patrickcorrigan** [kubernetes-client/javascript#895]
I want to start Kubernetes jobs on a GKE cluster from a Google Cloud Function (Firebase)

I've created a Kubernetes config file using `kubectl config view --flatten -o json'

and loaded it 

```
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();
kc.loadFromString(config)
```

This works perfectly locally but the problem is when running on cloud functions the token can't be refreshed so calls fail after a while. 

My config k8s config files contains

```
          "user": {
              "auth-provider": {
                  "name": "gcp",
                  "config": {
                      "access-token": "redacted-secret-token",
                      "cmd-args": "config config-helper --format=json",
                      "cmd-path": "/usr/lib/google-cloud-sdk/bin/gcloud",
                      "expiry": "2022-10-20T16:25:25Z",
                      "expiry-key": "{.credential.token_expiry}",
                      "token-key": "{.credential.access_token}"
                  }
              }
```

I'm guessing the command path points to the gcloud sdk which is used to get a new token when the current one expires. This works locally but on cloud functions it doesn't as there is no `/usr/lib/google-cloud-sdk/bin/gcloud`

Is there a better way to authenticate?

**Comment by brendandburns** [comment]
The current client code for GCP uses the `gcloud` tool as you suggest, if you identify a better way to do it inside a different environment feel free to send a PR to extend this support.
