### ISSUE TITLE
get all apiResource

### ISSUE THREAD

**Issue by vikram-katkar** [kubernetes-client/javascript#896]
How to get all available `api-resource` including `sub-resources`?

Equivalent to `kubectl api-resources`

**Comment by brendandburns** [comment]
Unfortunately, you need to enumerate them for each api group separately, for example:

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/apiregistrationV1Api.ts#L414
https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/appsV1Api.ts
