### ISSUE TITLE
Package.json missing @types/bluebird

### ISSUE THREAD

**Issue by JohnCMcDonough** [kubernetes-client/javascript#9]
The package.json currently has a dependency on the `bluebird` module, but doesn't include the typings for it. The means that any `Promise<...>` objects returned from the `Core_V1Api` are typed as `any`.

The fix is to include a dependency on `@types/bluebird`.

A temporary workaround is for the user to install `@types/bluebird`.

**Comment by brendandburns** [comment]
I see this here:

https://github.com/kubernetes-client/javascript/blob/master/node-client/package.json#L34

Is there something missing?

Thanks!

**Comment by JohnCMcDonough** [comment]
Weird. I seemingly got everything but bluebird when I installed. I blame our corporate proxy.

Yeah, this is a non issue, sorry!
