### ISSUE TITLE
Issue a release

### ISSUE THREAD

**Issue by dweitzman-codaio** [kubernetes-client/javascript#908]
There hasn't been a JS k8s client release for a bit.

My personal interest is that I'm trying to upgrade a project to typescript 4.8 and k8s-client is our only dependency that doesn't have a 4.8-compatible release yet (although the codebase has supported it since October: https://github.com/kubernetes-client/javascript/pull/897)

**Comment by JarnoRFB** [comment]
Also see #864.

**Comment by brendandburns** [comment]
Real life has been getting in the way of this, but will try to get it done by the end of this week.

**Comment by brendandburns** [comment]
This is now live:
https://www.npmjs.com/package/@kubernetes/client-node

Please let me know if you see any issues.

**Comment by dweitzman-codaio** [comment]
Thank you!
