### ISSUE TITLE
Bundling issues due to library dependency on shelljs

### ISSUE THREAD

**Issue by webratz** [kubernetes-client/javascript#944]
**Describe the bug**
When using the library and bundling it with esbuild (in this case for use within AWS lambda) an error is thrown.

```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module './src/cat'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module './src/cat'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
    "    at async start (file:///var/runtime/index.mjs:1200:23)",
    "    at async file:///var/runtime/index.mjs:1206:1"
  ]
}
```
This is being caused not by this library, but the direct dependency `shelljs`.
The reason why I'm reporting this here is, that this is not seen as a bug there

* https://github.com/shelljs/shelljs/issues/962
* https://github.com/shelljs/shelljs/issues/1047

As `shelljs` only seems to be used in very few places in this library, I'm wondering if it would be an option to remove the dependency and implement the few places it uses in a different way.

https://github.com/kubernetes-client/javascript/search?q=shelljs

** Client Version **
`0.18.0`

** Server Version **
e.g. `1.24.0`

**To Reproduce**

* Bundle any project that depends on `@kubernetes/client-node` with `esbuild` (or other bundlers)

**Expected behavior**
No error is thrown and the library can be used.

** Example Code**

```ts
import * as k8s from '@kubernetes/client-node';
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
```

**Environment (please complete the following information):**
 - OS: macOs 12.6
 - NodeJS Version: 18
 - Cloud runtime:  Lambda

**Additional context**
If you use AWS CDK `NodejsFunction` you can use the following bundling settings as a workaround
```ts
bundling: {
    forceDockerBundling: true,
    minify: false,
    keepNames: true,
    nodeModules: ['shelljs'],
}
 ```

**Comment by brendandburns** [comment]
I'm certainly open to taking PRs to reduce our dependencies, feel free to send them.

**Comment by brendandburns** [comment]
fwiw, the right thing to do might be to make shelljs an optional import, similar to what was done with OIDC (https://github.com/kubernetes-client/javascript/blob/master/src/oidc_auth_delayed.ts#L32) I doubt that shelljs works right inside of Lambda anyway.

**Comment by webratz** [comment]
i gave it a try at https://github.com/kubernetes-client/javascript/pull/945

**Comment by brendandburns** [comment]
Actually, I was in this code anyway removing the `execa` dependency, so I just added this to it:

https://github.com/kubernetes-client/javascript/pull/946

**Comment by brendandburns** [comment]
I'm going to close this PR in favor of #946, it turns out that some sort of `wsl.exe` on modern Windows in general, so there's not much point to checking for it.

**Comment by webratz** [comment]
less dependencies are even better 🥳

**Comment by webratz** [comment]
this seems to be merged 🎉  but it seems like the build pipeline fails and there is no new release. or am i missing something?

**Comment by brendandburns** [comment]
I'll try to get a release cut this week. Apologies for the delay.

**Comment by brendandburns** [comment]
Ok, that took longer than expected, but `0.18.1` just got pushed out to npm. Enjoy.
