### ISSUE TITLE
[docs]: Note before raising an issue

### ISSUE THREAD

**Issue by Vishvsalvi** [kubernetes-client/javascript#952]
It will be better if we add this line __"Prior to creating a new issue, please ensure that a similar issue has not already been raised by searching existing issues."__ in the contributing.md **Reporting an issue** section

**Comment by brendandburns** [comment]
Feel free to send a PR to improve this wording.

**Comment by Vishvsalvi** [comment]
Can I work on this ?

**Comment by brendandburns** [comment]
Closing via #957
