### ISSUE TITLE
Retry for transient faults

### ISSUE THREAD

**Issue by cjhpaul** [kubernetes-client/javascript#96]
Is it supposed to handle transient faults like 504 by retrying, or have users handle?
It seems to me the fix could be as simple as using one of request wrappers like node-request-retry in place of request, for example.
Any thoughts would be appreciated.

**Comment by brendandburns** [comment]
They are left for the user to handle.  The original code is generated from the [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) project, so if you wanted to add that retry library, that would be the right place to add it (unless you can figure out a way to add it into this library w/o modifying the generated code in `api.ts`)

PRs welcome.
