### ISSUE TITLE
Helper function for app client creation

### ISSUE THREAD

**Issue by sheldonkwok** [kubernetes-client/javascript#97]
Hello, 

I was trying to use the Apps API instead of the Core API and noticed there aren't helpers for creating clients from a config. I ended up writing my own that look almost identical to the config ones provided for Core. Should we add helpers for Apps as well? I can just submit a PR.

Thanks,
Sheldon

**Comment by brendandburns** [comment]
I recently added this generic function:

https://github.com/kubernetes-client/javascript/blob/master/node-client/src/config.ts#L220

Which should enable you to create any API object type. Does that suit your needs?

If not, a PR would definitely be welcome.

**Comment by sheldonkwok** [comment]
That's actually perfect! Thanks! Look forward to the release.

**Comment by sheldonkwok** [comment]
We could also add another helper at the Config level to make it a little easier too. I'll submit a PR

**Comment by brendandburns** [comment]
Thanks!

**Comment by brendandburns** [comment]
Just pushed `0.6.0` which should contain this.

**Comment by brendandburns** [comment]
Closed via #99
