### ISSUE TITLE
The result of using the labelSelector and limit arguments together is incorrect

### ISSUE THREAD

**Issue by zjy365** [kubernetes-client/javascript#974]
**Describe the bug**
The result of using the labelSelector and limit arguments together is incorrect

** Client Version **
e.g. `0.18.0`

** Server Version **
e.g. `1.24`

**To Reproduce**
kc.makeApiClient(k8s.CustomObjectsApi). **listClusterCustomObject()**  
If you use the labelSelector and limit arguments together, the result is incorrect, for example, expecting three data items to be returned, but only one data item is returned

**Expected behavior**
I expect this to return the correct result

** Example Code**
Code snippet for what you are doing
`
kc
    .makeApiClient(k8s.CustomObjectsApi)
    .listClusterCustomObject(
      meta.group,
      meta.version,
      meta.plural,
      undefined,
      undefined,
      _continue,
      undefined,
      labelSelector,
      limit,
    );
`

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version16.18.1
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by mstruebing** [comment]
I think `1.19.1` isn't fully supported by the client `0.18.0`, as you can see in this table: https://github.com/kubernetes-client/javascript#compatibility

I'm not sure if this is related, but what I would try is to use an older client or, if possible, update my Kubernetes Server.
If the issue is still happening this is a valid bug.

**Comment by zjy365** [comment]
> I think `1.19.1` isn't fully supported by the client `0.18.0`, as you can see in this table: https://github.com/kubernetes-client/javascript#compatibility
> 
> I'm not sure if this is related, but what I would try is to use an older client or, if possible, update my Kubernetes Server. If the issue is still happening this is a valid bug.

 I wrote my version wrong. It should be 1.24

**Comment by brendandburns** [comment]
I don't think that this is an error in the library. You can see in the code where this is set:

https://github.com/kubernetes-client/javascript/blob/481cdd246fd8b57fdb41d7b0ee7fbddab441aef4/src/gen/api/customObjectsApi.ts#L1416

And where it is turned into a URL:
https://github.com/kubernetes-client/javascript/blob/481cdd246fd8b57fdb41d7b0ee7fbddab441aef4/src/gen/api/customObjectsApi.ts#L1443

It's hard for me to see where this could happen. I suspect that either your label selector isn't working the way you think it should work or there is an issue with the server.

To investigate this further, I would ask you to determine the URL that the code is generating, and then attempt to call that URL directly using a tool like `curl`, and also look at what `kubectl` does using the same inputs.

As it stands, there's not enough information in this report to determine where (or indeed if) a problem exists.

**Comment by zjy365** [comment]
I have found the cause of the problem and am fixing it by upgrading the server version

https://github.com/kubernetes/kubernetes/pull/110652
