### ISSUE TITLE
How to connect to EKS with loadFromOptions?

### ISSUE THREAD

**Issue by juliusoh** [kubernetes-client/javascript#980]
I am getting User "system:anoymous" cannot list resource "pods" in API group in namespace "default"

    `    kc.loadFromOptions({
          clusters: [
            {
              name: cluster.cluster.name,
              server: cluster.cluster.endpoint,
              skipTLSVerify: true,
              caData: cluster.cluster.certificateAuthority.data,
            },
          ],
          users: [
            {
              name: accessKey,
              password: secretKey,
            },
          ],
          contexts: [
            {
              name: cluster.cluster.name,
              cluster: cluster.cluster.name,
              user: accessKey,
            },
          ],
          currentContext: cluster.cluster.name,
        });
        const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
    
        const result = await k8sApi.listNamespacedPod('default');

`

**Comment by brendandburns** [comment]
You need to make sure that the options configuration matches with the contents of your kubeconfig file.

The code that you specified above has numerous issues (e.g. skipTLSVerify: true is insecure, you shouldn't need to send a password, etc). It's beyond the scope to help with writing the correct config, but if you make it match your kubeconfig it should work

**Comment by liu-ming-tfs** [comment]
I ran into a similar problem...I'm trying to connect to a remote server and here is how I did it:

```
const k8s = require('@kubernetes/client-node')
const kc = new k8s.KubeConfig()
const cluster = {name: 'default', server: 'https://my-server.com'}
const user = {name: 'xxx', password: 'yyy'}
const context = {name: 'default', user: user.name, cluster: cluster.name}
kc.loadFromOptions({ clusters: [cluster], users: [user], contexts: [context], currentContext: context.name })
const k8sApi = kc.makeApiClient(k8s.CoreV1Api)
k8sApi.listPodForAllNamespaces().then(r => {
    console.log(r.body)
})
```
I don't see any error, but this is what I got:

```
V1PodList {
    apiVersion: undefined,
    items: undefined,
    kind: undefined,
    metadata: undefined
}
```
What did I miss? I checked many times and think I got all the parameters right. How do I debug this case?

I can ssh to the server and run kubectl with the same parameters.
